export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1613,
        "ordered_items": 134,
        "sell_earnings": 552,
        "commissions": 552,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6680,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1213,
        "ordered_items": 99,
        "sell_earnings": 541,
        "commissions": 541,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5315,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1215,
        "ordered_items": 109,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7174,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 2017,
        "ordered_items": 165,
        "sell_earnings": 721,
        "commissions": 721,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7232,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 2019,
        "ordered_items": 175,
        "sell_earnings": 675,
        "commissions": 675,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9091,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 1619,
        "ordered_items": 140,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7726,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1530,
        "ordered_items": 104,
        "sell_earnings": 573,
        "commissions": 573,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7034,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1342,
        "ordered_items": 126,
        "sell_earnings": 594,
        "commissions": 594,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5313,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1218,
        "ordered_items": 98,
        "sell_earnings": 509,
        "commissions": 509,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6809,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 2014,
        "ordered_items": 176,
        "sell_earnings": 707,
        "commissions": 707,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7597,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 1890,
        "ordered_items": 148,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9093,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 1702,
        "ordered_items": 170,
        "sell_earnings": 643,
        "commissions": 643,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7372,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1361,
        "ordered_items": 106,
        "sell_earnings": 529,
        "commissions": 529,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5709,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 1871,
        "ordered_items": 168,
        "sell_earnings": 687,
        "commissions": 687,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8697,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1394,
        "ordered_items": 117,
        "sell_earnings": 575,
        "commissions": 575,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6965,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 1838,
        "ordered_items": 157,
        "sell_earnings": 641,
        "commissions": 641,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7441,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1308,
        "ordered_items": 130,
        "sell_earnings": 603,
        "commissions": 603,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5375,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1548,
        "ordered_items": 137,
        "sell_earnings": 476,
        "commissions": 476,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5171,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1508,
        "ordered_items": 132,
        "sell_earnings": 459,
        "commissions": 459,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5460,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1329,
        "ordered_items": 97,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6111,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 1903,
        "ordered_items": 177,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8295,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 1724,
        "ordered_items": 142,
        "sell_earnings": 757,
        "commissions": 757,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8946,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 1684,
        "ordered_items": 137,
        "sell_earnings": 740,
        "commissions": 740,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9235,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 1924,
        "ordered_items": 144,
        "sell_earnings": 613,
        "commissions": 613,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9031,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1165,
        "ordered_items": 129,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5992,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1224,
        "ordered_items": 119,
        "sell_earnings": 521,
        "commissions": 521,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5285,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 2008,
        "ordered_items": 155,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9121,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 2067,
        "ordered_items": 145,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8414,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1564,
        "ordered_items": 122,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6846,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 1668,
        "ordered_items": 152,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7560,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];