export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1259,
        "ordered_items": 124,
        "sell_earnings": 510,
        "commissions": 510,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5817,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1581,
        "ordered_items": 109,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5740,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1232,
        "ordered_items": 139,
        "sell_earnings": 609,
        "commissions": 609,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7425,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 2108,
        "ordered_items": 145,
        "sell_earnings": 647,
        "commissions": 647,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7461,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 1759,
        "ordered_items": 175,
        "sell_earnings": 806,
        "commissions": 806,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9146,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 2081,
        "ordered_items": 160,
        "sell_earnings": 746,
        "commissions": 746,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9069,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1503,
        "ordered_items": 129,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7012,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1669,
        "ordered_items": 105,
        "sell_earnings": 521,
        "commissions": 521,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5773,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1613,
        "ordered_items": 111,
        "sell_earnings": 465,
        "commissions": 465,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6417,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 1727,
        "ordered_items": 173,
        "sell_earnings": 791,
        "commissions": 791,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 165,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8469,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 1671,
        "ordered_items": 179,
        "sell_earnings": 735,
        "commissions": 735,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9113,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 1837,
        "ordered_items": 155,
        "sell_earnings": 663,
        "commissions": 663,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7874,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1231,
        "ordered_items": 132,
        "sell_earnings": 505,
        "commissions": 505,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6263,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 2109,
        "ordered_items": 152,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8623,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1213,
        "ordered_items": 131,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5514,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 2127,
        "ordered_items": 153,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9372,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1263,
        "ordered_items": 142,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6778,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1255,
        "ordered_items": 127,
        "sell_earnings": 615,
        "commissions": 615,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6374,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1288,
        "ordered_items": 101,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5971,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1417,
        "ordered_items": 111,
        "sell_earnings": 525,
        "commissions": 525,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5668,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 1923,
        "ordered_items": 173,
        "sell_earnings": 731,
        "commissions": 731,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9218,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 2052,
        "ordered_items": 183,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8915,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 2085,
        "ordered_items": 157,
        "sell_earnings": 641,
        "commissions": 641,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8512,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 2077,
        "ordered_items": 142,
        "sell_earnings": 729,
        "commissions": 729,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8108,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1466,
        "ordered_items": 135,
        "sell_earnings": 570,
        "commissions": 570,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6098,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1539,
        "ordered_items": 116,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7051,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 1801,
        "ordered_items": 168,
        "sell_earnings": 634,
        "commissions": 634,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7835,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 1874,
        "ordered_items": 149,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8788,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1437,
        "ordered_items": 115,
        "sell_earnings": 550,
        "commissions": 550,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6648,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 1903,
        "ordered_items": 169,
        "sell_earnings": 706,
        "commissions": 706,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8238,
        "bonus": 0
    }
];