export let mar = [
    {
        "month": "Mar",
        "day": "01",
        "clicks": 1310,
        "ordered_items": 98,
        "sell_earnings": 514,
        "commissions": 514,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6902,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "02",
        "clicks": 1573,
        "ordered_items": 137,
        "sell_earnings": 573,
        "commissions": 573,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5738,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "03",
        "clicks": 1575,
        "ordered_items": 129,
        "sell_earnings": 433,
        "commissions": 433,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6100,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "04",
        "clicks": 1657,
        "ordered_items": 145,
        "sell_earnings": 783,
        "commissions": 783,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8306,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "05",
        "clicks": 1659,
        "ordered_items": 137,
        "sell_earnings": 643,
        "commissions": 643,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8668,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "06",
        "clicks": 1922,
        "ordered_items": 176,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7504,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "07",
        "clicks": 1241,
        "ordered_items": 104,
        "sell_earnings": 577,
        "commissions": 577,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5779,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "08",
        "clicks": 1501,
        "ordered_items": 117,
        "sell_earnings": 501,
        "commissions": 501,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5256,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "09",
        "clicks": 1447,
        "ordered_items": 131,
        "sell_earnings": 543,
        "commissions": 543,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5080,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "10",
        "clicks": 1785,
        "ordered_items": 143,
        "sell_earnings": 673,
        "commissions": 673,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9326,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "11",
        "clicks": 1731,
        "ordered_items": 157,
        "sell_earnings": 715,
        "commissions": 715,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9150,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "12",
        "clicks": 1991,
        "ordered_items": 170,
        "sell_earnings": 639,
        "commissions": 639,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8627,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "13",
        "clicks": 1481,
        "ordered_items": 102,
        "sell_earnings": 467,
        "commissions": 467,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6352,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "14",
        "clicks": 1751,
        "ordered_items": 172,
        "sell_earnings": 749,
        "commissions": 749,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8054,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "15",
        "clicks": 1343,
        "ordered_items": 136,
        "sell_earnings": 465,
        "commissions": 465,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5207,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "16",
        "clicks": 1889,
        "ordered_items": 138,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9199,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "17",
        "clicks": 1511,
        "ordered_items": 109,
        "sell_earnings": 560,
        "commissions": 560,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5675,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "18",
        "clicks": 1332,
        "ordered_items": 131,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7094,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "19",
        "clicks": 1200,
        "ordered_items": 110,
        "sell_earnings": 510,
        "commissions": 510,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6810,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "20",
        "clicks": 1294,
        "ordered_items": 116,
        "sell_earnings": 486,
        "commissions": 486,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6252,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "21",
        "clicks": 1938,
        "ordered_items": 158,
        "sell_earnings": 730,
        "commissions": 730,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8154,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "22",
        "clicks": 2032,
        "ordered_items": 164,
        "sell_earnings": 706,
        "commissions": 706,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7596,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "23",
        "clicks": 1900,
        "ordered_items": 143,
        "sell_earnings": 725,
        "commissions": 725,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7312,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "24",
        "clicks": 1721,
        "ordered_items": 165,
        "sell_earnings": 656,
        "commissions": 656,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8731,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "25",
        "clicks": 1608,
        "ordered_items": 133,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6205,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "26",
        "clicks": 1398,
        "ordered_items": 104,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6909,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "27",
        "clicks": 1834,
        "ordered_items": 170,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7497,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "28",
        "clicks": 1624,
        "ordered_items": 141,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8201,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "29",
        "clicks": 1229,
        "ordered_items": 119,
        "sell_earnings": 516,
        "commissions": 516,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5797,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "30",
        "clicks": 2003,
        "ordered_items": 155,
        "sell_earnings": 700,
        "commissions": 700,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8609,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];