export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1604,
        "ordered_items": 109,
        "sell_earnings": 429,
        "commissions": 429,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6852,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1205,
        "ordered_items": 132,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6326,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1586,
        "ordered_items": 135,
        "sell_earnings": 562,
        "commissions": 562,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7188,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 1646,
        "ordered_items": 139,
        "sell_earnings": 654,
        "commissions": 654,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7218,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 2027,
        "ordered_items": 142,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8080,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 1628,
        "ordered_items": 165,
        "sell_earnings": 787,
        "commissions": 787,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7554,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1311,
        "ordered_items": 106,
        "sell_earnings": 521,
        "commissions": 521,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6335,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1364,
        "ordered_items": 105,
        "sell_earnings": 571,
        "commissions": 571,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6496,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1230,
        "ordered_items": 115,
        "sell_earnings": 439,
        "commissions": 439,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6442,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 2002,
        "ordered_items": 159,
        "sell_earnings": 777,
        "commissions": 777,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7964,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 1868,
        "ordered_items": 169,
        "sell_earnings": 645,
        "commissions": 645,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7910,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1921,
        "ordered_items": 168,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8071,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1397,
        "ordered_items": 135,
        "sell_earnings": 468,
        "commissions": 468,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6607,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 1835,
        "ordered_items": 139,
        "sell_earnings": 748,
        "commissions": 748,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7799,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1510,
        "ordered_items": 126,
        "sell_earnings": 529,
        "commissions": 529,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5774,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 1722,
        "ordered_items": 148,
        "sell_earnings": 687,
        "commissions": 687,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8632,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1573,
        "ordered_items": 116,
        "sell_earnings": 605,
        "commissions": 605,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5756,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1314,
        "ordered_items": 97,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7182,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1467,
        "ordered_items": 119,
        "sell_earnings": 474,
        "commissions": 474,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5255,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1263,
        "ordered_items": 133,
        "sell_earnings": 552,
        "commissions": 552,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6221,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 1969,
        "ordered_items": 141,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8185,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 1765,
        "ordered_items": 155,
        "sell_earnings": 742,
        "commissions": 742,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9151,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 1918,
        "ordered_items": 177,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7224,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1659,
        "ordered_items": 158,
        "sell_earnings": 611,
        "commissions": 611,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8650,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1176,
        "ordered_items": 132,
        "sell_earnings": 467,
        "commissions": 467,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6213,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1584,
        "ordered_items": 101,
        "sell_earnings": 459,
        "commissions": 459,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6242,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 1648,
        "ordered_items": 173,
        "sell_earnings": 757,
        "commissions": 757,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8164,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 2056,
        "ordered_items": 142,
        "sell_earnings": 749,
        "commissions": 749,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8193,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1158,
        "ordered_items": 117,
        "sell_earnings": 439,
        "commissions": 439,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5258,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 2074,
        "ordered_items": 157,
        "sell_earnings": 777,
        "commissions": 777,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9148,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];