export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1644,
        "ordered_items": 107,
        "sell_earnings": 468,
        "commissions": 468,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5257,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1474,
        "ordered_items": 137,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7110,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1202,
        "ordered_items": 137,
        "sell_earnings": 614,
        "commissions": 614,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7361,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 2138,
        "ordered_items": 147,
        "sell_earnings": 642,
        "commissions": 642,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7525,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 1866,
        "ordered_items": 147,
        "sell_earnings": 798,
        "commissions": 798,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7776,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 1696,
        "ordered_items": 177,
        "sell_earnings": 788,
        "commissions": 788,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9629,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1448,
        "ordered_items": 117,
        "sell_earnings": 522,
        "commissions": 522,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6844,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1537,
        "ordered_items": 118,
        "sell_earnings": 575,
        "commissions": 575,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6972,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1238,
        "ordered_items": 134,
        "sell_earnings": 616,
        "commissions": 616,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5893,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 2102,
        "ordered_items": 150,
        "sell_earnings": 640,
        "commissions": 640,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8993,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 1803,
        "ordered_items": 166,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7914,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 1892,
        "ordered_items": 167,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8042,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1177,
        "ordered_items": 106,
        "sell_earnings": 466,
        "commissions": 466,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6823,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 2163,
        "ordered_items": 178,
        "sell_earnings": 790,
        "commissions": 790,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8063,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1414,
        "ordered_items": 116,
        "sell_earnings": 511,
        "commissions": 511,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6018,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 1926,
        "ordered_items": 168,
        "sell_earnings": 745,
        "commissions": 745,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8868,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1585,
        "ordered_items": 128,
        "sell_earnings": 547,
        "commissions": 547,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5262,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1457,
        "ordered_items": 120,
        "sell_earnings": 460,
        "commissions": 460,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5427,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1662,
        "ordered_items": 122,
        "sell_earnings": 611,
        "commissions": 611,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5611,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1596,
        "ordered_items": 123,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6299,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 1744,
        "ordered_items": 161,
        "sell_earnings": 756,
        "commissions": 756,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8587,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 1678,
        "ordered_items": 162,
        "sell_earnings": 645,
        "commissions": 645,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9275,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 1883,
        "ordered_items": 164,
        "sell_earnings": 796,
        "commissions": 796,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9459,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 1755,
        "ordered_items": 156,
        "sell_earnings": 709,
        "commissions": 709,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9624,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1656,
        "ordered_items": 128,
        "sell_earnings": 601,
        "commissions": 601,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5288,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1667,
        "ordered_items": 132,
        "sell_earnings": 592,
        "commissions": 592,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6668,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 1673,
        "ordered_items": 152,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8218,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 1684,
        "ordered_items": 156,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9598,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1564,
        "ordered_items": 137,
        "sell_earnings": 564,
        "commissions": 564,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6112,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 1776,
        "ordered_items": 147,
        "sell_earnings": 692,
        "commissions": 692,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8774,
        "bonus": 1
    }
];