export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1508,
        "ordered_items": 115,
        "sell_earnings": 510,
        "commissions": 510,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5553,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1379,
        "ordered_items": 123,
        "sell_earnings": 572,
        "commissions": 572,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5214,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1415,
        "ordered_items": 97,
        "sell_earnings": 586,
        "commissions": 586,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5544,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 1817,
        "ordered_items": 177,
        "sell_earnings": 630,
        "commissions": 630,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8862,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1853,
        "ordered_items": 151,
        "sell_earnings": 644,
        "commissions": 644,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9192,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 1724,
        "ordered_items": 159,
        "sell_earnings": 706,
        "commissions": 706,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8853,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1257,
        "ordered_items": 107,
        "sell_earnings": 486,
        "commissions": 486,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5872,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1198,
        "ordered_items": 103,
        "sell_earnings": 521,
        "commissions": 521,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5923,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1590,
        "ordered_items": 97,
        "sell_earnings": 570,
        "commissions": 570,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6899,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1642,
        "ordered_items": 177,
        "sell_earnings": 646,
        "commissions": 646,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7507,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 2034,
        "ordered_items": 171,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8483,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1975,
        "ordered_items": 167,
        "sell_earnings": 730,
        "commissions": 730,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8534,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1325,
        "ordered_items": 97,
        "sell_earnings": 459,
        "commissions": 459,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5279,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1907,
        "ordered_items": 177,
        "sell_earnings": 757,
        "commissions": 757,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9127,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1132,
        "ordered_items": 116,
        "sell_earnings": 518,
        "commissions": 518,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6250,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 2100,
        "ordered_items": 158,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8156,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1286,
        "ordered_items": 123,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5663,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1398,
        "ordered_items": 120,
        "sell_earnings": 433,
        "commissions": 433,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7077,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1307,
        "ordered_items": 111,
        "sell_earnings": 437,
        "commissions": 437,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6503,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1503,
        "ordered_items": 129,
        "sell_earnings": 473,
        "commissions": 473,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6482,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 1729,
        "ordered_items": 145,
        "sell_earnings": 743,
        "commissions": 743,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7924,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1925,
        "ordered_items": 163,
        "sell_earnings": 779,
        "commissions": 779,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7903,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 1834,
        "ordered_items": 154,
        "sell_earnings": 783,
        "commissions": 783,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7329,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1946,
        "ordered_items": 151,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8743,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1612,
        "ordered_items": 120,
        "sell_earnings": 447,
        "commissions": 447,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5103,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1385,
        "ordered_items": 125,
        "sell_earnings": 579,
        "commissions": 579,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6989,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1847,
        "ordered_items": 149,
        "sell_earnings": 637,
        "commissions": 637,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7417,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1620,
        "ordered_items": 154,
        "sell_earnings": 769,
        "commissions": 769,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9303,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1516,
        "ordered_items": 133,
        "sell_earnings": 537,
        "commissions": 537,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6069,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1716,
        "ordered_items": 141,
        "sell_earnings": 679,
        "commissions": 679,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8337,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];