export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 1500,
        "ordered_items": 130,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6061,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 1332,
        "ordered_items": 127,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6337,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 1498,
        "ordered_items": 125,
        "sell_earnings": 546,
        "commissions": 546,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6466,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 1842,
        "ordered_items": 159,
        "sell_earnings": 710,
        "commissions": 710,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8420,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 2008,
        "ordered_items": 157,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 165,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8549,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 1840,
        "ordered_items": 154,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8825,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 1444,
        "ordered_items": 111,
        "sell_earnings": 483,
        "commissions": 483,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6152,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 1173,
        "ordered_items": 124,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5473,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 1458,
        "ordered_items": 115,
        "sell_earnings": 599,
        "commissions": 599,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6442,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 1882,
        "ordered_items": 169,
        "sell_earnings": 657,
        "commissions": 657,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8444,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 2167,
        "ordered_items": 160,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9413,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 1896,
        "ordered_items": 173,
        "sell_earnings": 773,
        "commissions": 773,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8734,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 1171,
        "ordered_items": 104,
        "sell_earnings": 615,
        "commissions": 615,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5304,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 2169,
        "ordered_items": 180,
        "sell_earnings": 641,
        "commissions": 641,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9582,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 1324,
        "ordered_items": 100,
        "sell_earnings": 551,
        "commissions": 551,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6850,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 2016,
        "ordered_items": 184,
        "sell_earnings": 705,
        "commissions": 705,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8036,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 1562,
        "ordered_items": 104,
        "sell_earnings": 543,
        "commissions": 543,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6223,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 1286,
        "ordered_items": 132,
        "sell_earnings": 449,
        "commissions": 449,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5655,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 1631,
        "ordered_items": 142,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6510,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 1318,
        "ordered_items": 121,
        "sell_earnings": 501,
        "commissions": 501,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6846,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 2022,
        "ordered_items": 163,
        "sell_earnings": 755,
        "commissions": 755,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8040,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 1709,
        "ordered_items": 142,
        "sell_earnings": 650,
        "commissions": 650,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 167,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8376,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 2054,
        "ordered_items": 152,
        "sell_earnings": 807,
        "commissions": 807,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9231,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 1778,
        "ordered_items": 180,
        "sell_earnings": 713,
        "commissions": 713,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8663,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 1590,
        "ordered_items": 127,
        "sell_earnings": 574,
        "commissions": 574,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6505,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 1645,
        "ordered_items": 127,
        "sell_earnings": 502,
        "commissions": 502,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5773,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 1695,
        "ordered_items": 157,
        "sell_earnings": 754,
        "commissions": 754,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9113,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 1750,
        "ordered_items": 157,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8381,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 1552,
        "ordered_items": 139,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5477,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 1788,
        "ordered_items": 145,
        "sell_earnings": 793,
        "commissions": 793,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 168,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9409,
        "bonus": 1
    }
];