
let may = [
        {
            month: 'May',
            day: '01',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '02',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '03',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '04',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '05',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '06',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '07',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '08',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '09',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '10',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '11',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '12',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '13',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '14',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '15',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '16',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '17',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '18',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '19',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '20',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '21',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '22',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '23',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '24',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '25',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '26',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '27',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '28',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '29',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '30',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        },
        {
            month: 'May',
            day: '31',
            clicks: 0,
            ordered_items: 0,
            sell_earnings: 0,
            commissions: 0,
            bounties: 0,
            referrals: 0,
            referral_earnings: 0,
            shipped: 0,
            returned: 0,
            conversion: 0,
            shippedRev: 0,
            bonus: 0
        }
    ];


module.exports = may;
