export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1188,
        "ordered_items": 136,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5592,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1250,
        "ordered_items": 107,
        "sell_earnings": 541,
        "commissions": 541,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6250,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1161,
        "ordered_items": 131,
        "sell_earnings": 558,
        "commissions": 558,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7020,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 2071,
        "ordered_items": 143,
        "sell_earnings": 658,
        "commissions": 658,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7386,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 1982,
        "ordered_items": 167,
        "sell_earnings": 675,
        "commissions": 675,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8156,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 2044,
        "ordered_items": 138,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8814,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1234,
        "ordered_items": 113,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5902,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1563,
        "ordered_items": 99,
        "sell_earnings": 574,
        "commissions": 574,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5215,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1139,
        "ordered_items": 99,
        "sell_earnings": 557,
        "commissions": 557,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6678,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 2093,
        "ordered_items": 175,
        "sell_earnings": 659,
        "commissions": 659,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7728,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1669,
        "ordered_items": 175,
        "sell_earnings": 642,
        "commissions": 642,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9191,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 1998,
        "ordered_items": 161,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8504,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1137,
        "ordered_items": 132,
        "sell_earnings": 479,
        "commissions": 479,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6599,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 2095,
        "ordered_items": 142,
        "sell_earnings": 737,
        "commissions": 737,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7807,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1587,
        "ordered_items": 109,
        "sell_earnings": 597,
        "commissions": 597,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5423,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 1645,
        "ordered_items": 165,
        "sell_earnings": 619,
        "commissions": 619,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8983,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1448,
        "ordered_items": 103,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5350,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1243,
        "ordered_items": 118,
        "sell_earnings": 508,
        "commissions": 508,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5676,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1599,
        "ordered_items": 129,
        "sell_earnings": 559,
        "commissions": 559,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5245,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1446,
        "ordered_items": 113,
        "sell_earnings": 599,
        "commissions": 599,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5661,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 1786,
        "ordered_items": 161,
        "sell_earnings": 617,
        "commissions": 617,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8745,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 1633,
        "ordered_items": 145,
        "sell_earnings": 657,
        "commissions": 657,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9161,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 1989,
        "ordered_items": 156,
        "sell_earnings": 708,
        "commissions": 708,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8730,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 1784,
        "ordered_items": 171,
        "sell_earnings": 721,
        "commissions": 721,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9056,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1300,
        "ordered_items": 103,
        "sell_earnings": 461,
        "commissions": 461,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5136,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1493,
        "ordered_items": 106,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7088,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1739,
        "ordered_items": 168,
        "sell_earnings": 721,
        "commissions": 721,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7318,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 1932,
        "ordered_items": 171,
        "sell_earnings": 755,
        "commissions": 755,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9270,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1146,
        "ordered_items": 134,
        "sell_earnings": 433,
        "commissions": 433,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6058,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 2086,
        "ordered_items": 140,
        "sell_earnings": 783,
        "commissions": 783,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8348,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];