export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1627,
        "ordered_items": 126,
        "sell_earnings": 448,
        "commissions": 448,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6306,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1527,
        "ordered_items": 116,
        "sell_earnings": 523,
        "commissions": 523,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5727,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1406,
        "ordered_items": 118,
        "sell_earnings": 544,
        "commissions": 544,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7251,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 1934,
        "ordered_items": 166,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7635,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 1813,
        "ordered_items": 168,
        "sell_earnings": 733,
        "commissions": 733,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9159,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 1713,
        "ordered_items": 158,
        "sell_earnings": 808,
        "commissions": 808,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8580,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1343,
        "ordered_items": 138,
        "sell_earnings": 551,
        "commissions": 551,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5268,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1290,
        "ordered_items": 128,
        "sell_earnings": 523,
        "commissions": 523,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5380,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1543,
        "ordered_items": 135,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5557,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 1797,
        "ordered_items": 149,
        "sell_earnings": 644,
        "commissions": 644,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9329,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 2050,
        "ordered_items": 156,
        "sell_earnings": 733,
        "commissions": 733,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9506,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 1997,
        "ordered_items": 146,
        "sell_earnings": 705,
        "commissions": 705,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9618,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1366,
        "ordered_items": 125,
        "sell_earnings": 583,
        "commissions": 583,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6290,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 1974,
        "ordered_items": 159,
        "sell_earnings": 673,
        "commissions": 673,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8596,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1350,
        "ordered_items": 100,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7195,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 1990,
        "ordered_items": 184,
        "sell_earnings": 765,
        "commissions": 765,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7691,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1278,
        "ordered_items": 130,
        "sell_earnings": 578,
        "commissions": 578,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7307,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1375,
        "ordered_items": 129,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6061,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1244,
        "ordered_items": 103,
        "sell_earnings": 592,
        "commissions": 592,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5723,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1395,
        "ordered_items": 133,
        "sell_earnings": 610,
        "commissions": 610,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6569,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 1945,
        "ordered_items": 151,
        "sell_earnings": 646,
        "commissions": 646,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8317,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 2096,
        "ordered_items": 181,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9163,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 1965,
        "ordered_items": 155,
        "sell_earnings": 650,
        "commissions": 650,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8825,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 2062,
        "ordered_items": 154,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7579,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1559,
        "ordered_items": 109,
        "sell_earnings": 620,
        "commissions": 620,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7340,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1533,
        "ordered_items": 109,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5487,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 1807,
        "ordered_items": 175,
        "sell_earnings": 765,
        "commissions": 765,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9399,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 1781,
        "ordered_items": 175,
        "sell_earnings": 636,
        "commissions": 636,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7546,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1219,
        "ordered_items": 131,
        "sell_earnings": 469,
        "commissions": 469,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6394,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 2121,
        "ordered_items": 153,
        "sell_earnings": 787,
        "commissions": 787,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8492,
        "bonus": 0
    }
];