export let mar = [
    {
        "month": "Mar",
        "day": "01",
        "clicks": 1386,
        "ordered_items": 125,
        "sell_earnings": 506,
        "commissions": 506,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5354,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "02",
        "clicks": 1305,
        "ordered_items": 107,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5636,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "03",
        "clicks": 1587,
        "ordered_items": 137,
        "sell_earnings": 591,
        "commissions": 591,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6325,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "04",
        "clicks": 1645,
        "ordered_items": 137,
        "sell_earnings": 625,
        "commissions": 625,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8081,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "05",
        "clicks": 1927,
        "ordered_items": 167,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8770,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "06",
        "clicks": 1846,
        "ordered_items": 149,
        "sell_earnings": 710,
        "commissions": 710,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9052,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "07",
        "clicks": 1328,
        "ordered_items": 120,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5679,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "08",
        "clicks": 1193,
        "ordered_items": 118,
        "sell_earnings": 436,
        "commissions": 436,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5804,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "09",
        "clicks": 1263,
        "ordered_items": 97,
        "sell_earnings": 564,
        "commissions": 564,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6055,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "10",
        "clicks": 1969,
        "ordered_items": 177,
        "sell_earnings": 652,
        "commissions": 652,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8351,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "11",
        "clicks": 2039,
        "ordered_items": 156,
        "sell_earnings": 780,
        "commissions": 780,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8602,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "12",
        "clicks": 1904,
        "ordered_items": 154,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8727,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "13",
        "clicks": 1259,
        "ordered_items": 105,
        "sell_earnings": 532,
        "commissions": 532,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5066,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "14",
        "clicks": 1973,
        "ordered_items": 169,
        "sell_earnings": 684,
        "commissions": 684,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9340,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "15",
        "clicks": 1168,
        "ordered_items": 126,
        "sell_earnings": 553,
        "commissions": 553,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6663,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "16",
        "clicks": 2064,
        "ordered_items": 148,
        "sell_earnings": 663,
        "commissions": 663,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7743,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "17",
        "clicks": 1558,
        "ordered_items": 101,
        "sell_earnings": 550,
        "commissions": 550,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5590,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "18",
        "clicks": 1278,
        "ordered_items": 120,
        "sell_earnings": 578,
        "commissions": 578,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7169,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "19",
        "clicks": 1304,
        "ordered_items": 104,
        "sell_earnings": 580,
        "commissions": 580,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6856,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "20",
        "clicks": 1362,
        "ordered_items": 134,
        "sell_earnings": 585,
        "commissions": 585,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6764,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "21",
        "clicks": 1870,
        "ordered_items": 140,
        "sell_earnings": 631,
        "commissions": 631,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7642,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "22",
        "clicks": 1928,
        "ordered_items": 170,
        "sell_earnings": 636,
        "commissions": 636,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7550,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "23",
        "clicks": 1954,
        "ordered_items": 154,
        "sell_earnings": 638,
        "commissions": 638,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7237,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "24",
        "clicks": 1674,
        "ordered_items": 173,
        "sell_earnings": 666,
        "commissions": 666,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8816,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "25",
        "clicks": 1310,
        "ordered_items": 102,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7111,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "26",
        "clicks": 1563,
        "ordered_items": 97,
        "sell_earnings": 539,
        "commissions": 539,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6984,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "27",
        "clicks": 1669,
        "ordered_items": 177,
        "sell_earnings": 677,
        "commissions": 677,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7422,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "28",
        "clicks": 1922,
        "ordered_items": 172,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7295,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "29",
        "clicks": 1532,
        "ordered_items": 134,
        "sell_earnings": 488,
        "commissions": 488,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5971,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "30",
        "clicks": 1700,
        "ordered_items": 140,
        "sell_earnings": 728,
        "commissions": 728,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8435,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];