export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1590,
        "ordered_items": 100,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5722,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1608,
        "ordered_items": 141,
        "sell_earnings": 607,
        "commissions": 607,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6677,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1211,
        "ordered_items": 106,
        "sell_earnings": 487,
        "commissions": 487,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7409,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 2129,
        "ordered_items": 178,
        "sell_earnings": 769,
        "commissions": 769,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7477,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 1732,
        "ordered_items": 143,
        "sell_earnings": 649,
        "commissions": 649,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 164,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8209,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 1750,
        "ordered_items": 184,
        "sell_earnings": 638,
        "commissions": 638,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9164,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1258,
        "ordered_items": 139,
        "sell_earnings": 587,
        "commissions": 587,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7095,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1199,
        "ordered_items": 130,
        "sell_earnings": 502,
        "commissions": 502,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6187,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1465,
        "ordered_items": 100,
        "sell_earnings": 566,
        "commissions": 566,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6342,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 1875,
        "ordered_items": 184,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8544,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 2141,
        "ordered_items": 154,
        "sell_earnings": 754,
        "commissions": 754,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8699,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 2082,
        "ordered_items": 145,
        "sell_earnings": 669,
        "commissions": 669,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7791,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1532,
        "ordered_items": 141,
        "sell_earnings": 620,
        "commissions": 620,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5998,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 1808,
        "ordered_items": 143,
        "sell_earnings": 636,
        "commissions": 636,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8888,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1475,
        "ordered_items": 131,
        "sell_earnings": 444,
        "commissions": 444,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6859,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 1865,
        "ordered_items": 153,
        "sell_earnings": 812,
        "commissions": 812,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8027,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1303,
        "ordered_items": 108,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5413,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1415,
        "ordered_items": 115,
        "sell_earnings": 449,
        "commissions": 449,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6863,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1201,
        "ordered_items": 140,
        "sell_earnings": 452,
        "commissions": 452,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6037,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1216,
        "ordered_items": 122,
        "sell_earnings": 542,
        "commissions": 542,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5810,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 2124,
        "ordered_items": 162,
        "sell_earnings": 714,
        "commissions": 714,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9076,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 2139,
        "ordered_items": 144,
        "sell_earnings": 804,
        "commissions": 804,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8849,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 1925,
        "ordered_items": 169,
        "sell_earnings": 807,
        "commissions": 807,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8023,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 2037,
        "ordered_items": 176,
        "sell_earnings": 800,
        "commissions": 800,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9473,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1580,
        "ordered_items": 140,
        "sell_earnings": 558,
        "commissions": 558,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6596,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1321,
        "ordered_items": 117,
        "sell_earnings": 452,
        "commissions": 452,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6874,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 2019,
        "ordered_items": 167,
        "sell_earnings": 804,
        "commissions": 804,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8012,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 1760,
        "ordered_items": 144,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8290,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1185,
        "ordered_items": 106,
        "sell_earnings": 560,
        "commissions": 560,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 129,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6009,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 2155,
        "ordered_items": 178,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8877,
        "bonus": 2
    }
];