export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 1212,
        "ordered_items": 138,
        "sell_earnings": 605,
        "commissions": 605,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5517,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 1408,
        "ordered_items": 141,
        "sell_earnings": 455,
        "commissions": 455,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6535,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 1527,
        "ordered_items": 130,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7363,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 1813,
        "ordered_items": 154,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 167,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7523,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 1932,
        "ordered_items": 143,
        "sell_earnings": 801,
        "commissions": 801,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8351,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 2128,
        "ordered_items": 146,
        "sell_earnings": 651,
        "commissions": 651,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9369,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 1436,
        "ordered_items": 135,
        "sell_earnings": 567,
        "commissions": 567,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5767,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 1456,
        "ordered_items": 141,
        "sell_earnings": 449,
        "commissions": 449,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6383,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 1492,
        "ordered_items": 127,
        "sell_earnings": 484,
        "commissions": 484,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6041,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 1848,
        "ordered_items": 157,
        "sell_earnings": 772,
        "commissions": 772,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8845,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 1884,
        "ordered_items": 143,
        "sell_earnings": 807,
        "commissions": 807,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8503,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 1904,
        "ordered_items": 149,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9119,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 1375,
        "ordered_items": 118,
        "sell_earnings": 498,
        "commissions": 498,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5460,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 1965,
        "ordered_items": 166,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9426,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 1382,
        "ordered_items": 136,
        "sell_earnings": 601,
        "commissions": 601,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6955,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 1958,
        "ordered_items": 148,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7931,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 1227,
        "ordered_items": 110,
        "sell_earnings": 610,
        "commissions": 610,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6749,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 1667,
        "ordered_items": 108,
        "sell_earnings": 557,
        "commissions": 557,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7374,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 1473,
        "ordered_items": 100,
        "sell_earnings": 462,
        "commissions": 462,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6254,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 1330,
        "ordered_items": 110,
        "sell_earnings": 558,
        "commissions": 558,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6360,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 2010,
        "ordered_items": 174,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8526,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 1867,
        "ordered_items": 184,
        "sell_earnings": 794,
        "commissions": 794,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8632,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 1673,
        "ordered_items": 176,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7512,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 2113,
        "ordered_items": 174,
        "sell_earnings": 646,
        "commissions": 646,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8137,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 1541,
        "ordered_items": 140,
        "sell_earnings": 549,
        "commissions": 549,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6484,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 1217,
        "ordered_items": 141,
        "sell_earnings": 601,
        "commissions": 601,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5350,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 2123,
        "ordered_items": 143,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9536,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 1799,
        "ordered_items": 144,
        "sell_earnings": 707,
        "commissions": 707,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8402,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 1206,
        "ordered_items": 125,
        "sell_earnings": 472,
        "commissions": 472,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5993,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 2134,
        "ordered_items": 159,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8893,
        "bonus": 0
    }
];