export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1355,
        "ordered_items": 119,
        "sell_earnings": 607,
        "commissions": 607,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5348,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1429,
        "ordered_items": 114,
        "sell_earnings": 510,
        "commissions": 510,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6931,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1166,
        "ordered_items": 133,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7152,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 2066,
        "ordered_items": 141,
        "sell_earnings": 651,
        "commissions": 651,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7254,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 1803,
        "ordered_items": 160,
        "sell_earnings": 706,
        "commissions": 706,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7475,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 1877,
        "ordered_items": 155,
        "sell_earnings": 609,
        "commissions": 609,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9058,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1279,
        "ordered_items": 137,
        "sell_earnings": 449,
        "commissions": 449,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6144,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1452,
        "ordered_items": 136,
        "sell_earnings": 567,
        "commissions": 567,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5666,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1198,
        "ordered_items": 123,
        "sell_earnings": 459,
        "commissions": 459,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5589,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 2034,
        "ordered_items": 151,
        "sell_earnings": 757,
        "commissions": 757,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8817,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 1780,
        "ordered_items": 138,
        "sell_earnings": 649,
        "commissions": 649,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8740,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 1953,
        "ordered_items": 137,
        "sell_earnings": 767,
        "commissions": 767,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8262,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1489,
        "ordered_items": 115,
        "sell_earnings": 438,
        "commissions": 438,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5833,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 1743,
        "ordered_items": 159,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8573,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1409,
        "ordered_items": 127,
        "sell_earnings": 543,
        "commissions": 543,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5567,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 1823,
        "ordered_items": 147,
        "sell_earnings": 673,
        "commissions": 673,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8839,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1579,
        "ordered_items": 113,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6094,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1138,
        "ordered_items": 116,
        "sell_earnings": 535,
        "commissions": 535,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5792,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1313,
        "ordered_items": 126,
        "sell_earnings": 545,
        "commissions": 545,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7097,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1390,
        "ordered_items": 106,
        "sell_earnings": 521,
        "commissions": 521,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5605,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 1842,
        "ordered_items": 168,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8801,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1919,
        "ordered_items": 148,
        "sell_earnings": 671,
        "commissions": 671,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7309,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 2094,
        "ordered_items": 158,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8614,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 1653,
        "ordered_items": 161,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8312,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1430,
        "ordered_items": 133,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6343,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1294,
        "ordered_items": 123,
        "sell_earnings": 473,
        "commissions": 473,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5699,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 1938,
        "ordered_items": 151,
        "sell_earnings": 743,
        "commissions": 743,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8707,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1802,
        "ordered_items": 141,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8063,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1132,
        "ordered_items": 119,
        "sell_earnings": 525,
        "commissions": 525,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7030,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 2100,
        "ordered_items": 155,
        "sell_earnings": 691,
        "commissions": 691,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7376,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];