export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1186,
        "ordered_items": 130,
        "sell_earnings": 434,
        "commissions": 434,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6401,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1211,
        "ordered_items": 135,
        "sell_earnings": 564,
        "commissions": 564,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6830,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1502,
        "ordered_items": 119,
        "sell_earnings": 505,
        "commissions": 505,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5596,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 1730,
        "ordered_items": 155,
        "sell_earnings": 711,
        "commissions": 711,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8810,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 2021,
        "ordered_items": 139,
        "sell_earnings": 652,
        "commissions": 652,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7576,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 2046,
        "ordered_items": 144,
        "sell_earnings": 782,
        "commissions": 782,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8005,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1525,
        "ordered_items": 113,
        "sell_earnings": 453,
        "commissions": 453,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5675,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1420,
        "ordered_items": 120,
        "sell_earnings": 433,
        "commissions": 433,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5585,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1531,
        "ordered_items": 137,
        "sell_earnings": 511,
        "commissions": 511,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5334,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 1701,
        "ordered_items": 137,
        "sell_earnings": 705,
        "commissions": 705,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9072,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 1812,
        "ordered_items": 154,
        "sell_earnings": 783,
        "commissions": 783,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8821,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 1707,
        "ordered_items": 161,
        "sell_earnings": 763,
        "commissions": 763,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8731,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1353,
        "ordered_items": 103,
        "sell_earnings": 497,
        "commissions": 497,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5366,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 1879,
        "ordered_items": 171,
        "sell_earnings": 719,
        "commissions": 719,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9040,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1438,
        "ordered_items": 129,
        "sell_earnings": 535,
        "commissions": 535,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7090,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 1794,
        "ordered_items": 145,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7316,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1286,
        "ordered_items": 129,
        "sell_earnings": 502,
        "commissions": 502,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6558,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1600,
        "ordered_items": 99,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6285,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1415,
        "ordered_items": 104,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6923,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1147,
        "ordered_items": 113,
        "sell_earnings": 532,
        "commissions": 532,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6428,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 2085,
        "ordered_items": 161,
        "sell_earnings": 684,
        "commissions": 684,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7978,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 1817,
        "ordered_items": 170,
        "sell_earnings": 676,
        "commissions": 676,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7483,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 1632,
        "ordered_items": 175,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8121,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 1946,
        "ordered_items": 145,
        "sell_earnings": 714,
        "commissions": 714,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7848,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1203,
        "ordered_items": 113,
        "sell_earnings": 454,
        "commissions": 454,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6958,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1363,
        "ordered_items": 129,
        "sell_earnings": 449,
        "commissions": 449,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5389,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 1869,
        "ordered_items": 145,
        "sell_earnings": 767,
        "commissions": 767,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9017,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 2029,
        "ordered_items": 161,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7448,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1511,
        "ordered_items": 134,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6129,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 1721,
        "ordered_items": 140,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8277,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];