export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1643,
        "ordered_items": 103,
        "sell_earnings": 510,
        "commissions": 510,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5252,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1356,
        "ordered_items": 120,
        "sell_earnings": 578,
        "commissions": 578,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6223,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1630,
        "ordered_items": 136,
        "sell_earnings": 516,
        "commissions": 516,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6401,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 1710,
        "ordered_items": 148,
        "sell_earnings": 740,
        "commissions": 740,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8485,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 1984,
        "ordered_items": 164,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 168,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8663,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 1697,
        "ordered_items": 181,
        "sell_earnings": 746,
        "commissions": 746,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9634,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1364,
        "ordered_items": 101,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6408,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1414,
        "ordered_items": 133,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5395,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1396,
        "ordered_items": 139,
        "sell_earnings": 445,
        "commissions": 445,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5461,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 1944,
        "ordered_items": 145,
        "sell_earnings": 811,
        "commissions": 811,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9425,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 1926,
        "ordered_items": 151,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9491,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 1976,
        "ordered_items": 183,
        "sell_earnings": 776,
        "commissions": 776,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8478,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1478,
        "ordered_items": 120,
        "sell_earnings": 471,
        "commissions": 471,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5415,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 1862,
        "ordered_items": 164,
        "sell_earnings": 785,
        "commissions": 785,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 167,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9471,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1394,
        "ordered_items": 142,
        "sell_earnings": 524,
        "commissions": 524,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5668,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 1946,
        "ordered_items": 142,
        "sell_earnings": 732,
        "commissions": 732,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9218,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1335,
        "ordered_items": 114,
        "sell_earnings": 536,
        "commissions": 536,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7395,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1258,
        "ordered_items": 119,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6677,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1206,
        "ordered_items": 123,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6261,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1328,
        "ordered_items": 119,
        "sell_earnings": 557,
        "commissions": 557,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7345,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 2012,
        "ordered_items": 165,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 167,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7541,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 2134,
        "ordered_items": 161,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8625,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 2082,
        "ordered_items": 165,
        "sell_earnings": 663,
        "commissions": 663,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 165,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8209,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 2005,
        "ordered_items": 170,
        "sell_earnings": 720,
        "commissions": 720,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7491,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1625,
        "ordered_items": 129,
        "sell_earnings": 532,
        "commissions": 532,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7113,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1233,
        "ordered_items": 109,
        "sell_earnings": 531,
        "commissions": 531,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6131,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 2107,
        "ordered_items": 175,
        "sell_earnings": 725,
        "commissions": 725,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8755,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 1715,
        "ordered_items": 155,
        "sell_earnings": 724,
        "commissions": 724,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7773,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1306,
        "ordered_items": 108,
        "sell_earnings": 588,
        "commissions": 588,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5794,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 2034,
        "ordered_items": 176,
        "sell_earnings": 668,
        "commissions": 668,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9092,
        "bonus": 0
    }
];