export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1440,
        "ordered_items": 124,
        "sell_earnings": 541,
        "commissions": 541,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7052,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1286,
        "ordered_items": 139,
        "sell_earnings": 498,
        "commissions": 498,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5859,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1230,
        "ordered_items": 101,
        "sell_earnings": 566,
        "commissions": 566,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6060,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 2110,
        "ordered_items": 183,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8826,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 2054,
        "ordered_items": 145,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9027,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 1900,
        "ordered_items": 160,
        "sell_earnings": 715,
        "commissions": 715,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7834,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1667,
        "ordered_items": 115,
        "sell_earnings": 610,
        "commissions": 610,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6144,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1331,
        "ordered_items": 123,
        "sell_earnings": 560,
        "commissions": 560,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7354,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1225,
        "ordered_items": 122,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6396,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 2115,
        "ordered_items": 162,
        "sell_earnings": 792,
        "commissions": 792,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8490,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 2009,
        "ordered_items": 161,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7532,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 1673,
        "ordered_items": 169,
        "sell_earnings": 646,
        "commissions": 646,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8742,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1202,
        "ordered_items": 115,
        "sell_earnings": 587,
        "commissions": 587,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7431,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 2138,
        "ordered_items": 169,
        "sell_earnings": 669,
        "commissions": 669,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7455,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1540,
        "ordered_items": 131,
        "sell_earnings": 469,
        "commissions": 469,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6506,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 1800,
        "ordered_items": 153,
        "sell_earnings": 787,
        "commissions": 787,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8380,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1213,
        "ordered_items": 126,
        "sell_earnings": 441,
        "commissions": 441,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6209,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1195,
        "ordered_items": 125,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7371,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1491,
        "ordered_items": 136,
        "sell_earnings": 503,
        "commissions": 503,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6604,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1352,
        "ordered_items": 140,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6281,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 1988,
        "ordered_items": 144,
        "sell_earnings": 663,
        "commissions": 663,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8605,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 1849,
        "ordered_items": 148,
        "sell_earnings": 753,
        "commissions": 753,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8282,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 2145,
        "ordered_items": 159,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7515,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 2127,
        "ordered_items": 158,
        "sell_earnings": 815,
        "commissions": 815,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8677,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1651,
        "ordered_items": 104,
        "sell_earnings": 473,
        "commissions": 473,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7020,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1627,
        "ordered_items": 108,
        "sell_earnings": 605,
        "commissions": 605,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6842,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 1713,
        "ordered_items": 176,
        "sell_earnings": 651,
        "commissions": 651,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8044,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 1689,
        "ordered_items": 180,
        "sell_earnings": 783,
        "commissions": 783,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7866,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1224,
        "ordered_items": 141,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7007,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 2116,
        "ordered_items": 143,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7879,
        "bonus": 2
    }
];