export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1599,
        "ordered_items": 117,
        "sell_earnings": 538,
        "commissions": 538,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5961,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1510,
        "ordered_items": 102,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5726,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1577,
        "ordered_items": 121,
        "sell_earnings": 559,
        "commissions": 559,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5762,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 1655,
        "ordered_items": 153,
        "sell_earnings": 657,
        "commissions": 657,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8644,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1722,
        "ordered_items": 172,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8680,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 1633,
        "ordered_items": 157,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8445,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1336,
        "ordered_items": 127,
        "sell_earnings": 551,
        "commissions": 551,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6091,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1540,
        "ordered_items": 115,
        "sell_earnings": 467,
        "commissions": 467,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6174,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1295,
        "ordered_items": 115,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6953,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1937,
        "ordered_items": 159,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7453,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 1692,
        "ordered_items": 159,
        "sell_earnings": 749,
        "commissions": 749,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8232,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1896,
        "ordered_items": 147,
        "sell_earnings": 665,
        "commissions": 665,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8315,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1170,
        "ordered_items": 110,
        "sell_earnings": 468,
        "commissions": 468,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5471,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 2062,
        "ordered_items": 164,
        "sell_earnings": 748,
        "commissions": 748,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8935,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1551,
        "ordered_items": 131,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5953,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1681,
        "ordered_items": 143,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8453,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1477,
        "ordered_items": 109,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6228,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1268,
        "ordered_items": 97,
        "sell_earnings": 516,
        "commissions": 516,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6890,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1322,
        "ordered_items": 119,
        "sell_earnings": 567,
        "commissions": 567,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6414,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1561,
        "ordered_items": 101,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6152,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 1671,
        "ordered_items": 173,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8254,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1910,
        "ordered_items": 155,
        "sell_earnings": 649,
        "commissions": 649,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7992,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 1964,
        "ordered_items": 177,
        "sell_earnings": 700,
        "commissions": 700,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7516,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1755,
        "ordered_items": 165,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8178,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1314,
        "ordered_items": 125,
        "sell_earnings": 470,
        "commissions": 470,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5319,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1575,
        "ordered_items": 128,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5536,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1657,
        "ordered_items": 146,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8870,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1918,
        "ordered_items": 149,
        "sell_earnings": 746,
        "commissions": 746,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9087,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1460,
        "ordered_items": 135,
        "sell_earnings": 521,
        "commissions": 521,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5203,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1772,
        "ordered_items": 139,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9203,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];