export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1196,
        "ordered_items": 114,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6455,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1481,
        "ordered_items": 131,
        "sell_earnings": 524,
        "commissions": 524,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6305,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1212,
        "ordered_items": 102,
        "sell_earnings": 497,
        "commissions": 497,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6496,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 2020,
        "ordered_items": 172,
        "sell_earnings": 719,
        "commissions": 719,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7910,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 1751,
        "ordered_items": 143,
        "sell_earnings": 692,
        "commissions": 692,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8101,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 2036,
        "ordered_items": 160,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7951,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1580,
        "ordered_items": 131,
        "sell_earnings": 571,
        "commissions": 571,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6206,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1613,
        "ordered_items": 108,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6499,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1190,
        "ordered_items": 134,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6773,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 2042,
        "ordered_items": 140,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7633,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1619,
        "ordered_items": 166,
        "sell_earnings": 753,
        "commissions": 753,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7907,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 1652,
        "ordered_items": 143,
        "sell_earnings": 645,
        "commissions": 645,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8200,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1367,
        "ordered_items": 107,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5561,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 1865,
        "ordered_items": 167,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8845,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1325,
        "ordered_items": 131,
        "sell_earnings": 432,
        "commissions": 432,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7188,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 1907,
        "ordered_items": 143,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7218,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1204,
        "ordered_items": 98,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5055,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1196,
        "ordered_items": 132,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6068,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1490,
        "ordered_items": 100,
        "sell_earnings": 467,
        "commissions": 467,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7173,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1297,
        "ordered_items": 129,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6480,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 1935,
        "ordered_items": 145,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7926,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 1742,
        "ordered_items": 174,
        "sell_earnings": 749,
        "commissions": 749,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7233,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 2036,
        "ordered_items": 142,
        "sell_earnings": 725,
        "commissions": 725,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8338,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 2028,
        "ordered_items": 176,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9351,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1177,
        "ordered_items": 121,
        "sell_earnings": 487,
        "commissions": 487,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7006,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1420,
        "ordered_items": 125,
        "sell_earnings": 535,
        "commissions": 535,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6601,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1812,
        "ordered_items": 149,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7805,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 2055,
        "ordered_items": 153,
        "sell_earnings": 729,
        "commissions": 729,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7400,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1556,
        "ordered_items": 120,
        "sell_earnings": 583,
        "commissions": 583,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6541,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 1676,
        "ordered_items": 154,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7865,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];