export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1449,
        "ordered_items": 121,
        "sell_earnings": 589,
        "commissions": 589,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6450,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1596,
        "ordered_items": 129,
        "sell_earnings": 542,
        "commissions": 542,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5125,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1292,
        "ordered_items": 112,
        "sell_earnings": 502,
        "commissions": 502,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5279,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 1940,
        "ordered_items": 162,
        "sell_earnings": 714,
        "commissions": 714,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9127,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 1636,
        "ordered_items": 145,
        "sell_earnings": 674,
        "commissions": 674,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9281,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 1783,
        "ordered_items": 153,
        "sell_earnings": 627,
        "commissions": 627,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7956,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1474,
        "ordered_items": 126,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5691,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1269,
        "ordered_items": 127,
        "sell_earnings": 533,
        "commissions": 533,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6104,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1321,
        "ordered_items": 117,
        "sell_earnings": 570,
        "commissions": 570,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5189,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 1911,
        "ordered_items": 157,
        "sell_earnings": 646,
        "commissions": 646,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9217,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 1963,
        "ordered_items": 147,
        "sell_earnings": 683,
        "commissions": 683,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8302,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 1758,
        "ordered_items": 148,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8715,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1506,
        "ordered_items": 109,
        "sell_earnings": 509,
        "commissions": 509,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6761,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 1726,
        "ordered_items": 165,
        "sell_earnings": 707,
        "commissions": 707,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7645,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1379,
        "ordered_items": 129,
        "sell_earnings": 522,
        "commissions": 522,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5912,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 1853,
        "ordered_items": 145,
        "sell_earnings": 694,
        "commissions": 694,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8494,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1262,
        "ordered_items": 108,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6885,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1205,
        "ordered_items": 135,
        "sell_earnings": 443,
        "commissions": 443,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6536,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1292,
        "ordered_items": 100,
        "sell_earnings": 535,
        "commissions": 535,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6912,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1395,
        "ordered_items": 110,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5081,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 1837,
        "ordered_items": 164,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9325,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1940,
        "ordered_items": 174,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7494,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 2027,
        "ordered_items": 139,
        "sell_earnings": 773,
        "commissions": 773,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7870,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 1970,
        "ordered_items": 166,
        "sell_earnings": 651,
        "commissions": 651,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7521,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1578,
        "ordered_items": 126,
        "sell_earnings": 557,
        "commissions": 557,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5654,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1390,
        "ordered_items": 111,
        "sell_earnings": 575,
        "commissions": 575,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6821,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 1842,
        "ordered_items": 163,
        "sell_earnings": 641,
        "commissions": 641,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7585,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1654,
        "ordered_items": 148,
        "sell_earnings": 659,
        "commissions": 659,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8752,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1137,
        "ordered_items": 98,
        "sell_earnings": 592,
        "commissions": 592,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6542,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 2095,
        "ordered_items": 176,
        "sell_earnings": 624,
        "commissions": 624,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7864,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];