export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1166,
        "ordered_items": 103,
        "sell_earnings": 489,
        "commissions": 489,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6262,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1314,
        "ordered_items": 136,
        "sell_earnings": 531,
        "commissions": 531,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5082,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1267,
        "ordered_items": 137,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6550,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 1965,
        "ordered_items": 137,
        "sell_earnings": 753,
        "commissions": 753,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7856,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 1918,
        "ordered_items": 138,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9324,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 2066,
        "ordered_items": 171,
        "sell_earnings": 727,
        "commissions": 727,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8144,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1579,
        "ordered_items": 116,
        "sell_earnings": 436,
        "commissions": 436,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5928,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1339,
        "ordered_items": 115,
        "sell_earnings": 445,
        "commissions": 445,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6732,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1154,
        "ordered_items": 112,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5666,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 2078,
        "ordered_items": 162,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8740,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 1893,
        "ordered_items": 159,
        "sell_earnings": 771,
        "commissions": 771,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7674,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 1653,
        "ordered_items": 158,
        "sell_earnings": 780,
        "commissions": 780,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8478,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1411,
        "ordered_items": 97,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6123,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 1821,
        "ordered_items": 177,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8283,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1358,
        "ordered_items": 98,
        "sell_earnings": 430,
        "commissions": 430,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5557,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 1874,
        "ordered_items": 176,
        "sell_earnings": 786,
        "commissions": 786,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8849,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1251,
        "ordered_items": 99,
        "sell_earnings": 498,
        "commissions": 498,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5997,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1160,
        "ordered_items": 126,
        "sell_earnings": 536,
        "commissions": 536,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5799,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1475,
        "ordered_items": 137,
        "sell_earnings": 526,
        "commissions": 526,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5259,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1194,
        "ordered_items": 115,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5210,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 2038,
        "ordered_items": 159,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9196,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 1757,
        "ordered_items": 137,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9147,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 2072,
        "ordered_items": 148,
        "sell_earnings": 680,
        "commissions": 680,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8607,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 1981,
        "ordered_items": 175,
        "sell_earnings": 718,
        "commissions": 718,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8409,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1339,
        "ordered_items": 114,
        "sell_earnings": 447,
        "commissions": 447,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5959,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1508,
        "ordered_items": 97,
        "sell_earnings": 513,
        "commissions": 513,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5299,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 1724,
        "ordered_items": 177,
        "sell_earnings": 703,
        "commissions": 703,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9107,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 1893,
        "ordered_items": 160,
        "sell_earnings": 769,
        "commissions": 769,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8447,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1559,
        "ordered_items": 110,
        "sell_earnings": 488,
        "commissions": 488,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6235,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 1673,
        "ordered_items": 164,
        "sell_earnings": 728,
        "commissions": 728,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8171,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];