export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1345,
        "ordered_items": 122,
        "sell_earnings": 455,
        "commissions": 455,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6164,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1219,
        "ordered_items": 115,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6632,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1366,
        "ordered_items": 126,
        "sell_earnings": 549,
        "commissions": 549,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6178,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 1974,
        "ordered_items": 158,
        "sell_earnings": 707,
        "commissions": 707,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8708,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 2121,
        "ordered_items": 169,
        "sell_earnings": 800,
        "commissions": 800,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8254,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 1995,
        "ordered_items": 162,
        "sell_earnings": 801,
        "commissions": 801,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8722,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1518,
        "ordered_items": 108,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6028,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1348,
        "ordered_items": 106,
        "sell_earnings": 531,
        "commissions": 531,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5465,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1546,
        "ordered_items": 135,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6077,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 1794,
        "ordered_items": 149,
        "sell_earnings": 691,
        "commissions": 691,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8809,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 1992,
        "ordered_items": 178,
        "sell_earnings": 725,
        "commissions": 725,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9421,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 1822,
        "ordered_items": 176,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8858,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1388,
        "ordered_items": 126,
        "sell_earnings": 533,
        "commissions": 533,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6075,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 1952,
        "ordered_items": 158,
        "sell_earnings": 723,
        "commissions": 723,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8811,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1376,
        "ordered_items": 107,
        "sell_earnings": 544,
        "commissions": 544,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7076,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 1964,
        "ordered_items": 177,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7810,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1478,
        "ordered_items": 139,
        "sell_earnings": 584,
        "commissions": 584,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5477,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1202,
        "ordered_items": 142,
        "sell_earnings": 526,
        "commissions": 526,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6407,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1632,
        "ordered_items": 105,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6707,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1344,
        "ordered_items": 122,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5740,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 1996,
        "ordered_items": 162,
        "sell_earnings": 658,
        "commissions": 658,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9146,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 1708,
        "ordered_items": 179,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8179,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 2138,
        "ordered_items": 142,
        "sell_earnings": 730,
        "commissions": 730,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8479,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 1862,
        "ordered_items": 145,
        "sell_earnings": 672,
        "commissions": 672,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9409,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1563,
        "ordered_items": 104,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5583,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1366,
        "ordered_items": 127,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5310,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 1974,
        "ordered_items": 157,
        "sell_earnings": 752,
        "commissions": 752,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9576,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 1777,
        "ordered_items": 180,
        "sell_earnings": 638,
        "commissions": 638,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9303,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1460,
        "ordered_items": 102,
        "sell_earnings": 452,
        "commissions": 452,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6869,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 1880,
        "ordered_items": 182,
        "sell_earnings": 804,
        "commissions": 804,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8017,
        "bonus": 2
    }
];