export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1482,
        "ordered_items": 108,
        "sell_earnings": 539,
        "commissions": 539,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5263,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1258,
        "ordered_items": 114,
        "sell_earnings": 581,
        "commissions": 581,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5261,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1603,
        "ordered_items": 134,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5156,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 1629,
        "ordered_items": 140,
        "sell_earnings": 720,
        "commissions": 720,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9250,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 1974,
        "ordered_items": 160,
        "sell_earnings": 635,
        "commissions": 635,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9145,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 1750,
        "ordered_items": 166,
        "sell_earnings": 677,
        "commissions": 677,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9143,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1531,
        "ordered_items": 132,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5595,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1602,
        "ordered_items": 111,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5378,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1310,
        "ordered_items": 115,
        "sell_earnings": 511,
        "commissions": 511,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5501,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 1922,
        "ordered_items": 159,
        "sell_earnings": 705,
        "commissions": 705,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8905,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 1630,
        "ordered_items": 163,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9028,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1701,
        "ordered_items": 142,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8811,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1585,
        "ordered_items": 100,
        "sell_earnings": 476,
        "commissions": 476,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5050,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 1647,
        "ordered_items": 174,
        "sell_earnings": 740,
        "commissions": 740,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9356,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1392,
        "ordered_items": 110,
        "sell_earnings": 432,
        "commissions": 432,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6535,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 1840,
        "ordered_items": 164,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7871,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1453,
        "ordered_items": 122,
        "sell_earnings": 467,
        "commissions": 467,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6196,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1434,
        "ordered_items": 129,
        "sell_earnings": 601,
        "commissions": 601,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5497,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1230,
        "ordered_items": 128,
        "sell_earnings": 594,
        "commissions": 594,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6724,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1586,
        "ordered_items": 121,
        "sell_earnings": 497,
        "commissions": 497,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6433,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 1646,
        "ordered_items": 153,
        "sell_earnings": 719,
        "commissions": 719,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7973,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 2002,
        "ordered_items": 146,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7682,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 1798,
        "ordered_items": 145,
        "sell_earnings": 615,
        "commissions": 615,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8909,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1779,
        "ordered_items": 152,
        "sell_earnings": 749,
        "commissions": 749,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8210,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1584,
        "ordered_items": 114,
        "sell_earnings": 493,
        "commissions": 493,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5933,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1428,
        "ordered_items": 98,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6154,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 1804,
        "ordered_items": 176,
        "sell_earnings": 676,
        "commissions": 676,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8252,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 1648,
        "ordered_items": 160,
        "sell_earnings": 723,
        "commissions": 723,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8473,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1295,
        "ordered_items": 117,
        "sell_earnings": 484,
        "commissions": 484,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5156,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 1937,
        "ordered_items": 157,
        "sell_earnings": 732,
        "commissions": 732,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9250,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];