export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1523,
        "ordered_items": 117,
        "sell_earnings": 538,
        "commissions": 538,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5778,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1220,
        "ordered_items": 117,
        "sell_earnings": 455,
        "commissions": 455,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5502,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1360,
        "ordered_items": 130,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6868,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 1980,
        "ordered_items": 154,
        "sell_earnings": 793,
        "commissions": 793,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 168,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8018,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 2120,
        "ordered_items": 167,
        "sell_earnings": 801,
        "commissions": 801,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 168,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9384,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 1817,
        "ordered_items": 167,
        "sell_earnings": 718,
        "commissions": 718,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 167,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9108,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1540,
        "ordered_items": 122,
        "sell_earnings": 578,
        "commissions": 578,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6235,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1621,
        "ordered_items": 136,
        "sell_earnings": 492,
        "commissions": 492,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5799,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1591,
        "ordered_items": 109,
        "sell_earnings": 576,
        "commissions": 576,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7098,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 1749,
        "ordered_items": 175,
        "sell_earnings": 680,
        "commissions": 680,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7788,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 1719,
        "ordered_items": 148,
        "sell_earnings": 764,
        "commissions": 764,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9087,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 1800,
        "ordered_items": 162,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8651,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1190,
        "ordered_items": 135,
        "sell_earnings": 449,
        "commissions": 449,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7121,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 2150,
        "ordered_items": 149,
        "sell_earnings": 807,
        "commissions": 807,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7765,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1204,
        "ordered_items": 140,
        "sell_earnings": 457,
        "commissions": 457,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6620,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 2136,
        "ordered_items": 144,
        "sell_earnings": 799,
        "commissions": 799,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8266,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1297,
        "ordered_items": 107,
        "sell_earnings": 512,
        "commissions": 512,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6811,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1503,
        "ordered_items": 115,
        "sell_earnings": 567,
        "commissions": 567,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6448,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1581,
        "ordered_items": 106,
        "sell_earnings": 468,
        "commissions": 468,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6121,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1452,
        "ordered_items": 111,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6126,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 1888,
        "ordered_items": 173,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8760,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 1759,
        "ordered_items": 178,
        "sell_earnings": 788,
        "commissions": 788,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 165,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8765,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 1837,
        "ordered_items": 169,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8438,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 2043,
        "ordered_items": 177,
        "sell_earnings": 744,
        "commissions": 744,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8075,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1292,
        "ordered_items": 131,
        "sell_earnings": 510,
        "commissions": 510,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6644,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1342,
        "ordered_items": 130,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7192,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 1998,
        "ordered_items": 154,
        "sell_earnings": 650,
        "commissions": 650,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7694,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 2048,
        "ordered_items": 153,
        "sell_earnings": 746,
        "commissions": 746,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8242,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1418,
        "ordered_items": 135,
        "sell_earnings": 543,
        "commissions": 543,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6154,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 1922,
        "ordered_items": 149,
        "sell_earnings": 713,
        "commissions": 713,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 168,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8732,
        "bonus": 2
    }
];