export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1353,
        "ordered_items": 109,
        "sell_earnings": 576,
        "commissions": 576,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5139,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1569,
        "ordered_items": 131,
        "sell_earnings": 469,
        "commissions": 469,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6518,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1180,
        "ordered_items": 136,
        "sell_earnings": 472,
        "commissions": 472,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5476,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 2052,
        "ordered_items": 138,
        "sell_earnings": 744,
        "commissions": 744,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8930,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1663,
        "ordered_items": 143,
        "sell_earnings": 747,
        "commissions": 747,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7888,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 1879,
        "ordered_items": 165,
        "sell_earnings": 640,
        "commissions": 640,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9267,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1611,
        "ordered_items": 116,
        "sell_earnings": 479,
        "commissions": 479,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5251,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1344,
        "ordered_items": 118,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6411,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1316,
        "ordered_items": 119,
        "sell_earnings": 439,
        "commissions": 439,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6514,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1916,
        "ordered_items": 155,
        "sell_earnings": 777,
        "commissions": 777,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7892,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 1888,
        "ordered_items": 156,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7995,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1621,
        "ordered_items": 158,
        "sell_earnings": 737,
        "commissions": 737,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9155,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1400,
        "ordered_items": 112,
        "sell_earnings": 588,
        "commissions": 588,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7068,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1832,
        "ordered_items": 162,
        "sell_earnings": 628,
        "commissions": 628,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7338,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1288,
        "ordered_items": 100,
        "sell_earnings": 595,
        "commissions": 595,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7160,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1944,
        "ordered_items": 174,
        "sell_earnings": 621,
        "commissions": 621,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7246,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1499,
        "ordered_items": 115,
        "sell_earnings": 509,
        "commissions": 509,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6234,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1603,
        "ordered_items": 100,
        "sell_earnings": 437,
        "commissions": 437,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6172,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1482,
        "ordered_items": 98,
        "sell_earnings": 579,
        "commissions": 579,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7002,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1534,
        "ordered_items": 102,
        "sell_earnings": 549,
        "commissions": 549,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5680,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 1698,
        "ordered_items": 172,
        "sell_earnings": 667,
        "commissions": 667,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8726,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1750,
        "ordered_items": 176,
        "sell_earnings": 637,
        "commissions": 637,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7404,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 1629,
        "ordered_items": 174,
        "sell_earnings": 779,
        "commissions": 779,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8234,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1733,
        "ordered_items": 159,
        "sell_earnings": 707,
        "commissions": 707,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8172,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1395,
        "ordered_items": 108,
        "sell_earnings": 545,
        "commissions": 545,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6569,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1400,
        "ordered_items": 128,
        "sell_earnings": 473,
        "commissions": 473,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5207,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1832,
        "ordered_items": 146,
        "sell_earnings": 743,
        "commissions": 743,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9199,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1837,
        "ordered_items": 166,
        "sell_earnings": 671,
        "commissions": 671,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7837,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1239,
        "ordered_items": 123,
        "sell_earnings": 497,
        "commissions": 497,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5509,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1993,
        "ordered_items": 151,
        "sell_earnings": 719,
        "commissions": 719,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8897,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];