export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 1536,
        "ordered_items": 135,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6164,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 1202,
        "ordered_items": 135,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6613,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 1347,
        "ordered_items": 135,
        "sell_earnings": 536,
        "commissions": 536,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6608,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 1993,
        "ordered_items": 149,
        "sell_earnings": 720,
        "commissions": 720,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8278,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 2138,
        "ordered_items": 149,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8273,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 1804,
        "ordered_items": 149,
        "sell_earnings": 741,
        "commissions": 741,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 169,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8722,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 1218,
        "ordered_items": 120,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5930,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 1241,
        "ordered_items": 132,
        "sell_earnings": 538,
        "commissions": 538,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7293,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 1212,
        "ordered_items": 130,
        "sell_earnings": 492,
        "commissions": 492,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6180,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 2128,
        "ordered_items": 154,
        "sell_earnings": 764,
        "commissions": 764,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8706,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 2099,
        "ordered_items": 152,
        "sell_earnings": 718,
        "commissions": 718,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7593,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 2122,
        "ordered_items": 164,
        "sell_earnings": 806,
        "commissions": 806,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 167,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8956,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 1422,
        "ordered_items": 113,
        "sell_earnings": 600,
        "commissions": 600,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5524,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 1918,
        "ordered_items": 171,
        "sell_earnings": 656,
        "commissions": 656,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9362,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 1418,
        "ordered_items": 107,
        "sell_earnings": 552,
        "commissions": 552,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7422,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 1922,
        "ordered_items": 177,
        "sell_earnings": 704,
        "commissions": 704,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7464,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 1602,
        "ordered_items": 121,
        "sell_earnings": 601,
        "commissions": 601,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6653,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 1341,
        "ordered_items": 131,
        "sell_earnings": 468,
        "commissions": 468,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6490,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 1620,
        "ordered_items": 103,
        "sell_earnings": 443,
        "commissions": 443,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5733,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 1504,
        "ordered_items": 115,
        "sell_earnings": 489,
        "commissions": 489,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6775,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 1836,
        "ordered_items": 169,
        "sell_earnings": 767,
        "commissions": 767,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8111,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 1720,
        "ordered_items": 181,
        "sell_earnings": 813,
        "commissions": 813,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9153,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 1999,
        "ordered_items": 153,
        "sell_earnings": 788,
        "commissions": 788,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8396,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 1738,
        "ordered_items": 163,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8233,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 1561,
        "ordered_items": 110,
        "sell_earnings": 473,
        "commissions": 473,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6618,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 1269,
        "ordered_items": 102,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7349,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 2071,
        "ordered_items": 182,
        "sell_earnings": 776,
        "commissions": 776,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7537,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 1779,
        "ordered_items": 174,
        "sell_earnings": 783,
        "commissions": 783,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8268,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 1397,
        "ordered_items": 116,
        "sell_earnings": 542,
        "commissions": 542,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7244,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 1943,
        "ordered_items": 168,
        "sell_earnings": 714,
        "commissions": 714,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7642,
        "bonus": 1
    }
];