export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1147,
        "ordered_items": 111,
        "sell_earnings": 547,
        "commissions": 547,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5233,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1313,
        "ordered_items": 112,
        "sell_earnings": 444,
        "commissions": 444,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5563,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1480,
        "ordered_items": 124,
        "sell_earnings": 580,
        "commissions": 580,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5770,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 1752,
        "ordered_items": 150,
        "sell_earnings": 636,
        "commissions": 636,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8636,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 1919,
        "ordered_items": 162,
        "sell_earnings": 772,
        "commissions": 772,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8843,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 2085,
        "ordered_items": 163,
        "sell_earnings": 669,
        "commissions": 669,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9173,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1132,
        "ordered_items": 102,
        "sell_earnings": 442,
        "commissions": 442,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5554,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1254,
        "ordered_items": 106,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6748,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1145,
        "ordered_items": 102,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5700,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 2087,
        "ordered_items": 172,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8706,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1978,
        "ordered_items": 168,
        "sell_earnings": 651,
        "commissions": 651,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7658,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 2100,
        "ordered_items": 172,
        "sell_earnings": 774,
        "commissions": 774,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8852,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1386,
        "ordered_items": 126,
        "sell_earnings": 487,
        "commissions": 487,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6099,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 1846,
        "ordered_items": 148,
        "sell_earnings": 729,
        "commissions": 729,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8307,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1323,
        "ordered_items": 109,
        "sell_earnings": 574,
        "commissions": 574,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6518,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 1909,
        "ordered_items": 165,
        "sell_earnings": 642,
        "commissions": 642,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7888,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1497,
        "ordered_items": 133,
        "sell_earnings": 493,
        "commissions": 493,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6768,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1261,
        "ordered_items": 115,
        "sell_earnings": 545,
        "commissions": 545,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6428,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1498,
        "ordered_items": 135,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6268,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1454,
        "ordered_items": 100,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6144,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 1778,
        "ordered_items": 174,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8262,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 1734,
        "ordered_items": 139,
        "sell_earnings": 720,
        "commissions": 720,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8138,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 1971,
        "ordered_items": 159,
        "sell_earnings": 671,
        "commissions": 671,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7978,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 1735,
        "ordered_items": 141,
        "sell_earnings": 723,
        "commissions": 723,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7638,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1545,
        "ordered_items": 119,
        "sell_earnings": 465,
        "commissions": 465,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5452,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1280,
        "ordered_items": 124,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6548,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1952,
        "ordered_items": 150,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7858,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 1687,
        "ordered_items": 155,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8954,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1474,
        "ordered_items": 103,
        "sell_earnings": 554,
        "commissions": 554,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5712,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 1758,
        "ordered_items": 171,
        "sell_earnings": 662,
        "commissions": 662,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8694,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];