export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1468,
        "ordered_items": 107,
        "sell_earnings": 514,
        "commissions": 514,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5253,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1599,
        "ordered_items": 120,
        "sell_earnings": 451,
        "commissions": 451,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5787,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1555,
        "ordered_items": 111,
        "sell_earnings": 513,
        "commissions": 513,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6715,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 1677,
        "ordered_items": 163,
        "sell_earnings": 703,
        "commissions": 703,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7691,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 1633,
        "ordered_items": 154,
        "sell_earnings": 765,
        "commissions": 765,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8619,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 1764,
        "ordered_items": 167,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9153,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1400,
        "ordered_items": 104,
        "sell_earnings": 521,
        "commissions": 521,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5264,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1167,
        "ordered_items": 107,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7013,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1340,
        "ordered_items": 125,
        "sell_earnings": 508,
        "commissions": 508,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5806,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 1892,
        "ordered_items": 149,
        "sell_earnings": 708,
        "commissions": 708,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8600,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 2065,
        "ordered_items": 167,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7393,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 1832,
        "ordered_items": 170,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9142,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1396,
        "ordered_items": 128,
        "sell_earnings": 578,
        "commissions": 578,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6662,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 1836,
        "ordered_items": 146,
        "sell_earnings": 638,
        "commissions": 638,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7744,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1598,
        "ordered_items": 124,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5630,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 1634,
        "ordered_items": 150,
        "sell_earnings": 752,
        "commissions": 752,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8776,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1330,
        "ordered_items": 130,
        "sell_earnings": 440,
        "commissions": 440,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7021,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1186,
        "ordered_items": 114,
        "sell_earnings": 516,
        "commissions": 516,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7044,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1465,
        "ordered_items": 132,
        "sell_earnings": 486,
        "commissions": 486,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5926,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1494,
        "ordered_items": 99,
        "sell_earnings": 585,
        "commissions": 585,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5485,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 1738,
        "ordered_items": 175,
        "sell_earnings": 631,
        "commissions": 631,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8921,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 1767,
        "ordered_items": 142,
        "sell_earnings": 730,
        "commissions": 730,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8480,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 2046,
        "ordered_items": 160,
        "sell_earnings": 700,
        "commissions": 700,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7362,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 1902,
        "ordered_items": 144,
        "sell_earnings": 776,
        "commissions": 776,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7385,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1264,
        "ordered_items": 120,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5491,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1552,
        "ordered_items": 101,
        "sell_earnings": 433,
        "commissions": 433,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5158,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 1680,
        "ordered_items": 173,
        "sell_earnings": 783,
        "commissions": 783,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9248,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 1968,
        "ordered_items": 154,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8915,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1470,
        "ordered_items": 122,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6593,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 1762,
        "ordered_items": 152,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7813,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];