export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1247,
        "ordered_items": 137,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5877,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1479,
        "ordered_items": 126,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6772,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1375,
        "ordered_items": 100,
        "sell_earnings": 611,
        "commissions": 611,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5629,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 1965,
        "ordered_items": 184,
        "sell_earnings": 645,
        "commissions": 645,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9257,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 1861,
        "ordered_items": 158,
        "sell_earnings": 792,
        "commissions": 792,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8114,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 2093,
        "ordered_items": 147,
        "sell_earnings": 728,
        "commissions": 728,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9009,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1320,
        "ordered_items": 109,
        "sell_earnings": 514,
        "commissions": 514,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6588,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1370,
        "ordered_items": 131,
        "sell_earnings": 577,
        "commissions": 577,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5473,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1369,
        "ordered_items": 103,
        "sell_earnings": 474,
        "commissions": 474,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6891,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 1971,
        "ordered_items": 181,
        "sell_earnings": 782,
        "commissions": 782,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7995,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 1970,
        "ordered_items": 153,
        "sell_earnings": 679,
        "commissions": 679,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 166,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9413,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 2020,
        "ordered_items": 175,
        "sell_earnings": 742,
        "commissions": 742,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 165,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8298,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1529,
        "ordered_items": 142,
        "sell_earnings": 486,
        "commissions": 486,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7097,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 1811,
        "ordered_items": 142,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7789,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1332,
        "ordered_items": 102,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5783,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 2008,
        "ordered_items": 182,
        "sell_earnings": 765,
        "commissions": 765,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 168,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9103,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1226,
        "ordered_items": 131,
        "sell_earnings": 575,
        "commissions": 575,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5804,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1406,
        "ordered_items": 134,
        "sell_earnings": 519,
        "commissions": 519,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5779,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1430,
        "ordered_items": 129,
        "sell_earnings": 498,
        "commissions": 498,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7228,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1464,
        "ordered_items": 138,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5494,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 1876,
        "ordered_items": 146,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9392,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 1910,
        "ordered_items": 155,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 166,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7658,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 1934,
        "ordered_items": 150,
        "sell_earnings": 737,
        "commissions": 737,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9107,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 2114,
        "ordered_items": 153,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9082,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1469,
        "ordered_items": 137,
        "sell_earnings": 462,
        "commissions": 462,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7398,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1466,
        "ordered_items": 139,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6536,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 1874,
        "ordered_items": 145,
        "sell_earnings": 798,
        "commissions": 798,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8350,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 1871,
        "ordered_items": 147,
        "sell_earnings": 794,
        "commissions": 794,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7488,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1335,
        "ordered_items": 123,
        "sell_earnings": 505,
        "commissions": 505,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6150,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 2005,
        "ordered_items": 161,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8736,
        "bonus": 2
    }
];