export let mar = [
    {
        "month": "Mar",
        "day": "01",
        "clicks": 1452,
        "ordered_items": 105,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6144,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "02",
        "clicks": 1334,
        "ordered_items": 99,
        "sell_earnings": 544,
        "commissions": 544,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6510,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "03",
        "clicks": 1577,
        "ordered_items": 121,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7174,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "04",
        "clicks": 1655,
        "ordered_items": 153,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7232,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "05",
        "clicks": 1898,
        "ordered_items": 175,
        "sell_earnings": 672,
        "commissions": 672,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7896,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "06",
        "clicks": 1780,
        "ordered_items": 169,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8262,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "07",
        "clicks": 1210,
        "ordered_items": 122,
        "sell_earnings": 582,
        "commissions": 582,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5404,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "08",
        "clicks": 1340,
        "ordered_items": 126,
        "sell_earnings": 513,
        "commissions": 513,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6290,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "09",
        "clicks": 1559,
        "ordered_items": 134,
        "sell_earnings": 473,
        "commissions": 473,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5115,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "10",
        "clicks": 1673,
        "ordered_items": 140,
        "sell_earnings": 743,
        "commissions": 743,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9291,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "11",
        "clicks": 1892,
        "ordered_items": 148,
        "sell_earnings": 703,
        "commissions": 703,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8116,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "12",
        "clicks": 2022,
        "ordered_items": 152,
        "sell_earnings": 634,
        "commissions": 634,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9002,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "13",
        "clicks": 1554,
        "ordered_items": 101,
        "sell_earnings": 601,
        "commissions": 601,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6011,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "14",
        "clicks": 1678,
        "ordered_items": 173,
        "sell_earnings": 615,
        "commissions": 615,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8395,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "15",
        "clicks": 1319,
        "ordered_items": 103,
        "sell_earnings": 566,
        "commissions": 566,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6134,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "16",
        "clicks": 1913,
        "ordered_items": 171,
        "sell_earnings": 650,
        "commissions": 650,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8272,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "17",
        "clicks": 1542,
        "ordered_items": 104,
        "sell_earnings": 493,
        "commissions": 493,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5849,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "18",
        "clicks": 1568,
        "ordered_items": 125,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5381,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "19",
        "clicks": 1419,
        "ordered_items": 119,
        "sell_earnings": 600,
        "commissions": 600,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5858,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "20",
        "clicks": 1140,
        "ordered_items": 109,
        "sell_earnings": 563,
        "commissions": 563,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6373,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "21",
        "clicks": 2092,
        "ordered_items": 165,
        "sell_earnings": 653,
        "commissions": 653,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8033,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "22",
        "clicks": 1813,
        "ordered_items": 155,
        "sell_earnings": 616,
        "commissions": 616,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8548,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "23",
        "clicks": 1664,
        "ordered_items": 149,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9025,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "24",
        "clicks": 1690,
        "ordered_items": 170,
        "sell_earnings": 723,
        "commissions": 723,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8557,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "25",
        "clicks": 1379,
        "ordered_items": 102,
        "sell_earnings": 607,
        "commissions": 607,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5352,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "26",
        "clicks": 1478,
        "ordered_items": 120,
        "sell_earnings": 469,
        "commissions": 469,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5755,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "27",
        "clicks": 1754,
        "ordered_items": 154,
        "sell_earnings": 747,
        "commissions": 747,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8651,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "28",
        "clicks": 1853,
        "ordered_items": 172,
        "sell_earnings": 609,
        "commissions": 609,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9054,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "29",
        "clicks": 1437,
        "ordered_items": 137,
        "sell_earnings": 478,
        "commissions": 478,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5498,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "30",
        "clicks": 1795,
        "ordered_items": 137,
        "sell_earnings": 738,
        "commissions": 738,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8908,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];