export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1471,
        "ordered_items": 127,
        "sell_earnings": 544,
        "commissions": 544,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6494,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1239,
        "ordered_items": 113,
        "sell_earnings": 442,
        "commissions": 442,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7169,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1326,
        "ordered_items": 133,
        "sell_earnings": 445,
        "commissions": 445,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6214,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 1906,
        "ordered_items": 141,
        "sell_earnings": 771,
        "commissions": 771,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8192,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 1993,
        "ordered_items": 161,
        "sell_earnings": 774,
        "commissions": 774,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7237,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 1761,
        "ordered_items": 147,
        "sell_earnings": 672,
        "commissions": 672,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7912,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1429,
        "ordered_items": 106,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6243,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1414,
        "ordered_items": 102,
        "sell_earnings": 582,
        "commissions": 582,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6025,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1592,
        "ordered_items": 135,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7118,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 1640,
        "ordered_items": 139,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7288,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 1818,
        "ordered_items": 172,
        "sell_earnings": 634,
        "commissions": 634,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8381,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1803,
        "ordered_items": 168,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8163,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1333,
        "ordered_items": 137,
        "sell_earnings": 453,
        "commissions": 453,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5993,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 1899,
        "ordered_items": 137,
        "sell_earnings": 763,
        "commissions": 763,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8413,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1390,
        "ordered_items": 136,
        "sell_earnings": 489,
        "commissions": 489,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5880,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 1842,
        "ordered_items": 138,
        "sell_earnings": 727,
        "commissions": 727,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8526,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1548,
        "ordered_items": 108,
        "sell_earnings": 583,
        "commissions": 583,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6804,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1292,
        "ordered_items": 126,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5583,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1440,
        "ordered_items": 104,
        "sell_earnings": 470,
        "commissions": 470,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5229,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1574,
        "ordered_items": 107,
        "sell_earnings": 467,
        "commissions": 467,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5109,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 1658,
        "ordered_items": 167,
        "sell_earnings": 749,
        "commissions": 749,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9297,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 1792,
        "ordered_items": 170,
        "sell_earnings": 746,
        "commissions": 746,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9177,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 1940,
        "ordered_items": 148,
        "sell_earnings": 725,
        "commissions": 725,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8823,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1684,
        "ordered_items": 166,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7602,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1468,
        "ordered_items": 129,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6189,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1377,
        "ordered_items": 122,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6279,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 1855,
        "ordered_items": 152,
        "sell_earnings": 610,
        "commissions": 610,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8127,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 1764,
        "ordered_items": 145,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8217,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1491,
        "ordered_items": 107,
        "sell_earnings": 525,
        "commissions": 525,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6963,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 1741,
        "ordered_items": 167,
        "sell_earnings": 691,
        "commissions": 691,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7443,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];