export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1272,
        "ordered_items": 111,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5216,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1506,
        "ordered_items": 123,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7230,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1501,
        "ordered_items": 134,
        "sell_earnings": 588,
        "commissions": 588,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6140,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 1839,
        "ordered_items": 150,
        "sell_earnings": 668,
        "commissions": 668,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8746,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 1834,
        "ordered_items": 161,
        "sell_earnings": 658,
        "commissions": 658,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7656,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 2068,
        "ordered_items": 173,
        "sell_earnings": 728,
        "commissions": 728,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9670,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1222,
        "ordered_items": 125,
        "sell_earnings": 490,
        "commissions": 490,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6491,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1179,
        "ordered_items": 125,
        "sell_earnings": 564,
        "commissions": 564,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6983,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1449,
        "ordered_items": 133,
        "sell_earnings": 514,
        "commissions": 514,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7347,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 1891,
        "ordered_items": 151,
        "sell_earnings": 742,
        "commissions": 742,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7539,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 2161,
        "ordered_items": 159,
        "sell_earnings": 692,
        "commissions": 692,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7903,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 2118,
        "ordered_items": 159,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8395,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1450,
        "ordered_items": 128,
        "sell_earnings": 617,
        "commissions": 617,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5339,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 1890,
        "ordered_items": 156,
        "sell_earnings": 639,
        "commissions": 639,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9547,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1603,
        "ordered_items": 138,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5624,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 1737,
        "ordered_items": 146,
        "sell_earnings": 752,
        "commissions": 752,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9262,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1632,
        "ordered_items": 133,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7384,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1562,
        "ordered_items": 104,
        "sell_earnings": 549,
        "commissions": 549,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5955,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1524,
        "ordered_items": 114,
        "sell_earnings": 471,
        "commissions": 471,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5623,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1465,
        "ordered_items": 123,
        "sell_earnings": 531,
        "commissions": 531,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7411,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 1875,
        "ordered_items": 161,
        "sell_earnings": 725,
        "commissions": 725,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7475,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 1816,
        "ordered_items": 170,
        "sell_earnings": 785,
        "commissions": 785,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9263,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 1778,
        "ordered_items": 180,
        "sell_earnings": 707,
        "commissions": 707,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8931,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 1708,
        "ordered_items": 151,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7502,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1639,
        "ordered_items": 138,
        "sell_earnings": 529,
        "commissions": 529,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7076,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1347,
        "ordered_items": 106,
        "sell_earnings": 485,
        "commissions": 485,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5836,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 1993,
        "ordered_items": 178,
        "sell_earnings": 771,
        "commissions": 771,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9050,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 1701,
        "ordered_items": 146,
        "sell_earnings": 727,
        "commissions": 727,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7810,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1277,
        "ordered_items": 132,
        "sell_earnings": 488,
        "commissions": 488,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6396,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 2063,
        "ordered_items": 152,
        "sell_earnings": 768,
        "commissions": 768,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 164,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8490,
        "bonus": 0
    }
];