export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1350,
        "ordered_items": 120,
        "sell_earnings": 505,
        "commissions": 505,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6554,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1594,
        "ordered_items": 112,
        "sell_earnings": 564,
        "commissions": 564,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6017,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1347,
        "ordered_items": 136,
        "sell_earnings": 578,
        "commissions": 578,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6901,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 1885,
        "ordered_items": 138,
        "sell_earnings": 638,
        "commissions": 638,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7505,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1638,
        "ordered_items": 162,
        "sell_earnings": 652,
        "commissions": 652,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8389,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 1882,
        "ordered_items": 154,
        "sell_earnings": 711,
        "commissions": 711,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7852,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1368,
        "ordered_items": 107,
        "sell_earnings": 505,
        "commissions": 505,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5360,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1214,
        "ordered_items": 111,
        "sell_earnings": 453,
        "commissions": 453,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6000,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1168,
        "ordered_items": 116,
        "sell_earnings": 455,
        "commissions": 455,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5907,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 2064,
        "ordered_items": 158,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8499,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 2018,
        "ordered_items": 163,
        "sell_earnings": 763,
        "commissions": 763,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8406,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1864,
        "ordered_items": 167,
        "sell_earnings": 711,
        "commissions": 711,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9046,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1236,
        "ordered_items": 127,
        "sell_earnings": 594,
        "commissions": 594,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5989,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1996,
        "ordered_items": 147,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8417,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1273,
        "ordered_items": 120,
        "sell_earnings": 535,
        "commissions": 535,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5404,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1959,
        "ordered_items": 154,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9002,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1222,
        "ordered_items": 127,
        "sell_earnings": 468,
        "commissions": 468,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5231,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1599,
        "ordered_items": 100,
        "sell_earnings": 574,
        "commissions": 574,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6945,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1360,
        "ordered_items": 114,
        "sell_earnings": 594,
        "commissions": 594,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5474,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1506,
        "ordered_items": 108,
        "sell_earnings": 563,
        "commissions": 563,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5683,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 1726,
        "ordered_items": 166,
        "sell_earnings": 653,
        "commissions": 653,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8723,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1872,
        "ordered_items": 160,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8932,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 1633,
        "ordered_items": 174,
        "sell_earnings": 642,
        "commissions": 642,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7461,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 2010,
        "ordered_items": 147,
        "sell_earnings": 748,
        "commissions": 748,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9175,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1388,
        "ordered_items": 121,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6345,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1344,
        "ordered_items": 105,
        "sell_earnings": 441,
        "commissions": 441,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5454,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1888,
        "ordered_items": 169,
        "sell_earnings": 775,
        "commissions": 775,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8952,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1844,
        "ordered_items": 153,
        "sell_earnings": 752,
        "commissions": 752,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8061,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1317,
        "ordered_items": 124,
        "sell_earnings": 476,
        "commissions": 476,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5132,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1915,
        "ordered_items": 150,
        "sell_earnings": 740,
        "commissions": 740,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9274,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];