export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 1520,
        "ordered_items": 108,
        "sell_earnings": 584,
        "commissions": 584,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5313,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 1369,
        "ordered_items": 139,
        "sell_earnings": 579,
        "commissions": 579,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6269,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 1424,
        "ordered_items": 107,
        "sell_earnings": 508,
        "commissions": 508,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7390,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 1916,
        "ordered_items": 177,
        "sell_earnings": 748,
        "commissions": 748,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7496,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 1971,
        "ordered_items": 145,
        "sell_earnings": 677,
        "commissions": 677,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8617,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 1820,
        "ordered_items": 176,
        "sell_earnings": 672,
        "commissions": 672,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9573,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 1632,
        "ordered_items": 103,
        "sell_earnings": 610,
        "commissions": 610,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7231,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 1369,
        "ordered_items": 135,
        "sell_earnings": 573,
        "commissions": 573,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7157,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 1365,
        "ordered_items": 113,
        "sell_earnings": 574,
        "commissions": 574,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5976,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 1975,
        "ordered_items": 171,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8910,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 1971,
        "ordered_items": 149,
        "sell_earnings": 683,
        "commissions": 683,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7729,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 1708,
        "ordered_items": 181,
        "sell_earnings": 646,
        "commissions": 646,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7655,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 1332,
        "ordered_items": 106,
        "sell_earnings": 505,
        "commissions": 505,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7057,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 2008,
        "ordered_items": 178,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7829,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 1187,
        "ordered_items": 113,
        "sell_earnings": 488,
        "commissions": 488,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7046,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 2153,
        "ordered_items": 171,
        "sell_earnings": 768,
        "commissions": 768,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 164,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7840,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 1232,
        "ordered_items": 136,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7406,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 1580,
        "ordered_items": 142,
        "sell_earnings": 614,
        "commissions": 614,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5245,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 1480,
        "ordered_items": 105,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6572,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 1625,
        "ordered_items": 104,
        "sell_earnings": 615,
        "commissions": 615,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7161,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 1715,
        "ordered_items": 180,
        "sell_earnings": 641,
        "commissions": 641,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7725,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 1860,
        "ordered_items": 179,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8314,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 1760,
        "ordered_items": 142,
        "sell_earnings": 642,
        "commissions": 642,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9641,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 2108,
        "ordered_items": 148,
        "sell_earnings": 757,
        "commissions": 757,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7480,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 1633,
        "ordered_items": 140,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5955,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 1285,
        "ordered_items": 118,
        "sell_earnings": 560,
        "commissions": 560,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5557,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 2055,
        "ordered_items": 166,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 167,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9329,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 1707,
        "ordered_items": 144,
        "sell_earnings": 634,
        "commissions": 634,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8931,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 1536,
        "ordered_items": 110,
        "sell_earnings": 556,
        "commissions": 556,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6700,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 1804,
        "ordered_items": 174,
        "sell_earnings": 700,
        "commissions": 700,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8186,
        "bonus": 1
    }
];