export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1178,
        "ordered_items": 121,
        "sell_earnings": 536,
        "commissions": 536,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6890,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1210,
        "ordered_items": 131,
        "sell_earnings": 543,
        "commissions": 543,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5957,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1386,
        "ordered_items": 134,
        "sell_earnings": 580,
        "commissions": 580,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6844,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 1846,
        "ordered_items": 140,
        "sell_earnings": 636,
        "commissions": 636,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7562,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 2022,
        "ordered_items": 143,
        "sell_earnings": 673,
        "commissions": 673,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8449,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 2054,
        "ordered_items": 153,
        "sell_earnings": 680,
        "commissions": 680,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7516,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1165,
        "ordered_items": 97,
        "sell_earnings": 584,
        "commissions": 584,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6259,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1509,
        "ordered_items": 112,
        "sell_earnings": 492,
        "commissions": 492,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6982,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1585,
        "ordered_items": 127,
        "sell_earnings": 438,
        "commissions": 438,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6529,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 1647,
        "ordered_items": 147,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7877,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1723,
        "ordered_items": 162,
        "sell_earnings": 724,
        "commissions": 724,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7424,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 2067,
        "ordered_items": 177,
        "sell_earnings": 632,
        "commissions": 632,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8147,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1148,
        "ordered_items": 117,
        "sell_earnings": 433,
        "commissions": 433,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5311,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 2084,
        "ordered_items": 157,
        "sell_earnings": 783,
        "commissions": 783,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9095,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1191,
        "ordered_items": 106,
        "sell_earnings": 509,
        "commissions": 509,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5706,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 2041,
        "ordered_items": 168,
        "sell_earnings": 707,
        "commissions": 707,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8700,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1465,
        "ordered_items": 133,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6740,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1142,
        "ordered_items": 123,
        "sell_earnings": 603,
        "commissions": 603,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6778,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1426,
        "ordered_items": 125,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5924,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1508,
        "ordered_items": 137,
        "sell_earnings": 546,
        "commissions": 546,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5861,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 1724,
        "ordered_items": 137,
        "sell_earnings": 670,
        "commissions": 670,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8545,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 1806,
        "ordered_items": 149,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8482,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 2090,
        "ordered_items": 151,
        "sell_earnings": 613,
        "commissions": 613,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7628,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 1767,
        "ordered_items": 141,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7666,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1363,
        "ordered_items": 109,
        "sell_earnings": 592,
        "commissions": 592,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7191,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1595,
        "ordered_items": 126,
        "sell_earnings": 532,
        "commissions": 532,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7180,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1637,
        "ordered_items": 148,
        "sell_earnings": 684,
        "commissions": 684,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7226,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 1869,
        "ordered_items": 165,
        "sell_earnings": 624,
        "commissions": 624,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7215,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1186,
        "ordered_items": 137,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7012,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 2046,
        "ordered_items": 137,
        "sell_earnings": 651,
        "commissions": 651,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7394,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];