export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1172,
        "ordered_items": 129,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5940,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1363,
        "ordered_items": 115,
        "sell_earnings": 591,
        "commissions": 591,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6111,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1498,
        "ordered_items": 101,
        "sell_earnings": 447,
        "commissions": 447,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6281,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 1734,
        "ordered_items": 173,
        "sell_earnings": 769,
        "commissions": 769,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8125,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 1869,
        "ordered_items": 159,
        "sell_earnings": 625,
        "commissions": 625,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8295,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 2060,
        "ordered_items": 145,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8466,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1258,
        "ordered_items": 113,
        "sell_earnings": 578,
        "commissions": 578,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5170,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1315,
        "ordered_items": 101,
        "sell_earnings": 502,
        "commissions": 502,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6148,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1327,
        "ordered_items": 124,
        "sell_earnings": 434,
        "commissions": 434,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5734,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 1905,
        "ordered_items": 150,
        "sell_earnings": 782,
        "commissions": 782,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8672,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 1917,
        "ordered_items": 173,
        "sell_earnings": 714,
        "commissions": 714,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8258,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 1974,
        "ordered_items": 161,
        "sell_earnings": 638,
        "commissions": 638,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9236,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1284,
        "ordered_items": 118,
        "sell_earnings": 443,
        "commissions": 443,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6640,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 1948,
        "ordered_items": 156,
        "sell_earnings": 773,
        "commissions": 773,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7766,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1146,
        "ordered_items": 119,
        "sell_earnings": 563,
        "commissions": 563,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6299,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 2086,
        "ordered_items": 155,
        "sell_earnings": 653,
        "commissions": 653,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8107,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1441,
        "ordered_items": 104,
        "sell_earnings": 544,
        "commissions": 544,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6107,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1156,
        "ordered_items": 120,
        "sell_earnings": 493,
        "commissions": 493,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6984,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1239,
        "ordered_items": 101,
        "sell_earnings": 546,
        "commissions": 546,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5208,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1590,
        "ordered_items": 106,
        "sell_earnings": 474,
        "commissions": 474,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5055,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 1642,
        "ordered_items": 168,
        "sell_earnings": 742,
        "commissions": 742,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9351,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1993,
        "ordered_items": 173,
        "sell_earnings": 670,
        "commissions": 670,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9198,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 2076,
        "ordered_items": 154,
        "sell_earnings": 723,
        "commissions": 723,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7422,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 1791,
        "ordered_items": 170,
        "sell_earnings": 672,
        "commissions": 672,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8299,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1263,
        "ordered_items": 136,
        "sell_earnings": 522,
        "commissions": 522,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6080,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1174,
        "ordered_items": 102,
        "sell_earnings": 603,
        "commissions": 603,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5262,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 2058,
        "ordered_items": 172,
        "sell_earnings": 613,
        "commissions": 613,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9144,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1969,
        "ordered_items": 138,
        "sell_earnings": 694,
        "commissions": 694,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8326,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1336,
        "ordered_items": 97,
        "sell_earnings": 461,
        "commissions": 461,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6887,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 1896,
        "ordered_items": 177,
        "sell_earnings": 755,
        "commissions": 755,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7519,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];