export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1164,
        "ordered_items": 130,
        "sell_earnings": 519,
        "commissions": 519,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5593,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1354,
        "ordered_items": 132,
        "sell_earnings": 453,
        "commissions": 453,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7146,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1279,
        "ordered_items": 121,
        "sell_earnings": 566,
        "commissions": 566,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5279,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 1953,
        "ordered_items": 153,
        "sell_earnings": 650,
        "commissions": 650,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9127,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 1878,
        "ordered_items": 142,
        "sell_earnings": 763,
        "commissions": 763,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7260,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 2068,
        "ordered_items": 144,
        "sell_earnings": 697,
        "commissions": 697,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8813,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1484,
        "ordered_items": 97,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7089,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1434,
        "ordered_items": 124,
        "sell_earnings": 460,
        "commissions": 460,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6035,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1359,
        "ordered_items": 119,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7113,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 1873,
        "ordered_items": 155,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7293,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 1798,
        "ordered_items": 150,
        "sell_earnings": 756,
        "commissions": 756,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8371,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 1748,
        "ordered_items": 177,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7317,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1311,
        "ordered_items": 112,
        "sell_earnings": 552,
        "commissions": 552,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5373,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 1921,
        "ordered_items": 162,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9033,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1235,
        "ordered_items": 118,
        "sell_earnings": 432,
        "commissions": 432,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5281,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 1997,
        "ordered_items": 156,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9125,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1183,
        "ordered_items": 114,
        "sell_earnings": 436,
        "commissions": 436,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7037,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1571,
        "ordered_items": 118,
        "sell_earnings": 572,
        "commissions": 572,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7150,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1327,
        "ordered_items": 130,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5061,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1183,
        "ordered_items": 108,
        "sell_earnings": 580,
        "commissions": 580,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6700,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 2049,
        "ordered_items": 166,
        "sell_earnings": 636,
        "commissions": 636,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7706,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 1905,
        "ordered_items": 144,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9345,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 1661,
        "ordered_items": 156,
        "sell_earnings": 644,
        "commissions": 644,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7256,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 2049,
        "ordered_items": 160,
        "sell_earnings": 780,
        "commissions": 780,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7369,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1249,
        "ordered_items": 101,
        "sell_earnings": 551,
        "commissions": 551,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6639,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1265,
        "ordered_items": 109,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6415,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 1967,
        "ordered_items": 165,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7991,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 1983,
        "ordered_items": 173,
        "sell_earnings": 665,
        "commissions": 665,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7767,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1288,
        "ordered_items": 105,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5079,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 1944,
        "ordered_items": 169,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9327,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];