export let mar = [
    {
        "month": "Mar",
        "day": "01",
        "clicks": 1441,
        "ordered_items": 121,
        "sell_earnings": 599,
        "commissions": 599,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6632,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "02",
        "clicks": 1149,
        "ordered_items": 111,
        "sell_earnings": 531,
        "commissions": 531,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6082,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "03",
        "clicks": 1278,
        "ordered_items": 114,
        "sell_earnings": 526,
        "commissions": 526,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5215,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "04",
        "clicks": 1954,
        "ordered_items": 160,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9191,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "05",
        "clicks": 2083,
        "ordered_items": 163,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8324,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "06",
        "clicks": 1791,
        "ordered_items": 153,
        "sell_earnings": 617,
        "commissions": 617,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7774,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "07",
        "clicks": 1611,
        "ordered_items": 100,
        "sell_earnings": 472,
        "commissions": 472,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6715,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "08",
        "clicks": 1251,
        "ordered_items": 119,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5930,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "09",
        "clicks": 1599,
        "ordered_items": 126,
        "sell_earnings": 457,
        "commissions": 457,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5653,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "10",
        "clicks": 1633,
        "ordered_items": 148,
        "sell_earnings": 759,
        "commissions": 759,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8753,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "11",
        "clicks": 1981,
        "ordered_items": 155,
        "sell_earnings": 610,
        "commissions": 610,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8476,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "12",
        "clicks": 1621,
        "ordered_items": 174,
        "sell_earnings": 744,
        "commissions": 744,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7691,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "13",
        "clicks": 1175,
        "ordered_items": 108,
        "sell_earnings": 594,
        "commissions": 594,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6670,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "14",
        "clicks": 2057,
        "ordered_items": 166,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7736,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "15",
        "clicks": 1292,
        "ordered_items": 123,
        "sell_earnings": 452,
        "commissions": 452,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6241,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "16",
        "clicks": 1940,
        "ordered_items": 151,
        "sell_earnings": 764,
        "commissions": 764,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8165,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "17",
        "clicks": 1169,
        "ordered_items": 97,
        "sell_earnings": 435,
        "commissions": 435,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6052,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "18",
        "clicks": 1259,
        "ordered_items": 110,
        "sell_earnings": 443,
        "commissions": 443,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6438,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "19",
        "clicks": 1499,
        "ordered_items": 97,
        "sell_earnings": 434,
        "commissions": 434,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6974,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "20",
        "clicks": 1229,
        "ordered_items": 104,
        "sell_earnings": 607,
        "commissions": 607,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5052,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "21",
        "clicks": 2003,
        "ordered_items": 170,
        "sell_earnings": 609,
        "commissions": 609,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9354,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "22",
        "clicks": 1733,
        "ordered_items": 177,
        "sell_earnings": 782,
        "commissions": 782,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7432,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "23",
        "clicks": 1973,
        "ordered_items": 164,
        "sell_earnings": 773,
        "commissions": 773,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7968,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "24",
        "clicks": 2063,
        "ordered_items": 177,
        "sell_earnings": 781,
        "commissions": 781,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8354,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "25",
        "clicks": 1477,
        "ordered_items": 112,
        "sell_earnings": 546,
        "commissions": 546,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5335,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "26",
        "clicks": 1551,
        "ordered_items": 124,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5455,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "27",
        "clicks": 1681,
        "ordered_items": 150,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8951,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "28",
        "clicks": 1755,
        "ordered_items": 162,
        "sell_earnings": 670,
        "commissions": 670,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9071,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "29",
        "clicks": 1575,
        "ordered_items": 101,
        "sell_earnings": 442,
        "commissions": 442,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6380,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "30",
        "clicks": 1657,
        "ordered_items": 173,
        "sell_earnings": 774,
        "commissions": 774,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8026,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];