export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1453,
        "ordered_items": 124,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5534,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1144,
        "ordered_items": 106,
        "sell_earnings": 597,
        "commissions": 597,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5168,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1492,
        "ordered_items": 115,
        "sell_earnings": 536,
        "commissions": 536,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6781,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 1740,
        "ordered_items": 159,
        "sell_earnings": 680,
        "commissions": 680,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7625,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 2088,
        "ordered_items": 168,
        "sell_earnings": 619,
        "commissions": 619,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9238,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 1779,
        "ordered_items": 150,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8872,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1360,
        "ordered_items": 131,
        "sell_earnings": 584,
        "commissions": 584,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5777,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1373,
        "ordered_items": 98,
        "sell_earnings": 454,
        "commissions": 454,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5435,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1461,
        "ordered_items": 133,
        "sell_earnings": 483,
        "commissions": 483,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6242,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 1771,
        "ordered_items": 141,
        "sell_earnings": 733,
        "commissions": 733,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8164,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 1859,
        "ordered_items": 176,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8971,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1872,
        "ordered_items": 143,
        "sell_earnings": 632,
        "commissions": 632,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8629,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1159,
        "ordered_items": 136,
        "sell_earnings": 437,
        "commissions": 437,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5530,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 2073,
        "ordered_items": 138,
        "sell_earnings": 779,
        "commissions": 779,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8876,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1447,
        "ordered_items": 106,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5090,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 1785,
        "ordered_items": 168,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9316,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1614,
        "ordered_items": 104,
        "sell_earnings": 474,
        "commissions": 474,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6554,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1231,
        "ordered_items": 126,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6128,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1519,
        "ordered_items": 107,
        "sell_earnings": 533,
        "commissions": 533,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6796,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1234,
        "ordered_items": 102,
        "sell_earnings": 428,
        "commissions": 428,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6554,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 1998,
        "ordered_items": 172,
        "sell_earnings": 788,
        "commissions": 788,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7852,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 1713,
        "ordered_items": 167,
        "sell_earnings": 683,
        "commissions": 683,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7610,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 2001,
        "ordered_items": 148,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8278,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1618,
        "ordered_items": 170,
        "sell_earnings": 742,
        "commissions": 742,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7852,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1599,
        "ordered_items": 117,
        "sell_earnings": 550,
        "commissions": 550,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5924,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1342,
        "ordered_items": 113,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5794,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 1890,
        "ordered_items": 161,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8612,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 1633,
        "ordered_items": 157,
        "sell_earnings": 666,
        "commissions": 666,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8482,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1534,
        "ordered_items": 136,
        "sell_earnings": 428,
        "commissions": 428,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7114,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 1698,
        "ordered_items": 138,
        "sell_earnings": 788,
        "commissions": 788,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7292,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];