export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1541,
        "ordered_items": 138,
        "sell_earnings": 628,
        "commissions": 628,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7117,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1611,
        "ordered_items": 141,
        "sell_earnings": 619,
        "commissions": 619,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6103,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1390,
        "ordered_items": 118,
        "sell_earnings": 535,
        "commissions": 535,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7081,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 1950,
        "ordered_items": 166,
        "sell_earnings": 721,
        "commissions": 721,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7805,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 1729,
        "ordered_items": 143,
        "sell_earnings": 637,
        "commissions": 637,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 168,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8783,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 1799,
        "ordered_items": 146,
        "sell_earnings": 628,
        "commissions": 628,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7769,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1359,
        "ordered_items": 125,
        "sell_earnings": 508,
        "commissions": 508,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6340,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1391,
        "ordered_items": 118,
        "sell_earnings": 551,
        "commissions": 551,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 129,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6335,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1384,
        "ordered_items": 140,
        "sell_earnings": 569,
        "commissions": 569,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6013,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 1956,
        "ordered_items": 144,
        "sell_earnings": 687,
        "commissions": 687,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 168,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8873,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 1949,
        "ordered_items": 166,
        "sell_earnings": 705,
        "commissions": 705,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8551,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 1981,
        "ordered_items": 159,
        "sell_earnings": 748,
        "commissions": 748,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8546,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1593,
        "ordered_items": 141,
        "sell_earnings": 447,
        "commissions": 447,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5949,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 1747,
        "ordered_items": 143,
        "sell_earnings": 809,
        "commissions": 809,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8937,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1627,
        "ordered_items": 137,
        "sell_earnings": 498,
        "commissions": 498,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5285,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 1713,
        "ordered_items": 147,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9601,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1281,
        "ordered_items": 137,
        "sell_earnings": 594,
        "commissions": 594,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7149,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1320,
        "ordered_items": 130,
        "sell_earnings": 558,
        "commissions": 558,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6016,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1199,
        "ordered_items": 128,
        "sell_earnings": 580,
        "commissions": 580,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7332,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1327,
        "ordered_items": 117,
        "sell_earnings": 570,
        "commissions": 570,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6023,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 2013,
        "ordered_items": 167,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8863,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 2141,
        "ordered_items": 156,
        "sell_earnings": 676,
        "commissions": 676,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7554,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 2020,
        "ordered_items": 154,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8870,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 2059,
        "ordered_items": 147,
        "sell_earnings": 662,
        "commissions": 662,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7737,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1455,
        "ordered_items": 133,
        "sell_earnings": 525,
        "commissions": 525,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7351,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1474,
        "ordered_items": 140,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6010,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 1866,
        "ordered_items": 144,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8876,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 1885,
        "ordered_items": 151,
        "sell_earnings": 731,
        "commissions": 731,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7535,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1433,
        "ordered_items": 137,
        "sell_earnings": 478,
        "commissions": 478,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5368,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 1907,
        "ordered_items": 147,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 167,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9518,
        "bonus": 0
    }
];