export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 1357,
        "ordered_items": 118,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6896,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 1389,
        "ordered_items": 103,
        "sell_earnings": 555,
        "commissions": 555,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6053,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 1538,
        "ordered_items": 113,
        "sell_earnings": 570,
        "commissions": 570,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6750,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 1802,
        "ordered_items": 171,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8136,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 1951,
        "ordered_items": 181,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 168,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8833,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 1983,
        "ordered_items": 166,
        "sell_earnings": 652,
        "commissions": 652,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7990,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 1322,
        "ordered_items": 115,
        "sell_earnings": 626,
        "commissions": 626,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6100,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 1410,
        "ordered_items": 132,
        "sell_earnings": 558,
        "commissions": 558,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6384,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 1431,
        "ordered_items": 106,
        "sell_earnings": 479,
        "commissions": 479,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5263,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 1909,
        "ordered_items": 178,
        "sell_earnings": 777,
        "commissions": 777,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9623,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 1930,
        "ordered_items": 152,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8502,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 2018,
        "ordered_items": 169,
        "sell_earnings": 630,
        "commissions": 630,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8786,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 1356,
        "ordered_items": 140,
        "sell_earnings": 577,
        "commissions": 577,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5650,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 1984,
        "ordered_items": 144,
        "sell_earnings": 679,
        "commissions": 679,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9236,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 1363,
        "ordered_items": 128,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6090,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 1977,
        "ordered_items": 156,
        "sell_earnings": 658,
        "commissions": 658,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8796,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 1278,
        "ordered_items": 111,
        "sell_earnings": 445,
        "commissions": 445,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7443,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 1216,
        "ordered_items": 125,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6455,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 1587,
        "ordered_items": 108,
        "sell_earnings": 557,
        "commissions": 557,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7174,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 1244,
        "ordered_items": 111,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5734,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 2096,
        "ordered_items": 173,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9152,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 1753,
        "ordered_items": 176,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7712,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 2124,
        "ordered_items": 159,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8431,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 2062,
        "ordered_items": 173,
        "sell_earnings": 811,
        "commissions": 811,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7443,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 1508,
        "ordered_items": 105,
        "sell_earnings": 572,
        "commissions": 572,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5313,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 1531,
        "ordered_items": 142,
        "sell_earnings": 502,
        "commissions": 502,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7106,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 1809,
        "ordered_items": 142,
        "sell_earnings": 754,
        "commissions": 754,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7780,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 1832,
        "ordered_items": 179,
        "sell_earnings": 684,
        "commissions": 684,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 169,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9573,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 1373,
        "ordered_items": 107,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5478,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 1967,
        "ordered_items": 177,
        "sell_earnings": 663,
        "commissions": 663,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9408,
        "bonus": 0
    }
];