export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1403,
        "ordered_items": 104,
        "sell_earnings": 507,
        "commissions": 507,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5935,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1319,
        "ordered_items": 128,
        "sell_earnings": 560,
        "commissions": 560,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6998,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1324,
        "ordered_items": 133,
        "sell_earnings": 573,
        "commissions": 573,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6467,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 1908,
        "ordered_items": 141,
        "sell_earnings": 643,
        "commissions": 643,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7939,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 1913,
        "ordered_items": 146,
        "sell_earnings": 656,
        "commissions": 656,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7408,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 1829,
        "ordered_items": 170,
        "sell_earnings": 709,
        "commissions": 709,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8471,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1340,
        "ordered_items": 107,
        "sell_earnings": 493,
        "commissions": 493,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5924,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1546,
        "ordered_items": 102,
        "sell_earnings": 497,
        "commissions": 497,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5255,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1327,
        "ordered_items": 130,
        "sell_earnings": 448,
        "commissions": 448,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5053,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 1905,
        "ordered_items": 144,
        "sell_earnings": 768,
        "commissions": 768,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9353,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 1686,
        "ordered_items": 172,
        "sell_earnings": 719,
        "commissions": 719,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9151,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 1892,
        "ordered_items": 167,
        "sell_earnings": 723,
        "commissions": 723,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8482,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1446,
        "ordered_items": 124,
        "sell_earnings": 489,
        "commissions": 489,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6075,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 1786,
        "ordered_items": 150,
        "sell_earnings": 727,
        "commissions": 727,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8331,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1354,
        "ordered_items": 124,
        "sell_earnings": 454,
        "commissions": 454,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5848,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 1878,
        "ordered_items": 150,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8558,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1538,
        "ordered_items": 114,
        "sell_earnings": 559,
        "commissions": 559,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6084,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1561,
        "ordered_items": 121,
        "sell_earnings": 438,
        "commissions": 438,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6174,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1257,
        "ordered_items": 120,
        "sell_earnings": 603,
        "commissions": 603,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6823,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1300,
        "ordered_items": 116,
        "sell_earnings": 429,
        "commissions": 429,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6385,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 1932,
        "ordered_items": 158,
        "sell_earnings": 787,
        "commissions": 787,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8021,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1975,
        "ordered_items": 154,
        "sell_earnings": 613,
        "commissions": 613,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7583,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 1671,
        "ordered_items": 153,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8232,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 1694,
        "ordered_items": 160,
        "sell_earnings": 657,
        "commissions": 657,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8322,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1342,
        "ordered_items": 130,
        "sell_earnings": 522,
        "commissions": 522,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6107,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1161,
        "ordered_items": 107,
        "sell_earnings": 580,
        "commissions": 580,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7024,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 2071,
        "ordered_items": 167,
        "sell_earnings": 636,
        "commissions": 636,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7382,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1890,
        "ordered_items": 144,
        "sell_earnings": 694,
        "commissions": 694,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8299,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1321,
        "ordered_items": 99,
        "sell_earnings": 501,
        "commissions": 501,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7161,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 1911,
        "ordered_items": 175,
        "sell_earnings": 715,
        "commissions": 715,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7245,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];