export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1207,
        "ordered_items": 125,
        "sell_earnings": 485,
        "commissions": 485,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5318,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1218,
        "ordered_items": 122,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5546,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1157,
        "ordered_items": 135,
        "sell_earnings": 605,
        "commissions": 605,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6651,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 2075,
        "ordered_items": 139,
        "sell_earnings": 611,
        "commissions": 611,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7755,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 2014,
        "ordered_items": 152,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8860,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 2025,
        "ordered_items": 149,
        "sell_earnings": 731,
        "commissions": 731,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9088,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1186,
        "ordered_items": 106,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6735,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1556,
        "ordered_items": 111,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6450,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1531,
        "ordered_items": 99,
        "sell_earnings": 594,
        "commissions": 594,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6053,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 1701,
        "ordered_items": 175,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8353,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 1676,
        "ordered_items": 163,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7956,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 2046,
        "ordered_items": 168,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7671,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1412,
        "ordered_items": 120,
        "sell_earnings": 432,
        "commissions": 432,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5865,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 1820,
        "ordered_items": 154,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8541,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1369,
        "ordered_items": 135,
        "sell_earnings": 465,
        "commissions": 465,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5446,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 1863,
        "ordered_items": 139,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8960,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1186,
        "ordered_items": 117,
        "sell_earnings": 478,
        "commissions": 478,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6505,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1193,
        "ordered_items": 102,
        "sell_earnings": 469,
        "commissions": 469,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7143,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1300,
        "ordered_items": 110,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6177,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1161,
        "ordered_items": 99,
        "sell_earnings": 581,
        "commissions": 581,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5334,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 2071,
        "ordered_items": 175,
        "sell_earnings": 635,
        "commissions": 635,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9072,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 1932,
        "ordered_items": 164,
        "sell_earnings": 610,
        "commissions": 610,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8229,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 2039,
        "ordered_items": 172,
        "sell_earnings": 747,
        "commissions": 747,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7263,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 2046,
        "ordered_items": 157,
        "sell_earnings": 738,
        "commissions": 738,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7901,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1447,
        "ordered_items": 123,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6915,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1338,
        "ordered_items": 115,
        "sell_earnings": 596,
        "commissions": 596,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6728,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 1894,
        "ordered_items": 159,
        "sell_earnings": 620,
        "commissions": 620,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7678,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 1785,
        "ordered_items": 151,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7491,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1554,
        "ordered_items": 104,
        "sell_earnings": 492,
        "commissions": 492,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5048,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 1678,
        "ordered_items": 170,
        "sell_earnings": 724,
        "commissions": 724,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9358,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];