export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1451,
        "ordered_items": 119,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6637,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1451,
        "ordered_items": 113,
        "sell_earnings": 523,
        "commissions": 523,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6989,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1663,
        "ordered_items": 109,
        "sell_earnings": 445,
        "commissions": 445,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6751,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 1677,
        "ordered_items": 175,
        "sell_earnings": 811,
        "commissions": 811,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8135,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 1889,
        "ordered_items": 171,
        "sell_earnings": 733,
        "commissions": 733,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7897,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 1889,
        "ordered_items": 165,
        "sell_earnings": 728,
        "commissions": 728,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8249,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1478,
        "ordered_items": 114,
        "sell_earnings": 591,
        "commissions": 591,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6108,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1642,
        "ordered_items": 126,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5603,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1382,
        "ordered_items": 139,
        "sell_earnings": 578,
        "commissions": 578,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7161,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 1958,
        "ordered_items": 145,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7725,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 1698,
        "ordered_items": 158,
        "sell_earnings": 691,
        "commissions": 691,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 167,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9283,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 1862,
        "ordered_items": 170,
        "sell_earnings": 665,
        "commissions": 665,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8778,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1275,
        "ordered_items": 141,
        "sell_earnings": 602,
        "commissions": 602,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5767,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 2065,
        "ordered_items": 143,
        "sell_earnings": 654,
        "commissions": 654,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9119,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1532,
        "ordered_items": 136,
        "sell_earnings": 492,
        "commissions": 492,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5838,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 1808,
        "ordered_items": 148,
        "sell_earnings": 764,
        "commissions": 764,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9048,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1520,
        "ordered_items": 136,
        "sell_earnings": 516,
        "commissions": 516,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5709,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1647,
        "ordered_items": 105,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7200,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1280,
        "ordered_items": 136,
        "sell_earnings": 544,
        "commissions": 544,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5531,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1561,
        "ordered_items": 112,
        "sell_earnings": 489,
        "commissions": 489,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6696,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 1779,
        "ordered_items": 172,
        "sell_earnings": 767,
        "commissions": 767,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 166,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8190,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 2060,
        "ordered_items": 148,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9355,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 1693,
        "ordered_items": 179,
        "sell_earnings": 806,
        "commissions": 806,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7686,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 1820,
        "ordered_items": 148,
        "sell_earnings": 740,
        "commissions": 740,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 166,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9177,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1372,
        "ordered_items": 104,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6297,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1315,
        "ordered_items": 115,
        "sell_earnings": 605,
        "commissions": 605,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5441,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 2025,
        "ordered_items": 169,
        "sell_earnings": 651,
        "commissions": 651,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 168,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9445,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 1968,
        "ordered_items": 180,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8589,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1635,
        "ordered_items": 136,
        "sell_earnings": 562,
        "commissions": 562,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5700,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 1705,
        "ordered_items": 148,
        "sell_earnings": 694,
        "commissions": 694,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9186,
        "bonus": 2
    }
];