export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1595,
        "ordered_items": 110,
        "sell_earnings": 524,
        "commissions": 524,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5749,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1354,
        "ordered_items": 135,
        "sell_earnings": 493,
        "commissions": 493,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6921,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1227,
        "ordered_items": 107,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6039,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 2005,
        "ordered_items": 167,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8367,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 1878,
        "ordered_items": 139,
        "sell_earnings": 723,
        "commissions": 723,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7485,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 1637,
        "ordered_items": 164,
        "sell_earnings": 692,
        "commissions": 692,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8657,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1282,
        "ordered_items": 130,
        "sell_earnings": 602,
        "commissions": 602,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6051,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1487,
        "ordered_items": 111,
        "sell_earnings": 507,
        "commissions": 507,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5711,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1603,
        "ordered_items": 102,
        "sell_earnings": 591,
        "commissions": 591,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7147,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 1629,
        "ordered_items": 172,
        "sell_earnings": 625,
        "commissions": 625,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7259,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 1745,
        "ordered_items": 163,
        "sell_earnings": 709,
        "commissions": 709,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8695,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1950,
        "ordered_items": 144,
        "sell_earnings": 614,
        "commissions": 614,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8355,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1244,
        "ordered_items": 104,
        "sell_earnings": 474,
        "commissions": 474,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5939,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 1988,
        "ordered_items": 170,
        "sell_earnings": 742,
        "commissions": 742,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8467,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1325,
        "ordered_items": 137,
        "sell_earnings": 562,
        "commissions": 562,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5393,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 1907,
        "ordered_items": 137,
        "sell_earnings": 654,
        "commissions": 654,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9013,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1283,
        "ordered_items": 131,
        "sell_earnings": 536,
        "commissions": 536,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6240,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1326,
        "ordered_items": 118,
        "sell_earnings": 525,
        "commissions": 525,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6270,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1507,
        "ordered_items": 101,
        "sell_earnings": 479,
        "commissions": 479,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6313,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1201,
        "ordered_items": 106,
        "sell_earnings": 488,
        "commissions": 488,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6898,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 2031,
        "ordered_items": 168,
        "sell_earnings": 728,
        "commissions": 728,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7508,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 1725,
        "ordered_items": 173,
        "sell_earnings": 737,
        "commissions": 737,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8093,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 1906,
        "ordered_items": 156,
        "sell_earnings": 691,
        "commissions": 691,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8136,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1949,
        "ordered_items": 143,
        "sell_earnings": 680,
        "commissions": 680,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8166,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1173,
        "ordered_items": 108,
        "sell_earnings": 567,
        "commissions": 567,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6149,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1323,
        "ordered_items": 108,
        "sell_earnings": 526,
        "commissions": 526,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5221,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 1909,
        "ordered_items": 166,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9185,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 2059,
        "ordered_items": 166,
        "sell_earnings": 649,
        "commissions": 649,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8257,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1188,
        "ordered_items": 116,
        "sell_earnings": 549,
        "commissions": 549,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6485,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 2044,
        "ordered_items": 158,
        "sell_earnings": 667,
        "commissions": 667,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7921,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];