export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1401,
        "ordered_items": 105,
        "sell_earnings": 523,
        "commissions": 523,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6799,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1365,
        "ordered_items": 105,
        "sell_earnings": 615,
        "commissions": 615,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7038,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1449,
        "ordered_items": 121,
        "sell_earnings": 592,
        "commissions": 592,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7438,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 1891,
        "ordered_items": 163,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7448,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 1975,
        "ordered_items": 179,
        "sell_earnings": 641,
        "commissions": 641,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7848,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 1939,
        "ordered_items": 179,
        "sell_earnings": 733,
        "commissions": 733,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8087,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1280,
        "ordered_items": 101,
        "sell_earnings": 619,
        "commissions": 619,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5414,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1526,
        "ordered_items": 101,
        "sell_earnings": 600,
        "commissions": 600,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5890,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1579,
        "ordered_items": 106,
        "sell_earnings": 549,
        "commissions": 549,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6033,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 1761,
        "ordered_items": 178,
        "sell_earnings": 707,
        "commissions": 707,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8853,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 1814,
        "ordered_items": 183,
        "sell_earnings": 656,
        "commissions": 656,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8996,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 2060,
        "ordered_items": 183,
        "sell_earnings": 637,
        "commissions": 637,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9472,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1523,
        "ordered_items": 127,
        "sell_earnings": 544,
        "commissions": 544,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5735,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 1817,
        "ordered_items": 157,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9151,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1232,
        "ordered_items": 100,
        "sell_earnings": 460,
        "commissions": 460,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6489,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 2108,
        "ordered_items": 184,
        "sell_earnings": 796,
        "commissions": 796,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8397,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1401,
        "ordered_items": 113,
        "sell_earnings": 453,
        "commissions": 453,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5391,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1244,
        "ordered_items": 106,
        "sell_earnings": 492,
        "commissions": 492,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6803,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1250,
        "ordered_items": 119,
        "sell_earnings": 481,
        "commissions": 481,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6940,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1520,
        "ordered_items": 106,
        "sell_earnings": 507,
        "commissions": 507,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7217,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 1820,
        "ordered_items": 178,
        "sell_earnings": 749,
        "commissions": 749,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 169,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7669,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 2090,
        "ordered_items": 165,
        "sell_earnings": 775,
        "commissions": 775,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 166,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7946,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 2096,
        "ordered_items": 178,
        "sell_earnings": 764,
        "commissions": 764,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 168,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8083,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 1939,
        "ordered_items": 171,
        "sell_earnings": 803,
        "commissions": 803,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9495,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1551,
        "ordered_items": 121,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7264,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1437,
        "ordered_items": 141,
        "sell_earnings": 571,
        "commissions": 571,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6210,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 1903,
        "ordered_items": 143,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8676,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 1789,
        "ordered_items": 163,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7622,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1437,
        "ordered_items": 120,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6191,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 1903,
        "ordered_items": 164,
        "sell_earnings": 638,
        "commissions": 638,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8695,
        "bonus": 0
    }
];