export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1589,
        "ordered_items": 122,
        "sell_earnings": 605,
        "commissions": 605,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6614,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1158,
        "ordered_items": 131,
        "sell_earnings": 519,
        "commissions": 519,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5239,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1165,
        "ordered_items": 136,
        "sell_earnings": 546,
        "commissions": 546,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5455,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 2067,
        "ordered_items": 138,
        "sell_earnings": 670,
        "commissions": 670,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8951,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 2074,
        "ordered_items": 143,
        "sell_earnings": 697,
        "commissions": 697,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9167,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 1643,
        "ordered_items": 152,
        "sell_earnings": 611,
        "commissions": 611,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7792,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1437,
        "ordered_items": 128,
        "sell_earnings": 511,
        "commissions": 511,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7180,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1567,
        "ordered_items": 117,
        "sell_earnings": 546,
        "commissions": 546,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6161,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1175,
        "ordered_items": 120,
        "sell_earnings": 576,
        "commissions": 576,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5429,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 2057,
        "ordered_items": 154,
        "sell_earnings": 640,
        "commissions": 640,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8977,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 1665,
        "ordered_items": 157,
        "sell_earnings": 670,
        "commissions": 670,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8245,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1795,
        "ordered_items": 146,
        "sell_earnings": 705,
        "commissions": 705,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7226,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1276,
        "ordered_items": 128,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5126,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1956,
        "ordered_items": 146,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9280,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1377,
        "ordered_items": 136,
        "sell_earnings": 590,
        "commissions": 590,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5694,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1855,
        "ordered_items": 138,
        "sell_earnings": 626,
        "commissions": 626,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8712,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1280,
        "ordered_items": 99,
        "sell_earnings": 433,
        "commissions": 433,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6370,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1402,
        "ordered_items": 131,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5719,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1314,
        "ordered_items": 118,
        "sell_earnings": 506,
        "commissions": 506,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5053,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1152,
        "ordered_items": 103,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5648,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 2080,
        "ordered_items": 171,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8758,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1918,
        "ordered_items": 156,
        "sell_earnings": 710,
        "commissions": 710,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9353,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 1830,
        "ordered_items": 143,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8687,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1952,
        "ordered_items": 175,
        "sell_earnings": 783,
        "commissions": 783,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8036,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1491,
        "ordered_items": 109,
        "sell_earnings": 518,
        "commissions": 518,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5867,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1433,
        "ordered_items": 97,
        "sell_earnings": 445,
        "commissions": 445,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7085,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1799,
        "ordered_items": 177,
        "sell_earnings": 771,
        "commissions": 771,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7321,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1741,
        "ordered_items": 165,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8539,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1362,
        "ordered_items": 113,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7121,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1870,
        "ordered_items": 161,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7285,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];