export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1273,
        "ordered_items": 130,
        "sell_earnings": 511,
        "commissions": 511,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5863,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1553,
        "ordered_items": 121,
        "sell_earnings": 428,
        "commissions": 428,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6439,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1449,
        "ordered_items": 101,
        "sell_earnings": 555,
        "commissions": 555,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6210,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 1783,
        "ordered_items": 173,
        "sell_earnings": 661,
        "commissions": 661,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8196,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 1679,
        "ordered_items": 153,
        "sell_earnings": 788,
        "commissions": 788,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7967,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 1959,
        "ordered_items": 144,
        "sell_earnings": 705,
        "commissions": 705,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8543,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1368,
        "ordered_items": 116,
        "sell_earnings": 486,
        "commissions": 486,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6833,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1530,
        "ordered_items": 100,
        "sell_earnings": 493,
        "commissions": 493,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5813,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1347,
        "ordered_items": 118,
        "sell_earnings": 594,
        "commissions": 594,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6048,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 1885,
        "ordered_items": 156,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8358,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1702,
        "ordered_items": 174,
        "sell_earnings": 723,
        "commissions": 723,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8593,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 1864,
        "ordered_items": 158,
        "sell_earnings": 730,
        "commissions": 730,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7573,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1141,
        "ordered_items": 126,
        "sell_earnings": 535,
        "commissions": 535,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6245,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 2091,
        "ordered_items": 148,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8161,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1195,
        "ordered_items": 131,
        "sell_earnings": 452,
        "commissions": 452,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5513,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 2037,
        "ordered_items": 143,
        "sell_earnings": 764,
        "commissions": 764,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8893,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1180,
        "ordered_items": 97,
        "sell_earnings": 596,
        "commissions": 596,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5412,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1441,
        "ordered_items": 126,
        "sell_earnings": 443,
        "commissions": 443,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6363,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1267,
        "ordered_items": 99,
        "sell_earnings": 536,
        "commissions": 536,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5922,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1179,
        "ordered_items": 105,
        "sell_earnings": 503,
        "commissions": 503,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6556,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 2053,
        "ordered_items": 169,
        "sell_earnings": 713,
        "commissions": 713,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7850,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 1965,
        "ordered_items": 175,
        "sell_earnings": 680,
        "commissions": 680,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8484,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 1791,
        "ordered_items": 148,
        "sell_earnings": 773,
        "commissions": 773,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8043,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 2052,
        "ordered_items": 177,
        "sell_earnings": 620,
        "commissions": 620,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8994,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1588,
        "ordered_items": 119,
        "sell_earnings": 473,
        "commissions": 473,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5378,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1578,
        "ordered_items": 124,
        "sell_earnings": 429,
        "commissions": 429,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6480,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1654,
        "ordered_items": 150,
        "sell_earnings": 787,
        "commissions": 787,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7926,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 1644,
        "ordered_items": 155,
        "sell_earnings": 743,
        "commissions": 743,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9028,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1363,
        "ordered_items": 132,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6253,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 1869,
        "ordered_items": 142,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8153,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];