export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1502,
        "ordered_items": 119,
        "sell_earnings": 591,
        "commissions": 591,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5682,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1453,
        "ordered_items": 128,
        "sell_earnings": 575,
        "commissions": 575,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6711,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1598,
        "ordered_items": 115,
        "sell_earnings": 552,
        "commissions": 552,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6277,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 1634,
        "ordered_items": 159,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8129,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 1779,
        "ordered_items": 146,
        "sell_earnings": 641,
        "commissions": 641,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7695,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 1730,
        "ordered_items": 155,
        "sell_earnings": 625,
        "commissions": 625,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8724,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1575,
        "ordered_items": 125,
        "sell_earnings": 595,
        "commissions": 595,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7018,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1593,
        "ordered_items": 116,
        "sell_earnings": 473,
        "commissions": 473,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7155,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1573,
        "ordered_items": 119,
        "sell_earnings": 587,
        "commissions": 587,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5768,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 1659,
        "ordered_items": 155,
        "sell_earnings": 629,
        "commissions": 629,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8638,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 1639,
        "ordered_items": 158,
        "sell_earnings": 743,
        "commissions": 743,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7251,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 1657,
        "ordered_items": 149,
        "sell_earnings": 621,
        "commissions": 621,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7388,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1552,
        "ordered_items": 113,
        "sell_earnings": 550,
        "commissions": 550,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7171,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 1680,
        "ordered_items": 161,
        "sell_earnings": 666,
        "commissions": 666,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7235,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1307,
        "ordered_items": 124,
        "sell_earnings": 507,
        "commissions": 507,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6809,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 1925,
        "ordered_items": 150,
        "sell_earnings": 709,
        "commissions": 709,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7597,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1276,
        "ordered_items": 110,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6830,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1371,
        "ordered_items": 134,
        "sell_earnings": 449,
        "commissions": 449,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5363,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1384,
        "ordered_items": 101,
        "sell_earnings": 437,
        "commissions": 437,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6770,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1501,
        "ordered_items": 134,
        "sell_earnings": 451,
        "commissions": 451,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5232,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 1731,
        "ordered_items": 140,
        "sell_earnings": 765,
        "commissions": 765,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9174,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1848,
        "ordered_items": 173,
        "sell_earnings": 779,
        "commissions": 779,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7636,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 1861,
        "ordered_items": 140,
        "sell_earnings": 767,
        "commissions": 767,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9043,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 1956,
        "ordered_items": 164,
        "sell_earnings": 610,
        "commissions": 610,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7576,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1319,
        "ordered_items": 137,
        "sell_earnings": 427,
        "commissions": 427,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6138,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1345,
        "ordered_items": 135,
        "sell_earnings": 479,
        "commissions": 479,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5639,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 1887,
        "ordered_items": 139,
        "sell_earnings": 737,
        "commissions": 737,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8767,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1913,
        "ordered_items": 137,
        "sell_earnings": 789,
        "commissions": 789,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8268,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1532,
        "ordered_items": 115,
        "sell_earnings": 438,
        "commissions": 438,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6957,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 1700,
        "ordered_items": 159,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7449,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];