export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1434,
        "ordered_items": 99,
        "sell_earnings": 518,
        "commissions": 518,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5637,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1529,
        "ordered_items": 122,
        "sell_earnings": 588,
        "commissions": 588,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5390,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1562,
        "ordered_items": 125,
        "sell_earnings": 597,
        "commissions": 597,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5458,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 1670,
        "ordered_items": 149,
        "sell_earnings": 619,
        "commissions": 619,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8948,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 1703,
        "ordered_items": 152,
        "sell_earnings": 628,
        "commissions": 628,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9016,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 1798,
        "ordered_items": 175,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8769,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1541,
        "ordered_items": 122,
        "sell_earnings": 566,
        "commissions": 566,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5689,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1289,
        "ordered_items": 133,
        "sell_earnings": 583,
        "commissions": 583,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5100,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1441,
        "ordered_items": 113,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6766,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 1791,
        "ordered_items": 161,
        "sell_earnings": 753,
        "commissions": 753,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7640,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 1943,
        "ordered_items": 141,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9306,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 1691,
        "ordered_items": 152,
        "sell_earnings": 650,
        "commissions": 650,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8717,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1285,
        "ordered_items": 117,
        "sell_earnings": 524,
        "commissions": 524,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5323,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 1947,
        "ordered_items": 157,
        "sell_earnings": 692,
        "commissions": 692,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9083,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1239,
        "ordered_items": 106,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5596,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 1993,
        "ordered_items": 168,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8810,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1148,
        "ordered_items": 116,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5749,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1526,
        "ordered_items": 113,
        "sell_earnings": 471,
        "commissions": 471,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5544,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1214,
        "ordered_items": 120,
        "sell_earnings": 567,
        "commissions": 567,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6086,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1291,
        "ordered_items": 101,
        "sell_earnings": 498,
        "commissions": 498,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7003,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 1941,
        "ordered_items": 173,
        "sell_earnings": 718,
        "commissions": 718,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7403,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 2018,
        "ordered_items": 154,
        "sell_earnings": 649,
        "commissions": 649,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8320,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 1706,
        "ordered_items": 161,
        "sell_earnings": 745,
        "commissions": 745,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8862,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 2084,
        "ordered_items": 158,
        "sell_earnings": 651,
        "commissions": 651,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8657,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1203,
        "ordered_items": 127,
        "sell_earnings": 546,
        "commissions": 546,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6459,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1303,
        "ordered_items": 113,
        "sell_earnings": 526,
        "commissions": 526,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6472,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 1929,
        "ordered_items": 161,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7934,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 2029,
        "ordered_items": 147,
        "sell_earnings": 670,
        "commissions": 670,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7947,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1136,
        "ordered_items": 132,
        "sell_earnings": 597,
        "commissions": 597,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6548,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 2096,
        "ordered_items": 142,
        "sell_earnings": 619,
        "commissions": 619,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7858,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];