export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1291,
        "ordered_items": 105,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5755,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1352,
        "ordered_items": 103,
        "sell_earnings": 472,
        "commissions": 472,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6720,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1647,
        "ordered_items": 135,
        "sell_earnings": 569,
        "commissions": 569,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6781,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 1693,
        "ordered_items": 149,
        "sell_earnings": 687,
        "commissions": 687,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8105,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 1988,
        "ordered_items": 181,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8166,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 2049,
        "ordered_items": 179,
        "sell_earnings": 792,
        "commissions": 792,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9131,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1549,
        "ordered_items": 111,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5777,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1623,
        "ordered_items": 139,
        "sell_earnings": 486,
        "commissions": 486,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5736,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1245,
        "ordered_items": 117,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7308,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 2095,
        "ordered_items": 167,
        "sell_earnings": 729,
        "commissions": 729,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7578,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 1717,
        "ordered_items": 145,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9150,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 1791,
        "ordered_items": 173,
        "sell_earnings": 634,
        "commissions": 634,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9109,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1554,
        "ordered_items": 119,
        "sell_earnings": 455,
        "commissions": 455,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7263,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 1786,
        "ordered_items": 165,
        "sell_earnings": 801,
        "commissions": 801,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7623,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1501,
        "ordered_items": 128,
        "sell_earnings": 514,
        "commissions": 514,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6551,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 1839,
        "ordered_items": 156,
        "sell_earnings": 742,
        "commissions": 742,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8335,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1657,
        "ordered_items": 113,
        "sell_earnings": 559,
        "commissions": 559,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5408,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1448,
        "ordered_items": 112,
        "sell_earnings": 548,
        "commissions": 548,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7192,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1224,
        "ordered_items": 111,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6910,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1614,
        "ordered_items": 133,
        "sell_earnings": 476,
        "commissions": 476,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7253,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 1726,
        "ordered_items": 151,
        "sell_earnings": 780,
        "commissions": 780,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7633,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 2116,
        "ordered_items": 173,
        "sell_earnings": 741,
        "commissions": 741,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7976,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 1892,
        "ordered_items": 172,
        "sell_earnings": 708,
        "commissions": 708,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7694,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 1683,
        "ordered_items": 171,
        "sell_earnings": 697,
        "commissions": 697,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9478,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1506,
        "ordered_items": 134,
        "sell_earnings": 532,
        "commissions": 532,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7374,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1476,
        "ordered_items": 141,
        "sell_earnings": 556,
        "commissions": 556,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6901,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 1864,
        "ordered_items": 143,
        "sell_earnings": 700,
        "commissions": 700,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7985,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 1834,
        "ordered_items": 150,
        "sell_earnings": 724,
        "commissions": 724,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7512,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1481,
        "ordered_items": 134,
        "sell_earnings": 519,
        "commissions": 519,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5821,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 1859,
        "ordered_items": 150,
        "sell_earnings": 737,
        "commissions": 737,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9065,
        "bonus": 2
    }
];