export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1579,
        "ordered_items": 106,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5321,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1139,
        "ordered_items": 134,
        "sell_earnings": 602,
        "commissions": 602,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6471,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1212,
        "ordered_items": 126,
        "sell_earnings": 503,
        "commissions": 503,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6662,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 2020,
        "ordered_items": 148,
        "sell_earnings": 713,
        "commissions": 713,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7744,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 2093,
        "ordered_items": 140,
        "sell_earnings": 614,
        "commissions": 614,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7935,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 1653,
        "ordered_items": 168,
        "sell_earnings": 720,
        "commissions": 720,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9085,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1544,
        "ordered_items": 137,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5385,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1217,
        "ordered_items": 130,
        "sell_earnings": 439,
        "commissions": 439,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6708,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1489,
        "ordered_items": 116,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6027,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 1743,
        "ordered_items": 158,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8379,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 2015,
        "ordered_items": 144,
        "sell_earnings": 777,
        "commissions": 777,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7698,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1688,
        "ordered_items": 137,
        "sell_earnings": 610,
        "commissions": 610,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9021,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1266,
        "ordered_items": 109,
        "sell_earnings": 564,
        "commissions": 564,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7106,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 1966,
        "ordered_items": 165,
        "sell_earnings": 652,
        "commissions": 652,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7300,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1536,
        "ordered_items": 110,
        "sell_earnings": 449,
        "commissions": 449,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5460,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 1696,
        "ordered_items": 164,
        "sell_earnings": 767,
        "commissions": 767,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8946,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1523,
        "ordered_items": 98,
        "sell_earnings": 432,
        "commissions": 432,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6458,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1439,
        "ordered_items": 116,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5124,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1146,
        "ordered_items": 129,
        "sell_earnings": 473,
        "commissions": 473,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6187,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1294,
        "ordered_items": 125,
        "sell_earnings": 469,
        "commissions": 469,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5214,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 1938,
        "ordered_items": 149,
        "sell_earnings": 747,
        "commissions": 747,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9192,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 2086,
        "ordered_items": 145,
        "sell_earnings": 743,
        "commissions": 743,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8219,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 1793,
        "ordered_items": 158,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9282,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1709,
        "ordered_items": 176,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7948,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1616,
        "ordered_items": 120,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6810,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1437,
        "ordered_items": 116,
        "sell_earnings": 518,
        "commissions": 518,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5228,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 1795,
        "ordered_items": 158,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9178,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 1616,
        "ordered_items": 154,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7596,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1193,
        "ordered_items": 109,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6609,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 2039,
        "ordered_items": 165,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7797,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];