export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1328,
        "ordered_items": 124,
        "sell_earnings": 479,
        "commissions": 479,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6397,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1218,
        "ordered_items": 100,
        "sell_earnings": 445,
        "commissions": 445,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6999,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1229,
        "ordered_items": 133,
        "sell_earnings": 596,
        "commissions": 596,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5978,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 2003,
        "ordered_items": 141,
        "sell_earnings": 620,
        "commissions": 620,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8428,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 2014,
        "ordered_items": 174,
        "sell_earnings": 771,
        "commissions": 771,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7407,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 1904,
        "ordered_items": 150,
        "sell_earnings": 737,
        "commissions": 737,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8009,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1154,
        "ordered_items": 98,
        "sell_earnings": 447,
        "commissions": 447,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6209,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1427,
        "ordered_items": 134,
        "sell_earnings": 596,
        "commissions": 596,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5135,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1401,
        "ordered_items": 125,
        "sell_earnings": 581,
        "commissions": 581,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5059,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 1831,
        "ordered_items": 149,
        "sell_earnings": 635,
        "commissions": 635,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9347,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1805,
        "ordered_items": 140,
        "sell_earnings": 620,
        "commissions": 620,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9271,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 2078,
        "ordered_items": 176,
        "sell_earnings": 769,
        "commissions": 769,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8197,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1546,
        "ordered_items": 114,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5327,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 1686,
        "ordered_items": 160,
        "sell_earnings": 753,
        "commissions": 753,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9079,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1380,
        "ordered_items": 114,
        "sell_earnings": 548,
        "commissions": 548,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5859,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 1852,
        "ordered_items": 160,
        "sell_earnings": 668,
        "commissions": 668,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8547,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1354,
        "ordered_items": 133,
        "sell_earnings": 488,
        "commissions": 488,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7073,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1256,
        "ordered_items": 131,
        "sell_earnings": 518,
        "commissions": 518,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5792,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1571,
        "ordered_items": 133,
        "sell_earnings": 507,
        "commissions": 507,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5894,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1590,
        "ordered_items": 119,
        "sell_earnings": 441,
        "commissions": 441,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7067,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 1642,
        "ordered_items": 155,
        "sell_earnings": 775,
        "commissions": 775,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7339,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 1661,
        "ordered_items": 141,
        "sell_earnings": 709,
        "commissions": 709,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8512,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 1976,
        "ordered_items": 143,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8614,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 1878,
        "ordered_items": 141,
        "sell_earnings": 728,
        "commissions": 728,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7333,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1341,
        "ordered_items": 103,
        "sell_earnings": 427,
        "commissions": 427,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5233,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1242,
        "ordered_items": 135,
        "sell_earnings": 436,
        "commissions": 436,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5385,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1990,
        "ordered_items": 139,
        "sell_earnings": 780,
        "commissions": 780,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9021,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 1891,
        "ordered_items": 171,
        "sell_earnings": 789,
        "commissions": 789,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9173,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1602,
        "ordered_items": 104,
        "sell_earnings": 467,
        "commissions": 467,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5475,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 1630,
        "ordered_items": 170,
        "sell_earnings": 749,
        "commissions": 749,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8931,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];