export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1157,
        "ordered_items": 108,
        "sell_earnings": 516,
        "commissions": 516,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6785,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1241,
        "ordered_items": 132,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6086,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1583,
        "ordered_items": 118,
        "sell_earnings": 472,
        "commissions": 472,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6446,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 1649,
        "ordered_items": 156,
        "sell_earnings": 744,
        "commissions": 744,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7960,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 1991,
        "ordered_items": 142,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8320,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 2075,
        "ordered_items": 166,
        "sell_earnings": 700,
        "commissions": 700,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7621,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1209,
        "ordered_items": 129,
        "sell_earnings": 546,
        "commissions": 546,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6893,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1581,
        "ordered_items": 119,
        "sell_earnings": 537,
        "commissions": 537,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6134,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1437,
        "ordered_items": 103,
        "sell_earnings": 427,
        "commissions": 427,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6040,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 1795,
        "ordered_items": 171,
        "sell_earnings": 789,
        "commissions": 789,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8366,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 1651,
        "ordered_items": 155,
        "sell_earnings": 679,
        "commissions": 679,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8272,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 2023,
        "ordered_items": 145,
        "sell_earnings": 670,
        "commissions": 670,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7513,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1571,
        "ordered_items": 129,
        "sell_earnings": 584,
        "commissions": 584,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6701,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 1661,
        "ordered_items": 145,
        "sell_earnings": 632,
        "commissions": 632,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7705,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1422,
        "ordered_items": 97,
        "sell_earnings": 571,
        "commissions": 571,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6075,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 1810,
        "ordered_items": 177,
        "sell_earnings": 645,
        "commissions": 645,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8331,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1148,
        "ordered_items": 104,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5307,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1555,
        "ordered_items": 132,
        "sell_earnings": 546,
        "commissions": 546,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5953,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1307,
        "ordered_items": 116,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6531,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1142,
        "ordered_items": 102,
        "sell_earnings": 536,
        "commissions": 536,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6415,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 2090,
        "ordered_items": 172,
        "sell_earnings": 680,
        "commissions": 680,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7991,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1925,
        "ordered_items": 158,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7875,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 1677,
        "ordered_items": 142,
        "sell_earnings": 670,
        "commissions": 670,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8453,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 2084,
        "ordered_items": 170,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9099,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1423,
        "ordered_items": 108,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5821,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1349,
        "ordered_items": 109,
        "sell_earnings": 472,
        "commissions": 472,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5568,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 1883,
        "ordered_items": 165,
        "sell_earnings": 744,
        "commissions": 744,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8838,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1809,
        "ordered_items": 166,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8585,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1585,
        "ordered_items": 112,
        "sell_earnings": 468,
        "commissions": 468,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5848,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 1647,
        "ordered_items": 162,
        "sell_earnings": 748,
        "commissions": 748,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8558,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];