export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1334,
        "ordered_items": 111,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5958,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1466,
        "ordered_items": 114,
        "sell_earnings": 447,
        "commissions": 447,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6050,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1498,
        "ordered_items": 97,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7120,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 1734,
        "ordered_items": 177,
        "sell_earnings": 752,
        "commissions": 752,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7286,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 1766,
        "ordered_items": 160,
        "sell_earnings": 769,
        "commissions": 769,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8356,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 1898,
        "ordered_items": 163,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8448,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1578,
        "ordered_items": 103,
        "sell_earnings": 538,
        "commissions": 538,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5200,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1427,
        "ordered_items": 104,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5385,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1492,
        "ordered_items": 107,
        "sell_earnings": 549,
        "commissions": 549,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5323,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 1740,
        "ordered_items": 167,
        "sell_earnings": 667,
        "commissions": 667,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9083,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 1805,
        "ordered_items": 170,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9021,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 1654,
        "ordered_items": 171,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9206,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1454,
        "ordered_items": 103,
        "sell_earnings": 591,
        "commissions": 591,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6891,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 1778,
        "ordered_items": 171,
        "sell_earnings": 625,
        "commissions": 625,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7515,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1238,
        "ordered_items": 99,
        "sell_earnings": 558,
        "commissions": 558,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5303,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 1994,
        "ordered_items": 175,
        "sell_earnings": 658,
        "commissions": 658,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9103,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1217,
        "ordered_items": 120,
        "sell_earnings": 585,
        "commissions": 585,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7188,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1210,
        "ordered_items": 101,
        "sell_earnings": 457,
        "commissions": 457,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6682,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1135,
        "ordered_items": 132,
        "sell_earnings": 466,
        "commissions": 466,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5672,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1169,
        "ordered_items": 119,
        "sell_earnings": 484,
        "commissions": 484,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6028,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 2063,
        "ordered_items": 155,
        "sell_earnings": 732,
        "commissions": 732,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8378,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 2097,
        "ordered_items": 142,
        "sell_earnings": 750,
        "commissions": 750,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8734,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 2022,
        "ordered_items": 173,
        "sell_earnings": 759,
        "commissions": 759,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7724,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 2015,
        "ordered_items": 154,
        "sell_earnings": 631,
        "commissions": 631,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7218,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1582,
        "ordered_items": 126,
        "sell_earnings": 542,
        "commissions": 542,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6809,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1163,
        "ordered_items": 111,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5482,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 2069,
        "ordered_items": 163,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8924,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 1650,
        "ordered_items": 148,
        "sell_earnings": 674,
        "commissions": 674,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7597,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1457,
        "ordered_items": 111,
        "sell_earnings": 469,
        "commissions": 469,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6768,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 1775,
        "ordered_items": 163,
        "sell_earnings": 747,
        "commissions": 747,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7638,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];