export let mar = [
    {
        "month": "Mar",
        "day": "01",
        "clicks": 1578,
        "ordered_items": 128,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6539,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "02",
        "clicks": 1419,
        "ordered_items": 117,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5047,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "03",
        "clicks": 1269,
        "ordered_items": 110,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5991,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "04",
        "clicks": 1963,
        "ordered_items": 164,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8415,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "05",
        "clicks": 1813,
        "ordered_items": 157,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9359,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "06",
        "clicks": 1654,
        "ordered_items": 146,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7867,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "07",
        "clicks": 1386,
        "ordered_items": 130,
        "sell_earnings": 563,
        "commissions": 563,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5595,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "08",
        "clicks": 1328,
        "ordered_items": 135,
        "sell_earnings": 438,
        "commissions": 438,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6832,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "09",
        "clicks": 1444,
        "ordered_items": 134,
        "sell_earnings": 466,
        "commissions": 466,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5794,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "10",
        "clicks": 1788,
        "ordered_items": 140,
        "sell_earnings": 750,
        "commissions": 750,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8612,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "11",
        "clicks": 1904,
        "ordered_items": 139,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7574,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "12",
        "clicks": 1846,
        "ordered_items": 144,
        "sell_earnings": 653,
        "commissions": 653,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8811,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "13",
        "clicks": 1460,
        "ordered_items": 122,
        "sell_earnings": 525,
        "commissions": 525,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6201,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "14",
        "clicks": 1772,
        "ordered_items": 152,
        "sell_earnings": 691,
        "commissions": 691,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8205,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "15",
        "clicks": 1492,
        "ordered_items": 98,
        "sell_earnings": 532,
        "commissions": 532,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5504,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "16",
        "clicks": 1740,
        "ordered_items": 176,
        "sell_earnings": 684,
        "commissions": 684,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8902,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "17",
        "clicks": 1486,
        "ordered_items": 136,
        "sell_earnings": 435,
        "commissions": 435,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5610,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "18",
        "clicks": 1566,
        "ordered_items": 135,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6598,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "19",
        "clicks": 1240,
        "ordered_items": 127,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5735,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "20",
        "clicks": 1551,
        "ordered_items": 108,
        "sell_earnings": 486,
        "commissions": 486,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6547,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "21",
        "clicks": 1681,
        "ordered_items": 166,
        "sell_earnings": 730,
        "commissions": 730,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7859,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "22",
        "clicks": 1992,
        "ordered_items": 147,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8671,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "23",
        "clicks": 1666,
        "ordered_items": 139,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7808,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "24",
        "clicks": 1746,
        "ordered_items": 138,
        "sell_earnings": 781,
        "commissions": 781,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8796,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "25",
        "clicks": 1336,
        "ordered_items": 101,
        "sell_earnings": 556,
        "commissions": 556,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5754,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "26",
        "clicks": 1566,
        "ordered_items": 125,
        "sell_earnings": 592,
        "commissions": 592,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6023,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "27",
        "clicks": 1666,
        "ordered_items": 149,
        "sell_earnings": 624,
        "commissions": 624,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8383,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "28",
        "clicks": 1896,
        "ordered_items": 173,
        "sell_earnings": 660,
        "commissions": 660,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8652,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "29",
        "clicks": 1274,
        "ordered_items": 114,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5684,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "30",
        "clicks": 1958,
        "ordered_items": 160,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8722,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];