export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1224,
        "ordered_items": 135,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6222,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1135,
        "ordered_items": 99,
        "sell_earnings": 440,
        "commissions": 440,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6584,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1407,
        "ordered_items": 117,
        "sell_earnings": 579,
        "commissions": 579,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6641,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 1825,
        "ordered_items": 157,
        "sell_earnings": 637,
        "commissions": 637,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7765,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 2097,
        "ordered_items": 175,
        "sell_earnings": 776,
        "commissions": 776,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7822,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 2008,
        "ordered_items": 139,
        "sell_earnings": 676,
        "commissions": 676,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8184,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1254,
        "ordered_items": 112,
        "sell_earnings": 505,
        "commissions": 505,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7123,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1260,
        "ordered_items": 115,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5414,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1410,
        "ordered_items": 135,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6373,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 1822,
        "ordered_items": 139,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8033,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 1972,
        "ordered_items": 159,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8992,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1978,
        "ordered_items": 162,
        "sell_earnings": 711,
        "commissions": 711,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7283,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1477,
        "ordered_items": 118,
        "sell_earnings": 483,
        "commissions": 483,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6293,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 1755,
        "ordered_items": 156,
        "sell_earnings": 733,
        "commissions": 733,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8113,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1252,
        "ordered_items": 97,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5859,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 1980,
        "ordered_items": 177,
        "sell_earnings": 721,
        "commissions": 721,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8547,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1377,
        "ordered_items": 137,
        "sell_earnings": 519,
        "commissions": 519,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6859,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1240,
        "ordered_items": 133,
        "sell_earnings": 439,
        "commissions": 439,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5609,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1472,
        "ordered_items": 97,
        "sell_earnings": 601,
        "commissions": 601,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6223,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1514,
        "ordered_items": 113,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5737,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 1718,
        "ordered_items": 161,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8669,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 1760,
        "ordered_items": 177,
        "sell_earnings": 615,
        "commissions": 615,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8183,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 1992,
        "ordered_items": 141,
        "sell_earnings": 777,
        "commissions": 777,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8797,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1855,
        "ordered_items": 137,
        "sell_earnings": 697,
        "commissions": 697,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7547,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1334,
        "ordered_items": 102,
        "sell_earnings": 516,
        "commissions": 516,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6788,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1249,
        "ordered_items": 128,
        "sell_earnings": 484,
        "commissions": 484,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7072,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 1983,
        "ordered_items": 146,
        "sell_earnings": 732,
        "commissions": 732,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7334,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 1898,
        "ordered_items": 172,
        "sell_earnings": 700,
        "commissions": 700,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7618,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1517,
        "ordered_items": 122,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5115,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 1715,
        "ordered_items": 152,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9291,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];