export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1615,
        "ordered_items": 114,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7154,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1355,
        "ordered_items": 137,
        "sell_earnings": 538,
        "commissions": 538,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7032,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1206,
        "ordered_items": 110,
        "sell_earnings": 518,
        "commissions": 518,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6595,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 2134,
        "ordered_items": 174,
        "sell_earnings": 738,
        "commissions": 738,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8291,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 1985,
        "ordered_items": 147,
        "sell_earnings": 718,
        "commissions": 718,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7854,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 1725,
        "ordered_items": 170,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7732,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1339,
        "ordered_items": 136,
        "sell_earnings": 506,
        "commissions": 506,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5214,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1171,
        "ordered_items": 105,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5598,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1582,
        "ordered_items": 133,
        "sell_earnings": 548,
        "commissions": 548,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5890,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 1758,
        "ordered_items": 151,
        "sell_earnings": 708,
        "commissions": 708,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 167,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8996,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 2169,
        "ordered_items": 179,
        "sell_earnings": 793,
        "commissions": 793,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9288,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 2001,
        "ordered_items": 148,
        "sell_earnings": 750,
        "commissions": 750,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9672,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1598,
        "ordered_items": 116,
        "sell_earnings": 473,
        "commissions": 473,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6578,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 1742,
        "ordered_items": 168,
        "sell_earnings": 783,
        "commissions": 783,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8308,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1430,
        "ordered_items": 105,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5351,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 1910,
        "ordered_items": 179,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9535,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1503,
        "ordered_items": 129,
        "sell_earnings": 451,
        "commissions": 451,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6293,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1630,
        "ordered_items": 115,
        "sell_earnings": 452,
        "commissions": 452,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5448,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1252,
        "ordered_items": 135,
        "sell_earnings": 519,
        "commissions": 519,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6804,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1362,
        "ordered_items": 112,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6243,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 1978,
        "ordered_items": 172,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8643,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 2088,
        "ordered_items": 149,
        "sell_earnings": 737,
        "commissions": 737,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8082,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 1710,
        "ordered_items": 169,
        "sell_earnings": 804,
        "commissions": 804,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9438,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 1837,
        "ordered_items": 155,
        "sell_earnings": 805,
        "commissions": 805,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8593,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1454,
        "ordered_items": 128,
        "sell_earnings": 454,
        "commissions": 454,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6320,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1669,
        "ordered_items": 108,
        "sell_earnings": 577,
        "commissions": 577,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6918,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 1671,
        "ordered_items": 176,
        "sell_earnings": 679,
        "commissions": 679,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7968,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 1886,
        "ordered_items": 156,
        "sell_earnings": 802,
        "commissions": 802,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8566,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1271,
        "ordered_items": 138,
        "sell_earnings": 521,
        "commissions": 521,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7309,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 2069,
        "ordered_items": 146,
        "sell_earnings": 735,
        "commissions": 735,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7577,
        "bonus": 2
    }
];