export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1531,
        "ordered_items": 130,
        "sell_earnings": 435,
        "commissions": 435,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6447,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1286,
        "ordered_items": 132,
        "sell_earnings": 596,
        "commissions": 596,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7159,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1441,
        "ordered_items": 120,
        "sell_earnings": 537,
        "commissions": 537,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5284,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 1791,
        "ordered_items": 154,
        "sell_earnings": 679,
        "commissions": 679,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9122,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 1946,
        "ordered_items": 142,
        "sell_earnings": 620,
        "commissions": 620,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7247,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 1701,
        "ordered_items": 144,
        "sell_earnings": 781,
        "commissions": 781,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7959,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1240,
        "ordered_items": 135,
        "sell_earnings": 465,
        "commissions": 465,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5852,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1500,
        "ordered_items": 120,
        "sell_earnings": 530,
        "commissions": 530,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6155,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1589,
        "ordered_items": 119,
        "sell_earnings": 588,
        "commissions": 588,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6873,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 1643,
        "ordered_items": 155,
        "sell_earnings": 628,
        "commissions": 628,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7533,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 1732,
        "ordered_items": 154,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8251,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1992,
        "ordered_items": 139,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8554,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1569,
        "ordered_items": 137,
        "sell_earnings": 544,
        "commissions": 544,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5502,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 1663,
        "ordered_items": 137,
        "sell_earnings": 672,
        "commissions": 672,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8904,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1431,
        "ordered_items": 101,
        "sell_earnings": 594,
        "commissions": 594,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5826,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 1801,
        "ordered_items": 173,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8580,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1570,
        "ordered_items": 129,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5673,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1272,
        "ordered_items": 110,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7063,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1519,
        "ordered_items": 106,
        "sell_earnings": 444,
        "commissions": 444,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5256,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1403,
        "ordered_items": 98,
        "sell_earnings": 584,
        "commissions": 584,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6268,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 1829,
        "ordered_items": 176,
        "sell_earnings": 632,
        "commissions": 632,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8138,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 1713,
        "ordered_items": 168,
        "sell_earnings": 772,
        "commissions": 772,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9150,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 1960,
        "ordered_items": 164,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7343,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1662,
        "ordered_items": 145,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8733,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1134,
        "ordered_items": 134,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6614,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1383,
        "ordered_items": 111,
        "sell_earnings": 512,
        "commissions": 512,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5820,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 1849,
        "ordered_items": 163,
        "sell_earnings": 704,
        "commissions": 704,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8586,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 2098,
        "ordered_items": 140,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7792,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1475,
        "ordered_items": 108,
        "sell_earnings": 487,
        "commissions": 487,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5979,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 1757,
        "ordered_items": 166,
        "sell_earnings": 729,
        "commissions": 729,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8427,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];