export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1450,
        "ordered_items": 116,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6857,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1329,
        "ordered_items": 130,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7331,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1353,
        "ordered_items": 116,
        "sell_earnings": 522,
        "commissions": 522,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5366,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 1987,
        "ordered_items": 168,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9520,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 2011,
        "ordered_items": 154,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 165,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7555,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 1890,
        "ordered_items": 168,
        "sell_earnings": 800,
        "commissions": 800,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8029,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1419,
        "ordered_items": 106,
        "sell_earnings": 585,
        "commissions": 585,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6794,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1364,
        "ordered_items": 110,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5700,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1305,
        "ordered_items": 112,
        "sell_earnings": 625,
        "commissions": 625,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7423,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 2035,
        "ordered_items": 172,
        "sell_earnings": 631,
        "commissions": 631,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7463,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 1976,
        "ordered_items": 174,
        "sell_earnings": 741,
        "commissions": 741,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 168,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9186,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 1921,
        "ordered_items": 178,
        "sell_earnings": 671,
        "commissions": 671,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8092,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1579,
        "ordered_items": 117,
        "sell_earnings": 602,
        "commissions": 602,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6970,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 1761,
        "ordered_items": 167,
        "sell_earnings": 654,
        "commissions": 654,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7916,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1536,
        "ordered_items": 138,
        "sell_earnings": 602,
        "commissions": 602,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6542,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 1804,
        "ordered_items": 146,
        "sell_earnings": 654,
        "commissions": 654,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8344,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1336,
        "ordered_items": 118,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6133,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1249,
        "ordered_items": 109,
        "sell_earnings": 486,
        "commissions": 486,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6901,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1628,
        "ordered_items": 130,
        "sell_earnings": 473,
        "commissions": 473,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5226,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1566,
        "ordered_items": 103,
        "sell_earnings": 525,
        "commissions": 525,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6755,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 1774,
        "ordered_items": 181,
        "sell_earnings": 731,
        "commissions": 731,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8131,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 1712,
        "ordered_items": 154,
        "sell_earnings": 783,
        "commissions": 783,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 165,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9660,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 2091,
        "ordered_items": 175,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7985,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 2004,
        "ordered_items": 166,
        "sell_earnings": 798,
        "commissions": 798,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 169,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8753,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1664,
        "ordered_items": 116,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6305,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1241,
        "ordered_items": 106,
        "sell_earnings": 449,
        "commissions": 449,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6738,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 2099,
        "ordered_items": 178,
        "sell_earnings": 807,
        "commissions": 807,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 166,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8148,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 1676,
        "ordered_items": 168,
        "sell_earnings": 691,
        "commissions": 691,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8581,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1428,
        "ordered_items": 127,
        "sell_earnings": 577,
        "commissions": 577,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5310,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 1912,
        "ordered_items": 157,
        "sell_earnings": 679,
        "commissions": 679,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 165,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9576,
        "bonus": 2
    }
];