export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1360,
        "ordered_items": 103,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5723,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1445,
        "ordered_items": 117,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6840,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1396,
        "ordered_items": 131,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6445,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 1836,
        "ordered_items": 143,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7961,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1787,
        "ordered_items": 157,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7566,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 1872,
        "ordered_items": 171,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8683,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1297,
        "ordered_items": 118,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7185,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1310,
        "ordered_items": 137,
        "sell_earnings": 510,
        "commissions": 510,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6792,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1303,
        "ordered_items": 110,
        "sell_earnings": 578,
        "commissions": 578,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5288,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1929,
        "ordered_items": 164,
        "sell_earnings": 638,
        "commissions": 638,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9118,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 1922,
        "ordered_items": 137,
        "sell_earnings": 706,
        "commissions": 706,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7614,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1935,
        "ordered_items": 156,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7221,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1217,
        "ordered_items": 106,
        "sell_earnings": 590,
        "commissions": 590,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5892,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 2015,
        "ordered_items": 168,
        "sell_earnings": 626,
        "commissions": 626,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8514,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1520,
        "ordered_items": 117,
        "sell_earnings": 589,
        "commissions": 589,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5841,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1712,
        "ordered_items": 157,
        "sell_earnings": 627,
        "commissions": 627,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8565,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1456,
        "ordered_items": 101,
        "sell_earnings": 492,
        "commissions": 492,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5499,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1185,
        "ordered_items": 110,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5623,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1388,
        "ordered_items": 102,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6692,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1202,
        "ordered_items": 98,
        "sell_earnings": 600,
        "commissions": 600,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5179,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 2030,
        "ordered_items": 176,
        "sell_earnings": 616,
        "commissions": 616,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9227,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1844,
        "ordered_items": 172,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7714,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 2047,
        "ordered_items": 164,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8783,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1776,
        "ordered_items": 173,
        "sell_earnings": 724,
        "commissions": 724,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8907,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1214,
        "ordered_items": 119,
        "sell_earnings": 530,
        "commissions": 530,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6786,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1490,
        "ordered_items": 110,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5674,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1742,
        "ordered_items": 164,
        "sell_earnings": 720,
        "commissions": 720,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8732,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 2018,
        "ordered_items": 155,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7620,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1438,
        "ordered_items": 131,
        "sell_earnings": 584,
        "commissions": 584,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5953,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1794,
        "ordered_items": 143,
        "sell_earnings": 632,
        "commissions": 632,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8453,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];