export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 1448,
        "ordered_items": 123,
        "sell_earnings": 586,
        "commissions": 586,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5754,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 1269,
        "ordered_items": 138,
        "sell_earnings": 554,
        "commissions": 554,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5542,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 1302,
        "ordered_items": 142,
        "sell_earnings": 545,
        "commissions": 545,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5738,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 2038,
        "ordered_items": 142,
        "sell_earnings": 711,
        "commissions": 711,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9148,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 2071,
        "ordered_items": 146,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 167,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9344,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 1892,
        "ordered_items": 161,
        "sell_earnings": 670,
        "commissions": 670,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9132,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 1598,
        "ordered_items": 140,
        "sell_earnings": 619,
        "commissions": 619,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6219,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 1631,
        "ordered_items": 125,
        "sell_earnings": 538,
        "commissions": 538,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6903,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 1567,
        "ordered_items": 125,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6664,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 1773,
        "ordered_items": 159,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8222,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 1709,
        "ordered_items": 159,
        "sell_earnings": 718,
        "commissions": 718,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7983,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 1742,
        "ordered_items": 144,
        "sell_earnings": 637,
        "commissions": 637,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8667,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 1406,
        "ordered_items": 114,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6627,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 1934,
        "ordered_items": 170,
        "sell_earnings": 741,
        "commissions": 741,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8259,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 1596,
        "ordered_items": 139,
        "sell_earnings": 525,
        "commissions": 525,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6091,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 1744,
        "ordered_items": 145,
        "sell_earnings": 731,
        "commissions": 731,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8795,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 1419,
        "ordered_items": 112,
        "sell_earnings": 553,
        "commissions": 553,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7339,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 1276,
        "ordered_items": 103,
        "sell_earnings": 493,
        "commissions": 493,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6074,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 1489,
        "ordered_items": 133,
        "sell_earnings": 498,
        "commissions": 498,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7099,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 1569,
        "ordered_items": 111,
        "sell_earnings": 576,
        "commissions": 576,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5631,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 1771,
        "ordered_items": 173,
        "sell_earnings": 680,
        "commissions": 680,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 169,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9255,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 1851,
        "ordered_items": 151,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7787,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 2064,
        "ordered_items": 181,
        "sell_earnings": 763,
        "commissions": 763,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8812,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 1921,
        "ordered_items": 172,
        "sell_earnings": 703,
        "commissions": 703,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7547,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 1294,
        "ordered_items": 129,
        "sell_earnings": 607,
        "commissions": 607,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6130,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 1591,
        "ordered_items": 123,
        "sell_earnings": 522,
        "commissions": 522,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6684,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 1749,
        "ordered_items": 161,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8202,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 2046,
        "ordered_items": 155,
        "sell_earnings": 649,
        "commissions": 649,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8756,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 1434,
        "ordered_items": 121,
        "sell_earnings": 523,
        "commissions": 523,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7312,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 1906,
        "ordered_items": 163,
        "sell_earnings": 733,
        "commissions": 733,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7574,
        "bonus": 0
    }
];