export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1493,
        "ordered_items": 129,
        "sell_earnings": 486,
        "commissions": 486,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6218,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1424,
        "ordered_items": 125,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5820,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1596,
        "ordered_items": 114,
        "sell_earnings": 555,
        "commissions": 555,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5184,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 1636,
        "ordered_items": 160,
        "sell_earnings": 661,
        "commissions": 661,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9222,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 1808,
        "ordered_items": 149,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8586,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 1739,
        "ordered_items": 145,
        "sell_earnings": 730,
        "commissions": 730,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8188,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1400,
        "ordered_items": 122,
        "sell_earnings": 429,
        "commissions": 429,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6827,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1473,
        "ordered_items": 131,
        "sell_earnings": 590,
        "commissions": 590,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6533,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1466,
        "ordered_items": 122,
        "sell_earnings": 467,
        "commissions": 467,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5272,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 1766,
        "ordered_items": 152,
        "sell_earnings": 749,
        "commissions": 749,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9134,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1759,
        "ordered_items": 143,
        "sell_earnings": 626,
        "commissions": 626,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7873,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 1832,
        "ordered_items": 152,
        "sell_earnings": 787,
        "commissions": 787,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7579,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1267,
        "ordered_items": 127,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5188,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 1965,
        "ordered_items": 147,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9218,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1278,
        "ordered_items": 129,
        "sell_earnings": 510,
        "commissions": 510,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5333,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 1954,
        "ordered_items": 145,
        "sell_earnings": 706,
        "commissions": 706,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9073,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1501,
        "ordered_items": 119,
        "sell_earnings": 443,
        "commissions": 443,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6925,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1605,
        "ordered_items": 134,
        "sell_earnings": 563,
        "commissions": 563,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6839,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1484,
        "ordered_items": 121,
        "sell_earnings": 532,
        "commissions": 532,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7036,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1494,
        "ordered_items": 120,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7147,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 1738,
        "ordered_items": 154,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7259,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 1748,
        "ordered_items": 153,
        "sell_earnings": 684,
        "commissions": 684,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7370,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 1627,
        "ordered_items": 140,
        "sell_earnings": 653,
        "commissions": 653,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7567,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 1731,
        "ordered_items": 155,
        "sell_earnings": 773,
        "commissions": 773,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7481,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1225,
        "ordered_items": 106,
        "sell_earnings": 430,
        "commissions": 430,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5963,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1387,
        "ordered_items": 102,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5818,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1845,
        "ordered_items": 172,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8588,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 2007,
        "ordered_items": 168,
        "sell_earnings": 786,
        "commissions": 786,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8443,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1430,
        "ordered_items": 127,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5104,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 1802,
        "ordered_items": 147,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9302,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];