export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1556,
        "ordered_items": 125,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6876,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1506,
        "ordered_items": 127,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6795,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1311,
        "ordered_items": 126,
        "sell_earnings": 478,
        "commissions": 478,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6238,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 2029,
        "ordered_items": 158,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8648,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 1834,
        "ordered_items": 157,
        "sell_earnings": 634,
        "commissions": 634,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8091,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 1784,
        "ordered_items": 159,
        "sell_earnings": 741,
        "commissions": 741,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8010,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1190,
        "ordered_items": 110,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6854,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1360,
        "ordered_items": 120,
        "sell_earnings": 555,
        "commissions": 555,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7353,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1332,
        "ordered_items": 113,
        "sell_earnings": 516,
        "commissions": 516,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5915,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 2008,
        "ordered_items": 171,
        "sell_earnings": 740,
        "commissions": 740,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8971,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 1980,
        "ordered_items": 164,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7533,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 2150,
        "ordered_items": 174,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8032,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1311,
        "ordered_items": 110,
        "sell_earnings": 525,
        "commissions": 525,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7282,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 2029,
        "ordered_items": 174,
        "sell_earnings": 731,
        "commissions": 731,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 169,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7604,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1664,
        "ordered_items": 114,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7324,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 1676,
        "ordered_items": 170,
        "sell_earnings": 792,
        "commissions": 792,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7562,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1443,
        "ordered_items": 100,
        "sell_earnings": 476,
        "commissions": 476,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7389,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1562,
        "ordered_items": 120,
        "sell_earnings": 557,
        "commissions": 557,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7359,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1642,
        "ordered_items": 115,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6909,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1648,
        "ordered_items": 118,
        "sell_earnings": 586,
        "commissions": 586,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6314,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 1692,
        "ordered_items": 166,
        "sell_earnings": 670,
        "commissions": 670,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8572,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 1698,
        "ordered_items": 169,
        "sell_earnings": 798,
        "commissions": 798,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7977,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 1778,
        "ordered_items": 164,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7527,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 1897,
        "ordered_items": 184,
        "sell_earnings": 780,
        "commissions": 780,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7497,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1592,
        "ordered_items": 110,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6045,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1207,
        "ordered_items": 109,
        "sell_earnings": 547,
        "commissions": 547,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6433,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 2133,
        "ordered_items": 175,
        "sell_earnings": 709,
        "commissions": 709,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8453,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 1748,
        "ordered_items": 174,
        "sell_earnings": 644,
        "commissions": 644,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8841,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1414,
        "ordered_items": 104,
        "sell_earnings": 563,
        "commissions": 563,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6303,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 1926,
        "ordered_items": 180,
        "sell_earnings": 693,
        "commissions": 693,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8583,
        "bonus": 2
    }
];