export let mar = [
    {
        "month": "Mar",
        "day": "01",
        "clicks": 1497,
        "ordered_items": 112,
        "sell_earnings": 479,
        "commissions": 479,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6257,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "02",
        "clicks": 1257,
        "ordered_items": 133,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5360,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "03",
        "clicks": 1568,
        "ordered_items": 101,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6200,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "04",
        "clicks": 1664,
        "ordered_items": 173,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8206,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "05",
        "clicks": 1975,
        "ordered_items": 141,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9046,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "06",
        "clicks": 1735,
        "ordered_items": 162,
        "sell_earnings": 737,
        "commissions": 737,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8149,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "07",
        "clicks": 1365,
        "ordered_items": 106,
        "sell_earnings": 577,
        "commissions": 577,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5194,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "08",
        "clicks": 1230,
        "ordered_items": 122,
        "sell_earnings": 526,
        "commissions": 526,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5327,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "09",
        "clicks": 1285,
        "ordered_items": 97,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6165,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "10",
        "clicks": 1947,
        "ordered_items": 177,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8241,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "11",
        "clicks": 2002,
        "ordered_items": 152,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9079,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "12",
        "clicks": 1867,
        "ordered_items": 168,
        "sell_earnings": 639,
        "commissions": 639,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9212,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "13",
        "clicks": 1137,
        "ordered_items": 132,
        "sell_earnings": 533,
        "commissions": 533,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5857,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "14",
        "clicks": 2095,
        "ordered_items": 142,
        "sell_earnings": 683,
        "commissions": 683,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8549,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "15",
        "clicks": 1454,
        "ordered_items": 101,
        "sell_earnings": 459,
        "commissions": 459,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6636,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "16",
        "clicks": 1778,
        "ordered_items": 173,
        "sell_earnings": 757,
        "commissions": 757,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7770,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "17",
        "clicks": 1351,
        "ordered_items": 124,
        "sell_earnings": 479,
        "commissions": 479,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5929,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "18",
        "clicks": 1360,
        "ordered_items": 108,
        "sell_earnings": 537,
        "commissions": 537,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5154,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "19",
        "clicks": 1435,
        "ordered_items": 117,
        "sell_earnings": 601,
        "commissions": 601,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5731,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "20",
        "clicks": 1473,
        "ordered_items": 102,
        "sell_earnings": 438,
        "commissions": 438,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6369,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "21",
        "clicks": 1759,
        "ordered_items": 172,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8037,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "22",
        "clicks": 1797,
        "ordered_items": 157,
        "sell_earnings": 615,
        "commissions": 615,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8675,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "23",
        "clicks": 1872,
        "ordered_items": 166,
        "sell_earnings": 679,
        "commissions": 679,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9252,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "24",
        "clicks": 1881,
        "ordered_items": 150,
        "sell_earnings": 737,
        "commissions": 737,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8477,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "25",
        "clicks": 1515,
        "ordered_items": 102,
        "sell_earnings": 597,
        "commissions": 597,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6781,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "26",
        "clicks": 1387,
        "ordered_items": 104,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5781,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "27",
        "clicks": 1845,
        "ordered_items": 170,
        "sell_earnings": 753,
        "commissions": 753,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8625,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "28",
        "clicks": 1717,
        "ordered_items": 172,
        "sell_earnings": 619,
        "commissions": 619,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7625,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "29",
        "clicks": 1399,
        "ordered_items": 114,
        "sell_earnings": 455,
        "commissions": 455,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7169,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "30",
        "clicks": 1833,
        "ordered_items": 160,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7237,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];