export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1442,
        "ordered_items": 130,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6779,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1605,
        "ordered_items": 107,
        "sell_earnings": 459,
        "commissions": 459,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5551,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1575,
        "ordered_items": 119,
        "sell_earnings": 581,
        "commissions": 581,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6693,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 1657,
        "ordered_items": 155,
        "sell_earnings": 635,
        "commissions": 635,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7713,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 1627,
        "ordered_items": 167,
        "sell_earnings": 757,
        "commissions": 757,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8855,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 1790,
        "ordered_items": 144,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7627,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1391,
        "ordered_items": 136,
        "sell_earnings": 472,
        "commissions": 472,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6753,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1224,
        "ordered_items": 112,
        "sell_earnings": 536,
        "commissions": 536,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5504,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1211,
        "ordered_items": 122,
        "sell_earnings": 466,
        "commissions": 466,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7058,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 2021,
        "ordered_items": 152,
        "sell_earnings": 750,
        "commissions": 750,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7348,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 2008,
        "ordered_items": 162,
        "sell_earnings": 680,
        "commissions": 680,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8902,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1841,
        "ordered_items": 138,
        "sell_earnings": 744,
        "commissions": 744,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7653,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1571,
        "ordered_items": 108,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6868,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 1661,
        "ordered_items": 166,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7538,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1342,
        "ordered_items": 134,
        "sell_earnings": 591,
        "commissions": 591,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6710,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 1890,
        "ordered_items": 140,
        "sell_earnings": 625,
        "commissions": 625,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7696,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1435,
        "ordered_items": 125,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5589,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1392,
        "ordered_items": 105,
        "sell_earnings": 451,
        "commissions": 451,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5600,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1245,
        "ordered_items": 109,
        "sell_earnings": 573,
        "commissions": 573,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5634,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1497,
        "ordered_items": 109,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6742,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 1735,
        "ordered_items": 165,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7664,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 1987,
        "ordered_items": 165,
        "sell_earnings": 643,
        "commissions": 643,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8772,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 1840,
        "ordered_items": 169,
        "sell_earnings": 765,
        "commissions": 765,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8806,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1797,
        "ordered_items": 149,
        "sell_earnings": 676,
        "commissions": 676,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8817,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1374,
        "ordered_items": 107,
        "sell_earnings": 439,
        "commissions": 439,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6990,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1296,
        "ordered_items": 101,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5390,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 1936,
        "ordered_items": 173,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9016,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 1858,
        "ordered_items": 167,
        "sell_earnings": 777,
        "commissions": 777,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7416,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1303,
        "ordered_items": 126,
        "sell_earnings": 551,
        "commissions": 551,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6167,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 1929,
        "ordered_items": 148,
        "sell_earnings": 665,
        "commissions": 665,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8239,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];