export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1434,
        "ordered_items": 125,
        "sell_earnings": 620,
        "commissions": 620,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6677,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1367,
        "ordered_items": 123,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7116,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1430,
        "ordered_items": 142,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7360,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 1910,
        "ordered_items": 142,
        "sell_earnings": 650,
        "commissions": 650,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7526,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 1973,
        "ordered_items": 161,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7770,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 1906,
        "ordered_items": 159,
        "sell_earnings": 636,
        "commissions": 636,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8209,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1373,
        "ordered_items": 128,
        "sell_earnings": 492,
        "commissions": 492,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5294,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1308,
        "ordered_items": 131,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7371,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1291,
        "ordered_items": 100,
        "sell_earnings": 531,
        "commissions": 531,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5838,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 2049,
        "ordered_items": 184,
        "sell_earnings": 725,
        "commissions": 725,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9048,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 2032,
        "ordered_items": 153,
        "sell_earnings": 652,
        "commissions": 652,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7515,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 1967,
        "ordered_items": 156,
        "sell_earnings": 764,
        "commissions": 764,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9592,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1180,
        "ordered_items": 114,
        "sell_earnings": 610,
        "commissions": 610,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6141,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 2160,
        "ordered_items": 170,
        "sell_earnings": 646,
        "commissions": 646,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8745,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1197,
        "ordered_items": 119,
        "sell_earnings": 510,
        "commissions": 510,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6831,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 2143,
        "ordered_items": 165,
        "sell_earnings": 746,
        "commissions": 746,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8055,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1305,
        "ordered_items": 101,
        "sell_earnings": 571,
        "commissions": 571,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6307,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1443,
        "ordered_items": 119,
        "sell_earnings": 526,
        "commissions": 526,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6198,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1344,
        "ordered_items": 141,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5434,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1597,
        "ordered_items": 128,
        "sell_earnings": 449,
        "commissions": 449,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6577,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 1743,
        "ordered_items": 156,
        "sell_earnings": 807,
        "commissions": 807,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8309,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 1996,
        "ordered_items": 143,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9452,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 1897,
        "ordered_items": 165,
        "sell_earnings": 730,
        "commissions": 730,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8688,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 2035,
        "ordered_items": 183,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 166,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8579,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1305,
        "ordered_items": 103,
        "sell_earnings": 530,
        "commissions": 530,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6819,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1659,
        "ordered_items": 125,
        "sell_earnings": 475,
        "commissions": 475,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5734,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 1681,
        "ordered_items": 159,
        "sell_earnings": 781,
        "commissions": 781,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9152,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 2035,
        "ordered_items": 181,
        "sell_earnings": 726,
        "commissions": 726,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8067,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1557,
        "ordered_items": 112,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5250,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 1783,
        "ordered_items": 172,
        "sell_earnings": 644,
        "commissions": 644,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9636,
        "bonus": 0
    }
];