export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1507,
        "ordered_items": 121,
        "sell_earnings": 536,
        "commissions": 536,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5377,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1196,
        "ordered_items": 115,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6389,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1198,
        "ordered_items": 104,
        "sell_earnings": 511,
        "commissions": 511,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5226,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 2034,
        "ordered_items": 170,
        "sell_earnings": 705,
        "commissions": 705,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9180,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 2036,
        "ordered_items": 159,
        "sell_earnings": 610,
        "commissions": 610,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8017,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 1725,
        "ordered_items": 153,
        "sell_earnings": 680,
        "commissions": 680,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9029,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1569,
        "ordered_items": 135,
        "sell_earnings": 442,
        "commissions": 442,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5054,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1517,
        "ordered_items": 130,
        "sell_earnings": 434,
        "commissions": 434,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5243,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1537,
        "ordered_items": 117,
        "sell_earnings": 542,
        "commissions": 542,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5236,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1695,
        "ordered_items": 157,
        "sell_earnings": 674,
        "commissions": 674,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9170,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 1715,
        "ordered_items": 144,
        "sell_earnings": 782,
        "commissions": 782,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9163,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1663,
        "ordered_items": 139,
        "sell_earnings": 774,
        "commissions": 774,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9352,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1212,
        "ordered_items": 102,
        "sell_earnings": 468,
        "commissions": 468,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5303,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 2020,
        "ordered_items": 172,
        "sell_earnings": 748,
        "commissions": 748,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9103,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1269,
        "ordered_items": 106,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6389,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1963,
        "ordered_items": 168,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8017,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1313,
        "ordered_items": 123,
        "sell_earnings": 457,
        "commissions": 457,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6019,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1377,
        "ordered_items": 118,
        "sell_earnings": 466,
        "commissions": 466,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6559,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1268,
        "ordered_items": 97,
        "sell_earnings": 571,
        "commissions": 571,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5653,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1526,
        "ordered_items": 102,
        "sell_earnings": 574,
        "commissions": 574,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6768,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 1706,
        "ordered_items": 172,
        "sell_earnings": 642,
        "commissions": 642,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7638,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1964,
        "ordered_items": 177,
        "sell_earnings": 645,
        "commissions": 645,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8753,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 1855,
        "ordered_items": 156,
        "sell_earnings": 750,
        "commissions": 750,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7847,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1919,
        "ordered_items": 151,
        "sell_earnings": 759,
        "commissions": 759,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8387,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1506,
        "ordered_items": 101,
        "sell_earnings": 523,
        "commissions": 523,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7132,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1260,
        "ordered_items": 100,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6391,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1972,
        "ordered_items": 174,
        "sell_earnings": 720,
        "commissions": 720,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8015,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1726,
        "ordered_items": 173,
        "sell_earnings": 693,
        "commissions": 693,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7274,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1561,
        "ordered_items": 104,
        "sell_earnings": 602,
        "commissions": 602,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6117,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1671,
        "ordered_items": 170,
        "sell_earnings": 614,
        "commissions": 614,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8289,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];