export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1242,
        "ordered_items": 109,
        "sell_earnings": 549,
        "commissions": 549,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5297,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1154,
        "ordered_items": 106,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6972,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1218,
        "ordered_items": 100,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6982,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 2014,
        "ordered_items": 174,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7424,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 2078,
        "ordered_items": 168,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7434,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 1990,
        "ordered_items": 165,
        "sell_earnings": 667,
        "commissions": 667,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9109,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1577,
        "ordered_items": 107,
        "sell_earnings": 493,
        "commissions": 493,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5119,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1457,
        "ordered_items": 98,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5887,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1419,
        "ordered_items": 124,
        "sell_earnings": 535,
        "commissions": 535,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5446,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 1813,
        "ordered_items": 150,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8960,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 1775,
        "ordered_items": 176,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8519,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 1655,
        "ordered_items": 167,
        "sell_earnings": 723,
        "commissions": 723,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9287,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1588,
        "ordered_items": 110,
        "sell_earnings": 578,
        "commissions": 578,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5265,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 1644,
        "ordered_items": 164,
        "sell_earnings": 638,
        "commissions": 638,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9141,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1319,
        "ordered_items": 117,
        "sell_earnings": 605,
        "commissions": 605,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7110,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 1913,
        "ordered_items": 157,
        "sell_earnings": 611,
        "commissions": 611,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7296,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1202,
        "ordered_items": 120,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6069,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1191,
        "ordered_items": 133,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5489,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1167,
        "ordered_items": 102,
        "sell_earnings": 444,
        "commissions": 444,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6048,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1388,
        "ordered_items": 106,
        "sell_earnings": 516,
        "commissions": 516,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5388,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 1844,
        "ordered_items": 168,
        "sell_earnings": 700,
        "commissions": 700,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9018,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 2065,
        "ordered_items": 172,
        "sell_earnings": 772,
        "commissions": 772,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8358,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 2041,
        "ordered_items": 141,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8917,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 2030,
        "ordered_items": 154,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8337,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1562,
        "ordered_items": 102,
        "sell_earnings": 594,
        "commissions": 594,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6090,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1253,
        "ordered_items": 135,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6276,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 1979,
        "ordered_items": 139,
        "sell_earnings": 753,
        "commissions": 753,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8130,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 1670,
        "ordered_items": 172,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8316,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1565,
        "ordered_items": 127,
        "sell_earnings": 560,
        "commissions": 560,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6681,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 1667,
        "ordered_items": 147,
        "sell_earnings": 656,
        "commissions": 656,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7725,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];