export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1419,
        "ordered_items": 135,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7084,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1319,
        "ordered_items": 135,
        "sell_earnings": 570,
        "commissions": 570,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6520,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1239,
        "ordered_items": 124,
        "sell_earnings": 505,
        "commissions": 505,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6848,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 2101,
        "ordered_items": 160,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8038,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 2021,
        "ordered_items": 149,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8366,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 1921,
        "ordered_items": 149,
        "sell_earnings": 793,
        "commissions": 793,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7802,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1291,
        "ordered_items": 140,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6538,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1520,
        "ordered_items": 110,
        "sell_earnings": 501,
        "commissions": 501,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6412,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1307,
        "ordered_items": 111,
        "sell_earnings": 614,
        "commissions": 614,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6774,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 2033,
        "ordered_items": 173,
        "sell_earnings": 642,
        "commissions": 642,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8112,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 1820,
        "ordered_items": 174,
        "sell_earnings": 755,
        "commissions": 755,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8474,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 2049,
        "ordered_items": 144,
        "sell_earnings": 798,
        "commissions": 798,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8348,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1338,
        "ordered_items": 142,
        "sell_earnings": 607,
        "commissions": 607,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6186,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 2002,
        "ordered_items": 142,
        "sell_earnings": 649,
        "commissions": 649,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8700,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1455,
        "ordered_items": 127,
        "sell_earnings": 505,
        "commissions": 505,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6234,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 1885,
        "ordered_items": 157,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8652,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1325,
        "ordered_items": 118,
        "sell_earnings": 611,
        "commissions": 611,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6548,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1422,
        "ordered_items": 109,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6030,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1311,
        "ordered_items": 108,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6177,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1522,
        "ordered_items": 141,
        "sell_earnings": 574,
        "commissions": 574,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5894,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 1818,
        "ordered_items": 143,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8992,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 2029,
        "ordered_items": 176,
        "sell_earnings": 729,
        "commissions": 729,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8709,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 1918,
        "ordered_items": 175,
        "sell_earnings": 793,
        "commissions": 793,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8856,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 2015,
        "ordered_items": 166,
        "sell_earnings": 645,
        "commissions": 645,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8338,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1438,
        "ordered_items": 114,
        "sell_earnings": 511,
        "commissions": 511,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5603,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1563,
        "ordered_items": 110,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6350,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 1777,
        "ordered_items": 174,
        "sell_earnings": 800,
        "commissions": 800,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8536,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 1902,
        "ordered_items": 170,
        "sell_earnings": 745,
        "commissions": 745,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 167,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9283,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1571,
        "ordered_items": 112,
        "sell_earnings": 525,
        "commissions": 525,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7257,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 1769,
        "ordered_items": 172,
        "sell_earnings": 731,
        "commissions": 731,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7629,
        "bonus": 2
    }
];