export let mar = [
    {
        "month": "Mar",
        "day": "01",
        "clicks": 1554,
        "ordered_items": 134,
        "sell_earnings": 503,
        "commissions": 503,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5226,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "02",
        "clicks": 1447,
        "ordered_items": 106,
        "sell_earnings": 602,
        "commissions": 602,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5451,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "03",
        "clicks": 1244,
        "ordered_items": 112,
        "sell_earnings": 587,
        "commissions": 587,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6052,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "04",
        "clicks": 1988,
        "ordered_items": 162,
        "sell_earnings": 629,
        "commissions": 629,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8354,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "05",
        "clicks": 1785,
        "ordered_items": 168,
        "sell_earnings": 614,
        "commissions": 614,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8955,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "06",
        "clicks": 1678,
        "ordered_items": 140,
        "sell_earnings": 713,
        "commissions": 713,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9180,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "07",
        "clicks": 1326,
        "ordered_items": 121,
        "sell_earnings": 471,
        "commissions": 471,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6725,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "08",
        "clicks": 1514,
        "ordered_items": 112,
        "sell_earnings": 581,
        "commissions": 581,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6144,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "09",
        "clicks": 1257,
        "ordered_items": 97,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6383,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "10",
        "clicks": 1975,
        "ordered_items": 177,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8023,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "11",
        "clicks": 1718,
        "ordered_items": 162,
        "sell_earnings": 635,
        "commissions": 635,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8262,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "12",
        "clicks": 1906,
        "ordered_items": 153,
        "sell_earnings": 745,
        "commissions": 745,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7681,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "13",
        "clicks": 1281,
        "ordered_items": 108,
        "sell_earnings": 443,
        "commissions": 443,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7054,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "14",
        "clicks": 1951,
        "ordered_items": 166,
        "sell_earnings": 773,
        "commissions": 773,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7352,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "15",
        "clicks": 1612,
        "ordered_items": 135,
        "sell_earnings": 489,
        "commissions": 489,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7201,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "16",
        "clicks": 1620,
        "ordered_items": 139,
        "sell_earnings": 727,
        "commissions": 727,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7205,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "17",
        "clicks": 1513,
        "ordered_items": 111,
        "sell_earnings": 497,
        "commissions": 497,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6893,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "18",
        "clicks": 1348,
        "ordered_items": 100,
        "sell_earnings": 498,
        "commissions": 498,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6298,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "19",
        "clicks": 1435,
        "ordered_items": 111,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6412,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "20",
        "clicks": 1205,
        "ordered_items": 115,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7030,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "21",
        "clicks": 2027,
        "ordered_items": 159,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7376,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "22",
        "clicks": 1797,
        "ordered_items": 163,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7994,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "23",
        "clicks": 1884,
        "ordered_items": 174,
        "sell_earnings": 718,
        "commissions": 718,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8108,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "24",
        "clicks": 1719,
        "ordered_items": 163,
        "sell_earnings": 719,
        "commissions": 719,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7513,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "25",
        "clicks": 1604,
        "ordered_items": 100,
        "sell_earnings": 526,
        "commissions": 526,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6171,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "26",
        "clicks": 1177,
        "ordered_items": 112,
        "sell_earnings": 595,
        "commissions": 595,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6135,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "27",
        "clicks": 2055,
        "ordered_items": 162,
        "sell_earnings": 621,
        "commissions": 621,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8271,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "28",
        "clicks": 1628,
        "ordered_items": 174,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8235,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "29",
        "clicks": 1600,
        "ordered_items": 131,
        "sell_earnings": 431,
        "commissions": 431,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5716,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "30",
        "clicks": 1632,
        "ordered_items": 143,
        "sell_earnings": 785,
        "commissions": 785,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8690,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];