export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1362,
        "ordered_items": 135,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5614,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1609,
        "ordered_items": 104,
        "sell_earnings": 577,
        "commissions": 577,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5928,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1332,
        "ordered_items": 136,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7023,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 1900,
        "ordered_items": 138,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7383,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 1623,
        "ordered_items": 170,
        "sell_earnings": 639,
        "commissions": 639,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8478,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 1870,
        "ordered_items": 139,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8792,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1411,
        "ordered_items": 126,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6189,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1545,
        "ordered_items": 111,
        "sell_earnings": 466,
        "commissions": 466,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6190,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1354,
        "ordered_items": 137,
        "sell_earnings": 486,
        "commissions": 486,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6655,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 1878,
        "ordered_items": 137,
        "sell_earnings": 730,
        "commissions": 730,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7751,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 1687,
        "ordered_items": 163,
        "sell_earnings": 750,
        "commissions": 750,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8216,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1821,
        "ordered_items": 148,
        "sell_earnings": 676,
        "commissions": 676,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8217,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1444,
        "ordered_items": 125,
        "sell_earnings": 601,
        "commissions": 601,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6835,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 1788,
        "ordered_items": 149,
        "sell_earnings": 615,
        "commissions": 615,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7571,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1479,
        "ordered_items": 100,
        "sell_earnings": 576,
        "commissions": 576,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5281,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 1753,
        "ordered_items": 174,
        "sell_earnings": 640,
        "commissions": 640,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9125,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1345,
        "ordered_items": 128,
        "sell_earnings": 554,
        "commissions": 554,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5873,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1600,
        "ordered_items": 127,
        "sell_earnings": 531,
        "commissions": 531,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6498,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1603,
        "ordered_items": 129,
        "sell_earnings": 560,
        "commissions": 560,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5200,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1577,
        "ordered_items": 128,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5715,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 1655,
        "ordered_items": 146,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8691,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 1629,
        "ordered_items": 145,
        "sell_earnings": 656,
        "commissions": 656,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9206,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 1632,
        "ordered_items": 147,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7908,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1887,
        "ordered_items": 146,
        "sell_earnings": 662,
        "commissions": 662,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8533,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1404,
        "ordered_items": 123,
        "sell_earnings": 507,
        "commissions": 507,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7040,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1380,
        "ordered_items": 102,
        "sell_earnings": 579,
        "commissions": 579,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7032,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 1852,
        "ordered_items": 172,
        "sell_earnings": 637,
        "commissions": 637,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7374,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 1828,
        "ordered_items": 151,
        "sell_earnings": 709,
        "commissions": 709,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7366,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1249,
        "ordered_items": 118,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6520,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 1983,
        "ordered_items": 156,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7886,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];