export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1321,
        "ordered_items": 127,
        "sell_earnings": 567,
        "commissions": 567,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5991,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1213,
        "ordered_items": 139,
        "sell_earnings": 492,
        "commissions": 492,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7132,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1489,
        "ordered_items": 130,
        "sell_earnings": 553,
        "commissions": 553,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5680,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 1851,
        "ordered_items": 154,
        "sell_earnings": 703,
        "commissions": 703,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9206,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 2127,
        "ordered_items": 145,
        "sell_earnings": 764,
        "commissions": 764,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7754,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 2019,
        "ordered_items": 157,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8895,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1237,
        "ordered_items": 140,
        "sell_earnings": 576,
        "commissions": 576,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5801,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1238,
        "ordered_items": 110,
        "sell_earnings": 558,
        "commissions": 558,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6897,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1245,
        "ordered_items": 136,
        "sell_earnings": 488,
        "commissions": 488,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6162,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 2095,
        "ordered_items": 148,
        "sell_earnings": 768,
        "commissions": 768,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8724,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 2102,
        "ordered_items": 174,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7989,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 2103,
        "ordered_items": 144,
        "sell_earnings": 680,
        "commissions": 680,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9085,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1346,
        "ordered_items": 128,
        "sell_earnings": 599,
        "commissions": 599,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6017,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 1994,
        "ordered_items": 156,
        "sell_earnings": 657,
        "commissions": 657,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8869,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1528,
        "ordered_items": 120,
        "sell_earnings": 603,
        "commissions": 603,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5644,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 1812,
        "ordered_items": 164,
        "sell_earnings": 653,
        "commissions": 653,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9242,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1426,
        "ordered_items": 142,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6481,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1327,
        "ordered_items": 135,
        "sell_earnings": 467,
        "commissions": 467,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7001,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1249,
        "ordered_items": 140,
        "sell_earnings": 559,
        "commissions": 559,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6203,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1472,
        "ordered_items": 110,
        "sell_earnings": 575,
        "commissions": 575,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6364,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 1868,
        "ordered_items": 174,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 168,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8522,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 2091,
        "ordered_items": 144,
        "sell_earnings": 697,
        "commissions": 697,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8683,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 2013,
        "ordered_items": 149,
        "sell_earnings": 789,
        "commissions": 789,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7885,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 1914,
        "ordered_items": 142,
        "sell_earnings": 644,
        "commissions": 644,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8405,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1337,
        "ordered_items": 112,
        "sell_earnings": 529,
        "commissions": 529,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6064,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1226,
        "ordered_items": 110,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7267,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 2114,
        "ordered_items": 174,
        "sell_earnings": 634,
        "commissions": 634,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7619,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 2003,
        "ordered_items": 172,
        "sell_earnings": 727,
        "commissions": 727,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8822,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1553,
        "ordered_items": 131,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5501,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 1787,
        "ordered_items": 153,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9385,
        "bonus": 0
    }
];