export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1603,
        "ordered_items": 100,
        "sell_earnings": 452,
        "commissions": 452,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6776,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1246,
        "ordered_items": 116,
        "sell_earnings": 492,
        "commissions": 492,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6327,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1216,
        "ordered_items": 136,
        "sell_earnings": 508,
        "commissions": 508,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6928,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 2016,
        "ordered_items": 138,
        "sell_earnings": 708,
        "commissions": 708,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7478,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1986,
        "ordered_items": 158,
        "sell_earnings": 724,
        "commissions": 724,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8079,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 1629,
        "ordered_items": 174,
        "sell_earnings": 764,
        "commissions": 764,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7630,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1458,
        "ordered_items": 116,
        "sell_earnings": 569,
        "commissions": 569,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6280,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1164,
        "ordered_items": 97,
        "sell_earnings": 493,
        "commissions": 493,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6272,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1557,
        "ordered_items": 107,
        "sell_earnings": 431,
        "commissions": 431,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6925,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1675,
        "ordered_items": 167,
        "sell_earnings": 785,
        "commissions": 785,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7481,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 2068,
        "ordered_items": 177,
        "sell_earnings": 723,
        "commissions": 723,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8134,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1774,
        "ordered_items": 158,
        "sell_earnings": 647,
        "commissions": 647,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8126,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1199,
        "ordered_items": 121,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5622,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 2033,
        "ordered_items": 153,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8784,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1447,
        "ordered_items": 107,
        "sell_earnings": 485,
        "commissions": 485,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6249,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1785,
        "ordered_items": 167,
        "sell_earnings": 731,
        "commissions": 731,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8157,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1490,
        "ordered_items": 123,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6803,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1519,
        "ordered_items": 102,
        "sell_earnings": 552,
        "commissions": 552,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6773,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1312,
        "ordered_items": 119,
        "sell_earnings": 518,
        "commissions": 518,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5492,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1166,
        "ordered_items": 105,
        "sell_earnings": 594,
        "commissions": 594,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6982,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 2066,
        "ordered_items": 169,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7424,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1920,
        "ordered_items": 155,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8914,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 1713,
        "ordered_items": 172,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7633,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1742,
        "ordered_items": 151,
        "sell_earnings": 651,
        "commissions": 651,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7603,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1395,
        "ordered_items": 117,
        "sell_earnings": 580,
        "commissions": 580,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5831,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1309,
        "ordered_items": 132,
        "sell_earnings": 589,
        "commissions": 589,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7158,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1923,
        "ordered_items": 142,
        "sell_earnings": 627,
        "commissions": 627,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7248,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1837,
        "ordered_items": 157,
        "sell_earnings": 636,
        "commissions": 636,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8575,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1238,
        "ordered_items": 100,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6246,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1994,
        "ordered_items": 174,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8160,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];