export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1164,
        "ordered_items": 107,
        "sell_earnings": 558,
        "commissions": 558,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6641,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1616,
        "ordered_items": 121,
        "sell_earnings": 588,
        "commissions": 588,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5678,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1369,
        "ordered_items": 134,
        "sell_earnings": 481,
        "commissions": 481,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5387,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 1863,
        "ordered_items": 140,
        "sell_earnings": 735,
        "commissions": 735,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9019,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 1616,
        "ordered_items": 153,
        "sell_earnings": 628,
        "commissions": 628,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8728,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 2068,
        "ordered_items": 167,
        "sell_earnings": 658,
        "commissions": 658,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7765,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1499,
        "ordered_items": 132,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6117,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1554,
        "ordered_items": 134,
        "sell_earnings": 538,
        "commissions": 538,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5901,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1546,
        "ordered_items": 103,
        "sell_earnings": 605,
        "commissions": 605,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6032,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 1686,
        "ordered_items": 171,
        "sell_earnings": 611,
        "commissions": 611,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8374,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1678,
        "ordered_items": 140,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8505,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 1733,
        "ordered_items": 142,
        "sell_earnings": 752,
        "commissions": 752,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8289,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1592,
        "ordered_items": 118,
        "sell_earnings": 530,
        "commissions": 530,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6936,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 1640,
        "ordered_items": 156,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7470,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1551,
        "ordered_items": 119,
        "sell_earnings": 588,
        "commissions": 588,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6410,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 1681,
        "ordered_items": 155,
        "sell_earnings": 628,
        "commissions": 628,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7996,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1544,
        "ordered_items": 113,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6710,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1597,
        "ordered_items": 119,
        "sell_earnings": 438,
        "commissions": 438,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6683,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1585,
        "ordered_items": 105,
        "sell_earnings": 538,
        "commissions": 538,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5357,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1450,
        "ordered_items": 97,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5946,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 1782,
        "ordered_items": 177,
        "sell_earnings": 610,
        "commissions": 610,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8460,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 1647,
        "ordered_items": 169,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9049,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 1635,
        "ordered_items": 155,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7723,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 1688,
        "ordered_items": 161,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7696,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1353,
        "ordered_items": 109,
        "sell_earnings": 460,
        "commissions": 460,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6011,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1140,
        "ordered_items": 114,
        "sell_earnings": 451,
        "commissions": 451,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5942,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 2092,
        "ordered_items": 160,
        "sell_earnings": 765,
        "commissions": 765,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8464,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 1879,
        "ordered_items": 165,
        "sell_earnings": 756,
        "commissions": 756,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8395,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1423,
        "ordered_items": 101,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6105,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 1809,
        "ordered_items": 173,
        "sell_earnings": 721,
        "commissions": 721,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8301,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];