export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1144,
        "ordered_items": 120,
        "sell_earnings": 576,
        "commissions": 576,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6470,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1140,
        "ordered_items": 118,
        "sell_earnings": 454,
        "commissions": 454,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6462,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1351,
        "ordered_items": 98,
        "sell_earnings": 485,
        "commissions": 485,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7058,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 1881,
        "ordered_items": 176,
        "sell_earnings": 731,
        "commissions": 731,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7348,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 2092,
        "ordered_items": 156,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7944,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 2088,
        "ordered_items": 154,
        "sell_earnings": 640,
        "commissions": 640,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7936,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1478,
        "ordered_items": 115,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5885,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1149,
        "ordered_items": 99,
        "sell_earnings": 485,
        "commissions": 485,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5753,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1402,
        "ordered_items": 133,
        "sell_earnings": 438,
        "commissions": 438,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5783,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 1830,
        "ordered_items": 141,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8623,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 2083,
        "ordered_items": 175,
        "sell_earnings": 731,
        "commissions": 731,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8653,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 1754,
        "ordered_items": 159,
        "sell_earnings": 753,
        "commissions": 753,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8521,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1142,
        "ordered_items": 104,
        "sell_earnings": 432,
        "commissions": 432,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6932,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 2090,
        "ordered_items": 170,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7474,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1506,
        "ordered_items": 101,
        "sell_earnings": 599,
        "commissions": 599,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6004,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 1726,
        "ordered_items": 173,
        "sell_earnings": 617,
        "commissions": 617,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8402,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1600,
        "ordered_items": 109,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6405,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1506,
        "ordered_items": 104,
        "sell_earnings": 583,
        "commissions": 583,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6842,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1526,
        "ordered_items": 120,
        "sell_earnings": 437,
        "commissions": 437,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6675,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1445,
        "ordered_items": 102,
        "sell_earnings": 547,
        "commissions": 547,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5048,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 1787,
        "ordered_items": 172,
        "sell_earnings": 669,
        "commissions": 669,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9358,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1706,
        "ordered_items": 154,
        "sell_earnings": 779,
        "commissions": 779,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7731,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 1726,
        "ordered_items": 170,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7564,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 1632,
        "ordered_items": 165,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8001,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1570,
        "ordered_items": 129,
        "sell_earnings": 479,
        "commissions": 479,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6364,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1335,
        "ordered_items": 98,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6258,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 1897,
        "ordered_items": 176,
        "sell_earnings": 725,
        "commissions": 725,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8148,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1662,
        "ordered_items": 145,
        "sell_earnings": 737,
        "commissions": 737,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8042,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1490,
        "ordered_items": 122,
        "sell_earnings": 433,
        "commissions": 433,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6632,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 1742,
        "ordered_items": 152,
        "sell_earnings": 783,
        "commissions": 783,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7774,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];