export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1435,
        "ordered_items": 108,
        "sell_earnings": 599,
        "commissions": 599,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5276,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1477,
        "ordered_items": 121,
        "sell_earnings": 516,
        "commissions": 516,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6751,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1285,
        "ordered_items": 134,
        "sell_earnings": 486,
        "commissions": 486,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5847,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 2055,
        "ordered_items": 150,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9039,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 1863,
        "ordered_items": 163,
        "sell_earnings": 740,
        "commissions": 740,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8135,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 1905,
        "ordered_items": 176,
        "sell_earnings": 657,
        "commissions": 657,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9610,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1210,
        "ordered_items": 119,
        "sell_earnings": 547,
        "commissions": 547,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6575,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1244,
        "ordered_items": 123,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 128,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5879,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1189,
        "ordered_items": 101,
        "sell_earnings": 505,
        "commissions": 505,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6540,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 2151,
        "ordered_items": 183,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8346,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 2096,
        "ordered_items": 161,
        "sell_earnings": 806,
        "commissions": 806,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9007,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 2130,
        "ordered_items": 165,
        "sell_earnings": 709,
        "commissions": 709,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8311,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1207,
        "ordered_items": 138,
        "sell_earnings": 539,
        "commissions": 539,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7327,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 2133,
        "ordered_items": 146,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7559,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1299,
        "ordered_items": 104,
        "sell_earnings": 525,
        "commissions": 525,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5428,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 2041,
        "ordered_items": 180,
        "sell_earnings": 731,
        "commissions": 731,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9458,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1596,
        "ordered_items": 119,
        "sell_earnings": 589,
        "commissions": 589,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5883,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1277,
        "ordered_items": 113,
        "sell_earnings": 462,
        "commissions": 462,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6349,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1667,
        "ordered_items": 112,
        "sell_earnings": 490,
        "commissions": 490,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5291,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1463,
        "ordered_items": 103,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6866,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 1877,
        "ordered_items": 181,
        "sell_earnings": 644,
        "commissions": 644,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8020,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 1673,
        "ordered_items": 172,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9595,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 2063,
        "ordered_items": 171,
        "sell_earnings": 794,
        "commissions": 794,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8537,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 1744,
        "ordered_items": 165,
        "sell_earnings": 667,
        "commissions": 667,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9003,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1302,
        "ordered_items": 123,
        "sell_earnings": 562,
        "commissions": 562,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6048,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1316,
        "ordered_items": 112,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6330,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 2024,
        "ordered_items": 172,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8556,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 2038,
        "ordered_items": 161,
        "sell_earnings": 694,
        "commissions": 694,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8838,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1355,
        "ordered_items": 121,
        "sell_earnings": 573,
        "commissions": 573,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6336,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 1985,
        "ordered_items": 163,
        "sell_earnings": 683,
        "commissions": 683,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8550,
        "bonus": 1
    }
];