export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1285,
        "ordered_items": 109,
        "sell_earnings": 476,
        "commissions": 476,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6479,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1590,
        "ordered_items": 115,
        "sell_earnings": 460,
        "commissions": 460,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5342,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1561,
        "ordered_items": 97,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5722,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 1671,
        "ordered_items": 177,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8684,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 1642,
        "ordered_items": 159,
        "sell_earnings": 756,
        "commissions": 756,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9064,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 1947,
        "ordered_items": 165,
        "sell_earnings": 740,
        "commissions": 740,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7927,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1316,
        "ordered_items": 102,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5349,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1378,
        "ordered_items": 132,
        "sell_earnings": 547,
        "commissions": 547,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6274,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1200,
        "ordered_items": 113,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5052,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 2032,
        "ordered_items": 161,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9354,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 1854,
        "ordered_items": 142,
        "sell_earnings": 669,
        "commissions": 669,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8132,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1916,
        "ordered_items": 172,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9057,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1383,
        "ordered_items": 112,
        "sell_earnings": 600,
        "commissions": 600,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6405,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 1849,
        "ordered_items": 162,
        "sell_earnings": 616,
        "commissions": 616,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8001,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1364,
        "ordered_items": 109,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5588,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 1868,
        "ordered_items": 165,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8818,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1377,
        "ordered_items": 118,
        "sell_earnings": 602,
        "commissions": 602,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6865,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1147,
        "ordered_items": 119,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6870,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1531,
        "ordered_items": 132,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6319,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1469,
        "ordered_items": 103,
        "sell_earnings": 554,
        "commissions": 554,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6027,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 1763,
        "ordered_items": 171,
        "sell_earnings": 662,
        "commissions": 662,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8379,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 1701,
        "ordered_items": 142,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8087,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 2085,
        "ordered_items": 155,
        "sell_earnings": 725,
        "commissions": 725,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7536,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1855,
        "ordered_items": 156,
        "sell_earnings": 614,
        "commissions": 614,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7541,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1221,
        "ordered_items": 130,
        "sell_earnings": 459,
        "commissions": 459,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7113,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1282,
        "ordered_items": 118,
        "sell_earnings": 429,
        "commissions": 429,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5411,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 1950,
        "ordered_items": 156,
        "sell_earnings": 787,
        "commissions": 787,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8995,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 2011,
        "ordered_items": 144,
        "sell_earnings": 757,
        "commissions": 757,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7293,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1303,
        "ordered_items": 136,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5353,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 1929,
        "ordered_items": 138,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9053,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];