export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 1506,
        "ordered_items": 112,
        "sell_earnings": 459,
        "commissions": 459,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5445,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 1525,
        "ordered_items": 106,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5689,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 1425,
        "ordered_items": 119,
        "sell_earnings": 539,
        "commissions": 539,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6007,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 1915,
        "ordered_items": 165,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8879,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 1815,
        "ordered_items": 178,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9197,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 1834,
        "ordered_items": 172,
        "sell_earnings": 797,
        "commissions": 797,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 165,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9441,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 1552,
        "ordered_items": 125,
        "sell_earnings": 493,
        "commissions": 493,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6900,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 1365,
        "ordered_items": 141,
        "sell_earnings": 566,
        "commissions": 566,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6853,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 1177,
        "ordered_items": 139,
        "sell_earnings": 505,
        "commissions": 505,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5717,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 2163,
        "ordered_items": 145,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9169,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 1975,
        "ordered_items": 143,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8033,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 1788,
        "ordered_items": 159,
        "sell_earnings": 763,
        "commissions": 763,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7986,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 1670,
        "ordered_items": 112,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5487,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 1670,
        "ordered_items": 172,
        "sell_earnings": 792,
        "commissions": 792,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9399,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 1339,
        "ordered_items": 136,
        "sell_earnings": 461,
        "commissions": 461,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7212,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 2001,
        "ordered_items": 148,
        "sell_earnings": 795,
        "commissions": 795,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7674,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 1181,
        "ordered_items": 115,
        "sell_earnings": 563,
        "commissions": 563,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6074,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 1585,
        "ordered_items": 138,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7082,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 1654,
        "ordered_items": 139,
        "sell_earnings": 448,
        "commissions": 448,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5271,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 1300,
        "ordered_items": 110,
        "sell_earnings": 475,
        "commissions": 475,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5214,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 2040,
        "ordered_items": 174,
        "sell_earnings": 781,
        "commissions": 781,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 169,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9672,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 1686,
        "ordered_items": 145,
        "sell_earnings": 808,
        "commissions": 808,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 167,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9615,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 1755,
        "ordered_items": 146,
        "sell_earnings": 798,
        "commissions": 798,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7804,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 2159,
        "ordered_items": 169,
        "sell_earnings": 693,
        "commissions": 693,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8812,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 1189,
        "ordered_items": 108,
        "sell_earnings": 466,
        "commissions": 466,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5694,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 1588,
        "ordered_items": 125,
        "sell_earnings": 609,
        "commissions": 609,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6215,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 1752,
        "ordered_items": 159,
        "sell_earnings": 647,
        "commissions": 647,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8671,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 2151,
        "ordered_items": 176,
        "sell_earnings": 790,
        "commissions": 790,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9192,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 1200,
        "ordered_items": 111,
        "sell_earnings": 611,
        "commissions": 611,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6415,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 2140,
        "ordered_items": 173,
        "sell_earnings": 645,
        "commissions": 645,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8471,
        "bonus": 0
    }
];