export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1380,
        "ordered_items": 119,
        "sell_earnings": 588,
        "commissions": 588,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5589,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1536,
        "ordered_items": 121,
        "sell_earnings": 436,
        "commissions": 436,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5598,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1367,
        "ordered_items": 104,
        "sell_earnings": 532,
        "commissions": 532,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5512,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 1865,
        "ordered_items": 170,
        "sell_earnings": 684,
        "commissions": 684,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8894,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 1696,
        "ordered_items": 153,
        "sell_earnings": 780,
        "commissions": 780,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8808,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 1852,
        "ordered_items": 155,
        "sell_earnings": 628,
        "commissions": 628,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8817,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1391,
        "ordered_items": 129,
        "sell_earnings": 454,
        "commissions": 454,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5898,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1497,
        "ordered_items": 115,
        "sell_earnings": 513,
        "commissions": 513,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5462,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1200,
        "ordered_items": 103,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6519,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 2032,
        "ordered_items": 171,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7887,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1735,
        "ordered_items": 159,
        "sell_earnings": 703,
        "commissions": 703,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8944,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 1841,
        "ordered_items": 145,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8508,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1437,
        "ordered_items": 100,
        "sell_earnings": 607,
        "commissions": 607,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6400,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 1795,
        "ordered_items": 174,
        "sell_earnings": 609,
        "commissions": 609,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8006,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1377,
        "ordered_items": 114,
        "sell_earnings": 587,
        "commissions": 587,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5479,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 1855,
        "ordered_items": 160,
        "sell_earnings": 629,
        "commissions": 629,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8927,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1552,
        "ordered_items": 129,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5099,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1612,
        "ordered_items": 131,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6886,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1180,
        "ordered_items": 101,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5452,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1440,
        "ordered_items": 129,
        "sell_earnings": 489,
        "commissions": 489,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6018,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 1792,
        "ordered_items": 145,
        "sell_earnings": 727,
        "commissions": 727,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8388,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 2052,
        "ordered_items": 173,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8954,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 1620,
        "ordered_items": 143,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7520,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 1680,
        "ordered_items": 145,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9307,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1375,
        "ordered_items": 99,
        "sell_earnings": 601,
        "commissions": 601,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6960,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1393,
        "ordered_items": 108,
        "sell_earnings": 502,
        "commissions": 502,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6764,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1839,
        "ordered_items": 166,
        "sell_earnings": 714,
        "commissions": 714,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7642,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 1857,
        "ordered_items": 175,
        "sell_earnings": 615,
        "commissions": 615,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7446,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1402,
        "ordered_items": 120,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6075,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 1830,
        "ordered_items": 154,
        "sell_earnings": 651,
        "commissions": 651,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8331,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];