export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1183,
        "ordered_items": 122,
        "sell_earnings": 543,
        "commissions": 543,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5557,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1499,
        "ordered_items": 124,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5105,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1349,
        "ordered_items": 116,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5089,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 1883,
        "ordered_items": 158,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9317,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 1733,
        "ordered_items": 150,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9301,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 2049,
        "ordered_items": 152,
        "sell_earnings": 673,
        "commissions": 673,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8849,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1509,
        "ordered_items": 119,
        "sell_earnings": 590,
        "commissions": 590,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6803,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1399,
        "ordered_items": 99,
        "sell_earnings": 607,
        "commissions": 607,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5658,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1281,
        "ordered_items": 119,
        "sell_earnings": 555,
        "commissions": 555,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6486,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 1951,
        "ordered_items": 155,
        "sell_earnings": 661,
        "commissions": 661,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7920,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 1833,
        "ordered_items": 175,
        "sell_earnings": 609,
        "commissions": 609,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8748,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 1723,
        "ordered_items": 155,
        "sell_earnings": 626,
        "commissions": 626,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7603,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1332,
        "ordered_items": 136,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5166,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 1900,
        "ordered_items": 138,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9240,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1162,
        "ordered_items": 114,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5768,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 2070,
        "ordered_items": 160,
        "sell_earnings": 725,
        "commissions": 725,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8638,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1245,
        "ordered_items": 129,
        "sell_earnings": 438,
        "commissions": 438,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5216,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1299,
        "ordered_items": 124,
        "sell_earnings": 526,
        "commissions": 526,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5862,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1219,
        "ordered_items": 134,
        "sell_earnings": 476,
        "commissions": 476,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5194,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1392,
        "ordered_items": 97,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7181,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 1840,
        "ordered_items": 177,
        "sell_earnings": 720,
        "commissions": 720,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7225,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 2013,
        "ordered_items": 140,
        "sell_earnings": 740,
        "commissions": 740,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9212,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 1933,
        "ordered_items": 150,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8544,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 1987,
        "ordered_items": 145,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9190,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1381,
        "ordered_items": 133,
        "sell_earnings": 441,
        "commissions": 441,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5970,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1135,
        "ordered_items": 101,
        "sell_earnings": 434,
        "commissions": 434,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6619,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 2097,
        "ordered_items": 173,
        "sell_earnings": 782,
        "commissions": 782,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7787,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1851,
        "ordered_items": 141,
        "sell_earnings": 775,
        "commissions": 775,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8436,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1533,
        "ordered_items": 104,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5544,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 1699,
        "ordered_items": 170,
        "sell_earnings": 725,
        "commissions": 725,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8862,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];