export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1594,
        "ordered_items": 129,
        "sell_earnings": 597,
        "commissions": 597,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7060,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1510,
        "ordered_items": 110,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5296,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1168,
        "ordered_items": 132,
        "sell_earnings": 557,
        "commissions": 557,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5709,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 2064,
        "ordered_items": 142,
        "sell_earnings": 659,
        "commissions": 659,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8697,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 1722,
        "ordered_items": 164,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9110,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 1638,
        "ordered_items": 145,
        "sell_earnings": 619,
        "commissions": 619,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7346,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1604,
        "ordered_items": 121,
        "sell_earnings": 430,
        "commissions": 430,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6139,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1283,
        "ordered_items": 105,
        "sell_earnings": 602,
        "commissions": 602,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6173,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1479,
        "ordered_items": 123,
        "sell_earnings": 473,
        "commissions": 473,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5249,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 1753,
        "ordered_items": 151,
        "sell_earnings": 743,
        "commissions": 743,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9157,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 1949,
        "ordered_items": 169,
        "sell_earnings": 614,
        "commissions": 614,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8233,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 1628,
        "ordered_items": 153,
        "sell_earnings": 786,
        "commissions": 786,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8267,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1584,
        "ordered_items": 108,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5436,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 1648,
        "ordered_items": 166,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8970,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1363,
        "ordered_items": 133,
        "sell_earnings": 545,
        "commissions": 545,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6183,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 1869,
        "ordered_items": 141,
        "sell_earnings": 671,
        "commissions": 671,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8223,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1243,
        "ordered_items": 129,
        "sell_earnings": 556,
        "commissions": 556,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5053,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1137,
        "ordered_items": 108,
        "sell_earnings": 487,
        "commissions": 487,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5120,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1442,
        "ordered_items": 111,
        "sell_earnings": 441,
        "commissions": 441,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6898,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1580,
        "ordered_items": 121,
        "sell_earnings": 538,
        "commissions": 538,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5481,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 1652,
        "ordered_items": 153,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8925,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 1790,
        "ordered_items": 163,
        "sell_earnings": 775,
        "commissions": 775,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7508,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 2095,
        "ordered_items": 166,
        "sell_earnings": 729,
        "commissions": 729,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9286,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 1989,
        "ordered_items": 145,
        "sell_earnings": 660,
        "commissions": 660,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9353,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1463,
        "ordered_items": 134,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7130,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1273,
        "ordered_items": 104,
        "sell_earnings": 533,
        "commissions": 533,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5788,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 1959,
        "ordered_items": 170,
        "sell_earnings": 683,
        "commissions": 683,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8618,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 1769,
        "ordered_items": 140,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7276,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1274,
        "ordered_items": 107,
        "sell_earnings": 490,
        "commissions": 490,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5087,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 1958,
        "ordered_items": 167,
        "sell_earnings": 726,
        "commissions": 726,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9319,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];