export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1276,
        "ordered_items": 119,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5323,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1626,
        "ordered_items": 112,
        "sell_earnings": 584,
        "commissions": 584,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7098,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1622,
        "ordered_items": 137,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7417,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 1718,
        "ordered_items": 147,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7469,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 1714,
        "ordered_items": 172,
        "sell_earnings": 672,
        "commissions": 672,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7788,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 2064,
        "ordered_items": 165,
        "sell_earnings": 779,
        "commissions": 779,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9563,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1427,
        "ordered_items": 106,
        "sell_earnings": 508,
        "commissions": 508,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6642,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1199,
        "ordered_items": 109,
        "sell_earnings": 536,
        "commissions": 536,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6459,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1177,
        "ordered_items": 117,
        "sell_earnings": 552,
        "commissions": 552,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7018,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 2163,
        "ordered_items": 167,
        "sell_earnings": 704,
        "commissions": 704,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7868,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 2141,
        "ordered_items": 175,
        "sell_earnings": 720,
        "commissions": 720,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8427,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 1913,
        "ordered_items": 178,
        "sell_earnings": 748,
        "commissions": 748,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 168,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8244,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1576,
        "ordered_items": 102,
        "sell_earnings": 521,
        "commissions": 521,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7019,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 1764,
        "ordered_items": 182,
        "sell_earnings": 735,
        "commissions": 735,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7867,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1365,
        "ordered_items": 116,
        "sell_earnings": 614,
        "commissions": 614,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6214,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 1975,
        "ordered_items": 168,
        "sell_earnings": 642,
        "commissions": 642,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8672,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1600,
        "ordered_items": 120,
        "sell_earnings": 523,
        "commissions": 523,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7066,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1604,
        "ordered_items": 117,
        "sell_earnings": 560,
        "commissions": 560,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6787,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1307,
        "ordered_items": 131,
        "sell_earnings": 489,
        "commissions": 489,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5402,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1226,
        "ordered_items": 138,
        "sell_earnings": 567,
        "commissions": 567,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5752,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 2114,
        "ordered_items": 146,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9134,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 2033,
        "ordered_items": 153,
        "sell_earnings": 767,
        "commissions": 767,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9484,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 1736,
        "ordered_items": 167,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8099,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 1740,
        "ordered_items": 164,
        "sell_earnings": 733,
        "commissions": 733,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7820,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1638,
        "ordered_items": 112,
        "sell_earnings": 479,
        "commissions": 479,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7232,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1380,
        "ordered_items": 106,
        "sell_earnings": 552,
        "commissions": 552,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5508,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 1960,
        "ordered_items": 178,
        "sell_earnings": 704,
        "commissions": 704,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9378,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 1702,
        "ordered_items": 172,
        "sell_earnings": 777,
        "commissions": 777,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7654,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1608,
        "ordered_items": 121,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7044,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 1732,
        "ordered_items": 163,
        "sell_earnings": 729,
        "commissions": 729,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7842,
        "bonus": 1
    }
];