export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1262,
        "ordered_items": 122,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5459,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1340,
        "ordered_items": 104,
        "sell_earnings": 583,
        "commissions": 583,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6066,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1590,
        "ordered_items": 106,
        "sell_earnings": 470,
        "commissions": 470,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6474,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 1642,
        "ordered_items": 168,
        "sell_earnings": 746,
        "commissions": 746,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7932,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 1892,
        "ordered_items": 170,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8340,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 1970,
        "ordered_items": 152,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8947,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1398,
        "ordered_items": 113,
        "sell_earnings": 440,
        "commissions": 440,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6900,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1520,
        "ordered_items": 116,
        "sell_earnings": 508,
        "commissions": 508,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6442,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1500,
        "ordered_items": 121,
        "sell_earnings": 533,
        "commissions": 533,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6359,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 1732,
        "ordered_items": 153,
        "sell_earnings": 683,
        "commissions": 683,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8047,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 1712,
        "ordered_items": 158,
        "sell_earnings": 708,
        "commissions": 708,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7964,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1834,
        "ordered_items": 161,
        "sell_earnings": 776,
        "commissions": 776,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7506,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1589,
        "ordered_items": 125,
        "sell_earnings": 521,
        "commissions": 521,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5955,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 1643,
        "ordered_items": 149,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8451,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1518,
        "ordered_items": 132,
        "sell_earnings": 447,
        "commissions": 447,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5699,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 1714,
        "ordered_items": 142,
        "sell_earnings": 769,
        "commissions": 769,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8707,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1182,
        "ordered_items": 101,
        "sell_earnings": 575,
        "commissions": 575,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6482,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1534,
        "ordered_items": 101,
        "sell_earnings": 571,
        "commissions": 571,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7130,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1529,
        "ordered_items": 101,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5103,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1423,
        "ordered_items": 108,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6336,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 1809,
        "ordered_items": 166,
        "sell_earnings": 725,
        "commissions": 725,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8070,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 1703,
        "ordered_items": 173,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9303,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 1698,
        "ordered_items": 173,
        "sell_earnings": 645,
        "commissions": 645,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7276,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 2050,
        "ordered_items": 173,
        "sell_earnings": 641,
        "commissions": 641,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7924,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1424,
        "ordered_items": 120,
        "sell_earnings": 543,
        "commissions": 543,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6204,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1203,
        "ordered_items": 122,
        "sell_earnings": 452,
        "commissions": 452,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6105,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 2029,
        "ordered_items": 152,
        "sell_earnings": 764,
        "commissions": 764,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8301,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 1808,
        "ordered_items": 154,
        "sell_earnings": 673,
        "commissions": 673,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8202,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1339,
        "ordered_items": 124,
        "sell_earnings": 552,
        "commissions": 552,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6532,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 1893,
        "ordered_items": 150,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7874,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];