export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1308,
        "ordered_items": 109,
        "sell_earnings": 579,
        "commissions": 579,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6030,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1509,
        "ordered_items": 115,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6071,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1217,
        "ordered_items": 114,
        "sell_earnings": 474,
        "commissions": 474,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6599,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 2015,
        "ordered_items": 160,
        "sell_earnings": 742,
        "commissions": 742,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7807,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1723,
        "ordered_items": 159,
        "sell_earnings": 720,
        "commissions": 720,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8335,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 1924,
        "ordered_items": 165,
        "sell_earnings": 637,
        "commissions": 637,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8376,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1441,
        "ordered_items": 99,
        "sell_earnings": 468,
        "commissions": 468,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6006,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1236,
        "ordered_items": 125,
        "sell_earnings": 469,
        "commissions": 469,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6961,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1477,
        "ordered_items": 118,
        "sell_earnings": 541,
        "commissions": 541,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6175,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1755,
        "ordered_items": 156,
        "sell_earnings": 675,
        "commissions": 675,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8231,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 1996,
        "ordered_items": 149,
        "sell_earnings": 747,
        "commissions": 747,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7445,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1791,
        "ordered_items": 175,
        "sell_earnings": 748,
        "commissions": 748,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8400,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1519,
        "ordered_items": 128,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6260,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1713,
        "ordered_items": 146,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8146,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1487,
        "ordered_items": 109,
        "sell_earnings": 594,
        "commissions": 594,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6908,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1745,
        "ordered_items": 165,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7498,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1612,
        "ordered_items": 105,
        "sell_earnings": 557,
        "commissions": 557,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5643,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1206,
        "ordered_items": 118,
        "sell_earnings": 471,
        "commissions": 471,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6069,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1482,
        "ordered_items": 128,
        "sell_earnings": 599,
        "commissions": 599,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5419,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1341,
        "ordered_items": 135,
        "sell_earnings": 492,
        "commissions": 492,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6103,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 1891,
        "ordered_items": 139,
        "sell_earnings": 724,
        "commissions": 724,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8303,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1750,
        "ordered_items": 146,
        "sell_earnings": 617,
        "commissions": 617,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8987,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 2026,
        "ordered_items": 156,
        "sell_earnings": 745,
        "commissions": 745,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8337,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1620,
        "ordered_items": 169,
        "sell_earnings": 659,
        "commissions": 659,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8763,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1446,
        "ordered_items": 114,
        "sell_earnings": 432,
        "commissions": 432,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5055,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1492,
        "ordered_items": 120,
        "sell_earnings": 566,
        "commissions": 566,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5681,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1740,
        "ordered_items": 154,
        "sell_earnings": 650,
        "commissions": 650,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8725,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1786,
        "ordered_items": 160,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9351,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1469,
        "ordered_items": 128,
        "sell_earnings": 472,
        "commissions": 472,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5557,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1763,
        "ordered_items": 146,
        "sell_earnings": 744,
        "commissions": 744,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8849,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];