export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 1284,
        "ordered_items": 112,
        "sell_earnings": 498,
        "commissions": 498,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5962,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 1518,
        "ordered_items": 101,
        "sell_earnings": 621,
        "commissions": 621,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6783,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 1663,
        "ordered_items": 117,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6574,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 1677,
        "ordered_items": 167,
        "sell_earnings": 650,
        "commissions": 650,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8312,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 1822,
        "ordered_items": 183,
        "sell_earnings": 635,
        "commissions": 635,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8103,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 2056,
        "ordered_items": 172,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8924,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 1644,
        "ordered_items": 101,
        "sell_earnings": 559,
        "commissions": 559,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7033,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 1209,
        "ordered_items": 138,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6602,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 1593,
        "ordered_items": 124,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7354,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 1747,
        "ordered_items": 160,
        "sell_earnings": 806,
        "commissions": 806,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7532,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 2131,
        "ordered_items": 146,
        "sell_earnings": 793,
        "commissions": 793,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8284,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 1696,
        "ordered_items": 183,
        "sell_earnings": 697,
        "commissions": 697,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7853,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 1427,
        "ordered_items": 126,
        "sell_earnings": 581,
        "commissions": 581,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6685,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 1913,
        "ordered_items": 158,
        "sell_earnings": 675,
        "commissions": 675,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8201,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 1222,
        "ordered_items": 111,
        "sell_earnings": 601,
        "commissions": 601,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6559,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 2118,
        "ordered_items": 173,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8327,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 1391,
        "ordered_items": 113,
        "sell_earnings": 470,
        "commissions": 470,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5320,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 1615,
        "ordered_items": 137,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6157,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 1605,
        "ordered_items": 137,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5574,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 1627,
        "ordered_items": 105,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5662,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 1713,
        "ordered_items": 179,
        "sell_earnings": 663,
        "commissions": 663,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9224,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 1735,
        "ordered_items": 147,
        "sell_earnings": 728,
        "commissions": 728,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9312,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 1725,
        "ordered_items": 147,
        "sell_earnings": 650,
        "commissions": 650,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8729,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 1949,
        "ordered_items": 171,
        "sell_earnings": 786,
        "commissions": 786,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9566,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 1198,
        "ordered_items": 116,
        "sell_earnings": 461,
        "commissions": 461,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7000,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 1299,
        "ordered_items": 129,
        "sell_earnings": 586,
        "commissions": 586,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5401,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 2041,
        "ordered_items": 155,
        "sell_earnings": 670,
        "commissions": 670,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9485,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 2142,
        "ordered_items": 168,
        "sell_earnings": 795,
        "commissions": 795,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7886,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 1404,
        "ordered_items": 113,
        "sell_earnings": 512,
        "commissions": 512,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6736,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 1936,
        "ordered_items": 171,
        "sell_earnings": 744,
        "commissions": 744,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8150,
        "bonus": 2
    }
];