export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1601,
        "ordered_items": 112,
        "sell_earnings": 552,
        "commissions": 552,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5999,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1286,
        "ordered_items": 121,
        "sell_earnings": 529,
        "commissions": 529,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5296,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1416,
        "ordered_items": 132,
        "sell_earnings": 430,
        "commissions": 430,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6668,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 1816,
        "ordered_items": 142,
        "sell_earnings": 786,
        "commissions": 786,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7738,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 1946,
        "ordered_items": 153,
        "sell_earnings": 687,
        "commissions": 687,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9110,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 1631,
        "ordered_items": 162,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8407,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1533,
        "ordered_items": 116,
        "sell_earnings": 537,
        "commissions": 537,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5128,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1294,
        "ordered_items": 125,
        "sell_earnings": 595,
        "commissions": 595,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6950,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1485,
        "ordered_items": 125,
        "sell_earnings": 506,
        "commissions": 506,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5835,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 1747,
        "ordered_items": 149,
        "sell_earnings": 710,
        "commissions": 710,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8571,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1938,
        "ordered_items": 149,
        "sell_earnings": 621,
        "commissions": 621,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7456,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 1699,
        "ordered_items": 158,
        "sell_earnings": 679,
        "commissions": 679,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9278,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1474,
        "ordered_items": 107,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6647,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 1758,
        "ordered_items": 167,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7759,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1564,
        "ordered_items": 120,
        "sell_earnings": 553,
        "commissions": 553,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5241,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 1668,
        "ordered_items": 154,
        "sell_earnings": 663,
        "commissions": 663,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9165,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1328,
        "ordered_items": 125,
        "sell_earnings": 523,
        "commissions": 523,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6998,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1311,
        "ordered_items": 136,
        "sell_earnings": 493,
        "commissions": 493,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7174,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1204,
        "ordered_items": 111,
        "sell_earnings": 462,
        "commissions": 462,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7130,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1264,
        "ordered_items": 113,
        "sell_earnings": 465,
        "commissions": 465,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5869,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 1968,
        "ordered_items": 161,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8537,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 2028,
        "ordered_items": 163,
        "sell_earnings": 754,
        "commissions": 754,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7276,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 1921,
        "ordered_items": 138,
        "sell_earnings": 723,
        "commissions": 723,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7232,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 1904,
        "ordered_items": 149,
        "sell_earnings": 693,
        "commissions": 693,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7408,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1193,
        "ordered_items": 131,
        "sell_earnings": 605,
        "commissions": 605,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7004,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1408,
        "ordered_items": 104,
        "sell_earnings": 523,
        "commissions": 523,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5088,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1824,
        "ordered_items": 170,
        "sell_earnings": 693,
        "commissions": 693,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9318,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 2039,
        "ordered_items": 143,
        "sell_earnings": 611,
        "commissions": 611,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7402,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1453,
        "ordered_items": 134,
        "sell_earnings": 506,
        "commissions": 506,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6771,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 1779,
        "ordered_items": 140,
        "sell_earnings": 710,
        "commissions": 710,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7635,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];