export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1317,
        "ordered_items": 135,
        "sell_earnings": 587,
        "commissions": 587,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5902,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1479,
        "ordered_items": 108,
        "sell_earnings": 484,
        "commissions": 484,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5191,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1158,
        "ordered_items": 129,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7118,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 2074,
        "ordered_items": 145,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7288,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 1753,
        "ordered_items": 166,
        "sell_earnings": 732,
        "commissions": 732,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9215,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 1915,
        "ordered_items": 139,
        "sell_earnings": 629,
        "commissions": 629,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8504,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1469,
        "ordered_items": 110,
        "sell_earnings": 429,
        "commissions": 429,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5843,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1566,
        "ordered_items": 105,
        "sell_earnings": 479,
        "commissions": 479,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5408,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1501,
        "ordered_items": 122,
        "sell_earnings": 590,
        "commissions": 590,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5045,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 1731,
        "ordered_items": 152,
        "sell_earnings": 626,
        "commissions": 626,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9361,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 1666,
        "ordered_items": 169,
        "sell_earnings": 737,
        "commissions": 737,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8998,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 1763,
        "ordered_items": 164,
        "sell_earnings": 787,
        "commissions": 787,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8563,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1442,
        "ordered_items": 116,
        "sell_earnings": 587,
        "commissions": 587,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5683,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 1790,
        "ordered_items": 158,
        "sell_earnings": 629,
        "commissions": 629,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8723,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1613,
        "ordered_items": 132,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6907,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 1619,
        "ordered_items": 142,
        "sell_earnings": 753,
        "commissions": 753,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7499,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1154,
        "ordered_items": 121,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7033,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1134,
        "ordered_items": 121,
        "sell_earnings": 516,
        "commissions": 516,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6051,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1182,
        "ordered_items": 107,
        "sell_earnings": 472,
        "commissions": 472,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5256,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1264,
        "ordered_items": 116,
        "sell_earnings": 509,
        "commissions": 509,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5303,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 1968,
        "ordered_items": 158,
        "sell_earnings": 707,
        "commissions": 707,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9103,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 2050,
        "ordered_items": 167,
        "sell_earnings": 744,
        "commissions": 744,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9150,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 2098,
        "ordered_items": 153,
        "sell_earnings": 700,
        "commissions": 700,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8355,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 2078,
        "ordered_items": 153,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7373,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1407,
        "ordered_items": 97,
        "sell_earnings": 502,
        "commissions": 502,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5870,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1172,
        "ordered_items": 123,
        "sell_earnings": 567,
        "commissions": 567,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5839,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 2060,
        "ordered_items": 151,
        "sell_earnings": 649,
        "commissions": 649,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8567,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1825,
        "ordered_items": 177,
        "sell_earnings": 714,
        "commissions": 714,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8536,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1264,
        "ordered_items": 102,
        "sell_earnings": 580,
        "commissions": 580,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5368,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 1968,
        "ordered_items": 172,
        "sell_earnings": 636,
        "commissions": 636,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9038,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];