export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1261,
        "ordered_items": 105,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 128,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6665,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1452,
        "ordered_items": 112,
        "sell_earnings": 445,
        "commissions": 445,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5667,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1208,
        "ordered_items": 140,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7072,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 2132,
        "ordered_items": 144,
        "sell_earnings": 779,
        "commissions": 779,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7814,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 1888,
        "ordered_items": 172,
        "sell_earnings": 811,
        "commissions": 811,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 169,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9219,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 2079,
        "ordered_items": 179,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8221,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1644,
        "ordered_items": 140,
        "sell_earnings": 610,
        "commissions": 610,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6409,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1624,
        "ordered_items": 100,
        "sell_earnings": 457,
        "commissions": 457,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6078,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1229,
        "ordered_items": 119,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6802,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 2111,
        "ordered_items": 165,
        "sell_earnings": 765,
        "commissions": 765,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8084,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 1716,
        "ordered_items": 184,
        "sell_earnings": 799,
        "commissions": 799,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8808,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 1696,
        "ordered_items": 144,
        "sell_earnings": 646,
        "commissions": 646,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 165,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8477,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1577,
        "ordered_items": 137,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6809,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 1763,
        "ordered_items": 147,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8077,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1638,
        "ordered_items": 123,
        "sell_earnings": 508,
        "commissions": 508,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5242,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 1702,
        "ordered_items": 161,
        "sell_earnings": 748,
        "commissions": 748,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9644,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1261,
        "ordered_items": 116,
        "sell_earnings": 513,
        "commissions": 513,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7199,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1403,
        "ordered_items": 127,
        "sell_earnings": 616,
        "commissions": 616,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5700,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1193,
        "ordered_items": 100,
        "sell_earnings": 557,
        "commissions": 557,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 128,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5989,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1222,
        "ordered_items": 100,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5718,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 2118,
        "ordered_items": 184,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 167,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9168,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 2147,
        "ordered_items": 184,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8897,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 1937,
        "ordered_items": 157,
        "sell_earnings": 640,
        "commissions": 640,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9186,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 2079,
        "ordered_items": 168,
        "sell_earnings": 743,
        "commissions": 743,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7687,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1247,
        "ordered_items": 103,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6038,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1419,
        "ordered_items": 137,
        "sell_earnings": 501,
        "commissions": 501,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6034,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 1921,
        "ordered_items": 147,
        "sell_earnings": 755,
        "commissions": 755,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8852,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 2093,
        "ordered_items": 181,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8848,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1449,
        "ordered_items": 122,
        "sell_earnings": 529,
        "commissions": 529,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6314,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 1891,
        "ordered_items": 162,
        "sell_earnings": 727,
        "commissions": 727,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 165,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8572,
        "bonus": 2
    }
];