export let mar = [
    {
        "month": "Mar",
        "day": "01",
        "clicks": 1216,
        "ordered_items": 106,
        "sell_earnings": 591,
        "commissions": 591,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6597,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "02",
        "clicks": 1432,
        "ordered_items": 104,
        "sell_earnings": 605,
        "commissions": 605,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5619,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "03",
        "clicks": 1395,
        "ordered_items": 97,
        "sell_earnings": 506,
        "commissions": 506,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6079,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "04",
        "clicks": 1837,
        "ordered_items": 177,
        "sell_earnings": 710,
        "commissions": 710,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8327,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "05",
        "clicks": 1800,
        "ordered_items": 170,
        "sell_earnings": 611,
        "commissions": 611,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8787,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "06",
        "clicks": 2016,
        "ordered_items": 168,
        "sell_earnings": 625,
        "commissions": 625,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7809,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "07",
        "clicks": 1531,
        "ordered_items": 105,
        "sell_earnings": 572,
        "commissions": 572,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6100,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "08",
        "clicks": 1584,
        "ordered_items": 107,
        "sell_earnings": 584,
        "commissions": 584,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6327,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "09",
        "clicks": 1140,
        "ordered_items": 102,
        "sell_earnings": 501,
        "commissions": 501,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6116,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "10",
        "clicks": 2092,
        "ordered_items": 172,
        "sell_earnings": 715,
        "commissions": 715,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8290,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "11",
        "clicks": 1648,
        "ordered_items": 167,
        "sell_earnings": 632,
        "commissions": 632,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8079,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "12",
        "clicks": 1701,
        "ordered_items": 169,
        "sell_earnings": 644,
        "commissions": 644,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8306,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "13",
        "clicks": 1234,
        "ordered_items": 135,
        "sell_earnings": 585,
        "commissions": 585,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5306,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "14",
        "clicks": 1998,
        "ordered_items": 139,
        "sell_earnings": 631,
        "commissions": 631,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9100,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "15",
        "clicks": 1582,
        "ordered_items": 125,
        "sell_earnings": 599,
        "commissions": 599,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5843,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "16",
        "clicks": 1650,
        "ordered_items": 149,
        "sell_earnings": 617,
        "commissions": 617,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8563,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "17",
        "clicks": 1218,
        "ordered_items": 111,
        "sell_earnings": 592,
        "commissions": 592,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6945,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "18",
        "clicks": 1144,
        "ordered_items": 105,
        "sell_earnings": 543,
        "commissions": 543,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6322,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "19",
        "clicks": 1591,
        "ordered_items": 126,
        "sell_earnings": 453,
        "commissions": 453,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6307,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "20",
        "clicks": 1614,
        "ordered_items": 98,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5848,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "21",
        "clicks": 1618,
        "ordered_items": 176,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8558,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "22",
        "clicks": 1641,
        "ordered_items": 148,
        "sell_earnings": 763,
        "commissions": 763,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8099,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "23",
        "clicks": 2088,
        "ordered_items": 169,
        "sell_earnings": 673,
        "commissions": 673,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8084,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "24",
        "clicks": 2014,
        "ordered_items": 163,
        "sell_earnings": 624,
        "commissions": 624,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7461,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "25",
        "clicks": 1474,
        "ordered_items": 103,
        "sell_earnings": 602,
        "commissions": 602,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6950,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "26",
        "clicks": 1574,
        "ordered_items": 137,
        "sell_earnings": 581,
        "commissions": 581,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5934,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "27",
        "clicks": 1658,
        "ordered_items": 137,
        "sell_earnings": 635,
        "commissions": 635,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8472,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "28",
        "clicks": 1758,
        "ordered_items": 171,
        "sell_earnings": 614,
        "commissions": 614,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7456,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "29",
        "clicks": 1431,
        "ordered_items": 113,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7169,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "30",
        "clicks": 1801,
        "ordered_items": 161,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7237,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];