export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1193,
        "ordered_items": 131,
        "sell_earnings": 432,
        "commissions": 432,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7019,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1411,
        "ordered_items": 128,
        "sell_earnings": 538,
        "commissions": 538,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5749,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1370,
        "ordered_items": 108,
        "sell_earnings": 576,
        "commissions": 576,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6459,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 1862,
        "ordered_items": 166,
        "sell_earnings": 640,
        "commissions": 640,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7947,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1821,
        "ordered_items": 146,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8657,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 2039,
        "ordered_items": 143,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7387,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1333,
        "ordered_items": 122,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6124,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1598,
        "ordered_items": 117,
        "sell_earnings": 451,
        "commissions": 451,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5886,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1579,
        "ordered_items": 118,
        "sell_earnings": 503,
        "commissions": 503,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5205,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1653,
        "ordered_items": 156,
        "sell_earnings": 713,
        "commissions": 713,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9201,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 1634,
        "ordered_items": 157,
        "sell_earnings": 765,
        "commissions": 765,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8520,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1899,
        "ordered_items": 152,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8282,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1426,
        "ordered_items": 135,
        "sell_earnings": 439,
        "commissions": 439,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6730,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1806,
        "ordered_items": 139,
        "sell_earnings": 777,
        "commissions": 777,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7676,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1451,
        "ordered_items": 132,
        "sell_earnings": 455,
        "commissions": 455,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7168,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1781,
        "ordered_items": 142,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7238,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1596,
        "ordered_items": 116,
        "sell_earnings": 489,
        "commissions": 489,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5822,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1452,
        "ordered_items": 116,
        "sell_earnings": 474,
        "commissions": 474,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5751,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1186,
        "ordered_items": 128,
        "sell_earnings": 564,
        "commissions": 564,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5629,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1144,
        "ordered_items": 119,
        "sell_earnings": 431,
        "commissions": 431,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6622,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 2088,
        "ordered_items": 155,
        "sell_earnings": 785,
        "commissions": 785,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7784,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 2046,
        "ordered_items": 146,
        "sell_earnings": 652,
        "commissions": 652,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8777,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 1780,
        "ordered_items": 158,
        "sell_earnings": 742,
        "commissions": 742,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8655,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1636,
        "ordered_items": 158,
        "sell_earnings": 727,
        "commissions": 727,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8584,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1317,
        "ordered_items": 108,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6947,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1221,
        "ordered_items": 134,
        "sell_earnings": 437,
        "commissions": 437,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7006,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 2011,
        "ordered_items": 140,
        "sell_earnings": 779,
        "commissions": 779,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7400,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1915,
        "ordered_items": 166,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7459,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1406,
        "ordered_items": 123,
        "sell_earnings": 429,
        "commissions": 429,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6223,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1826,
        "ordered_items": 151,
        "sell_earnings": 787,
        "commissions": 787,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8183,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];