export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 1190,
        "ordered_items": 130,
        "sell_earnings": 447,
        "commissions": 447,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7128,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 1431,
        "ordered_items": 104,
        "sell_earnings": 510,
        "commissions": 510,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6480,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 1362,
        "ordered_items": 137,
        "sell_earnings": 484,
        "commissions": 484,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6545,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 1978,
        "ordered_items": 147,
        "sell_earnings": 772,
        "commissions": 772,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8341,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 1909,
        "ordered_items": 180,
        "sell_earnings": 746,
        "commissions": 746,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8406,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 2150,
        "ordered_items": 154,
        "sell_earnings": 809,
        "commissions": 809,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7758,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 1519,
        "ordered_items": 130,
        "sell_earnings": 575,
        "commissions": 575,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5351,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 1585,
        "ordered_items": 107,
        "sell_earnings": 621,
        "commissions": 621,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5505,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 1351,
        "ordered_items": 131,
        "sell_earnings": 578,
        "commissions": 578,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 128,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6201,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 1989,
        "ordered_items": 153,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8685,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 1755,
        "ordered_items": 177,
        "sell_earnings": 635,
        "commissions": 635,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9381,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 1821,
        "ordered_items": 154,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9535,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 1267,
        "ordered_items": 136,
        "sell_earnings": 466,
        "commissions": 466,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5972,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 2073,
        "ordered_items": 148,
        "sell_earnings": 790,
        "commissions": 790,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8914,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 1205,
        "ordered_items": 116,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6055,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 2135,
        "ordered_items": 168,
        "sell_earnings": 634,
        "commissions": 634,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8831,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 1378,
        "ordered_items": 116,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7189,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 1501,
        "ordered_items": 107,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6914,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 1211,
        "ordered_items": 103,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5814,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 1411,
        "ordered_items": 139,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6654,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 1929,
        "ordered_items": 145,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8232,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 2129,
        "ordered_items": 181,
        "sell_earnings": 792,
        "commissions": 792,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9072,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 1839,
        "ordered_items": 177,
        "sell_earnings": 752,
        "commissions": 752,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7972,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 1962,
        "ordered_items": 168,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 165,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7697,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 1386,
        "ordered_items": 128,
        "sell_earnings": 597,
        "commissions": 597,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5476,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 1612,
        "ordered_items": 138,
        "sell_earnings": 548,
        "commissions": 548,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7041,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 1728,
        "ordered_items": 146,
        "sell_earnings": 708,
        "commissions": 708,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7845,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 1954,
        "ordered_items": 156,
        "sell_earnings": 659,
        "commissions": 659,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9410,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 1285,
        "ordered_items": 132,
        "sell_earnings": 588,
        "commissions": 588,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6380,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 2055,
        "ordered_items": 152,
        "sell_earnings": 668,
        "commissions": 668,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8506,
        "bonus": 0
    }
];