export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1382,
        "ordered_items": 99,
        "sell_earnings": 512,
        "commissions": 512,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6630,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1580,
        "ordered_items": 108,
        "sell_earnings": 508,
        "commissions": 508,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6065,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1389,
        "ordered_items": 130,
        "sell_earnings": 586,
        "commissions": 586,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5756,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 1843,
        "ordered_items": 144,
        "sell_earnings": 630,
        "commissions": 630,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8650,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 1652,
        "ordered_items": 166,
        "sell_earnings": 708,
        "commissions": 708,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8341,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 1850,
        "ordered_items": 175,
        "sell_earnings": 704,
        "commissions": 704,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7776,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1334,
        "ordered_items": 108,
        "sell_earnings": 442,
        "commissions": 442,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6481,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1264,
        "ordered_items": 115,
        "sell_earnings": 483,
        "commissions": 483,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6314,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1377,
        "ordered_items": 123,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7085,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 1855,
        "ordered_items": 151,
        "sell_earnings": 753,
        "commissions": 753,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7321,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1968,
        "ordered_items": 159,
        "sell_earnings": 733,
        "commissions": 733,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8092,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 1898,
        "ordered_items": 166,
        "sell_earnings": 774,
        "commissions": 774,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7925,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1151,
        "ordered_items": 135,
        "sell_earnings": 518,
        "commissions": 518,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6003,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 2081,
        "ordered_items": 139,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8403,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1132,
        "ordered_items": 102,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5970,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 2100,
        "ordered_items": 172,
        "sell_earnings": 752,
        "commissions": 752,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8436,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1274,
        "ordered_items": 126,
        "sell_earnings": 538,
        "commissions": 538,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5657,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1139,
        "ordered_items": 104,
        "sell_earnings": 557,
        "commissions": 557,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7056,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1138,
        "ordered_items": 97,
        "sell_earnings": 556,
        "commissions": 556,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6584,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1307,
        "ordered_items": 107,
        "sell_earnings": 519,
        "commissions": 519,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7089,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 1925,
        "ordered_items": 167,
        "sell_earnings": 697,
        "commissions": 697,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7317,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 2094,
        "ordered_items": 177,
        "sell_earnings": 660,
        "commissions": 660,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7822,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 2093,
        "ordered_items": 170,
        "sell_earnings": 659,
        "commissions": 659,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7350,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 1958,
        "ordered_items": 148,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8749,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1193,
        "ordered_items": 127,
        "sell_earnings": 454,
        "commissions": 454,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5740,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1168,
        "ordered_items": 104,
        "sell_earnings": 585,
        "commissions": 585,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5671,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 2064,
        "ordered_items": 170,
        "sell_earnings": 631,
        "commissions": 631,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8735,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 2039,
        "ordered_items": 147,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8666,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1500,
        "ordered_items": 112,
        "sell_earnings": 427,
        "commissions": 427,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6641,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 1732,
        "ordered_items": 162,
        "sell_earnings": 789,
        "commissions": 789,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7765,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];