export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1138,
        "ordered_items": 101,
        "sell_earnings": 506,
        "commissions": 506,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5236,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1210,
        "ordered_items": 125,
        "sell_earnings": 602,
        "commissions": 602,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5343,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1241,
        "ordered_items": 120,
        "sell_earnings": 493,
        "commissions": 493,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6312,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 1991,
        "ordered_items": 154,
        "sell_earnings": 723,
        "commissions": 723,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8094,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 2022,
        "ordered_items": 149,
        "sell_earnings": 614,
        "commissions": 614,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9063,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 2094,
        "ordered_items": 173,
        "sell_earnings": 710,
        "commissions": 710,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9170,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1135,
        "ordered_items": 111,
        "sell_earnings": 514,
        "commissions": 514,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6074,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1411,
        "ordered_items": 108,
        "sell_earnings": 553,
        "commissions": 553,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6954,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1488,
        "ordered_items": 119,
        "sell_earnings": 454,
        "commissions": 454,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5908,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 1744,
        "ordered_items": 155,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8498,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 1821,
        "ordered_items": 166,
        "sell_earnings": 663,
        "commissions": 663,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7452,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 2097,
        "ordered_items": 163,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8332,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1267,
        "ordered_items": 118,
        "sell_earnings": 514,
        "commissions": 514,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5670,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 1965,
        "ordered_items": 156,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8736,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1589,
        "ordered_items": 136,
        "sell_earnings": 524,
        "commissions": 524,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5347,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 1643,
        "ordered_items": 138,
        "sell_earnings": 692,
        "commissions": 692,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9059,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1439,
        "ordered_items": 113,
        "sell_earnings": 559,
        "commissions": 559,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7109,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1225,
        "ordered_items": 100,
        "sell_earnings": 498,
        "commissions": 498,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5491,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1445,
        "ordered_items": 136,
        "sell_earnings": 433,
        "commissions": 433,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5580,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1586,
        "ordered_items": 116,
        "sell_earnings": 489,
        "commissions": 489,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5316,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 1646,
        "ordered_items": 158,
        "sell_earnings": 727,
        "commissions": 727,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9090,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1787,
        "ordered_items": 138,
        "sell_earnings": 783,
        "commissions": 783,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8826,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 2007,
        "ordered_items": 174,
        "sell_earnings": 718,
        "commissions": 718,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8915,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 1793,
        "ordered_items": 161,
        "sell_earnings": 657,
        "commissions": 657,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7297,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1485,
        "ordered_items": 105,
        "sell_earnings": 462,
        "commissions": 462,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5056,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1605,
        "ordered_items": 116,
        "sell_earnings": 596,
        "commissions": 596,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6783,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 1627,
        "ordered_items": 158,
        "sell_earnings": 620,
        "commissions": 620,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7623,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1747,
        "ordered_items": 169,
        "sell_earnings": 754,
        "commissions": 754,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9350,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1337,
        "ordered_items": 137,
        "sell_earnings": 579,
        "commissions": 579,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6063,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 1895,
        "ordered_items": 137,
        "sell_earnings": 637,
        "commissions": 637,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8343,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];