export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1243,
        "ordered_items": 117,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6032,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1314,
        "ordered_items": 106,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6013,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1507,
        "ordered_items": 134,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5757,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 1833,
        "ordered_items": 150,
        "sell_earnings": 658,
        "commissions": 658,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9129,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 2026,
        "ordered_items": 178,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8873,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 2097,
        "ordered_items": 167,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8854,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1300,
        "ordered_items": 114,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5339,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1262,
        "ordered_items": 128,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7115,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1200,
        "ordered_items": 121,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5779,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 2140,
        "ordered_items": 163,
        "sell_earnings": 756,
        "commissions": 756,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9107,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 2078,
        "ordered_items": 156,
        "sell_earnings": 634,
        "commissions": 634,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7771,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 2040,
        "ordered_items": 170,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9547,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1215,
        "ordered_items": 126,
        "sell_earnings": 531,
        "commissions": 531,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5571,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 2125,
        "ordered_items": 158,
        "sell_earnings": 725,
        "commissions": 725,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9315,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1537,
        "ordered_items": 138,
        "sell_earnings": 502,
        "commissions": 502,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6787,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 1803,
        "ordered_items": 146,
        "sell_earnings": 754,
        "commissions": 754,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8099,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1455,
        "ordered_items": 113,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6002,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1214,
        "ordered_items": 133,
        "sell_earnings": 574,
        "commissions": 574,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7321,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1646,
        "ordered_items": 117,
        "sell_earnings": 584,
        "commissions": 584,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6921,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1314,
        "ordered_items": 103,
        "sell_earnings": 580,
        "commissions": 580,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6186,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 2026,
        "ordered_items": 181,
        "sell_earnings": 676,
        "commissions": 676,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8700,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 1694,
        "ordered_items": 167,
        "sell_earnings": 672,
        "commissions": 672,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7965,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 2126,
        "ordered_items": 151,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7565,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 1885,
        "ordered_items": 171,
        "sell_earnings": 793,
        "commissions": 793,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 166,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8884,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1567,
        "ordered_items": 107,
        "sell_earnings": 560,
        "commissions": 560,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5919,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1259,
        "ordered_items": 136,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7252,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 2081,
        "ordered_items": 148,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7634,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 1773,
        "ordered_items": 177,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8967,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1500,
        "ordered_items": 108,
        "sell_earnings": 605,
        "commissions": 605,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6590,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 1840,
        "ordered_items": 176,
        "sell_earnings": 651,
        "commissions": 651,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8296,
        "bonus": 1
    }
];