export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1136,
        "ordered_items": 100,
        "sell_earnings": 513,
        "commissions": 513,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5952,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1229,
        "ordered_items": 137,
        "sell_earnings": 548,
        "commissions": 548,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5416,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1289,
        "ordered_items": 98,
        "sell_earnings": 523,
        "commissions": 523,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5281,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 1943,
        "ordered_items": 176,
        "sell_earnings": 693,
        "commissions": 693,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9125,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 2003,
        "ordered_items": 137,
        "sell_earnings": 668,
        "commissions": 668,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8990,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 2096,
        "ordered_items": 174,
        "sell_earnings": 703,
        "commissions": 703,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8454,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1370,
        "ordered_items": 107,
        "sell_earnings": 440,
        "commissions": 440,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5053,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1428,
        "ordered_items": 122,
        "sell_earnings": 595,
        "commissions": 595,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5097,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1462,
        "ordered_items": 129,
        "sell_earnings": 541,
        "commissions": 541,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6077,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 1770,
        "ordered_items": 145,
        "sell_earnings": 675,
        "commissions": 675,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8329,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 1804,
        "ordered_items": 152,
        "sell_earnings": 621,
        "commissions": 621,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9309,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1862,
        "ordered_items": 167,
        "sell_earnings": 776,
        "commissions": 776,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9353,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1247,
        "ordered_items": 102,
        "sell_earnings": 542,
        "commissions": 542,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6043,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 1985,
        "ordered_items": 172,
        "sell_earnings": 674,
        "commissions": 674,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8363,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1187,
        "ordered_items": 137,
        "sell_earnings": 521,
        "commissions": 521,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6474,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 2045,
        "ordered_items": 137,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7932,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1534,
        "ordered_items": 120,
        "sell_earnings": 438,
        "commissions": 438,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6543,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1316,
        "ordered_items": 133,
        "sell_earnings": 524,
        "commissions": 524,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5708,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1276,
        "ordered_items": 112,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5926,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1178,
        "ordered_items": 127,
        "sell_earnings": 550,
        "commissions": 550,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6212,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 2054,
        "ordered_items": 147,
        "sell_earnings": 666,
        "commissions": 666,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8194,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 1956,
        "ordered_items": 162,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8480,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 1916,
        "ordered_items": 141,
        "sell_earnings": 692,
        "commissions": 692,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8698,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1698,
        "ordered_items": 154,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7863,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1447,
        "ordered_items": 101,
        "sell_earnings": 587,
        "commissions": 587,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6647,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1489,
        "ordered_items": 103,
        "sell_earnings": 541,
        "commissions": 541,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6852,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 1743,
        "ordered_items": 171,
        "sell_earnings": 675,
        "commissions": 675,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7554,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 1785,
        "ordered_items": 173,
        "sell_earnings": 629,
        "commissions": 629,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7759,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1190,
        "ordered_items": 129,
        "sell_earnings": 435,
        "commissions": 435,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6385,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 2042,
        "ordered_items": 145,
        "sell_earnings": 781,
        "commissions": 781,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8021,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];