export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1582,
        "ordered_items": 111,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6968,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1369,
        "ordered_items": 101,
        "sell_earnings": 554,
        "commissions": 554,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5604,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1591,
        "ordered_items": 103,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6095,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 1749,
        "ordered_items": 181,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8791,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 1971,
        "ordered_items": 183,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9282,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 1758,
        "ordered_items": 173,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7918,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1502,
        "ordered_items": 140,
        "sell_earnings": 554,
        "commissions": 554,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7398,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1451,
        "ordered_items": 119,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6568,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1615,
        "ordered_items": 124,
        "sell_earnings": 600,
        "commissions": 600,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6622,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 1725,
        "ordered_items": 160,
        "sell_earnings": 656,
        "commissions": 656,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8264,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 1889,
        "ordered_items": 165,
        "sell_earnings": 800,
        "commissions": 800,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8318,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 1838,
        "ordered_items": 144,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7488,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1306,
        "ordered_items": 106,
        "sell_earnings": 532,
        "commissions": 532,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6912,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 2034,
        "ordered_items": 178,
        "sell_earnings": 724,
        "commissions": 724,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7974,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1455,
        "ordered_items": 131,
        "sell_earnings": 569,
        "commissions": 569,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7073,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 1885,
        "ordered_items": 153,
        "sell_earnings": 687,
        "commissions": 687,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7813,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1246,
        "ordered_items": 125,
        "sell_earnings": 620,
        "commissions": 620,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7072,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1471,
        "ordered_items": 121,
        "sell_earnings": 601,
        "commissions": 601,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5875,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1566,
        "ordered_items": 113,
        "sell_earnings": 462,
        "commissions": 462,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6654,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1546,
        "ordered_items": 117,
        "sell_earnings": 479,
        "commissions": 479,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7128,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 1794,
        "ordered_items": 167,
        "sell_earnings": 777,
        "commissions": 777,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7758,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 1774,
        "ordered_items": 171,
        "sell_earnings": 794,
        "commissions": 794,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 165,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8232,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 1869,
        "ordered_items": 163,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9011,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 2094,
        "ordered_items": 159,
        "sell_earnings": 636,
        "commissions": 636,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7814,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1412,
        "ordered_items": 125,
        "sell_earnings": 486,
        "commissions": 486,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5538,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1612,
        "ordered_items": 133,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7180,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 1728,
        "ordered_items": 151,
        "sell_earnings": 779,
        "commissions": 779,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7706,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 1928,
        "ordered_items": 159,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9348,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1285,
        "ordered_items": 115,
        "sell_earnings": 572,
        "commissions": 572,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7414,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 2055,
        "ordered_items": 169,
        "sell_earnings": 684,
        "commissions": 684,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7472,
        "bonus": 0
    }
];