export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1176,
        "ordered_items": 98,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5248,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1610,
        "ordered_items": 113,
        "sell_earnings": 603,
        "commissions": 603,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5415,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1494,
        "ordered_items": 100,
        "sell_earnings": 501,
        "commissions": 501,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6017,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 1738,
        "ordered_items": 174,
        "sell_earnings": 715,
        "commissions": 715,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8389,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1622,
        "ordered_items": 161,
        "sell_earnings": 613,
        "commissions": 613,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8991,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 2056,
        "ordered_items": 176,
        "sell_earnings": 721,
        "commissions": 721,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9158,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1448,
        "ordered_items": 119,
        "sell_earnings": 529,
        "commissions": 529,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5175,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1133,
        "ordered_items": 124,
        "sell_earnings": 563,
        "commissions": 563,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5520,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1328,
        "ordered_items": 104,
        "sell_earnings": 588,
        "commissions": 588,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5429,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1904,
        "ordered_items": 170,
        "sell_earnings": 628,
        "commissions": 628,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8977,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 2099,
        "ordered_items": 150,
        "sell_earnings": 653,
        "commissions": 653,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8886,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1784,
        "ordered_items": 155,
        "sell_earnings": 687,
        "commissions": 687,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9231,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1273,
        "ordered_items": 134,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5344,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1959,
        "ordered_items": 140,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9062,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1493,
        "ordered_items": 111,
        "sell_earnings": 564,
        "commissions": 564,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5220,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1739,
        "ordered_items": 163,
        "sell_earnings": 652,
        "commissions": 652,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9186,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1459,
        "ordered_items": 117,
        "sell_earnings": 452,
        "commissions": 452,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6057,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1545,
        "ordered_items": 112,
        "sell_earnings": 526,
        "commissions": 526,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6370,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1375,
        "ordered_items": 98,
        "sell_earnings": 581,
        "commissions": 581,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6458,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1407,
        "ordered_items": 133,
        "sell_earnings": 455,
        "commissions": 455,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6579,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 1825,
        "ordered_items": 141,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7827,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1857,
        "ordered_items": 176,
        "sell_earnings": 635,
        "commissions": 635,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7948,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 1687,
        "ordered_items": 162,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8036,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1773,
        "ordered_items": 157,
        "sell_earnings": 764,
        "commissions": 764,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8349,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1263,
        "ordered_items": 105,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6956,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1353,
        "ordered_items": 119,
        "sell_earnings": 547,
        "commissions": 547,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6304,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1879,
        "ordered_items": 155,
        "sell_earnings": 669,
        "commissions": 669,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8102,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1969,
        "ordered_items": 169,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7450,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1529,
        "ordered_items": 104,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5805,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1703,
        "ordered_items": 170,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8601,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];