export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 1454,
        "ordered_items": 120,
        "sell_earnings": 595,
        "commissions": 595,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6685,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 1629,
        "ordered_items": 121,
        "sell_earnings": 539,
        "commissions": 539,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5870,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 1334,
        "ordered_items": 102,
        "sell_earnings": 595,
        "commissions": 595,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7240,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 2006,
        "ordered_items": 182,
        "sell_earnings": 661,
        "commissions": 661,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7646,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 1711,
        "ordered_items": 163,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9016,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 1886,
        "ordered_items": 164,
        "sell_earnings": 661,
        "commissions": 661,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8201,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 1638,
        "ordered_items": 129,
        "sell_earnings": 578,
        "commissions": 578,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5673,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 1263,
        "ordered_items": 128,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5391,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 1178,
        "ordered_items": 106,
        "sell_earnings": 452,
        "commissions": 452,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6136,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 2162,
        "ordered_items": 178,
        "sell_earnings": 804,
        "commissions": 804,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8750,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 2077,
        "ordered_items": 156,
        "sell_earnings": 658,
        "commissions": 658,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9495,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 1702,
        "ordered_items": 155,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 167,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9213,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 1498,
        "ordered_items": 141,
        "sell_earnings": 525,
        "commissions": 525,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6288,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 1842,
        "ordered_items": 143,
        "sell_earnings": 731,
        "commissions": 731,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8598,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 1593,
        "ordered_items": 139,
        "sell_earnings": 627,
        "commissions": 627,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6837,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 1747,
        "ordered_items": 145,
        "sell_earnings": 629,
        "commissions": 629,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8049,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 1280,
        "ordered_items": 112,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5639,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 1275,
        "ordered_items": 140,
        "sell_earnings": 589,
        "commissions": 589,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6187,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 1342,
        "ordered_items": 138,
        "sell_earnings": 472,
        "commissions": 472,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6981,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 1447,
        "ordered_items": 140,
        "sell_earnings": 447,
        "commissions": 447,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5340,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 1893,
        "ordered_items": 144,
        "sell_earnings": 809,
        "commissions": 809,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9546,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 1998,
        "ordered_items": 146,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7905,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 2065,
        "ordered_items": 144,
        "sell_earnings": 667,
        "commissions": 667,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8699,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 2060,
        "ordered_items": 172,
        "sell_earnings": 800,
        "commissions": 800,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9247,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 1474,
        "ordered_items": 129,
        "sell_earnings": 487,
        "commissions": 487,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6849,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 1212,
        "ordered_items": 114,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7442,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 2128,
        "ordered_items": 170,
        "sell_earnings": 644,
        "commissions": 644,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7444,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 1866,
        "ordered_items": 155,
        "sell_earnings": 769,
        "commissions": 769,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8037,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 1424,
        "ordered_items": 104,
        "sell_earnings": 560,
        "commissions": 560,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6455,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 1916,
        "ordered_items": 180,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8431,
        "bonus": 0
    }
];