export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1428,
        "ordered_items": 132,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5538,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1525,
        "ordered_items": 109,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6446,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1335,
        "ordered_items": 97,
        "sell_earnings": 552,
        "commissions": 552,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6881,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 1897,
        "ordered_items": 177,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7525,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 1707,
        "ordered_items": 165,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7960,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 1804,
        "ordered_items": 142,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8868,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1196,
        "ordered_items": 124,
        "sell_earnings": 535,
        "commissions": 535,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5501,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1157,
        "ordered_items": 124,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6516,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1309,
        "ordered_items": 125,
        "sell_earnings": 575,
        "commissions": 575,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6784,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 1923,
        "ordered_items": 149,
        "sell_earnings": 641,
        "commissions": 641,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7622,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 2075,
        "ordered_items": 150,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7890,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 2036,
        "ordered_items": 150,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8905,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1336,
        "ordered_items": 132,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7132,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 1896,
        "ordered_items": 142,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7274,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1391,
        "ordered_items": 116,
        "sell_earnings": 453,
        "commissions": 453,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5927,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 1841,
        "ordered_items": 158,
        "sell_earnings": 763,
        "commissions": 763,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8479,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1172,
        "ordered_items": 111,
        "sell_earnings": 439,
        "commissions": 439,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5747,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1272,
        "ordered_items": 116,
        "sell_earnings": 432,
        "commissions": 432,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6435,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1278,
        "ordered_items": 105,
        "sell_earnings": 524,
        "commissions": 524,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6330,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1280,
        "ordered_items": 108,
        "sell_earnings": 605,
        "commissions": 605,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6530,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 1952,
        "ordered_items": 166,
        "sell_earnings": 611,
        "commissions": 611,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7876,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1954,
        "ordered_items": 169,
        "sell_earnings": 692,
        "commissions": 692,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8076,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 1960,
        "ordered_items": 158,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7971,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 2060,
        "ordered_items": 163,
        "sell_earnings": 777,
        "commissions": 777,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8659,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1477,
        "ordered_items": 135,
        "sell_earnings": 431,
        "commissions": 431,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6453,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1372,
        "ordered_items": 97,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7007,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 1860,
        "ordered_items": 177,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7399,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1755,
        "ordered_items": 139,
        "sell_earnings": 785,
        "commissions": 785,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7953,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1303,
        "ordered_items": 123,
        "sell_earnings": 454,
        "commissions": 454,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5053,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 1929,
        "ordered_items": 151,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9353,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];