export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1299,
        "ordered_items": 119,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5965,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1319,
        "ordered_items": 123,
        "sell_earnings": 607,
        "commissions": 607,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6763,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1495,
        "ordered_items": 105,
        "sell_earnings": 459,
        "commissions": 459,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7053,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 1737,
        "ordered_items": 169,
        "sell_earnings": 757,
        "commissions": 757,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7353,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 1913,
        "ordered_items": 151,
        "sell_earnings": 609,
        "commissions": 609,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7643,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 1933,
        "ordered_items": 155,
        "sell_earnings": 676,
        "commissions": 676,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8441,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1564,
        "ordered_items": 114,
        "sell_earnings": 444,
        "commissions": 444,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6619,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1555,
        "ordered_items": 114,
        "sell_earnings": 508,
        "commissions": 508,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6770,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1533,
        "ordered_items": 116,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5652,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 1699,
        "ordered_items": 158,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8754,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 1677,
        "ordered_items": 160,
        "sell_earnings": 708,
        "commissions": 708,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7636,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 1668,
        "ordered_items": 160,
        "sell_earnings": 772,
        "commissions": 772,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7787,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1297,
        "ordered_items": 111,
        "sell_earnings": 522,
        "commissions": 522,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6931,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 1935,
        "ordered_items": 163,
        "sell_earnings": 694,
        "commissions": 694,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7475,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1363,
        "ordered_items": 101,
        "sell_earnings": 439,
        "commissions": 439,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5088,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 1869,
        "ordered_items": 173,
        "sell_earnings": 777,
        "commissions": 777,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9318,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1299,
        "ordered_items": 120,
        "sell_earnings": 526,
        "commissions": 526,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5164,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1293,
        "ordered_items": 130,
        "sell_earnings": 539,
        "commissions": 539,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7147,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1219,
        "ordered_items": 130,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5668,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1532,
        "ordered_items": 99,
        "sell_earnings": 457,
        "commissions": 457,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5634,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 1700,
        "ordered_items": 175,
        "sell_earnings": 759,
        "commissions": 759,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8772,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 2013,
        "ordered_items": 144,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8738,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 1939,
        "ordered_items": 144,
        "sell_earnings": 677,
        "commissions": 677,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7259,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 1933,
        "ordered_items": 154,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9242,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1155,
        "ordered_items": 106,
        "sell_earnings": 506,
        "commissions": 506,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6034,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1194,
        "ordered_items": 103,
        "sell_earnings": 429,
        "commissions": 429,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5362,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 2038,
        "ordered_items": 171,
        "sell_earnings": 787,
        "commissions": 787,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9044,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 2077,
        "ordered_items": 168,
        "sell_earnings": 710,
        "commissions": 710,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8372,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1407,
        "ordered_items": 101,
        "sell_earnings": 529,
        "commissions": 529,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5638,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 1825,
        "ordered_items": 173,
        "sell_earnings": 687,
        "commissions": 687,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8768,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];