export let mar = [
    {
        "month": "Mar",
        "day": "01",
        "clicks": 1358,
        "ordered_items": 137,
        "sell_earnings": 519,
        "commissions": 519,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6908,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "02",
        "clicks": 1460,
        "ordered_items": 118,
        "sell_earnings": 588,
        "commissions": 588,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5537,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "03",
        "clicks": 1152,
        "ordered_items": 98,
        "sell_earnings": 466,
        "commissions": 466,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6036,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "04",
        "clicks": 2080,
        "ordered_items": 176,
        "sell_earnings": 750,
        "commissions": 750,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8370,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "05",
        "clicks": 1772,
        "ordered_items": 156,
        "sell_earnings": 628,
        "commissions": 628,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8869,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "06",
        "clicks": 1874,
        "ordered_items": 137,
        "sell_earnings": 697,
        "commissions": 697,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7498,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "07",
        "clicks": 1409,
        "ordered_items": 115,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6725,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "08",
        "clicks": 1367,
        "ordered_items": 116,
        "sell_earnings": 514,
        "commissions": 514,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5306,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "09",
        "clicks": 1142,
        "ordered_items": 137,
        "sell_earnings": 478,
        "commissions": 478,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5800,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "10",
        "clicks": 2090,
        "ordered_items": 137,
        "sell_earnings": 738,
        "commissions": 738,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8606,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "11",
        "clicks": 1865,
        "ordered_items": 158,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9100,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "12",
        "clicks": 1823,
        "ordered_items": 159,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7681,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "13",
        "clicks": 1550,
        "ordered_items": 131,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6838,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "14",
        "clicks": 1682,
        "ordered_items": 143,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7568,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "15",
        "clicks": 1165,
        "ordered_items": 114,
        "sell_earnings": 486,
        "commissions": 486,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6328,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "16",
        "clicks": 2067,
        "ordered_items": 160,
        "sell_earnings": 730,
        "commissions": 730,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8078,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "17",
        "clicks": 1503,
        "ordered_items": 117,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6715,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "18",
        "clicks": 1360,
        "ordered_items": 113,
        "sell_earnings": 580,
        "commissions": 580,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5188,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "19",
        "clicks": 1149,
        "ordered_items": 110,
        "sell_earnings": 486,
        "commissions": 486,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6749,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "20",
        "clicks": 1145,
        "ordered_items": 119,
        "sell_earnings": 529,
        "commissions": 529,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6301,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "21",
        "clicks": 2087,
        "ordered_items": 155,
        "sell_earnings": 687,
        "commissions": 687,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8105,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "22",
        "clicks": 2083,
        "ordered_items": 164,
        "sell_earnings": 730,
        "commissions": 730,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7657,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "23",
        "clicks": 1872,
        "ordered_items": 161,
        "sell_earnings": 636,
        "commissions": 636,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9218,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "24",
        "clicks": 1729,
        "ordered_items": 157,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7691,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "25",
        "clicks": 1328,
        "ordered_items": 121,
        "sell_earnings": 438,
        "commissions": 438,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7116,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "26",
        "clicks": 1360,
        "ordered_items": 111,
        "sell_earnings": 489,
        "commissions": 489,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5169,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "27",
        "clicks": 1872,
        "ordered_items": 163,
        "sell_earnings": 727,
        "commissions": 727,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9237,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "28",
        "clicks": 1904,
        "ordered_items": 153,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7290,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "29",
        "clicks": 1498,
        "ordered_items": 121,
        "sell_earnings": 529,
        "commissions": 529,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5078,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "30",
        "clicks": 1734,
        "ordered_items": 153,
        "sell_earnings": 687,
        "commissions": 687,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9328,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];