export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1516,
        "ordered_items": 116,
        "sell_earnings": 581,
        "commissions": 581,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6425,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1528,
        "ordered_items": 124,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6608,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1273,
        "ordered_items": 118,
        "sell_earnings": 599,
        "commissions": 599,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5726,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 1959,
        "ordered_items": 156,
        "sell_earnings": 617,
        "commissions": 617,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8680,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 1704,
        "ordered_items": 150,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7798,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 1716,
        "ordered_items": 158,
        "sell_earnings": 635,
        "commissions": 635,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7981,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1284,
        "ordered_items": 104,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6969,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1156,
        "ordered_items": 134,
        "sell_earnings": 530,
        "commissions": 530,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5763,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1139,
        "ordered_items": 126,
        "sell_earnings": 600,
        "commissions": 600,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5292,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 2093,
        "ordered_items": 148,
        "sell_earnings": 616,
        "commissions": 616,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9114,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 2076,
        "ordered_items": 140,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8643,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1948,
        "ordered_items": 170,
        "sell_earnings": 720,
        "commissions": 720,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7437,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1218,
        "ordered_items": 98,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5878,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 2014,
        "ordered_items": 176,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8528,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1180,
        "ordered_items": 134,
        "sell_earnings": 539,
        "commissions": 539,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5104,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 2052,
        "ordered_items": 140,
        "sell_earnings": 677,
        "commissions": 677,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9302,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1451,
        "ordered_items": 136,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7165,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1588,
        "ordered_items": 115,
        "sell_earnings": 465,
        "commissions": 465,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6323,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1538,
        "ordered_items": 126,
        "sell_earnings": 530,
        "commissions": 530,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5144,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1473,
        "ordered_items": 111,
        "sell_earnings": 563,
        "commissions": 563,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7075,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 1759,
        "ordered_items": 163,
        "sell_earnings": 653,
        "commissions": 653,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7331,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 1694,
        "ordered_items": 148,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9262,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 1644,
        "ordered_items": 159,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8083,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1781,
        "ordered_items": 138,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7241,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1239,
        "ordered_items": 134,
        "sell_earnings": 469,
        "commissions": 469,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6370,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1614,
        "ordered_items": 111,
        "sell_earnings": 437,
        "commissions": 437,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6139,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 1618,
        "ordered_items": 163,
        "sell_earnings": 779,
        "commissions": 779,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8267,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 1993,
        "ordered_items": 140,
        "sell_earnings": 747,
        "commissions": 747,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8036,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1501,
        "ordered_items": 115,
        "sell_earnings": 531,
        "commissions": 531,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5190,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 1731,
        "ordered_items": 159,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9216,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];