export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1400,
        "ordered_items": 125,
        "sell_earnings": 591,
        "commissions": 591,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6655,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1352,
        "ordered_items": 125,
        "sell_earnings": 551,
        "commissions": 551,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7339,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1554,
        "ordered_items": 125,
        "sell_earnings": 564,
        "commissions": 564,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6961,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 1786,
        "ordered_items": 159,
        "sell_earnings": 692,
        "commissions": 692,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7925,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 1988,
        "ordered_items": 159,
        "sell_earnings": 705,
        "commissions": 705,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7547,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 1940,
        "ordered_items": 159,
        "sell_earnings": 665,
        "commissions": 665,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8231,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1264,
        "ordered_items": 120,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6616,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1542,
        "ordered_items": 120,
        "sell_earnings": 597,
        "commissions": 597,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7210,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1266,
        "ordered_items": 126,
        "sell_earnings": 616,
        "commissions": 616,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5384,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 2074,
        "ordered_items": 158,
        "sell_earnings": 640,
        "commissions": 640,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9502,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 1798,
        "ordered_items": 164,
        "sell_earnings": 659,
        "commissions": 659,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7676,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 2076,
        "ordered_items": 164,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8270,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1182,
        "ordered_items": 140,
        "sell_earnings": 525,
        "commissions": 525,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5786,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 2158,
        "ordered_items": 144,
        "sell_earnings": 731,
        "commissions": 731,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9100,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1638,
        "ordered_items": 121,
        "sell_earnings": 571,
        "commissions": 571,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6690,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 1702,
        "ordered_items": 163,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 165,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8196,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1541,
        "ordered_items": 102,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5236,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1337,
        "ordered_items": 118,
        "sell_earnings": 620,
        "commissions": 620,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6364,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1433,
        "ordered_items": 102,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6784,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1245,
        "ordered_items": 116,
        "sell_earnings": 522,
        "commissions": 522,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6346,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 2095,
        "ordered_items": 168,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8540,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 1907,
        "ordered_items": 182,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 164,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8102,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 2003,
        "ordered_items": 166,
        "sell_earnings": 636,
        "commissions": 636,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8522,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 1799,
        "ordered_items": 182,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9650,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1349,
        "ordered_items": 115,
        "sell_earnings": 542,
        "commissions": 542,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5934,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1503,
        "ordered_items": 118,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6153,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 1837,
        "ordered_items": 166,
        "sell_earnings": 776,
        "commissions": 776,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 165,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8733,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 1991,
        "ordered_items": 169,
        "sell_earnings": 714,
        "commissions": 714,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8952,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1457,
        "ordered_items": 142,
        "sell_earnings": 599,
        "commissions": 599,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6329,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 1883,
        "ordered_items": 142,
        "sell_earnings": 657,
        "commissions": 657,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 168,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8557,
        "bonus": 0
    }
];