export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1486,
        "ordered_items": 130,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7119,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1472,
        "ordered_items": 102,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6358,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1161,
        "ordered_items": 100,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6466,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 2071,
        "ordered_items": 174,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7940,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1760,
        "ordered_items": 172,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8048,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 1746,
        "ordered_items": 144,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7287,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1299,
        "ordered_items": 127,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5636,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1207,
        "ordered_items": 102,
        "sell_earnings": 452,
        "commissions": 452,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6180,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1331,
        "ordered_items": 99,
        "sell_earnings": 572,
        "commissions": 572,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6561,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1901,
        "ordered_items": 175,
        "sell_earnings": 644,
        "commissions": 644,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7845,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 2025,
        "ordered_items": 172,
        "sell_earnings": 764,
        "commissions": 764,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8226,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1933,
        "ordered_items": 147,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8770,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1331,
        "ordered_items": 100,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6326,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1901,
        "ordered_items": 174,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8080,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1212,
        "ordered_items": 102,
        "sell_earnings": 599,
        "commissions": 599,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6144,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 2020,
        "ordered_items": 172,
        "sell_earnings": 617,
        "commissions": 617,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8262,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1400,
        "ordered_items": 106,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5885,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1490,
        "ordered_items": 126,
        "sell_earnings": 533,
        "commissions": 533,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6294,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1162,
        "ordered_items": 121,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5214,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1580,
        "ordered_items": 124,
        "sell_earnings": 427,
        "commissions": 427,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5689,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 1652,
        "ordered_items": 150,
        "sell_earnings": 789,
        "commissions": 789,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8717,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 2070,
        "ordered_items": 153,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9192,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 1742,
        "ordered_items": 148,
        "sell_earnings": 683,
        "commissions": 683,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8112,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1832,
        "ordered_items": 168,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8521,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1513,
        "ordered_items": 129,
        "sell_earnings": 519,
        "commissions": 519,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5995,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1197,
        "ordered_items": 112,
        "sell_earnings": 478,
        "commissions": 478,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7182,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 2035,
        "ordered_items": 162,
        "sell_earnings": 738,
        "commissions": 738,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7224,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1719,
        "ordered_items": 145,
        "sell_earnings": 697,
        "commissions": 697,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8411,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1319,
        "ordered_items": 99,
        "sell_earnings": 511,
        "commissions": 511,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6574,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1913,
        "ordered_items": 175,
        "sell_earnings": 705,
        "commissions": 705,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7832,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];