export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1418,
        "ordered_items": 121,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5978,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1263,
        "ordered_items": 124,
        "sell_earnings": 603,
        "commissions": 603,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6449,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1538,
        "ordered_items": 133,
        "sell_earnings": 498,
        "commissions": 498,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6008,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 1694,
        "ordered_items": 141,
        "sell_earnings": 718,
        "commissions": 718,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8398,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 1969,
        "ordered_items": 150,
        "sell_earnings": 613,
        "commissions": 613,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7957,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 1814,
        "ordered_items": 153,
        "sell_earnings": 651,
        "commissions": 651,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8428,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1355,
        "ordered_items": 108,
        "sell_earnings": 440,
        "commissions": 440,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6432,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1359,
        "ordered_items": 134,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7041,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1271,
        "ordered_items": 102,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6855,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 1961,
        "ordered_items": 172,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7551,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 1873,
        "ordered_items": 140,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7365,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 1877,
        "ordered_items": 166,
        "sell_earnings": 776,
        "commissions": 776,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7974,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1509,
        "ordered_items": 113,
        "sell_earnings": 590,
        "commissions": 590,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5968,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 1723,
        "ordered_items": 161,
        "sell_earnings": 626,
        "commissions": 626,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8438,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1521,
        "ordered_items": 105,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5729,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 1711,
        "ordered_items": 169,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8677,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1192,
        "ordered_items": 124,
        "sell_earnings": 444,
        "commissions": 444,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5341,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1571,
        "ordered_items": 100,
        "sell_earnings": 557,
        "commissions": 557,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7037,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1384,
        "ordered_items": 107,
        "sell_earnings": 592,
        "commissions": 592,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5142,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1301,
        "ordered_items": 123,
        "sell_earnings": 548,
        "commissions": 548,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6497,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 1931,
        "ordered_items": 151,
        "sell_earnings": 668,
        "commissions": 668,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7909,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1848,
        "ordered_items": 167,
        "sell_earnings": 624,
        "commissions": 624,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9264,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 1661,
        "ordered_items": 174,
        "sell_earnings": 659,
        "commissions": 659,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7369,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 2040,
        "ordered_items": 150,
        "sell_earnings": 772,
        "commissions": 772,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9065,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1482,
        "ordered_items": 135,
        "sell_earnings": 479,
        "commissions": 479,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6604,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1545,
        "ordered_items": 130,
        "sell_earnings": 510,
        "commissions": 510,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7020,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 1687,
        "ordered_items": 144,
        "sell_earnings": 706,
        "commissions": 706,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7386,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1750,
        "ordered_items": 139,
        "sell_earnings": 737,
        "commissions": 737,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7802,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1188,
        "ordered_items": 134,
        "sell_earnings": 444,
        "commissions": 444,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5902,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 2044,
        "ordered_items": 140,
        "sell_earnings": 772,
        "commissions": 772,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8504,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];