export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1421,
        "ordered_items": 127,
        "sell_earnings": 544,
        "commissions": 544,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5399,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1440,
        "ordered_items": 131,
        "sell_earnings": 584,
        "commissions": 584,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7081,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1132,
        "ordered_items": 102,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6810,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 2100,
        "ordered_items": 172,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7596,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 1792,
        "ordered_items": 143,
        "sell_earnings": 632,
        "commissions": 632,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7325,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 1811,
        "ordered_items": 147,
        "sell_earnings": 672,
        "commissions": 672,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9007,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1524,
        "ordered_items": 134,
        "sell_earnings": 490,
        "commissions": 490,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5968,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1229,
        "ordered_items": 107,
        "sell_earnings": 489,
        "commissions": 489,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5693,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1525,
        "ordered_items": 104,
        "sell_earnings": 555,
        "commissions": 555,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5633,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 1707,
        "ordered_items": 170,
        "sell_earnings": 661,
        "commissions": 661,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8773,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 2003,
        "ordered_items": 167,
        "sell_earnings": 727,
        "commissions": 727,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8713,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 1708,
        "ordered_items": 140,
        "sell_earnings": 726,
        "commissions": 726,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8438,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1233,
        "ordered_items": 113,
        "sell_earnings": 530,
        "commissions": 530,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6231,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 1999,
        "ordered_items": 161,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8175,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1559,
        "ordered_items": 135,
        "sell_earnings": 521,
        "commissions": 521,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6286,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 1673,
        "ordered_items": 139,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8120,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1290,
        "ordered_items": 125,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5625,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1439,
        "ordered_items": 131,
        "sell_earnings": 553,
        "commissions": 553,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6677,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1178,
        "ordered_items": 118,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5861,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1568,
        "ordered_items": 129,
        "sell_earnings": 514,
        "commissions": 514,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6543,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 1664,
        "ordered_items": 145,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7863,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 2054,
        "ordered_items": 156,
        "sell_earnings": 721,
        "commissions": 721,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8545,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 1793,
        "ordered_items": 143,
        "sell_earnings": 663,
        "commissions": 663,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7729,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 1942,
        "ordered_items": 149,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8781,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1225,
        "ordered_items": 122,
        "sell_earnings": 488,
        "commissions": 488,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5313,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1384,
        "ordered_items": 136,
        "sell_earnings": 607,
        "commissions": 607,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6223,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 1848,
        "ordered_items": 138,
        "sell_earnings": 609,
        "commissions": 609,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8183,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 2007,
        "ordered_items": 152,
        "sell_earnings": 728,
        "commissions": 728,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9093,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1275,
        "ordered_items": 102,
        "sell_earnings": 438,
        "commissions": 438,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7000,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 1957,
        "ordered_items": 172,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7406,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];