export let mar = [
    {
        "month": "Mar",
        "day": "01",
        "clicks": 1174,
        "ordered_items": 109,
        "sell_earnings": 435,
        "commissions": 435,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6379,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "02",
        "clicks": 1178,
        "ordered_items": 126,
        "sell_earnings": 536,
        "commissions": 536,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5474,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "03",
        "clicks": 1581,
        "ordered_items": 104,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6637,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "04",
        "clicks": 1651,
        "ordered_items": 170,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7769,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "05",
        "clicks": 2054,
        "ordered_items": 148,
        "sell_earnings": 680,
        "commissions": 680,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8932,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "06",
        "clicks": 2058,
        "ordered_items": 165,
        "sell_earnings": 781,
        "commissions": 781,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8027,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "07",
        "clicks": 1359,
        "ordered_items": 100,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6435,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "08",
        "clicks": 1144,
        "ordered_items": 103,
        "sell_earnings": 549,
        "commissions": 549,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5863,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "09",
        "clicks": 1223,
        "ordered_items": 130,
        "sell_earnings": 562,
        "commissions": 562,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5129,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "10",
        "clicks": 2009,
        "ordered_items": 144,
        "sell_earnings": 654,
        "commissions": 654,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9277,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "11",
        "clicks": 2088,
        "ordered_items": 171,
        "sell_earnings": 667,
        "commissions": 667,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8543,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "12",
        "clicks": 1873,
        "ordered_items": 174,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7971,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "13",
        "clicks": 1596,
        "ordered_items": 122,
        "sell_earnings": 573,
        "commissions": 573,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5422,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "14",
        "clicks": 1636,
        "ordered_items": 152,
        "sell_earnings": 643,
        "commissions": 643,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8984,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "15",
        "clicks": 1406,
        "ordered_items": 126,
        "sell_earnings": 592,
        "commissions": 592,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5090,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "16",
        "clicks": 1826,
        "ordered_items": 148,
        "sell_earnings": 624,
        "commissions": 624,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9316,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "17",
        "clicks": 1600,
        "ordered_items": 104,
        "sell_earnings": 487,
        "commissions": 487,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7164,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "18",
        "clicks": 1397,
        "ordered_items": 113,
        "sell_earnings": 455,
        "commissions": 455,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5283,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "19",
        "clicks": 1287,
        "ordered_items": 101,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5146,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "20",
        "clicks": 1183,
        "ordered_items": 105,
        "sell_earnings": 530,
        "commissions": 530,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6159,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "21",
        "clicks": 2049,
        "ordered_items": 169,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8247,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "22",
        "clicks": 1945,
        "ordered_items": 173,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9260,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "23",
        "clicks": 1835,
        "ordered_items": 161,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9123,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "24",
        "clicks": 1632,
        "ordered_items": 170,
        "sell_earnings": 729,
        "commissions": 729,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7242,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "25",
        "clicks": 1552,
        "ordered_items": 134,
        "sell_earnings": 602,
        "commissions": 602,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7009,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "26",
        "clicks": 1596,
        "ordered_items": 104,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6361,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "27",
        "clicks": 1636,
        "ordered_items": 170,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8045,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "28",
        "clicks": 1680,
        "ordered_items": 140,
        "sell_earnings": 614,
        "commissions": 614,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7397,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "29",
        "clicks": 1246,
        "ordered_items": 110,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6371,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "30",
        "clicks": 1986,
        "ordered_items": 164,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8035,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];