export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1464,
        "ordered_items": 112,
        "sell_earnings": 475,
        "commissions": 475,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6443,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1260,
        "ordered_items": 104,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6032,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1455,
        "ordered_items": 133,
        "sell_earnings": 440,
        "commissions": 440,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6894,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 1777,
        "ordered_items": 141,
        "sell_earnings": 776,
        "commissions": 776,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7512,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 1972,
        "ordered_items": 170,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8374,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 1768,
        "ordered_items": 162,
        "sell_earnings": 741,
        "commissions": 741,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7963,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1147,
        "ordered_items": 115,
        "sell_earnings": 573,
        "commissions": 573,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6606,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1148,
        "ordered_items": 104,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5590,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1380,
        "ordered_items": 123,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5701,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 1852,
        "ordered_items": 151,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8705,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 2084,
        "ordered_items": 170,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8816,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 2085,
        "ordered_items": 159,
        "sell_earnings": 643,
        "commissions": 643,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7800,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1428,
        "ordered_items": 121,
        "sell_earnings": 552,
        "commissions": 552,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6597,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 1804,
        "ordered_items": 153,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7809,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1280,
        "ordered_items": 106,
        "sell_earnings": 445,
        "commissions": 445,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5774,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 1952,
        "ordered_items": 168,
        "sell_earnings": 771,
        "commissions": 771,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8632,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1442,
        "ordered_items": 132,
        "sell_earnings": 575,
        "commissions": 575,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6724,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1558,
        "ordered_items": 124,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5929,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1516,
        "ordered_items": 129,
        "sell_earnings": 516,
        "commissions": 516,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5080,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1244,
        "ordered_items": 120,
        "sell_earnings": 524,
        "commissions": 524,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5192,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 1988,
        "ordered_items": 154,
        "sell_earnings": 692,
        "commissions": 692,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9214,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 1716,
        "ordered_items": 145,
        "sell_earnings": 700,
        "commissions": 700,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9326,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 1674,
        "ordered_items": 150,
        "sell_earnings": 651,
        "commissions": 651,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8477,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1790,
        "ordered_items": 142,
        "sell_earnings": 641,
        "commissions": 641,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7682,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1209,
        "ordered_items": 131,
        "sell_earnings": 492,
        "commissions": 492,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6372,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1155,
        "ordered_items": 120,
        "sell_earnings": 503,
        "commissions": 503,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6190,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 2077,
        "ordered_items": 154,
        "sell_earnings": 713,
        "commissions": 713,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8216,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 2023,
        "ordered_items": 143,
        "sell_earnings": 724,
        "commissions": 724,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8034,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1427,
        "ordered_items": 106,
        "sell_earnings": 560,
        "commissions": 560,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5324,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 1805,
        "ordered_items": 168,
        "sell_earnings": 656,
        "commissions": 656,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9082,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];