export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1541,
        "ordered_items": 142,
        "sell_earnings": 530,
        "commissions": 530,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5319,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1337,
        "ordered_items": 105,
        "sell_earnings": 590,
        "commissions": 590,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7397,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1594,
        "ordered_items": 121,
        "sell_earnings": 447,
        "commissions": 447,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6818,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 1746,
        "ordered_items": 163,
        "sell_earnings": 809,
        "commissions": 809,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8068,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 2003,
        "ordered_items": 179,
        "sell_earnings": 666,
        "commissions": 666,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7489,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 1799,
        "ordered_items": 142,
        "sell_earnings": 726,
        "commissions": 726,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9567,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1195,
        "ordered_items": 111,
        "sell_earnings": 613,
        "commissions": 613,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7432,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1510,
        "ordered_items": 114,
        "sell_earnings": 505,
        "commissions": 505,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6251,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1505,
        "ordered_items": 136,
        "sell_earnings": 592,
        "commissions": 592,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7269,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 1835,
        "ordered_items": 148,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7617,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 1830,
        "ordered_items": 170,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8635,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 2145,
        "ordered_items": 173,
        "sell_earnings": 643,
        "commissions": 643,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7454,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1320,
        "ordered_items": 109,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7235,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 2020,
        "ordered_items": 175,
        "sell_earnings": 728,
        "commissions": 728,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7651,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1584,
        "ordered_items": 135,
        "sell_earnings": 571,
        "commissions": 571,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5545,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 1756,
        "ordered_items": 149,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9341,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1190,
        "ordered_items": 107,
        "sell_earnings": 498,
        "commissions": 498,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6551,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1670,
        "ordered_items": 126,
        "sell_earnings": 570,
        "commissions": 570,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6123,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1209,
        "ordered_items": 119,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7055,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1197,
        "ordered_items": 130,
        "sell_earnings": 556,
        "commissions": 556,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7316,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 2143,
        "ordered_items": 154,
        "sell_earnings": 700,
        "commissions": 700,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7570,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 2131,
        "ordered_items": 165,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7831,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 1670,
        "ordered_items": 158,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8763,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 2150,
        "ordered_items": 177,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8335,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1549,
        "ordered_items": 119,
        "sell_earnings": 579,
        "commissions": 579,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7204,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1535,
        "ordered_items": 128,
        "sell_earnings": 549,
        "commissions": 549,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7141,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 1805,
        "ordered_items": 156,
        "sell_earnings": 707,
        "commissions": 707,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7745,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 1791,
        "ordered_items": 165,
        "sell_earnings": 677,
        "commissions": 677,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7682,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1461,
        "ordered_items": 128,
        "sell_earnings": 564,
        "commissions": 564,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6965,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 1879,
        "ordered_items": 156,
        "sell_earnings": 692,
        "commissions": 692,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7921,
        "bonus": 0
    }
];