export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1384,
        "ordered_items": 115,
        "sell_earnings": 529,
        "commissions": 529,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5986,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1335,
        "ordered_items": 115,
        "sell_earnings": 541,
        "commissions": 541,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5389,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1210,
        "ordered_items": 110,
        "sell_earnings": 539,
        "commissions": 539,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6804,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 2022,
        "ordered_items": 164,
        "sell_earnings": 677,
        "commissions": 677,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7602,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1897,
        "ordered_items": 159,
        "sell_earnings": 675,
        "commissions": 675,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9017,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 1848,
        "ordered_items": 159,
        "sell_earnings": 687,
        "commissions": 687,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8420,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1388,
        "ordered_items": 117,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5969,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1353,
        "ordered_items": 113,
        "sell_earnings": 447,
        "commissions": 447,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6703,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1374,
        "ordered_items": 133,
        "sell_earnings": 531,
        "commissions": 531,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5322,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1858,
        "ordered_items": 141,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9084,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 1879,
        "ordered_items": 161,
        "sell_earnings": 769,
        "commissions": 769,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7703,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1844,
        "ordered_items": 157,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8437,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1254,
        "ordered_items": 107,
        "sell_earnings": 484,
        "commissions": 484,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6926,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1978,
        "ordered_items": 167,
        "sell_earnings": 732,
        "commissions": 732,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7480,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1278,
        "ordered_items": 121,
        "sell_earnings": 438,
        "commissions": 438,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6063,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1954,
        "ordered_items": 153,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8343,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1565,
        "ordered_items": 118,
        "sell_earnings": 558,
        "commissions": 558,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5657,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1534,
        "ordered_items": 128,
        "sell_earnings": 470,
        "commissions": 470,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6048,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1207,
        "ordered_items": 113,
        "sell_earnings": 474,
        "commissions": 474,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5293,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1139,
        "ordered_items": 123,
        "sell_earnings": 503,
        "commissions": 503,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6434,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 2093,
        "ordered_items": 151,
        "sell_earnings": 713,
        "commissions": 713,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7972,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 2025,
        "ordered_items": 161,
        "sell_earnings": 742,
        "commissions": 742,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9113,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 1698,
        "ordered_items": 146,
        "sell_earnings": 746,
        "commissions": 746,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8358,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1667,
        "ordered_items": 156,
        "sell_earnings": 658,
        "commissions": 658,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8749,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1366,
        "ordered_items": 136,
        "sell_earnings": 511,
        "commissions": 511,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6573,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1515,
        "ordered_items": 106,
        "sell_earnings": 546,
        "commissions": 546,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5536,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1717,
        "ordered_items": 168,
        "sell_earnings": 670,
        "commissions": 670,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8870,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1866,
        "ordered_items": 138,
        "sell_earnings": 705,
        "commissions": 705,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7833,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1415,
        "ordered_items": 110,
        "sell_earnings": 526,
        "commissions": 526,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5332,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1817,
        "ordered_items": 164,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9074,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];