export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1268,
        "ordered_items": 122,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6676,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1441,
        "ordered_items": 97,
        "sell_earnings": 559,
        "commissions": 559,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6937,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1329,
        "ordered_items": 103,
        "sell_earnings": 431,
        "commissions": 431,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6563,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 1903,
        "ordered_items": 171,
        "sell_earnings": 785,
        "commissions": 785,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7843,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 1791,
        "ordered_items": 177,
        "sell_earnings": 657,
        "commissions": 657,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7469,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 1964,
        "ordered_items": 152,
        "sell_earnings": 720,
        "commissions": 720,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7730,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1615,
        "ordered_items": 118,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6278,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1475,
        "ordered_items": 119,
        "sell_earnings": 475,
        "commissions": 475,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5496,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1353,
        "ordered_items": 106,
        "sell_earnings": 603,
        "commissions": 603,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6275,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 1879,
        "ordered_items": 168,
        "sell_earnings": 613,
        "commissions": 613,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8131,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1757,
        "ordered_items": 155,
        "sell_earnings": 741,
        "commissions": 741,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8910,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 1617,
        "ordered_items": 156,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8128,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1561,
        "ordered_items": 132,
        "sell_earnings": 607,
        "commissions": 607,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7182,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 1671,
        "ordered_items": 142,
        "sell_earnings": 609,
        "commissions": 609,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7224,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1463,
        "ordered_items": 98,
        "sell_earnings": 600,
        "commissions": 600,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5227,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 1769,
        "ordered_items": 176,
        "sell_earnings": 616,
        "commissions": 616,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9179,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1588,
        "ordered_items": 104,
        "sell_earnings": 526,
        "commissions": 526,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6197,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1487,
        "ordered_items": 131,
        "sell_earnings": 546,
        "commissions": 546,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6736,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1491,
        "ordered_items": 102,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5830,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1551,
        "ordered_items": 126,
        "sell_earnings": 531,
        "commissions": 531,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6088,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 1681,
        "ordered_items": 148,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8318,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 1741,
        "ordered_items": 172,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8576,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 1745,
        "ordered_items": 143,
        "sell_earnings": 670,
        "commissions": 670,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7670,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 1644,
        "ordered_items": 170,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8209,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1596,
        "ordered_items": 117,
        "sell_earnings": 442,
        "commissions": 442,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6116,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1363,
        "ordered_items": 127,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6099,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1869,
        "ordered_items": 147,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8307,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 1636,
        "ordered_items": 157,
        "sell_earnings": 774,
        "commissions": 774,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8290,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1214,
        "ordered_items": 99,
        "sell_earnings": 483,
        "commissions": 483,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5231,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 2018,
        "ordered_items": 175,
        "sell_earnings": 733,
        "commissions": 733,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9175,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];