export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1388,
        "ordered_items": 111,
        "sell_earnings": 475,
        "commissions": 475,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6099,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1179,
        "ordered_items": 103,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6145,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1433,
        "ordered_items": 110,
        "sell_earnings": 452,
        "commissions": 452,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5728,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 1799,
        "ordered_items": 164,
        "sell_earnings": 764,
        "commissions": 764,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8678,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 2053,
        "ordered_items": 171,
        "sell_earnings": 753,
        "commissions": 753,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8261,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 1844,
        "ordered_items": 163,
        "sell_earnings": 741,
        "commissions": 741,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8307,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1152,
        "ordered_items": 123,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5611,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1537,
        "ordered_items": 122,
        "sell_earnings": 533,
        "commissions": 533,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5896,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1227,
        "ordered_items": 127,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5741,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 2005,
        "ordered_items": 147,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8665,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 1695,
        "ordered_items": 152,
        "sell_earnings": 683,
        "commissions": 683,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8510,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 2080,
        "ordered_items": 151,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8795,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1137,
        "ordered_items": 113,
        "sell_earnings": 468,
        "commissions": 468,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7122,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 2095,
        "ordered_items": 161,
        "sell_earnings": 748,
        "commissions": 748,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7284,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1532,
        "ordered_items": 104,
        "sell_earnings": 588,
        "commissions": 588,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6501,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 1700,
        "ordered_items": 170,
        "sell_earnings": 628,
        "commissions": 628,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7905,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1189,
        "ordered_items": 130,
        "sell_earnings": 505,
        "commissions": 505,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5150,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1304,
        "ordered_items": 114,
        "sell_earnings": 538,
        "commissions": 538,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6471,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1246,
        "ordered_items": 111,
        "sell_earnings": 439,
        "commissions": 439,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5997,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1355,
        "ordered_items": 115,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5831,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 1877,
        "ordered_items": 159,
        "sell_earnings": 725,
        "commissions": 725,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8575,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1986,
        "ordered_items": 163,
        "sell_earnings": 777,
        "commissions": 777,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8409,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 1928,
        "ordered_items": 160,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7935,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 2043,
        "ordered_items": 144,
        "sell_earnings": 711,
        "commissions": 711,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9256,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1449,
        "ordered_items": 108,
        "sell_earnings": 478,
        "commissions": 478,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6837,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1470,
        "ordered_items": 113,
        "sell_earnings": 535,
        "commissions": 535,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6120,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 1762,
        "ordered_items": 161,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8286,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1783,
        "ordered_items": 166,
        "sell_earnings": 738,
        "commissions": 738,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7569,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1467,
        "ordered_items": 123,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5420,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 1765,
        "ordered_items": 151,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8986,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];