export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1333,
        "ordered_items": 112,
        "sell_earnings": 579,
        "commissions": 579,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6065,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1322,
        "ordered_items": 116,
        "sell_earnings": 535,
        "commissions": 535,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6670,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1398,
        "ordered_items": 103,
        "sell_earnings": 505,
        "commissions": 505,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5682,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 1942,
        "ordered_items": 181,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 166,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9204,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 2018,
        "ordered_items": 168,
        "sell_earnings": 721,
        "commissions": 721,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8216,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 2007,
        "ordered_items": 172,
        "sell_earnings": 677,
        "commissions": 677,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8821,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1339,
        "ordered_items": 141,
        "sell_earnings": 563,
        "commissions": 563,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7131,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1640,
        "ordered_items": 116,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6223,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1613,
        "ordered_items": 139,
        "sell_earnings": 611,
        "commissions": 611,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7332,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 1727,
        "ordered_items": 145,
        "sell_earnings": 645,
        "commissions": 645,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7554,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 1700,
        "ordered_items": 168,
        "sell_earnings": 650,
        "commissions": 650,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8663,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 2001,
        "ordered_items": 143,
        "sell_earnings": 693,
        "commissions": 693,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7755,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1188,
        "ordered_items": 124,
        "sell_earnings": 554,
        "commissions": 554,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7138,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 2152,
        "ordered_items": 160,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7748,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1252,
        "ordered_items": 133,
        "sell_earnings": 555,
        "commissions": 555,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 129,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7215,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 2088,
        "ordered_items": 151,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7671,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1383,
        "ordered_items": 119,
        "sell_earnings": 467,
        "commissions": 467,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6990,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1615,
        "ordered_items": 137,
        "sell_earnings": 461,
        "commissions": 461,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6652,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1508,
        "ordered_items": 109,
        "sell_earnings": 473,
        "commissions": 473,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6874,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1431,
        "ordered_items": 107,
        "sell_earnings": 448,
        "commissions": 448,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7029,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 1909,
        "ordered_items": 177,
        "sell_earnings": 808,
        "commissions": 808,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7857,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 1832,
        "ordered_items": 175,
        "sell_earnings": 783,
        "commissions": 783,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 169,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8012,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 1725,
        "ordered_items": 147,
        "sell_earnings": 795,
        "commissions": 795,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8234,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 1957,
        "ordered_items": 165,
        "sell_earnings": 789,
        "commissions": 789,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7896,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1315,
        "ordered_items": 106,
        "sell_earnings": 447,
        "commissions": 447,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7229,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1611,
        "ordered_items": 126,
        "sell_earnings": 511,
        "commissions": 511,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6801,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 1729,
        "ordered_items": 158,
        "sell_earnings": 745,
        "commissions": 745,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8085,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 2025,
        "ordered_items": 178,
        "sell_earnings": 809,
        "commissions": 809,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7657,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1452,
        "ordered_items": 105,
        "sell_earnings": 524,
        "commissions": 524,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7021,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 1888,
        "ordered_items": 179,
        "sell_earnings": 732,
        "commissions": 732,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7865,
        "bonus": 0
    }
];