export let mar = [
    {
        "month": "Mar",
        "day": "01",
        "clicks": 1601,
        "ordered_items": 124,
        "sell_earnings": 541,
        "commissions": 541,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5063,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "02",
        "clicks": 1296,
        "ordered_items": 128,
        "sell_earnings": 579,
        "commissions": 579,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5212,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "03",
        "clicks": 1302,
        "ordered_items": 101,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5706,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "04",
        "clicks": 1930,
        "ordered_items": 173,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8700,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "05",
        "clicks": 1936,
        "ordered_items": 146,
        "sell_earnings": 637,
        "commissions": 637,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9194,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "06",
        "clicks": 1631,
        "ordered_items": 150,
        "sell_earnings": 675,
        "commissions": 675,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9343,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "07",
        "clicks": 1295,
        "ordered_items": 112,
        "sell_earnings": 461,
        "commissions": 461,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6437,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "08",
        "clicks": 1376,
        "ordered_items": 102,
        "sell_earnings": 551,
        "commissions": 551,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6492,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "09",
        "clicks": 1333,
        "ordered_items": 133,
        "sell_earnings": 437,
        "commissions": 437,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6519,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "10",
        "clicks": 1899,
        "ordered_items": 141,
        "sell_earnings": 779,
        "commissions": 779,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7887,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "11",
        "clicks": 1856,
        "ordered_items": 172,
        "sell_earnings": 665,
        "commissions": 665,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7914,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "12",
        "clicks": 1937,
        "ordered_items": 162,
        "sell_earnings": 755,
        "commissions": 755,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7969,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "13",
        "clicks": 1166,
        "ordered_items": 131,
        "sell_earnings": 518,
        "commissions": 518,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6965,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "14",
        "clicks": 2066,
        "ordered_items": 143,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7441,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "15",
        "clicks": 1519,
        "ordered_items": 112,
        "sell_earnings": 462,
        "commissions": 462,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6482,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "16",
        "clicks": 1713,
        "ordered_items": 162,
        "sell_earnings": 754,
        "commissions": 754,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7924,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "17",
        "clicks": 1148,
        "ordered_items": 115,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6023,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "18",
        "clicks": 1354,
        "ordered_items": 109,
        "sell_earnings": 535,
        "commissions": 535,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5240,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "19",
        "clicks": 1586,
        "ordered_items": 115,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6220,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "20",
        "clicks": 1156,
        "ordered_items": 103,
        "sell_earnings": 439,
        "commissions": 439,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6809,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "21",
        "clicks": 2076,
        "ordered_items": 171,
        "sell_earnings": 777,
        "commissions": 777,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7597,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "22",
        "clicks": 1646,
        "ordered_items": 159,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8186,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "23",
        "clicks": 1878,
        "ordered_items": 165,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9166,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "24",
        "clicks": 2084,
        "ordered_items": 159,
        "sell_earnings": 651,
        "commissions": 651,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8383,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "25",
        "clicks": 1174,
        "ordered_items": 99,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6479,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "26",
        "clicks": 1172,
        "ordered_items": 103,
        "sell_earnings": 572,
        "commissions": 572,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6844,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "27",
        "clicks": 2060,
        "ordered_items": 171,
        "sell_earnings": 644,
        "commissions": 644,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7562,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "28",
        "clicks": 2058,
        "ordered_items": 175,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7927,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "29",
        "clicks": 1363,
        "ordered_items": 122,
        "sell_earnings": 473,
        "commissions": 473,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6244,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "30",
        "clicks": 1869,
        "ordered_items": 152,
        "sell_earnings": 743,
        "commissions": 743,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8162,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];