export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1194,
        "ordered_items": 104,
        "sell_earnings": 481,
        "commissions": 481,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6326,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1272,
        "ordered_items": 117,
        "sell_earnings": 443,
        "commissions": 443,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6729,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1560,
        "ordered_items": 120,
        "sell_earnings": 471,
        "commissions": 471,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6914,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 1672,
        "ordered_items": 154,
        "sell_earnings": 745,
        "commissions": 745,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7492,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1960,
        "ordered_items": 157,
        "sell_earnings": 773,
        "commissions": 773,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7677,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 2038,
        "ordered_items": 170,
        "sell_earnings": 735,
        "commissions": 735,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8080,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1224,
        "ordered_items": 104,
        "sell_earnings": 569,
        "commissions": 569,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6208,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1491,
        "ordered_items": 134,
        "sell_earnings": 437,
        "commissions": 437,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5119,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1161,
        "ordered_items": 97,
        "sell_earnings": 486,
        "commissions": 486,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5468,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 2071,
        "ordered_items": 177,
        "sell_earnings": 730,
        "commissions": 730,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8938,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 1741,
        "ordered_items": 140,
        "sell_earnings": 779,
        "commissions": 779,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9287,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 2008,
        "ordered_items": 170,
        "sell_earnings": 647,
        "commissions": 647,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8198,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1527,
        "ordered_items": 124,
        "sell_earnings": 475,
        "commissions": 475,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6643,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1705,
        "ordered_items": 150,
        "sell_earnings": 741,
        "commissions": 741,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7763,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1263,
        "ordered_items": 109,
        "sell_earnings": 564,
        "commissions": 564,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5609,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1969,
        "ordered_items": 165,
        "sell_earnings": 652,
        "commissions": 652,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8797,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1527,
        "ordered_items": 118,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5248,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1383,
        "ordered_items": 105,
        "sell_earnings": 516,
        "commissions": 516,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6329,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1476,
        "ordered_items": 128,
        "sell_earnings": 506,
        "commissions": 506,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6110,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1366,
        "ordered_items": 124,
        "sell_earnings": 436,
        "commissions": 436,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6426,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 1866,
        "ordered_items": 150,
        "sell_earnings": 780,
        "commissions": 780,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7980,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1756,
        "ordered_items": 146,
        "sell_earnings": 710,
        "commissions": 710,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8296,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 1849,
        "ordered_items": 169,
        "sell_earnings": 700,
        "commissions": 700,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8077,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1705,
        "ordered_items": 156,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9158,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1439,
        "ordered_items": 108,
        "sell_earnings": 532,
        "commissions": 532,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6347,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1298,
        "ordered_items": 106,
        "sell_earnings": 554,
        "commissions": 554,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6171,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1934,
        "ordered_items": 168,
        "sell_earnings": 662,
        "commissions": 662,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8235,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1793,
        "ordered_items": 166,
        "sell_earnings": 684,
        "commissions": 684,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8059,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1593,
        "ordered_items": 102,
        "sell_earnings": 549,
        "commissions": 549,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5556,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1639,
        "ordered_items": 172,
        "sell_earnings": 667,
        "commissions": 667,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8850,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];