export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 1506,
        "ordered_items": 136,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6054,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 1433,
        "ordered_items": 101,
        "sell_earnings": 599,
        "commissions": 599,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6895,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 1424,
        "ordered_items": 118,
        "sell_earnings": 553,
        "commissions": 553,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6584,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 1916,
        "ordered_items": 166,
        "sell_earnings": 703,
        "commissions": 703,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8302,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 1907,
        "ordered_items": 183,
        "sell_earnings": 657,
        "commissions": 657,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7991,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 1834,
        "ordered_items": 148,
        "sell_earnings": 691,
        "commissions": 691,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8832,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 1507,
        "ordered_items": 121,
        "sell_earnings": 490,
        "commissions": 490,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6260,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 1296,
        "ordered_items": 111,
        "sell_earnings": 609,
        "commissions": 609,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6810,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 1641,
        "ordered_items": 108,
        "sell_earnings": 533,
        "commissions": 533,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7335,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 1699,
        "ordered_items": 176,
        "sell_earnings": 723,
        "commissions": 723,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7551,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 2044,
        "ordered_items": 173,
        "sell_earnings": 647,
        "commissions": 647,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8076,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 1833,
        "ordered_items": 163,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8626,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 1613,
        "ordered_items": 141,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7183,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 1727,
        "ordered_items": 143,
        "sell_earnings": 658,
        "commissions": 658,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7703,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 1473,
        "ordered_items": 114,
        "sell_earnings": 486,
        "commissions": 486,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5540,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 1867,
        "ordered_items": 170,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9346,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 1638,
        "ordered_items": 106,
        "sell_earnings": 529,
        "commissions": 529,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5668,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 1360,
        "ordered_items": 109,
        "sell_earnings": 519,
        "commissions": 519,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5745,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 1389,
        "ordered_items": 109,
        "sell_earnings": 591,
        "commissions": 591,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6849,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 1294,
        "ordered_items": 110,
        "sell_earnings": 615,
        "commissions": 615,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6885,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 2046,
        "ordered_items": 174,
        "sell_earnings": 641,
        "commissions": 641,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8001,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 1951,
        "ordered_items": 175,
        "sell_earnings": 665,
        "commissions": 665,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8037,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 1980,
        "ordered_items": 175,
        "sell_earnings": 737,
        "commissions": 737,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9141,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 1702,
        "ordered_items": 178,
        "sell_earnings": 727,
        "commissions": 727,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9218,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 1306,
        "ordered_items": 119,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5735,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 1412,
        "ordered_items": 142,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5548,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 1928,
        "ordered_items": 142,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9338,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 2034,
        "ordered_items": 165,
        "sell_earnings": 644,
        "commissions": 644,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9151,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 1393,
        "ordered_items": 121,
        "sell_earnings": 542,
        "commissions": 542,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6710,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 1947,
        "ordered_items": 163,
        "sell_earnings": 714,
        "commissions": 714,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 166,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8176,
        "bonus": 2
    }
];