export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1255,
        "ordered_items": 116,
        "sell_earnings": 603,
        "commissions": 603,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6355,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1448,
        "ordered_items": 110,
        "sell_earnings": 595,
        "commissions": 595,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5265,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1369,
        "ordered_items": 131,
        "sell_earnings": 594,
        "commissions": 594,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5405,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 1863,
        "ordered_items": 143,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9001,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 1784,
        "ordered_items": 164,
        "sell_earnings": 621,
        "commissions": 621,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9141,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 1977,
        "ordered_items": 158,
        "sell_earnings": 613,
        "commissions": 613,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8051,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1445,
        "ordered_items": 118,
        "sell_earnings": 440,
        "commissions": 440,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5934,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1473,
        "ordered_items": 127,
        "sell_earnings": 478,
        "commissions": 478,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5106,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1424,
        "ordered_items": 120,
        "sell_earnings": 583,
        "commissions": 583,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5102,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 1808,
        "ordered_items": 154,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9304,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 1759,
        "ordered_items": 147,
        "sell_earnings": 738,
        "commissions": 738,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9300,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 1787,
        "ordered_items": 156,
        "sell_earnings": 776,
        "commissions": 776,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8472,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1210,
        "ordered_items": 126,
        "sell_earnings": 562,
        "commissions": 562,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6970,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 2022,
        "ordered_items": 148,
        "sell_earnings": 654,
        "commissions": 654,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7436,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1539,
        "ordered_items": 98,
        "sell_earnings": 603,
        "commissions": 603,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6782,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 1693,
        "ordered_items": 176,
        "sell_earnings": 613,
        "commissions": 613,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7624,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1473,
        "ordered_items": 131,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5673,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1516,
        "ordered_items": 103,
        "sell_earnings": 552,
        "commissions": 552,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5931,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1208,
        "ordered_items": 98,
        "sell_earnings": 607,
        "commissions": 607,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6952,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1196,
        "ordered_items": 131,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5933,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 2036,
        "ordered_items": 143,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8473,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 2024,
        "ordered_items": 176,
        "sell_earnings": 609,
        "commissions": 609,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7454,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 1716,
        "ordered_items": 171,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8475,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 1759,
        "ordered_items": 143,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8733,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1602,
        "ordered_items": 106,
        "sell_earnings": 523,
        "commissions": 523,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6837,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1415,
        "ordered_items": 112,
        "sell_earnings": 546,
        "commissions": 546,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6833,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 1817,
        "ordered_items": 162,
        "sell_earnings": 670,
        "commissions": 670,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7573,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 1630,
        "ordered_items": 168,
        "sell_earnings": 693,
        "commissions": 693,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7569,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1171,
        "ordered_items": 120,
        "sell_earnings": 465,
        "commissions": 465,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5117,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 2061,
        "ordered_items": 154,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9289,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];