export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1296,
        "ordered_items": 106,
        "sell_earnings": 539,
        "commissions": 539,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5619,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1265,
        "ordered_items": 100,
        "sell_earnings": 490,
        "commissions": 490,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6614,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1195,
        "ordered_items": 129,
        "sell_earnings": 462,
        "commissions": 462,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6649,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 2145,
        "ordered_items": 155,
        "sell_earnings": 794,
        "commissions": 794,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 169,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8237,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 2075,
        "ordered_items": 184,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8272,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 2044,
        "ordered_items": 178,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9267,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1659,
        "ordered_items": 124,
        "sell_earnings": 601,
        "commissions": 601,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6352,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1409,
        "ordered_items": 139,
        "sell_earnings": 627,
        "commissions": 627,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6458,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1562,
        "ordered_items": 105,
        "sell_earnings": 541,
        "commissions": 541,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6444,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 1778,
        "ordered_items": 179,
        "sell_earnings": 715,
        "commissions": 715,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8442,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 1931,
        "ordered_items": 145,
        "sell_earnings": 629,
        "commissions": 629,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 166,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8428,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 1681,
        "ordered_items": 160,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8534,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1216,
        "ordered_items": 110,
        "sell_earnings": 564,
        "commissions": 564,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5396,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 2124,
        "ordered_items": 174,
        "sell_earnings": 692,
        "commissions": 692,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9490,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1330,
        "ordered_items": 139,
        "sell_earnings": 524,
        "commissions": 524,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7116,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 2010,
        "ordered_items": 145,
        "sell_earnings": 732,
        "commissions": 732,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7770,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1407,
        "ordered_items": 133,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5464,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1318,
        "ordered_items": 112,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5287,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1215,
        "ordered_items": 110,
        "sell_earnings": 590,
        "commissions": 590,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5388,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1505,
        "ordered_items": 141,
        "sell_earnings": 609,
        "commissions": 609,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6438,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 1835,
        "ordered_items": 143,
        "sell_earnings": 647,
        "commissions": 647,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8448,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 2125,
        "ordered_items": 174,
        "sell_earnings": 666,
        "commissions": 666,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 167,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9498,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 2022,
        "ordered_items": 172,
        "sell_earnings": 756,
        "commissions": 756,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9599,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 1933,
        "ordered_items": 151,
        "sell_earnings": 776,
        "commissions": 776,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9422,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1520,
        "ordered_items": 112,
        "sell_earnings": 465,
        "commissions": 465,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 128,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6943,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1277,
        "ordered_items": 110,
        "sell_earnings": 509,
        "commissions": 509,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6191,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 2063,
        "ordered_items": 174,
        "sell_earnings": 747,
        "commissions": 747,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8695,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 1820,
        "ordered_items": 172,
        "sell_earnings": 791,
        "commissions": 791,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7943,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1564,
        "ordered_items": 121,
        "sell_earnings": 575,
        "commissions": 575,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5597,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 1776,
        "ordered_items": 163,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 165,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9289,
        "bonus": 2
    }
];