export let mar = [
    {
        "month": "Mar",
        "day": "01",
        "clicks": 1269,
        "ordered_items": 114,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6804,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "02",
        "clicks": 1582,
        "ordered_items": 98,
        "sell_earnings": 440,
        "commissions": 440,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5383,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "03",
        "clicks": 1156,
        "ordered_items": 99,
        "sell_earnings": 605,
        "commissions": 605,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5238,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "04",
        "clicks": 2076,
        "ordered_items": 175,
        "sell_earnings": 611,
        "commissions": 611,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9168,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "05",
        "clicks": 1650,
        "ordered_items": 176,
        "sell_earnings": 776,
        "commissions": 776,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9023,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "06",
        "clicks": 1963,
        "ordered_items": 160,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7602,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "07",
        "clicks": 1263,
        "ordered_items": 109,
        "sell_earnings": 602,
        "commissions": 602,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6474,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "08",
        "clicks": 1510,
        "ordered_items": 101,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5769,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "09",
        "clicks": 1273,
        "ordered_items": 110,
        "sell_earnings": 558,
        "commissions": 558,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5528,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "10",
        "clicks": 1959,
        "ordered_items": 164,
        "sell_earnings": 658,
        "commissions": 658,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8878,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "11",
        "clicks": 1722,
        "ordered_items": 173,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8637,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "12",
        "clicks": 1969,
        "ordered_items": 165,
        "sell_earnings": 614,
        "commissions": 614,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7932,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "13",
        "clicks": 1187,
        "ordered_items": 126,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5048,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "14",
        "clicks": 2045,
        "ordered_items": 148,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9358,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "15",
        "clicks": 1453,
        "ordered_items": 111,
        "sell_earnings": 448,
        "commissions": 448,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6373,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "16",
        "clicks": 1779,
        "ordered_items": 163,
        "sell_earnings": 768,
        "commissions": 768,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8033,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "17",
        "clicks": 1403,
        "ordered_items": 112,
        "sell_earnings": 559,
        "commissions": 559,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6591,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "18",
        "clicks": 1585,
        "ordered_items": 119,
        "sell_earnings": 549,
        "commissions": 549,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5130,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "19",
        "clicks": 1567,
        "ordered_items": 106,
        "sell_earnings": 481,
        "commissions": 481,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5638,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "20",
        "clicks": 1405,
        "ordered_items": 108,
        "sell_earnings": 435,
        "commissions": 435,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5420,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "21",
        "clicks": 1827,
        "ordered_items": 166,
        "sell_earnings": 781,
        "commissions": 781,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8986,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "22",
        "clicks": 1665,
        "ordered_items": 168,
        "sell_earnings": 735,
        "commissions": 735,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8768,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "23",
        "clicks": 1647,
        "ordered_items": 155,
        "sell_earnings": 667,
        "commissions": 667,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9276,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "24",
        "clicks": 1829,
        "ordered_items": 162,
        "sell_earnings": 657,
        "commissions": 657,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7815,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "25",
        "clicks": 1604,
        "ordered_items": 134,
        "sell_earnings": 591,
        "commissions": 591,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5756,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "26",
        "clicks": 1351,
        "ordered_items": 136,
        "sell_earnings": 571,
        "commissions": 571,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5424,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "27",
        "clicks": 1881,
        "ordered_items": 138,
        "sell_earnings": 645,
        "commissions": 645,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8982,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "28",
        "clicks": 1628,
        "ordered_items": 140,
        "sell_earnings": 625,
        "commissions": 625,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8650,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "29",
        "clicks": 1418,
        "ordered_items": 125,
        "sell_earnings": 513,
        "commissions": 513,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7006,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "30",
        "clicks": 1814,
        "ordered_items": 149,
        "sell_earnings": 703,
        "commissions": 703,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7400,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];