export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1140,
        "ordered_items": 127,
        "sell_earnings": 469,
        "commissions": 469,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7175,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1588,
        "ordered_items": 128,
        "sell_earnings": 490,
        "commissions": 490,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5421,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1458,
        "ordered_items": 116,
        "sell_earnings": 447,
        "commissions": 447,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6641,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 1774,
        "ordered_items": 158,
        "sell_earnings": 769,
        "commissions": 769,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7765,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 1644,
        "ordered_items": 146,
        "sell_earnings": 726,
        "commissions": 726,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8985,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 2092,
        "ordered_items": 147,
        "sell_earnings": 747,
        "commissions": 747,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7231,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1413,
        "ordered_items": 116,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6009,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1229,
        "ordered_items": 99,
        "sell_earnings": 467,
        "commissions": 467,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6754,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1418,
        "ordered_items": 108,
        "sell_earnings": 483,
        "commissions": 483,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6120,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 1814,
        "ordered_items": 166,
        "sell_earnings": 733,
        "commissions": 733,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8286,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 2003,
        "ordered_items": 175,
        "sell_earnings": 749,
        "commissions": 749,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7652,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1819,
        "ordered_items": 158,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8397,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1283,
        "ordered_items": 97,
        "sell_earnings": 505,
        "commissions": 505,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5212,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 1949,
        "ordered_items": 177,
        "sell_earnings": 711,
        "commissions": 711,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9194,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1547,
        "ordered_items": 118,
        "sell_earnings": 435,
        "commissions": 435,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6987,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 1685,
        "ordered_items": 156,
        "sell_earnings": 781,
        "commissions": 781,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7419,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1414,
        "ordered_items": 111,
        "sell_earnings": 429,
        "commissions": 429,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6486,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1407,
        "ordered_items": 134,
        "sell_earnings": 569,
        "commissions": 569,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5592,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1385,
        "ordered_items": 107,
        "sell_earnings": 535,
        "commissions": 535,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6819,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1384,
        "ordered_items": 135,
        "sell_earnings": 589,
        "commissions": 589,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6834,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 1848,
        "ordered_items": 139,
        "sell_earnings": 627,
        "commissions": 627,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7572,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 1847,
        "ordered_items": 167,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7587,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 1825,
        "ordered_items": 140,
        "sell_earnings": 647,
        "commissions": 647,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8814,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1818,
        "ordered_items": 163,
        "sell_earnings": 787,
        "commissions": 787,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7920,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1597,
        "ordered_items": 116,
        "sell_earnings": 546,
        "commissions": 546,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5647,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1163,
        "ordered_items": 116,
        "sell_earnings": 444,
        "commissions": 444,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6075,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 2069,
        "ordered_items": 158,
        "sell_earnings": 772,
        "commissions": 772,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8331,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 1635,
        "ordered_items": 158,
        "sell_earnings": 670,
        "commissions": 670,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8759,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1316,
        "ordered_items": 114,
        "sell_earnings": 538,
        "commissions": 538,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5217,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 1916,
        "ordered_items": 160,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9189,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];