export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1660,
        "ordered_items": 137,
        "sell_earnings": 610,
        "commissions": 610,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6163,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1668,
        "ordered_items": 132,
        "sell_earnings": 578,
        "commissions": 578,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6358,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1568,
        "ordered_items": 106,
        "sell_earnings": 445,
        "commissions": 445,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6289,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 1772,
        "ordered_items": 178,
        "sell_earnings": 811,
        "commissions": 811,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8597,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 1672,
        "ordered_items": 152,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8528,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 1680,
        "ordered_items": 147,
        "sell_earnings": 646,
        "commissions": 646,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8723,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1414,
        "ordered_items": 138,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5459,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1205,
        "ordered_items": 127,
        "sell_earnings": 586,
        "commissions": 586,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7410,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1541,
        "ordered_items": 127,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6151,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 1799,
        "ordered_items": 157,
        "sell_earnings": 792,
        "commissions": 792,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8735,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 2135,
        "ordered_items": 157,
        "sell_earnings": 670,
        "commissions": 670,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7476,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 1926,
        "ordered_items": 146,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9427,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1436,
        "ordered_items": 121,
        "sell_earnings": 599,
        "commissions": 599,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6948,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 1904,
        "ordered_items": 163,
        "sell_earnings": 657,
        "commissions": 657,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7938,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1180,
        "ordered_items": 119,
        "sell_earnings": 461,
        "commissions": 461,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6305,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 2160,
        "ordered_items": 165,
        "sell_earnings": 795,
        "commissions": 795,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8581,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1395,
        "ordered_items": 138,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5362,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1412,
        "ordered_items": 125,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7388,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1219,
        "ordered_items": 110,
        "sell_earnings": 578,
        "commissions": 578,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6983,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1353,
        "ordered_items": 100,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5759,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 1987,
        "ordered_items": 184,
        "sell_earnings": 663,
        "commissions": 663,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9127,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 2121,
        "ordered_items": 174,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7903,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 1928,
        "ordered_items": 159,
        "sell_earnings": 756,
        "commissions": 756,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7498,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 1945,
        "ordered_items": 146,
        "sell_earnings": 806,
        "commissions": 806,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9524,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1336,
        "ordered_items": 105,
        "sell_earnings": 554,
        "commissions": 554,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6671,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1486,
        "ordered_items": 129,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7391,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 1854,
        "ordered_items": 155,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 165,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7495,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 2004,
        "ordered_items": 179,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8215,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1438,
        "ordered_items": 104,
        "sell_earnings": 513,
        "commissions": 513,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5266,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 1902,
        "ordered_items": 180,
        "sell_earnings": 743,
        "commissions": 743,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9620,
        "bonus": 1
    }
];