export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1346,
        "ordered_items": 98,
        "sell_earnings": 600,
        "commissions": 600,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5930,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1420,
        "ordered_items": 100,
        "sell_earnings": 476,
        "commissions": 476,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5117,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1321,
        "ordered_items": 126,
        "sell_earnings": 474,
        "commissions": 474,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6086,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 1911,
        "ordered_items": 148,
        "sell_earnings": 742,
        "commissions": 742,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8320,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1812,
        "ordered_items": 174,
        "sell_earnings": 740,
        "commissions": 740,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9289,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 1886,
        "ordered_items": 176,
        "sell_earnings": 616,
        "commissions": 616,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8476,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1547,
        "ordered_items": 126,
        "sell_earnings": 607,
        "commissions": 607,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6588,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1483,
        "ordered_items": 118,
        "sell_earnings": 507,
        "commissions": 507,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5216,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1352,
        "ordered_items": 97,
        "sell_earnings": 585,
        "commissions": 585,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7029,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1880,
        "ordered_items": 177,
        "sell_earnings": 631,
        "commissions": 631,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7377,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 1749,
        "ordered_items": 156,
        "sell_earnings": 709,
        "commissions": 709,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9190,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1685,
        "ordered_items": 148,
        "sell_earnings": 609,
        "commissions": 609,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7818,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1611,
        "ordered_items": 121,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6346,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1621,
        "ordered_items": 153,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8060,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1553,
        "ordered_items": 115,
        "sell_earnings": 544,
        "commissions": 544,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5085,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1679,
        "ordered_items": 159,
        "sell_earnings": 672,
        "commissions": 672,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9321,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1291,
        "ordered_items": 119,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5818,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1155,
        "ordered_items": 131,
        "sell_earnings": 459,
        "commissions": 459,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5168,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1387,
        "ordered_items": 107,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6260,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1470,
        "ordered_items": 102,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5132,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 1762,
        "ordered_items": 172,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9274,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1845,
        "ordered_items": 167,
        "sell_earnings": 721,
        "commissions": 721,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8146,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 2077,
        "ordered_items": 143,
        "sell_earnings": 757,
        "commissions": 757,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9238,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1941,
        "ordered_items": 155,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8588,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1481,
        "ordered_items": 102,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6462,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1505,
        "ordered_items": 106,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5115,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1727,
        "ordered_items": 168,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9291,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1751,
        "ordered_items": 172,
        "sell_earnings": 752,
        "commissions": 752,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7944,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1284,
        "ordered_items": 119,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6643,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1948,
        "ordered_items": 155,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7763,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];