export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 1309,
        "ordered_items": 112,
        "sell_earnings": 530,
        "commissions": 530,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6796,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 1655,
        "ordered_items": 112,
        "sell_earnings": 451,
        "commissions": 451,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5691,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 1423,
        "ordered_items": 115,
        "sell_earnings": 553,
        "commissions": 553,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6481,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 1917,
        "ordered_items": 169,
        "sell_earnings": 703,
        "commissions": 703,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8405,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 1685,
        "ordered_items": 172,
        "sell_earnings": 805,
        "commissions": 805,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9195,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 2031,
        "ordered_items": 172,
        "sell_earnings": 726,
        "commissions": 726,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 165,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8090,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 1460,
        "ordered_items": 129,
        "sell_earnings": 600,
        "commissions": 600,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6449,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 1591,
        "ordered_items": 107,
        "sell_earnings": 487,
        "commissions": 487,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5738,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 1430,
        "ordered_items": 115,
        "sell_earnings": 569,
        "commissions": 569,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5965,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 1910,
        "ordered_items": 169,
        "sell_earnings": 687,
        "commissions": 687,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8921,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 1749,
        "ordered_items": 177,
        "sell_earnings": 769,
        "commissions": 769,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9148,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 1880,
        "ordered_items": 155,
        "sell_earnings": 656,
        "commissions": 656,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8437,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 1232,
        "ordered_items": 114,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5591,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 2108,
        "ordered_items": 170,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9295,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 1603,
        "ordered_items": 102,
        "sell_earnings": 572,
        "commissions": 572,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7427,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 1737,
        "ordered_items": 182,
        "sell_earnings": 684,
        "commissions": 684,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7459,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 1459,
        "ordered_items": 102,
        "sell_earnings": 607,
        "commissions": 607,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6677,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 1470,
        "ordered_items": 108,
        "sell_earnings": 490,
        "commissions": 490,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6710,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 1657,
        "ordered_items": 135,
        "sell_earnings": 445,
        "commissions": 445,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6159,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 1649,
        "ordered_items": 107,
        "sell_earnings": 526,
        "commissions": 526,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7311,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 1691,
        "ordered_items": 177,
        "sell_earnings": 730,
        "commissions": 730,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7575,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 1683,
        "ordered_items": 149,
        "sell_earnings": 811,
        "commissions": 811,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8727,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 1870,
        "ordered_items": 176,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8176,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 1881,
        "ordered_items": 182,
        "sell_earnings": 649,
        "commissions": 649,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8209,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 1631,
        "ordered_items": 102,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6206,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 1657,
        "ordered_items": 134,
        "sell_earnings": 566,
        "commissions": 566,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7443,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 1683,
        "ordered_items": 150,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7443,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 1709,
        "ordered_items": 182,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8680,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 1237,
        "ordered_items": 134,
        "sell_earnings": 574,
        "commissions": 574,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5774,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 2103,
        "ordered_items": 150,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9112,
        "bonus": 0
    }
];