export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1184,
        "ordered_items": 103,
        "sell_earnings": 573,
        "commissions": 573,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5191,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1294,
        "ordered_items": 135,
        "sell_earnings": 438,
        "commissions": 438,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6983,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1410,
        "ordered_items": 115,
        "sell_earnings": 567,
        "commissions": 567,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6897,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 1822,
        "ordered_items": 159,
        "sell_earnings": 649,
        "commissions": 649,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7509,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 1938,
        "ordered_items": 139,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7423,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 2048,
        "ordered_items": 171,
        "sell_earnings": 643,
        "commissions": 643,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9215,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1277,
        "ordered_items": 104,
        "sell_earnings": 473,
        "commissions": 473,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6702,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1197,
        "ordered_items": 121,
        "sell_earnings": 557,
        "commissions": 557,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6151,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1172,
        "ordered_items": 130,
        "sell_earnings": 574,
        "commissions": 574,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6559,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 2060,
        "ordered_items": 144,
        "sell_earnings": 642,
        "commissions": 642,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7847,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 2035,
        "ordered_items": 153,
        "sell_earnings": 659,
        "commissions": 659,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8255,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 1955,
        "ordered_items": 170,
        "sell_earnings": 743,
        "commissions": 743,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7704,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1195,
        "ordered_items": 112,
        "sell_earnings": 600,
        "commissions": 600,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5354,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 2037,
        "ordered_items": 162,
        "sell_earnings": 616,
        "commissions": 616,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9052,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1387,
        "ordered_items": 102,
        "sell_earnings": 497,
        "commissions": 497,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6585,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 1845,
        "ordered_items": 172,
        "sell_earnings": 719,
        "commissions": 719,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7821,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1582,
        "ordered_items": 125,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5730,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1526,
        "ordered_items": 103,
        "sell_earnings": 466,
        "commissions": 466,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6663,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1506,
        "ordered_items": 136,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6192,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1430,
        "ordered_items": 126,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6802,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 1802,
        "ordered_items": 148,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7604,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1726,
        "ordered_items": 138,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8214,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 1706,
        "ordered_items": 171,
        "sell_earnings": 750,
        "commissions": 750,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7743,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 1650,
        "ordered_items": 149,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8676,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1246,
        "ordered_items": 125,
        "sell_earnings": 547,
        "commissions": 547,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5835,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1570,
        "ordered_items": 100,
        "sell_earnings": 448,
        "commissions": 448,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7105,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 1662,
        "ordered_items": 174,
        "sell_earnings": 768,
        "commissions": 768,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7301,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1986,
        "ordered_items": 149,
        "sell_earnings": 669,
        "commissions": 669,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8571,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1471,
        "ordered_items": 101,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6622,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 1761,
        "ordered_items": 173,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7784,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];