export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1223,
        "ordered_items": 109,
        "sell_earnings": 460,
        "commissions": 460,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5563,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1479,
        "ordered_items": 130,
        "sell_earnings": 427,
        "commissions": 427,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6414,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1301,
        "ordered_items": 123,
        "sell_earnings": 584,
        "commissions": 584,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5869,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 1931,
        "ordered_items": 151,
        "sell_earnings": 632,
        "commissions": 632,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8537,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 1753,
        "ordered_items": 144,
        "sell_earnings": 789,
        "commissions": 789,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7992,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 2009,
        "ordered_items": 165,
        "sell_earnings": 756,
        "commissions": 756,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8843,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1387,
        "ordered_items": 104,
        "sell_earnings": 567,
        "commissions": 567,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6802,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1303,
        "ordered_items": 116,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5291,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1552,
        "ordered_items": 131,
        "sell_earnings": 548,
        "commissions": 548,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5771,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 1680,
        "ordered_items": 143,
        "sell_earnings": 668,
        "commissions": 668,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8635,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 1929,
        "ordered_items": 158,
        "sell_earnings": 610,
        "commissions": 610,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9115,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 1845,
        "ordered_items": 170,
        "sell_earnings": 649,
        "commissions": 649,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7604,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1245,
        "ordered_items": 119,
        "sell_earnings": 483,
        "commissions": 483,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5270,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 1987,
        "ordered_items": 155,
        "sell_earnings": 733,
        "commissions": 733,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9136,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1280,
        "ordered_items": 115,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6746,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 1952,
        "ordered_items": 159,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7660,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1136,
        "ordered_items": 124,
        "sell_earnings": 509,
        "commissions": 509,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6980,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1601,
        "ordered_items": 132,
        "sell_earnings": 571,
        "commissions": 571,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5297,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1152,
        "ordered_items": 115,
        "sell_earnings": 510,
        "commissions": 510,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6959,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1568,
        "ordered_items": 112,
        "sell_earnings": 501,
        "commissions": 501,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6414,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 1664,
        "ordered_items": 162,
        "sell_earnings": 715,
        "commissions": 715,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7992,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 2080,
        "ordered_items": 159,
        "sell_earnings": 706,
        "commissions": 706,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7447,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 1631,
        "ordered_items": 142,
        "sell_earnings": 645,
        "commissions": 645,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9109,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 2096,
        "ordered_items": 150,
        "sell_earnings": 707,
        "commissions": 707,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7426,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1511,
        "ordered_items": 125,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6086,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1506,
        "ordered_items": 125,
        "sell_earnings": 488,
        "commissions": 488,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5587,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 1726,
        "ordered_items": 149,
        "sell_earnings": 728,
        "commissions": 728,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8819,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 1721,
        "ordered_items": 149,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8320,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1433,
        "ordered_items": 137,
        "sell_earnings": 478,
        "commissions": 478,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5485,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 1799,
        "ordered_items": 137,
        "sell_earnings": 738,
        "commissions": 738,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8921,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];