export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1304,
        "ordered_items": 101,
        "sell_earnings": 597,
        "commissions": 597,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5405,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1648,
        "ordered_items": 124,
        "sell_earnings": 592,
        "commissions": 592,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5399,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1361,
        "ordered_items": 113,
        "sell_earnings": 614,
        "commissions": 614,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7132,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 1979,
        "ordered_items": 171,
        "sell_earnings": 642,
        "commissions": 642,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7754,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 1692,
        "ordered_items": 160,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9487,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 2036,
        "ordered_items": 183,
        "sell_earnings": 659,
        "commissions": 659,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9481,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1465,
        "ordered_items": 106,
        "sell_earnings": 611,
        "commissions": 611,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6351,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1663,
        "ordered_items": 130,
        "sell_earnings": 584,
        "commissions": 584,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6824,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1563,
        "ordered_items": 109,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6663,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 1777,
        "ordered_items": 175,
        "sell_earnings": 663,
        "commissions": 663,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8223,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 1677,
        "ordered_items": 154,
        "sell_earnings": 672,
        "commissions": 672,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8062,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 1875,
        "ordered_items": 178,
        "sell_earnings": 645,
        "commissions": 645,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8535,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1642,
        "ordered_items": 124,
        "sell_earnings": 570,
        "commissions": 570,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7185,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 1698,
        "ordered_items": 160,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7701,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1622,
        "ordered_items": 112,
        "sell_earnings": 576,
        "commissions": 576,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7384,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 1718,
        "ordered_items": 172,
        "sell_earnings": 680,
        "commissions": 680,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7502,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1547,
        "ordered_items": 139,
        "sell_earnings": 542,
        "commissions": 542,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7369,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1366,
        "ordered_items": 135,
        "sell_earnings": 591,
        "commissions": 591,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6992,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1243,
        "ordered_items": 111,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5702,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1661,
        "ordered_items": 142,
        "sell_earnings": 459,
        "commissions": 459,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7278,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 1679,
        "ordered_items": 142,
        "sell_earnings": 797,
        "commissions": 797,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7608,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 2097,
        "ordered_items": 173,
        "sell_earnings": 798,
        "commissions": 798,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 168,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9184,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 1974,
        "ordered_items": 149,
        "sell_earnings": 665,
        "commissions": 665,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7894,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 1793,
        "ordered_items": 145,
        "sell_earnings": 714,
        "commissions": 714,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7517,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1366,
        "ordered_items": 110,
        "sell_earnings": 498,
        "commissions": 498,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5944,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1337,
        "ordered_items": 112,
        "sell_earnings": 481,
        "commissions": 481,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6408,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 2003,
        "ordered_items": 172,
        "sell_earnings": 775,
        "commissions": 775,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8478,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 1974,
        "ordered_items": 174,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8942,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1580,
        "ordered_items": 106,
        "sell_earnings": 478,
        "commissions": 478,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5469,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 1760,
        "ordered_items": 178,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9417,
        "bonus": 1
    }
];