export let mar = [
    {
        "month": "Mar",
        "day": "01",
        "clicks": 1319,
        "ordered_items": 116,
        "sell_earnings": 591,
        "commissions": 591,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5404,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "02",
        "clicks": 1268,
        "ordered_items": 98,
        "sell_earnings": 566,
        "commissions": 566,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7075,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "03",
        "clicks": 1376,
        "ordered_items": 125,
        "sell_earnings": 441,
        "commissions": 441,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6960,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "04",
        "clicks": 1856,
        "ordered_items": 149,
        "sell_earnings": 775,
        "commissions": 775,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7446,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "05",
        "clicks": 1964,
        "ordered_items": 176,
        "sell_earnings": 650,
        "commissions": 650,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7331,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "06",
        "clicks": 1913,
        "ordered_items": 158,
        "sell_earnings": 625,
        "commissions": 625,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9002,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "07",
        "clicks": 1220,
        "ordered_items": 118,
        "sell_earnings": 551,
        "commissions": 551,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5886,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "08",
        "clicks": 1436,
        "ordered_items": 97,
        "sell_earnings": 469,
        "commissions": 469,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6478,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "09",
        "clicks": 1484,
        "ordered_items": 108,
        "sell_earnings": 548,
        "commissions": 548,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6122,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "10",
        "clicks": 1748,
        "ordered_items": 166,
        "sell_earnings": 668,
        "commissions": 668,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8284,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "11",
        "clicks": 1796,
        "ordered_items": 177,
        "sell_earnings": 747,
        "commissions": 747,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7928,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "12",
        "clicks": 2012,
        "ordered_items": 156,
        "sell_earnings": 665,
        "commissions": 665,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8520,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "13",
        "clicks": 1182,
        "ordered_items": 134,
        "sell_earnings": 465,
        "commissions": 465,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5071,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "14",
        "clicks": 2050,
        "ordered_items": 140,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9335,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "15",
        "clicks": 1453,
        "ordered_items": 130,
        "sell_earnings": 427,
        "commissions": 427,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6915,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "16",
        "clicks": 1779,
        "ordered_items": 144,
        "sell_earnings": 789,
        "commissions": 789,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7491,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "17",
        "clicks": 1577,
        "ordered_items": 129,
        "sell_earnings": 481,
        "commissions": 481,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5333,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "18",
        "clicks": 1561,
        "ordered_items": 107,
        "sell_earnings": 508,
        "commissions": 508,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6119,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "19",
        "clicks": 1220,
        "ordered_items": 119,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7036,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "20",
        "clicks": 1470,
        "ordered_items": 122,
        "sell_earnings": 484,
        "commissions": 484,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5711,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "21",
        "clicks": 1762,
        "ordered_items": 152,
        "sell_earnings": 732,
        "commissions": 732,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8695,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "22",
        "clicks": 2012,
        "ordered_items": 155,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7370,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "23",
        "clicks": 1671,
        "ordered_items": 167,
        "sell_earnings": 708,
        "commissions": 708,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8287,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "24",
        "clicks": 1655,
        "ordered_items": 145,
        "sell_earnings": 735,
        "commissions": 735,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9073,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "25",
        "clicks": 1576,
        "ordered_items": 99,
        "sell_earnings": 434,
        "commissions": 434,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5444,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "26",
        "clicks": 1254,
        "ordered_items": 126,
        "sell_earnings": 526,
        "commissions": 526,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6897,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "27",
        "clicks": 1978,
        "ordered_items": 148,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7509,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "28",
        "clicks": 1656,
        "ordered_items": 175,
        "sell_earnings": 782,
        "commissions": 782,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8962,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "29",
        "clicks": 1205,
        "ordered_items": 130,
        "sell_earnings": 493,
        "commissions": 493,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7041,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "30",
        "clicks": 2027,
        "ordered_items": 144,
        "sell_earnings": 723,
        "commissions": 723,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7365,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];