export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1226,
        "ordered_items": 107,
        "sell_earnings": 591,
        "commissions": 591,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7052,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1304,
        "ordered_items": 122,
        "sell_earnings": 588,
        "commissions": 588,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6714,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1466,
        "ordered_items": 133,
        "sell_earnings": 476,
        "commissions": 476,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6157,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 1874,
        "ordered_items": 151,
        "sell_earnings": 780,
        "commissions": 780,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8729,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 2036,
        "ordered_items": 162,
        "sell_earnings": 668,
        "commissions": 668,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8172,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 2114,
        "ordered_items": 177,
        "sell_earnings": 665,
        "commissions": 665,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7834,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1641,
        "ordered_items": 121,
        "sell_earnings": 553,
        "commissions": 553,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6476,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1439,
        "ordered_items": 109,
        "sell_earnings": 462,
        "commissions": 462,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6045,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1329,
        "ordered_items": 105,
        "sell_earnings": 519,
        "commissions": 519,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5717,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 2011,
        "ordered_items": 179,
        "sell_earnings": 737,
        "commissions": 737,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9169,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 1901,
        "ordered_items": 175,
        "sell_earnings": 794,
        "commissions": 794,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8841,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 1699,
        "ordered_items": 163,
        "sell_earnings": 703,
        "commissions": 703,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 167,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8410,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1612,
        "ordered_items": 126,
        "sell_earnings": 488,
        "commissions": 488,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6964,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 1728,
        "ordered_items": 158,
        "sell_earnings": 768,
        "commissions": 768,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7922,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1204,
        "ordered_items": 125,
        "sell_earnings": 567,
        "commissions": 567,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6416,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 2136,
        "ordered_items": 159,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8470,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1637,
        "ordered_items": 121,
        "sell_earnings": 555,
        "commissions": 555,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5800,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1497,
        "ordered_items": 113,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6410,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1569,
        "ordered_items": 114,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5938,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1330,
        "ordered_items": 111,
        "sell_earnings": 614,
        "commissions": 614,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7089,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 2010,
        "ordered_items": 173,
        "sell_earnings": 642,
        "commissions": 642,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7797,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 1771,
        "ordered_items": 170,
        "sell_earnings": 691,
        "commissions": 691,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8948,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 1843,
        "ordered_items": 171,
        "sell_earnings": 658,
        "commissions": 658,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8476,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 1703,
        "ordered_items": 163,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9086,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1527,
        "ordered_items": 120,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7331,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1352,
        "ordered_items": 125,
        "sell_earnings": 454,
        "commissions": 454,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5353,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 1988,
        "ordered_items": 159,
        "sell_earnings": 802,
        "commissions": 802,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9533,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 1813,
        "ordered_items": 164,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7555,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1292,
        "ordered_items": 124,
        "sell_earnings": 550,
        "commissions": 550,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5506,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 2048,
        "ordered_items": 160,
        "sell_earnings": 706,
        "commissions": 706,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9380,
        "bonus": 1
    }
];