export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1550,
        "ordered_items": 105,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6994,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1558,
        "ordered_items": 125,
        "sell_earnings": 586,
        "commissions": 586,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5248,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1242,
        "ordered_items": 120,
        "sell_earnings": 550,
        "commissions": 550,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6671,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 1990,
        "ordered_items": 154,
        "sell_earnings": 666,
        "commissions": 666,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7735,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1674,
        "ordered_items": 149,
        "sell_earnings": 630,
        "commissions": 630,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9158,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 1682,
        "ordered_items": 169,
        "sell_earnings": 610,
        "commissions": 610,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7412,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1355,
        "ordered_items": 98,
        "sell_earnings": 514,
        "commissions": 514,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6881,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1268,
        "ordered_items": 108,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5369,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1373,
        "ordered_items": 108,
        "sell_earnings": 533,
        "commissions": 533,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7189,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1859,
        "ordered_items": 166,
        "sell_earnings": 683,
        "commissions": 683,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7217,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 1964,
        "ordered_items": 166,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9037,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1877,
        "ordered_items": 176,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7525,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1602,
        "ordered_items": 126,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5340,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1630,
        "ordered_items": 148,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9066,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1264,
        "ordered_items": 115,
        "sell_earnings": 553,
        "commissions": 553,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5852,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1968,
        "ordered_items": 159,
        "sell_earnings": 663,
        "commissions": 663,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8554,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1379,
        "ordered_items": 111,
        "sell_earnings": 524,
        "commissions": 524,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6982,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1445,
        "ordered_items": 118,
        "sell_earnings": 444,
        "commissions": 444,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5264,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1255,
        "ordered_items": 128,
        "sell_earnings": 465,
        "commissions": 465,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5320,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1297,
        "ordered_items": 126,
        "sell_earnings": 447,
        "commissions": 447,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6366,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 1935,
        "ordered_items": 148,
        "sell_earnings": 769,
        "commissions": 769,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8040,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1977,
        "ordered_items": 146,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9086,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 1787,
        "ordered_items": 156,
        "sell_earnings": 772,
        "commissions": 772,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9142,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1853,
        "ordered_items": 163,
        "sell_earnings": 692,
        "commissions": 692,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7424,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1236,
        "ordered_items": 108,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6906,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1413,
        "ordered_items": 126,
        "sell_earnings": 560,
        "commissions": 560,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6968,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1819,
        "ordered_items": 148,
        "sell_earnings": 656,
        "commissions": 656,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7438,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1996,
        "ordered_items": 166,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7500,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1539,
        "ordered_items": 134,
        "sell_earnings": 590,
        "commissions": 590,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6700,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1693,
        "ordered_items": 140,
        "sell_earnings": 626,
        "commissions": 626,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7706,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];