export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1218,
        "ordered_items": 113,
        "sell_earnings": 449,
        "commissions": 449,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6563,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1268,
        "ordered_items": 122,
        "sell_earnings": 597,
        "commissions": 597,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7108,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1409,
        "ordered_items": 110,
        "sell_earnings": 600,
        "commissions": 600,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6025,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 1823,
        "ordered_items": 164,
        "sell_earnings": 616,
        "commissions": 616,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8381,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 1964,
        "ordered_items": 152,
        "sell_earnings": 619,
        "commissions": 619,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7298,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 2014,
        "ordered_items": 161,
        "sell_earnings": 767,
        "commissions": 767,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7843,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1591,
        "ordered_items": 118,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6489,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1385,
        "ordered_items": 119,
        "sell_earnings": 481,
        "commissions": 481,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5882,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1333,
        "ordered_items": 123,
        "sell_earnings": 445,
        "commissions": 445,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6085,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 1899,
        "ordered_items": 151,
        "sell_earnings": 771,
        "commissions": 771,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8321,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1847,
        "ordered_items": 155,
        "sell_earnings": 735,
        "commissions": 735,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8524,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 1641,
        "ordered_items": 156,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7917,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1369,
        "ordered_items": 106,
        "sell_earnings": 454,
        "commissions": 454,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5155,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 1863,
        "ordered_items": 168,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9251,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1484,
        "ordered_items": 114,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5988,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 1748,
        "ordered_items": 160,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8418,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1410,
        "ordered_items": 105,
        "sell_earnings": 538,
        "commissions": 538,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6194,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1308,
        "ordered_items": 100,
        "sell_earnings": 518,
        "commissions": 518,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5379,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1138,
        "ordered_items": 111,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7126,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1318,
        "ordered_items": 120,
        "sell_earnings": 492,
        "commissions": 492,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6509,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 1914,
        "ordered_items": 154,
        "sell_earnings": 724,
        "commissions": 724,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7897,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 2094,
        "ordered_items": 163,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7280,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 1924,
        "ordered_items": 174,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9027,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 1822,
        "ordered_items": 169,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8212,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1409,
        "ordered_items": 136,
        "sell_earnings": 478,
        "commissions": 478,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6224,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1533,
        "ordered_items": 111,
        "sell_earnings": 555,
        "commissions": 555,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6330,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1699,
        "ordered_items": 163,
        "sell_earnings": 661,
        "commissions": 661,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8076,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 1823,
        "ordered_items": 138,
        "sell_earnings": 738,
        "commissions": 738,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8182,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1338,
        "ordered_items": 128,
        "sell_earnings": 466,
        "commissions": 466,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5516,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 1894,
        "ordered_items": 146,
        "sell_earnings": 750,
        "commissions": 750,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8890,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];