export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1333,
        "ordered_items": 117,
        "sell_earnings": 467,
        "commissions": 467,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5191,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1508,
        "ordered_items": 114,
        "sell_earnings": 523,
        "commissions": 523,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7190,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1547,
        "ordered_items": 119,
        "sell_earnings": 577,
        "commissions": 577,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5740,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 1685,
        "ordered_items": 155,
        "sell_earnings": 639,
        "commissions": 639,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8666,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 1724,
        "ordered_items": 160,
        "sell_earnings": 693,
        "commissions": 693,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7216,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 1899,
        "ordered_items": 157,
        "sell_earnings": 749,
        "commissions": 749,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9215,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1445,
        "ordered_items": 118,
        "sell_earnings": 523,
        "commissions": 523,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6663,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1183,
        "ordered_items": 97,
        "sell_earnings": 588,
        "commissions": 588,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5397,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1514,
        "ordered_items": 114,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5934,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 1718,
        "ordered_items": 160,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8472,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 2049,
        "ordered_items": 177,
        "sell_earnings": 628,
        "commissions": 628,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9009,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 1787,
        "ordered_items": 156,
        "sell_earnings": 693,
        "commissions": 693,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7743,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1495,
        "ordered_items": 126,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5954,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 1737,
        "ordered_items": 148,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8452,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1548,
        "ordered_items": 109,
        "sell_earnings": 497,
        "commissions": 497,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5894,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 1684,
        "ordered_items": 165,
        "sell_earnings": 719,
        "commissions": 719,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8512,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1329,
        "ordered_items": 129,
        "sell_earnings": 547,
        "commissions": 547,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6991,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1581,
        "ordered_items": 123,
        "sell_earnings": 514,
        "commissions": 514,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5655,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1550,
        "ordered_items": 120,
        "sell_earnings": 512,
        "commissions": 512,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5813,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1283,
        "ordered_items": 110,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6170,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 1949,
        "ordered_items": 164,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8236,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 1682,
        "ordered_items": 154,
        "sell_earnings": 704,
        "commissions": 704,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8593,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 1651,
        "ordered_items": 151,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8751,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 1903,
        "ordered_items": 145,
        "sell_earnings": 669,
        "commissions": 669,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7415,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1495,
        "ordered_items": 112,
        "sell_earnings": 541,
        "commissions": 541,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5789,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1525,
        "ordered_items": 123,
        "sell_earnings": 448,
        "commissions": 448,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6919,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 1707,
        "ordered_items": 151,
        "sell_earnings": 768,
        "commissions": 768,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7487,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 1737,
        "ordered_items": 162,
        "sell_earnings": 675,
        "commissions": 675,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8617,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1232,
        "ordered_items": 119,
        "sell_earnings": 530,
        "commissions": 530,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5611,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 2000,
        "ordered_items": 155,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8795,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];