export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1209,
        "ordered_items": 135,
        "sell_earnings": 429,
        "commissions": 429,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5801,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1339,
        "ordered_items": 127,
        "sell_earnings": 459,
        "commissions": 459,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6124,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1268,
        "ordered_items": 101,
        "sell_earnings": 461,
        "commissions": 461,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6346,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 1964,
        "ordered_items": 173,
        "sell_earnings": 755,
        "commissions": 755,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8060,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1893,
        "ordered_items": 147,
        "sell_earnings": 757,
        "commissions": 757,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8282,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 2023,
        "ordered_items": 139,
        "sell_earnings": 787,
        "commissions": 787,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8605,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1588,
        "ordered_items": 135,
        "sell_earnings": 583,
        "commissions": 583,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7154,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1283,
        "ordered_items": 98,
        "sell_earnings": 443,
        "commissions": 443,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7015,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1588,
        "ordered_items": 119,
        "sell_earnings": 531,
        "commissions": 531,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5865,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1644,
        "ordered_items": 155,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8541,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 1949,
        "ordered_items": 176,
        "sell_earnings": 773,
        "commissions": 773,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7391,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1644,
        "ordered_items": 139,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7252,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1413,
        "ordered_items": 98,
        "sell_earnings": 605,
        "commissions": 605,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5346,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1819,
        "ordered_items": 176,
        "sell_earnings": 611,
        "commissions": 611,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9060,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1612,
        "ordered_items": 99,
        "sell_earnings": 544,
        "commissions": 544,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7190,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1620,
        "ordered_items": 175,
        "sell_earnings": 672,
        "commissions": 672,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7216,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1242,
        "ordered_items": 129,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6639,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1496,
        "ordered_items": 102,
        "sell_earnings": 487,
        "commissions": 487,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6328,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1578,
        "ordered_items": 112,
        "sell_earnings": 603,
        "commissions": 603,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7016,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1175,
        "ordered_items": 105,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6255,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 2057,
        "ordered_items": 169,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8151,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1654,
        "ordered_items": 162,
        "sell_earnings": 613,
        "commissions": 613,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7390,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 1736,
        "ordered_items": 172,
        "sell_earnings": 729,
        "commissions": 729,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8078,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1990,
        "ordered_items": 145,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7767,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1502,
        "ordered_items": 107,
        "sell_earnings": 492,
        "commissions": 492,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6175,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1255,
        "ordered_items": 124,
        "sell_earnings": 531,
        "commissions": 531,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6086,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1977,
        "ordered_items": 150,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8320,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1730,
        "ordered_items": 167,
        "sell_earnings": 724,
        "commissions": 724,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8231,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1347,
        "ordered_items": 118,
        "sell_earnings": 594,
        "commissions": 594,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6600,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1885,
        "ordered_items": 156,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7806,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];