export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1141,
        "ordered_items": 128,
        "sell_earnings": 582,
        "commissions": 582,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5795,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1264,
        "ordered_items": 131,
        "sell_earnings": 445,
        "commissions": 445,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6073,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1487,
        "ordered_items": 114,
        "sell_earnings": 438,
        "commissions": 438,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6602,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 1745,
        "ordered_items": 160,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7804,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 1968,
        "ordered_items": 143,
        "sell_earnings": 771,
        "commissions": 771,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8333,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 2091,
        "ordered_items": 146,
        "sell_earnings": 634,
        "commissions": 634,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8611,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1206,
        "ordered_items": 109,
        "sell_earnings": 440,
        "commissions": 440,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5825,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1464,
        "ordered_items": 131,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6277,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1266,
        "ordered_items": 110,
        "sell_earnings": 519,
        "commissions": 519,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6206,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 1966,
        "ordered_items": 164,
        "sell_earnings": 697,
        "commissions": 697,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8200,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1768,
        "ordered_items": 143,
        "sell_earnings": 721,
        "commissions": 721,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8129,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 2026,
        "ordered_items": 165,
        "sell_earnings": 776,
        "commissions": 776,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8581,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1275,
        "ordered_items": 101,
        "sell_earnings": 589,
        "commissions": 589,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6741,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 1957,
        "ordered_items": 173,
        "sell_earnings": 627,
        "commissions": 627,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7665,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1462,
        "ordered_items": 117,
        "sell_earnings": 441,
        "commissions": 441,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6461,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 1770,
        "ordered_items": 157,
        "sell_earnings": 775,
        "commissions": 775,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7945,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1402,
        "ordered_items": 106,
        "sell_earnings": 492,
        "commissions": 492,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5934,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1384,
        "ordered_items": 116,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6237,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1575,
        "ordered_items": 137,
        "sell_earnings": 530,
        "commissions": 530,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6749,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1190,
        "ordered_items": 102,
        "sell_earnings": 514,
        "commissions": 514,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6534,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 2042,
        "ordered_items": 172,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7872,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 1657,
        "ordered_items": 137,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7657,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 1848,
        "ordered_items": 158,
        "sell_earnings": 753,
        "commissions": 753,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8169,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 1830,
        "ordered_items": 168,
        "sell_earnings": 724,
        "commissions": 724,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8472,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1455,
        "ordered_items": 100,
        "sell_earnings": 577,
        "commissions": 577,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6490,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1277,
        "ordered_items": 114,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5483,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1955,
        "ordered_items": 160,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8923,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 1777,
        "ordered_items": 174,
        "sell_earnings": 639,
        "commissions": 639,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7916,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1476,
        "ordered_items": 123,
        "sell_earnings": 435,
        "commissions": 435,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5133,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 1756,
        "ordered_items": 151,
        "sell_earnings": 781,
        "commissions": 781,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9273,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];