export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1551,
        "ordered_items": 130,
        "sell_earnings": 591,
        "commissions": 591,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5690,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1239,
        "ordered_items": 122,
        "sell_earnings": 485,
        "commissions": 485,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7196,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1474,
        "ordered_items": 122,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5529,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 1758,
        "ordered_items": 152,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8877,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 1993,
        "ordered_items": 152,
        "sell_earnings": 731,
        "commissions": 731,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7210,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 1681,
        "ordered_items": 144,
        "sell_earnings": 625,
        "commissions": 625,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8716,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1159,
        "ordered_items": 100,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5106,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1458,
        "ordered_items": 102,
        "sell_earnings": 531,
        "commissions": 531,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6954,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1414,
        "ordered_items": 134,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6586,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 1818,
        "ordered_items": 140,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7820,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 1774,
        "ordered_items": 172,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7452,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 2073,
        "ordered_items": 174,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9300,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1296,
        "ordered_items": 101,
        "sell_earnings": 585,
        "commissions": 585,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5781,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 1936,
        "ordered_items": 173,
        "sell_earnings": 631,
        "commissions": 631,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8625,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1146,
        "ordered_items": 119,
        "sell_earnings": 543,
        "commissions": 543,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6393,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 2086,
        "ordered_items": 155,
        "sell_earnings": 673,
        "commissions": 673,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8013,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1325,
        "ordered_items": 137,
        "sell_earnings": 509,
        "commissions": 509,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6851,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1490,
        "ordered_items": 124,
        "sell_earnings": 487,
        "commissions": 487,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5451,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1374,
        "ordered_items": 134,
        "sell_earnings": 555,
        "commissions": 555,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6766,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1191,
        "ordered_items": 131,
        "sell_earnings": 487,
        "commissions": 487,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6892,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 2041,
        "ordered_items": 143,
        "sell_earnings": 729,
        "commissions": 729,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7514,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1858,
        "ordered_items": 140,
        "sell_earnings": 661,
        "commissions": 661,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7640,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 1742,
        "ordered_items": 150,
        "sell_earnings": 729,
        "commissions": 729,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8955,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 1907,
        "ordered_items": 137,
        "sell_earnings": 707,
        "commissions": 707,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7555,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1438,
        "ordered_items": 111,
        "sell_earnings": 471,
        "commissions": 471,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6935,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1487,
        "ordered_items": 111,
        "sell_earnings": 469,
        "commissions": 469,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5433,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 1745,
        "ordered_items": 163,
        "sell_earnings": 747,
        "commissions": 747,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8973,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1794,
        "ordered_items": 163,
        "sell_earnings": 745,
        "commissions": 745,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7471,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1216,
        "ordered_items": 122,
        "sell_earnings": 473,
        "commissions": 473,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6171,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 2016,
        "ordered_items": 152,
        "sell_earnings": 743,
        "commissions": 743,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8235,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];