export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1514,
        "ordered_items": 107,
        "sell_earnings": 542,
        "commissions": 542,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6114,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1189,
        "ordered_items": 123,
        "sell_earnings": 532,
        "commissions": 532,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6766,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1580,
        "ordered_items": 115,
        "sell_earnings": 434,
        "commissions": 434,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5718,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 1652,
        "ordered_items": 159,
        "sell_earnings": 782,
        "commissions": 782,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8688,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 2043,
        "ordered_items": 151,
        "sell_earnings": 684,
        "commissions": 684,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7640,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 1718,
        "ordered_items": 167,
        "sell_earnings": 674,
        "commissions": 674,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8292,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1605,
        "ordered_items": 125,
        "sell_earnings": 559,
        "commissions": 559,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6326,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1296,
        "ordered_items": 117,
        "sell_earnings": 429,
        "commissions": 429,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6530,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1495,
        "ordered_items": 113,
        "sell_earnings": 588,
        "commissions": 588,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6342,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 1737,
        "ordered_items": 161,
        "sell_earnings": 628,
        "commissions": 628,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8064,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 1936,
        "ordered_items": 157,
        "sell_earnings": 787,
        "commissions": 787,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7876,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 1627,
        "ordered_items": 149,
        "sell_earnings": 657,
        "commissions": 657,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8080,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1610,
        "ordered_items": 136,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6681,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 1622,
        "ordered_items": 138,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7725,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1494,
        "ordered_items": 137,
        "sell_earnings": 434,
        "commissions": 434,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6447,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 1738,
        "ordered_items": 137,
        "sell_earnings": 782,
        "commissions": 782,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7959,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1293,
        "ordered_items": 116,
        "sell_earnings": 497,
        "commissions": 497,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6930,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1492,
        "ordered_items": 132,
        "sell_earnings": 475,
        "commissions": 475,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6542,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1220,
        "ordered_items": 105,
        "sell_earnings": 432,
        "commissions": 432,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5490,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1611,
        "ordered_items": 129,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6498,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 1621,
        "ordered_items": 145,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7908,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 2012,
        "ordered_items": 169,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8916,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 1740,
        "ordered_items": 142,
        "sell_earnings": 741,
        "commissions": 741,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7864,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 1939,
        "ordered_items": 158,
        "sell_earnings": 719,
        "commissions": 719,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7476,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1474,
        "ordered_items": 137,
        "sell_earnings": 582,
        "commissions": 582,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7124,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1529,
        "ordered_items": 129,
        "sell_earnings": 575,
        "commissions": 575,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6905,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 1703,
        "ordered_items": 145,
        "sell_earnings": 641,
        "commissions": 641,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7501,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 1758,
        "ordered_items": 137,
        "sell_earnings": 634,
        "commissions": 634,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7282,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1543,
        "ordered_items": 112,
        "sell_earnings": 549,
        "commissions": 549,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5232,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 1689,
        "ordered_items": 162,
        "sell_earnings": 667,
        "commissions": 667,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9174,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];