export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1184,
        "ordered_items": 139,
        "sell_earnings": 583,
        "commissions": 583,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5676,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1312,
        "ordered_items": 104,
        "sell_earnings": 583,
        "commissions": 583,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5435,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1446,
        "ordered_items": 135,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5367,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 1894,
        "ordered_items": 149,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9519,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 2028,
        "ordered_items": 180,
        "sell_earnings": 673,
        "commissions": 673,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9451,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 2156,
        "ordered_items": 145,
        "sell_earnings": 673,
        "commissions": 673,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9210,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1409,
        "ordered_items": 132,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5318,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1213,
        "ordered_items": 105,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7363,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1328,
        "ordered_items": 138,
        "sell_earnings": 488,
        "commissions": 488,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6085,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 2012,
        "ordered_items": 146,
        "sell_earnings": 768,
        "commissions": 768,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8801,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 2127,
        "ordered_items": 179,
        "sell_earnings": 652,
        "commissions": 652,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7523,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 1931,
        "ordered_items": 152,
        "sell_earnings": 806,
        "commissions": 806,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9568,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1305,
        "ordered_items": 129,
        "sell_earnings": 453,
        "commissions": 453,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6553,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 2035,
        "ordered_items": 155,
        "sell_earnings": 803,
        "commissions": 803,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8333,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1526,
        "ordered_items": 118,
        "sell_earnings": 590,
        "commissions": 590,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6035,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 1814,
        "ordered_items": 166,
        "sell_earnings": 666,
        "commissions": 666,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8851,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1458,
        "ordered_items": 116,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7129,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1612,
        "ordered_items": 116,
        "sell_earnings": 462,
        "commissions": 462,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6426,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1373,
        "ordered_items": 106,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5929,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1550,
        "ordered_items": 133,
        "sell_earnings": 579,
        "commissions": 579,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5866,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 1790,
        "ordered_items": 151,
        "sell_earnings": 677,
        "commissions": 677,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9020,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 1967,
        "ordered_items": 178,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8957,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 1728,
        "ordered_items": 168,
        "sell_earnings": 794,
        "commissions": 794,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8460,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 1882,
        "ordered_items": 168,
        "sell_earnings": 756,
        "commissions": 756,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7757,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1502,
        "ordered_items": 132,
        "sell_earnings": 547,
        "commissions": 547,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6384,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1597,
        "ordered_items": 111,
        "sell_earnings": 562,
        "commissions": 562,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5631,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 1743,
        "ordered_items": 173,
        "sell_earnings": 694,
        "commissions": 694,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9255,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 1838,
        "ordered_items": 152,
        "sell_earnings": 709,
        "commissions": 709,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8502,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1319,
        "ordered_items": 137,
        "sell_earnings": 562,
        "commissions": 562,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6615,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 2021,
        "ordered_items": 147,
        "sell_earnings": 694,
        "commissions": 694,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8271,
        "bonus": 1
    }
];