export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1160,
        "ordered_items": 106,
        "sell_earnings": 554,
        "commissions": 554,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6212,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1387,
        "ordered_items": 114,
        "sell_earnings": 569,
        "commissions": 569,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5860,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1420,
        "ordered_items": 114,
        "sell_earnings": 471,
        "commissions": 471,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6608,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 1812,
        "ordered_items": 160,
        "sell_earnings": 745,
        "commissions": 745,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7798,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1845,
        "ordered_items": 160,
        "sell_earnings": 647,
        "commissions": 647,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8546,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 2072,
        "ordered_items": 168,
        "sell_earnings": 662,
        "commissions": 662,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8194,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1384,
        "ordered_items": 132,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5769,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1330,
        "ordered_items": 97,
        "sell_earnings": 558,
        "commissions": 558,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5160,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1581,
        "ordered_items": 127,
        "sell_earnings": 579,
        "commissions": 579,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5946,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1651,
        "ordered_items": 147,
        "sell_earnings": 637,
        "commissions": 637,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8460,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 1902,
        "ordered_items": 177,
        "sell_earnings": 658,
        "commissions": 658,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9246,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1848,
        "ordered_items": 142,
        "sell_earnings": 720,
        "commissions": 720,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8637,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1484,
        "ordered_items": 114,
        "sell_earnings": 539,
        "commissions": 539,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5103,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1748,
        "ordered_items": 160,
        "sell_earnings": 677,
        "commissions": 677,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9303,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1543,
        "ordered_items": 107,
        "sell_earnings": 597,
        "commissions": 597,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6615,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1689,
        "ordered_items": 167,
        "sell_earnings": 619,
        "commissions": 619,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7791,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1368,
        "ordered_items": 129,
        "sell_earnings": 435,
        "commissions": 435,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6014,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1191,
        "ordered_items": 127,
        "sell_earnings": 505,
        "commissions": 505,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6008,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1580,
        "ordered_items": 102,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5637,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1365,
        "ordered_items": 114,
        "sell_earnings": 585,
        "commissions": 585,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7041,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 1867,
        "ordered_items": 160,
        "sell_earnings": 631,
        "commissions": 631,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7365,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1652,
        "ordered_items": 172,
        "sell_earnings": 752,
        "commissions": 752,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8769,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 2041,
        "ordered_items": 147,
        "sell_earnings": 711,
        "commissions": 711,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8398,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1864,
        "ordered_items": 145,
        "sell_earnings": 781,
        "commissions": 781,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8392,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1190,
        "ordered_items": 128,
        "sell_earnings": 548,
        "commissions": 548,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6442,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1509,
        "ordered_items": 109,
        "sell_earnings": 587,
        "commissions": 587,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5856,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1723,
        "ordered_items": 165,
        "sell_earnings": 629,
        "commissions": 629,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8550,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 2042,
        "ordered_items": 146,
        "sell_earnings": 668,
        "commissions": 668,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7964,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1430,
        "ordered_items": 126,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5443,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1802,
        "ordered_items": 148,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8963,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];