export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 1554,
        "ordered_items": 118,
        "sell_earnings": 533,
        "commissions": 533,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6956,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 1189,
        "ordered_items": 122,
        "sell_earnings": 562,
        "commissions": 562,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7408,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 1396,
        "ordered_items": 137,
        "sell_earnings": 449,
        "commissions": 449,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7400,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 1944,
        "ordered_items": 147,
        "sell_earnings": 807,
        "commissions": 807,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7486,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 2151,
        "ordered_items": 162,
        "sell_earnings": 694,
        "commissions": 694,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7478,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 1786,
        "ordered_items": 166,
        "sell_earnings": 723,
        "commissions": 723,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7930,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 1377,
        "ordered_items": 121,
        "sell_earnings": 554,
        "commissions": 554,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7330,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 1278,
        "ordered_items": 119,
        "sell_earnings": 544,
        "commissions": 544,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5539,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 1515,
        "ordered_items": 119,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6540,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 1825,
        "ordered_items": 165,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 168,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8346,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 2062,
        "ordered_items": 165,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 165,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9347,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 1963,
        "ordered_items": 163,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7556,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 1214,
        "ordered_items": 135,
        "sell_earnings": 570,
        "commissions": 570,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5434,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 2126,
        "ordered_items": 149,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9452,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 1256,
        "ordered_items": 110,
        "sell_earnings": 523,
        "commissions": 523,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7237,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 2084,
        "ordered_items": 174,
        "sell_earnings": 733,
        "commissions": 733,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7649,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 1346,
        "ordered_items": 129,
        "sell_earnings": 537,
        "commissions": 537,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5586,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 1615,
        "ordered_items": 126,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6731,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 1451,
        "ordered_items": 126,
        "sell_earnings": 580,
        "commissions": 580,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6844,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 1421,
        "ordered_items": 102,
        "sell_earnings": 566,
        "commissions": 566,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6440,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 1919,
        "ordered_items": 182,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8446,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 1889,
        "ordered_items": 158,
        "sell_earnings": 676,
        "commissions": 676,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 167,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8042,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 1725,
        "ordered_items": 158,
        "sell_earnings": 638,
        "commissions": 638,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8155,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 1994,
        "ordered_items": 155,
        "sell_earnings": 719,
        "commissions": 719,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9300,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 1495,
        "ordered_items": 115,
        "sell_earnings": 585,
        "commissions": 585,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6994,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 1265,
        "ordered_items": 101,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5351,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 2075,
        "ordered_items": 183,
        "sell_earnings": 752,
        "commissions": 752,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9535,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 1845,
        "ordered_items": 169,
        "sell_earnings": 671,
        "commissions": 671,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7892,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 1223,
        "ordered_items": 114,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7107,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 2117,
        "ordered_items": 170,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7779,
        "bonus": 1
    }
];