export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1483,
        "ordered_items": 135,
        "sell_earnings": 470,
        "commissions": 470,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6870,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1216,
        "ordered_items": 97,
        "sell_earnings": 556,
        "commissions": 556,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5899,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1148,
        "ordered_items": 122,
        "sell_earnings": 588,
        "commissions": 588,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5795,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 2084,
        "ordered_items": 152,
        "sell_earnings": 628,
        "commissions": 628,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8611,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 2016,
        "ordered_items": 177,
        "sell_earnings": 660,
        "commissions": 660,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8507,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 1749,
        "ordered_items": 139,
        "sell_earnings": 746,
        "commissions": 746,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7536,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1402,
        "ordered_items": 113,
        "sell_earnings": 547,
        "commissions": 547,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6277,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1529,
        "ordered_items": 128,
        "sell_earnings": 607,
        "commissions": 607,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5275,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1204,
        "ordered_items": 109,
        "sell_earnings": 428,
        "commissions": 428,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5911,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 2028,
        "ordered_items": 165,
        "sell_earnings": 788,
        "commissions": 788,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8495,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1703,
        "ordered_items": 146,
        "sell_earnings": 609,
        "commissions": 609,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9131,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 1830,
        "ordered_items": 161,
        "sell_earnings": 669,
        "commissions": 669,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8129,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1343,
        "ordered_items": 118,
        "sell_earnings": 451,
        "commissions": 451,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6175,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 1889,
        "ordered_items": 156,
        "sell_earnings": 765,
        "commissions": 765,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8231,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1612,
        "ordered_items": 129,
        "sell_earnings": 509,
        "commissions": 509,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5940,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 1620,
        "ordered_items": 145,
        "sell_earnings": 707,
        "commissions": 707,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8466,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1603,
        "ordered_items": 128,
        "sell_earnings": 442,
        "commissions": 442,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5442,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1498,
        "ordered_items": 98,
        "sell_earnings": 576,
        "commissions": 576,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7149,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1613,
        "ordered_items": 137,
        "sell_earnings": 438,
        "commissions": 438,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6296,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1586,
        "ordered_items": 97,
        "sell_earnings": 452,
        "commissions": 452,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6475,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 1646,
        "ordered_items": 177,
        "sell_earnings": 764,
        "commissions": 764,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7931,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 1619,
        "ordered_items": 137,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8110,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 1734,
        "ordered_items": 176,
        "sell_earnings": 640,
        "commissions": 640,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7257,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 1629,
        "ordered_items": 146,
        "sell_earnings": 774,
        "commissions": 774,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8964,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1306,
        "ordered_items": 101,
        "sell_earnings": 444,
        "commissions": 444,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6767,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1351,
        "ordered_items": 102,
        "sell_earnings": 570,
        "commissions": 570,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5211,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1881,
        "ordered_items": 172,
        "sell_earnings": 646,
        "commissions": 646,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9195,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 1926,
        "ordered_items": 173,
        "sell_earnings": 772,
        "commissions": 772,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7639,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1184,
        "ordered_items": 125,
        "sell_earnings": 570,
        "commissions": 570,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6236,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 2048,
        "ordered_items": 149,
        "sell_earnings": 646,
        "commissions": 646,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8170,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];