export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1527,
        "ordered_items": 128,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5066,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1364,
        "ordered_items": 103,
        "sell_earnings": 469,
        "commissions": 469,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6855,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1450,
        "ordered_items": 97,
        "sell_earnings": 441,
        "commissions": 441,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6992,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 1782,
        "ordered_items": 177,
        "sell_earnings": 775,
        "commissions": 775,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7414,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 1868,
        "ordered_items": 171,
        "sell_earnings": 747,
        "commissions": 747,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7551,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 1705,
        "ordered_items": 146,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9340,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1580,
        "ordered_items": 130,
        "sell_earnings": 453,
        "commissions": 453,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5332,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1438,
        "ordered_items": 98,
        "sell_earnings": 586,
        "commissions": 586,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6745,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1515,
        "ordered_items": 107,
        "sell_earnings": 462,
        "commissions": 462,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6754,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 1717,
        "ordered_items": 167,
        "sell_earnings": 754,
        "commissions": 754,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7652,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 1794,
        "ordered_items": 176,
        "sell_earnings": 630,
        "commissions": 630,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7661,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 1652,
        "ordered_items": 144,
        "sell_earnings": 763,
        "commissions": 763,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9074,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1571,
        "ordered_items": 102,
        "sell_earnings": 545,
        "commissions": 545,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6117,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 1661,
        "ordered_items": 172,
        "sell_earnings": 671,
        "commissions": 671,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8289,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1146,
        "ordered_items": 122,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7155,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 2086,
        "ordered_items": 152,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7251,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1255,
        "ordered_items": 118,
        "sell_earnings": 452,
        "commissions": 452,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6733,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1284,
        "ordered_items": 111,
        "sell_earnings": 512,
        "commissions": 512,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5102,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1253,
        "ordered_items": 117,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6959,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1462,
        "ordered_items": 125,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7078,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 1770,
        "ordered_items": 149,
        "sell_earnings": 753,
        "commissions": 753,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7328,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1979,
        "ordered_items": 157,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7447,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 1948,
        "ordered_items": 163,
        "sell_earnings": 704,
        "commissions": 704,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9304,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 1977,
        "ordered_items": 156,
        "sell_earnings": 764,
        "commissions": 764,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7673,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1581,
        "ordered_items": 110,
        "sell_earnings": 466,
        "commissions": 466,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6324,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1246,
        "ordered_items": 108,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5100,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 1986,
        "ordered_items": 166,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9306,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1651,
        "ordered_items": 164,
        "sell_earnings": 750,
        "commissions": 750,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8082,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1267,
        "ordered_items": 106,
        "sell_earnings": 599,
        "commissions": 599,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5586,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 1965,
        "ordered_items": 168,
        "sell_earnings": 617,
        "commissions": 617,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8820,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];