export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1536,
        "ordered_items": 98,
        "sell_earnings": 468,
        "commissions": 468,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6425,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1259,
        "ordered_items": 107,
        "sell_earnings": 529,
        "commissions": 529,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6188,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1219,
        "ordered_items": 122,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7159,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 2013,
        "ordered_items": 152,
        "sell_earnings": 753,
        "commissions": 753,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7247,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 1973,
        "ordered_items": 167,
        "sell_earnings": 687,
        "commissions": 687,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8218,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 1696,
        "ordered_items": 176,
        "sell_earnings": 748,
        "commissions": 748,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7981,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1566,
        "ordered_items": 106,
        "sell_earnings": 457,
        "commissions": 457,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5570,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1572,
        "ordered_items": 134,
        "sell_earnings": 594,
        "commissions": 594,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6143,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1186,
        "ordered_items": 124,
        "sell_earnings": 586,
        "commissions": 586,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6449,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 2046,
        "ordered_items": 150,
        "sell_earnings": 630,
        "commissions": 630,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7957,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 1660,
        "ordered_items": 140,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8263,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 1666,
        "ordered_items": 168,
        "sell_earnings": 759,
        "commissions": 759,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8836,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1132,
        "ordered_items": 97,
        "sell_earnings": 524,
        "commissions": 524,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6617,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 2100,
        "ordered_items": 177,
        "sell_earnings": 692,
        "commissions": 692,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7789,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1161,
        "ordered_items": 134,
        "sell_earnings": 508,
        "commissions": 508,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6739,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 2071,
        "ordered_items": 140,
        "sell_earnings": 708,
        "commissions": 708,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7667,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1595,
        "ordered_items": 130,
        "sell_earnings": 539,
        "commissions": 539,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5670,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1237,
        "ordered_items": 115,
        "sell_earnings": 584,
        "commissions": 584,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6514,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1211,
        "ordered_items": 122,
        "sell_earnings": 585,
        "commissions": 585,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5933,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1153,
        "ordered_items": 129,
        "sell_earnings": 508,
        "commissions": 508,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5345,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 2079,
        "ordered_items": 145,
        "sell_earnings": 708,
        "commissions": 708,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9061,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 2021,
        "ordered_items": 152,
        "sell_earnings": 631,
        "commissions": 631,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8473,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 1995,
        "ordered_items": 159,
        "sell_earnings": 632,
        "commissions": 632,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7892,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 1637,
        "ordered_items": 144,
        "sell_earnings": 677,
        "commissions": 677,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8736,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1134,
        "ordered_items": 97,
        "sell_earnings": 573,
        "commissions": 573,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5175,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1419,
        "ordered_items": 134,
        "sell_earnings": 511,
        "commissions": 511,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5600,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 1813,
        "ordered_items": 140,
        "sell_earnings": 705,
        "commissions": 705,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8806,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 2098,
        "ordered_items": 177,
        "sell_earnings": 643,
        "commissions": 643,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9231,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1182,
        "ordered_items": 124,
        "sell_earnings": 506,
        "commissions": 506,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6382,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 2050,
        "ordered_items": 150,
        "sell_earnings": 710,
        "commissions": 710,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8024,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];