export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1503,
        "ordered_items": 133,
        "sell_earnings": 498,
        "commissions": 498,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6362,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1258,
        "ordered_items": 107,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6041,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1625,
        "ordered_items": 116,
        "sell_earnings": 483,
        "commissions": 483,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5620,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 1715,
        "ordered_items": 168,
        "sell_earnings": 773,
        "commissions": 773,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9266,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 2082,
        "ordered_items": 177,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8845,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 1837,
        "ordered_items": 151,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 169,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8524,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1240,
        "ordered_items": 117,
        "sell_earnings": 571,
        "commissions": 571,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5929,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1346,
        "ordered_items": 139,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5754,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1273,
        "ordered_items": 100,
        "sell_earnings": 587,
        "commissions": 587,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5930,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 2067,
        "ordered_items": 184,
        "sell_earnings": 669,
        "commissions": 669,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8956,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 1994,
        "ordered_items": 145,
        "sell_earnings": 776,
        "commissions": 776,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9132,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 2100,
        "ordered_items": 167,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8957,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1184,
        "ordered_items": 129,
        "sell_earnings": 560,
        "commissions": 560,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5946,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 2156,
        "ordered_items": 155,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8940,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1399,
        "ordered_items": 137,
        "sell_earnings": 457,
        "commissions": 457,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6672,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 1941,
        "ordered_items": 147,
        "sell_earnings": 799,
        "commissions": 799,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8214,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1319,
        "ordered_items": 111,
        "sell_earnings": 451,
        "commissions": 451,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6840,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1371,
        "ordered_items": 104,
        "sell_earnings": 587,
        "commissions": 587,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6979,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1232,
        "ordered_items": 107,
        "sell_earnings": 508,
        "commissions": 508,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6234,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1321,
        "ordered_items": 125,
        "sell_earnings": 583,
        "commissions": 583,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6120,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 2019,
        "ordered_items": 159,
        "sell_earnings": 673,
        "commissions": 673,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8766,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 2108,
        "ordered_items": 177,
        "sell_earnings": 748,
        "commissions": 748,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 167,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8652,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 1969,
        "ordered_items": 180,
        "sell_earnings": 669,
        "commissions": 669,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7907,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 2021,
        "ordered_items": 173,
        "sell_earnings": 805,
        "commissions": 805,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8046,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1488,
        "ordered_items": 128,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5949,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1520,
        "ordered_items": 129,
        "sell_earnings": 524,
        "commissions": 524,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5574,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 1820,
        "ordered_items": 155,
        "sell_earnings": 732,
        "commissions": 732,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9312,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 1852,
        "ordered_items": 156,
        "sell_earnings": 798,
        "commissions": 798,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8937,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1349,
        "ordered_items": 121,
        "sell_earnings": 542,
        "commissions": 542,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5667,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 1991,
        "ordered_items": 163,
        "sell_earnings": 714,
        "commissions": 714,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9219,
        "bonus": 0
    }
];