export let mar = [
    {
        "month": "Mar",
        "day": "01",
        "clicks": 1432,
        "ordered_items": 111,
        "sell_earnings": 551,
        "commissions": 551,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6720,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "02",
        "clicks": 1376,
        "ordered_items": 110,
        "sell_earnings": 560,
        "commissions": 560,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6433,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "03",
        "clicks": 1193,
        "ordered_items": 117,
        "sell_earnings": 435,
        "commissions": 435,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6086,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "04",
        "clicks": 2039,
        "ordered_items": 157,
        "sell_earnings": 781,
        "commissions": 781,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8320,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "05",
        "clicks": 1856,
        "ordered_items": 164,
        "sell_earnings": 656,
        "commissions": 656,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7973,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "06",
        "clicks": 1800,
        "ordered_items": 163,
        "sell_earnings": 665,
        "commissions": 665,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7686,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "07",
        "clicks": 1559,
        "ordered_items": 127,
        "sell_earnings": 444,
        "commissions": 444,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5423,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "08",
        "clicks": 1301,
        "ordered_items": 109,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6228,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "09",
        "clicks": 1400,
        "ordered_items": 131,
        "sell_earnings": 566,
        "commissions": 566,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7070,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "10",
        "clicks": 1832,
        "ordered_items": 143,
        "sell_earnings": 650,
        "commissions": 650,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7336,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "11",
        "clicks": 1931,
        "ordered_items": 165,
        "sell_earnings": 752,
        "commissions": 752,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8178,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "12",
        "clicks": 1673,
        "ordered_items": 147,
        "sell_earnings": 772,
        "commissions": 772,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8983,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "13",
        "clicks": 1224,
        "ordered_items": 112,
        "sell_earnings": 484,
        "commissions": 484,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7188,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "14",
        "clicks": 2008,
        "ordered_items": 162,
        "sell_earnings": 732,
        "commissions": 732,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7218,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "15",
        "clicks": 1509,
        "ordered_items": 135,
        "sell_earnings": 579,
        "commissions": 579,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5701,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "16",
        "clicks": 1723,
        "ordered_items": 139,
        "sell_earnings": 637,
        "commissions": 637,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8705,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "17",
        "clicks": 1436,
        "ordered_items": 102,
        "sell_earnings": 433,
        "commissions": 433,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5967,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "18",
        "clicks": 1260,
        "ordered_items": 106,
        "sell_earnings": 461,
        "commissions": 461,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6494,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "19",
        "clicks": 1329,
        "ordered_items": 106,
        "sell_earnings": 554,
        "commissions": 554,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5588,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "20",
        "clicks": 1500,
        "ordered_items": 101,
        "sell_earnings": 547,
        "commissions": 547,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6999,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "21",
        "clicks": 1732,
        "ordered_items": 173,
        "sell_earnings": 669,
        "commissions": 669,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7407,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "22",
        "clicks": 1903,
        "ordered_items": 168,
        "sell_earnings": 662,
        "commissions": 662,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8818,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "23",
        "clicks": 1972,
        "ordered_items": 168,
        "sell_earnings": 755,
        "commissions": 755,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7912,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "24",
        "clicks": 1796,
        "ordered_items": 172,
        "sell_earnings": 783,
        "commissions": 783,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8439,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "25",
        "clicks": 1522,
        "ordered_items": 110,
        "sell_earnings": 558,
        "commissions": 558,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6115,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "26",
        "clicks": 1223,
        "ordered_items": 103,
        "sell_earnings": 525,
        "commissions": 525,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5989,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "27",
        "clicks": 2009,
        "ordered_items": 171,
        "sell_earnings": 691,
        "commissions": 691,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8417,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "28",
        "clicks": 1710,
        "ordered_items": 164,
        "sell_earnings": 658,
        "commissions": 658,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8291,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "29",
        "clicks": 1373,
        "ordered_items": 101,
        "sell_earnings": 483,
        "commissions": 483,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5398,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "30",
        "clicks": 1859,
        "ordered_items": 173,
        "sell_earnings": 733,
        "commissions": 733,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9008,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];