export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1464,
        "ordered_items": 104,
        "sell_earnings": 577,
        "commissions": 577,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6773,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1279,
        "ordered_items": 125,
        "sell_earnings": 543,
        "commissions": 543,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5966,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1637,
        "ordered_items": 117,
        "sell_earnings": 521,
        "commissions": 521,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6417,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 1703,
        "ordered_items": 167,
        "sell_earnings": 735,
        "commissions": 735,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8469,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 2061,
        "ordered_items": 159,
        "sell_earnings": 713,
        "commissions": 713,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8920,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 1876,
        "ordered_items": 180,
        "sell_earnings": 679,
        "commissions": 679,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 166,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8113,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1485,
        "ordered_items": 120,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6107,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1618,
        "ordered_items": 142,
        "sell_earnings": 556,
        "commissions": 556,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5378,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1196,
        "ordered_items": 102,
        "sell_earnings": 578,
        "commissions": 578,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5597,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 2144,
        "ordered_items": 182,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9289,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 1722,
        "ordered_items": 142,
        "sell_earnings": 700,
        "commissions": 700,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9508,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 1855,
        "ordered_items": 164,
        "sell_earnings": 757,
        "commissions": 757,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8779,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1470,
        "ordered_items": 108,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7134,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 1870,
        "ordered_items": 176,
        "sell_earnings": 691,
        "commissions": 691,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7752,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1654,
        "ordered_items": 129,
        "sell_earnings": 585,
        "commissions": 585,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6592,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 1686,
        "ordered_items": 155,
        "sell_earnings": 671,
        "commissions": 671,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8294,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1337,
        "ordered_items": 108,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6411,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1170,
        "ordered_items": 114,
        "sell_earnings": 560,
        "commissions": 560,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6731,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1335,
        "ordered_items": 111,
        "sell_earnings": 530,
        "commissions": 530,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6646,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1235,
        "ordered_items": 113,
        "sell_earnings": 473,
        "commissions": 473,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6436,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 2105,
        "ordered_items": 171,
        "sell_earnings": 783,
        "commissions": 783,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8450,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 2005,
        "ordered_items": 173,
        "sell_earnings": 726,
        "commissions": 726,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8240,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 2170,
        "ordered_items": 170,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8155,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 2003,
        "ordered_items": 176,
        "sell_earnings": 810,
        "commissions": 810,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8475,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1465,
        "ordered_items": 112,
        "sell_earnings": 559,
        "commissions": 559,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7322,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1188,
        "ordered_items": 114,
        "sell_earnings": 516,
        "commissions": 516,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6376,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 2152,
        "ordered_items": 170,
        "sell_earnings": 740,
        "commissions": 740,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8510,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 1875,
        "ordered_items": 172,
        "sell_earnings": 697,
        "commissions": 697,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7564,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1605,
        "ordered_items": 107,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7250,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 1735,
        "ordered_items": 177,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7636,
        "bonus": 2
    }
];