export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1566,
        "ordered_items": 122,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7166,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1345,
        "ordered_items": 132,
        "sell_earnings": 533,
        "commissions": 533,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5615,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1543,
        "ordered_items": 132,
        "sell_earnings": 483,
        "commissions": 483,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5762,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 1689,
        "ordered_items": 142,
        "sell_earnings": 733,
        "commissions": 733,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8644,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1887,
        "ordered_items": 142,
        "sell_earnings": 683,
        "commissions": 683,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8791,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 1666,
        "ordered_items": 152,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7240,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1350,
        "ordered_items": 128,
        "sell_earnings": 552,
        "commissions": 552,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6075,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1228,
        "ordered_items": 109,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6215,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1135,
        "ordered_items": 107,
        "sell_earnings": 453,
        "commissions": 453,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7015,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 2097,
        "ordered_items": 167,
        "sell_earnings": 763,
        "commissions": 763,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7391,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 2004,
        "ordered_items": 165,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8191,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1882,
        "ordered_items": 146,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8331,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1604,
        "ordered_items": 124,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5444,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1628,
        "ordered_items": 150,
        "sell_earnings": 753,
        "commissions": 753,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8962,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1293,
        "ordered_items": 98,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5233,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1939,
        "ordered_items": 176,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9173,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1409,
        "ordered_items": 130,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6968,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1159,
        "ordered_items": 105,
        "sell_earnings": 441,
        "commissions": 441,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6848,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1205,
        "ordered_items": 104,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6448,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1299,
        "ordered_items": 105,
        "sell_earnings": 476,
        "commissions": 476,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6710,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 1933,
        "ordered_items": 169,
        "sell_earnings": 740,
        "commissions": 740,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7696,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 2027,
        "ordered_items": 170,
        "sell_earnings": 651,
        "commissions": 651,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7958,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 2073,
        "ordered_items": 169,
        "sell_earnings": 775,
        "commissions": 775,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7558,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1823,
        "ordered_items": 144,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7438,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1554,
        "ordered_items": 99,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5729,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1147,
        "ordered_items": 126,
        "sell_earnings": 470,
        "commissions": 470,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5727,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 2085,
        "ordered_items": 148,
        "sell_earnings": 746,
        "commissions": 746,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8679,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1678,
        "ordered_items": 175,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8677,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1459,
        "ordered_items": 131,
        "sell_earnings": 555,
        "commissions": 555,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6492,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1773,
        "ordered_items": 143,
        "sell_earnings": 661,
        "commissions": 661,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7914,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];