export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1147,
        "ordered_items": 102,
        "sell_earnings": 536,
        "commissions": 536,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5768,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1186,
        "ordered_items": 137,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5364,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1457,
        "ordered_items": 123,
        "sell_earnings": 444,
        "commissions": 444,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7011,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 1775,
        "ordered_items": 151,
        "sell_earnings": 772,
        "commissions": 772,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7395,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 2046,
        "ordered_items": 137,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9042,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 2085,
        "ordered_items": 172,
        "sell_earnings": 680,
        "commissions": 680,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8638,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1414,
        "ordered_items": 109,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5271,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1264,
        "ordered_items": 113,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6566,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1394,
        "ordered_items": 100,
        "sell_earnings": 525,
        "commissions": 525,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5699,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 1838,
        "ordered_items": 174,
        "sell_earnings": 691,
        "commissions": 691,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8707,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1968,
        "ordered_items": 161,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7840,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 1818,
        "ordered_items": 165,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9135,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1211,
        "ordered_items": 99,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6192,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 2021,
        "ordered_items": 175,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8214,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1137,
        "ordered_items": 133,
        "sell_earnings": 584,
        "commissions": 584,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5388,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 2095,
        "ordered_items": 141,
        "sell_earnings": 632,
        "commissions": 632,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9018,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1424,
        "ordered_items": 100,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5100,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1429,
        "ordered_items": 110,
        "sell_earnings": 518,
        "commissions": 518,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5278,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1463,
        "ordered_items": 129,
        "sell_earnings": 582,
        "commissions": 582,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5062,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1536,
        "ordered_items": 128,
        "sell_earnings": 550,
        "commissions": 550,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6125,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 1696,
        "ordered_items": 146,
        "sell_earnings": 666,
        "commissions": 666,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8281,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 1769,
        "ordered_items": 145,
        "sell_earnings": 634,
        "commissions": 634,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9344,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 1803,
        "ordered_items": 164,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9128,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 1808,
        "ordered_items": 174,
        "sell_earnings": 676,
        "commissions": 676,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9306,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1180,
        "ordered_items": 122,
        "sell_earnings": 557,
        "commissions": 557,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6973,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1561,
        "ordered_items": 122,
        "sell_earnings": 539,
        "commissions": 539,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5358,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1671,
        "ordered_items": 152,
        "sell_earnings": 677,
        "commissions": 677,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9048,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 2052,
        "ordered_items": 152,
        "sell_earnings": 659,
        "commissions": 659,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7433,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1297,
        "ordered_items": 104,
        "sell_earnings": 501,
        "commissions": 501,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5093,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 1935,
        "ordered_items": 170,
        "sell_earnings": 715,
        "commissions": 715,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9313,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];