export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1273,
        "ordered_items": 111,
        "sell_earnings": 557,
        "commissions": 557,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5576,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1250,
        "ordered_items": 135,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5886,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1477,
        "ordered_items": 122,
        "sell_earnings": 557,
        "commissions": 557,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6515,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 1755,
        "ordered_items": 152,
        "sell_earnings": 659,
        "commissions": 659,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7891,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 1982,
        "ordered_items": 139,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8520,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 1959,
        "ordered_items": 163,
        "sell_earnings": 659,
        "commissions": 659,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8830,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1205,
        "ordered_items": 110,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7069,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1184,
        "ordered_items": 125,
        "sell_earnings": 475,
        "commissions": 475,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5434,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1472,
        "ordered_items": 125,
        "sell_earnings": 551,
        "commissions": 551,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7052,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 1760,
        "ordered_items": 149,
        "sell_earnings": 665,
        "commissions": 665,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7354,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 2048,
        "ordered_items": 149,
        "sell_earnings": 741,
        "commissions": 741,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8972,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 2027,
        "ordered_items": 164,
        "sell_earnings": 752,
        "commissions": 752,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7337,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1608,
        "ordered_items": 104,
        "sell_earnings": 474,
        "commissions": 474,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6279,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 1624,
        "ordered_items": 170,
        "sell_earnings": 742,
        "commissions": 742,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8127,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1222,
        "ordered_items": 106,
        "sell_earnings": 586,
        "commissions": 586,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5667,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 2010,
        "ordered_items": 168,
        "sell_earnings": 630,
        "commissions": 630,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8739,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1278,
        "ordered_items": 109,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6425,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1483,
        "ordered_items": 134,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6481,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1521,
        "ordered_items": 101,
        "sell_earnings": 532,
        "commissions": 532,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6944,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1509,
        "ordered_items": 112,
        "sell_earnings": 478,
        "commissions": 478,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6838,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 1723,
        "ordered_items": 162,
        "sell_earnings": 738,
        "commissions": 738,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7568,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 1711,
        "ordered_items": 173,
        "sell_earnings": 684,
        "commissions": 684,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7462,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 1749,
        "ordered_items": 140,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7925,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 1954,
        "ordered_items": 165,
        "sell_earnings": 676,
        "commissions": 676,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7981,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1258,
        "ordered_items": 124,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7091,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1261,
        "ordered_items": 108,
        "sell_earnings": 473,
        "commissions": 473,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6691,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 1971,
        "ordered_items": 166,
        "sell_earnings": 743,
        "commissions": 743,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7715,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 1974,
        "ordered_items": 150,
        "sell_earnings": 610,
        "commissions": 610,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7315,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1451,
        "ordered_items": 122,
        "sell_earnings": 467,
        "commissions": 467,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6245,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 1781,
        "ordered_items": 152,
        "sell_earnings": 749,
        "commissions": 749,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8161,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];