export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1509,
        "ordered_items": 132,
        "sell_earnings": 448,
        "commissions": 448,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5639,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1603,
        "ordered_items": 129,
        "sell_earnings": 462,
        "commissions": 462,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6118,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1630,
        "ordered_items": 110,
        "sell_earnings": 572,
        "commissions": 572,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6111,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 1710,
        "ordered_items": 174,
        "sell_earnings": 684,
        "commissions": 684,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8775,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 1737,
        "ordered_items": 155,
        "sell_earnings": 794,
        "commissions": 794,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8768,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 1831,
        "ordered_items": 152,
        "sell_earnings": 808,
        "commissions": 808,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9247,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1389,
        "ordered_items": 119,
        "sell_earnings": 443,
        "commissions": 443,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6880,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1561,
        "ordered_items": 142,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6944,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1306,
        "ordered_items": 109,
        "sell_earnings": 567,
        "commissions": 567,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5797,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 2034,
        "ordered_items": 175,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9089,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 1779,
        "ordered_items": 142,
        "sell_earnings": 650,
        "commissions": 650,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7942,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 1951,
        "ordered_items": 165,
        "sell_earnings": 813,
        "commissions": 813,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8006,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1665,
        "ordered_items": 101,
        "sell_earnings": 448,
        "commissions": 448,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5910,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 1675,
        "ordered_items": 183,
        "sell_earnings": 808,
        "commissions": 808,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8976,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1491,
        "ordered_items": 101,
        "sell_earnings": 587,
        "commissions": 587,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6419,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 1849,
        "ordered_items": 183,
        "sell_earnings": 669,
        "commissions": 669,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8467,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1516,
        "ordered_items": 123,
        "sell_earnings": 489,
        "commissions": 489,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6431,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1460,
        "ordered_items": 126,
        "sell_earnings": 479,
        "commissions": 479,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5724,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1654,
        "ordered_items": 101,
        "sell_earnings": 507,
        "commissions": 507,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6892,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1316,
        "ordered_items": 135,
        "sell_earnings": 556,
        "commissions": 556,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6782,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 2024,
        "ordered_items": 149,
        "sell_earnings": 700,
        "commissions": 700,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 165,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8104,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 1686,
        "ordered_items": 183,
        "sell_earnings": 749,
        "commissions": 749,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7994,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 1880,
        "ordered_items": 158,
        "sell_earnings": 777,
        "commissions": 777,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9162,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 1824,
        "ordered_items": 161,
        "sell_earnings": 767,
        "commissions": 767,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8455,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1546,
        "ordered_items": 124,
        "sell_earnings": 583,
        "commissions": 583,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5439,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1370,
        "ordered_items": 132,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5645,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 1970,
        "ordered_items": 152,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9241,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 1794,
        "ordered_items": 160,
        "sell_earnings": 673,
        "commissions": 673,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9447,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1228,
        "ordered_items": 102,
        "sell_earnings": 559,
        "commissions": 559,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7183,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 2112,
        "ordered_items": 182,
        "sell_earnings": 697,
        "commissions": 697,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7703,
        "bonus": 2
    }
];