export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1428,
        "ordered_items": 116,
        "sell_earnings": 440,
        "commissions": 440,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5880,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1350,
        "ordered_items": 111,
        "sell_earnings": 578,
        "commissions": 578,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6204,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1298,
        "ordered_items": 118,
        "sell_earnings": 601,
        "commissions": 601,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6443,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 1934,
        "ordered_items": 156,
        "sell_earnings": 615,
        "commissions": 615,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7963,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 1882,
        "ordered_items": 163,
        "sell_earnings": 638,
        "commissions": 638,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8202,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 1804,
        "ordered_items": 158,
        "sell_earnings": 776,
        "commissions": 776,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8526,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1534,
        "ordered_items": 130,
        "sell_earnings": 539,
        "commissions": 539,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7033,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1587,
        "ordered_items": 97,
        "sell_earnings": 475,
        "commissions": 475,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7011,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1196,
        "ordered_items": 106,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6158,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 2036,
        "ordered_items": 168,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8248,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 1645,
        "ordered_items": 177,
        "sell_earnings": 741,
        "commissions": 741,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7395,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1698,
        "ordered_items": 144,
        "sell_earnings": 677,
        "commissions": 677,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7373,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1411,
        "ordered_items": 113,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6562,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 1821,
        "ordered_items": 161,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7844,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1579,
        "ordered_items": 137,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6625,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 1653,
        "ordered_items": 137,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7781,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1331,
        "ordered_items": 128,
        "sell_earnings": 591,
        "commissions": 591,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6934,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1603,
        "ordered_items": 116,
        "sell_earnings": 531,
        "commissions": 531,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6168,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1282,
        "ordered_items": 110,
        "sell_earnings": 580,
        "commissions": 580,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5977,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1383,
        "ordered_items": 132,
        "sell_earnings": 523,
        "commissions": 523,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6914,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 1849,
        "ordered_items": 142,
        "sell_earnings": 693,
        "commissions": 693,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7492,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 1950,
        "ordered_items": 164,
        "sell_earnings": 636,
        "commissions": 636,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8429,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 1629,
        "ordered_items": 158,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8238,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1901,
        "ordered_items": 146,
        "sell_earnings": 625,
        "commissions": 625,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7472,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1391,
        "ordered_items": 121,
        "sell_earnings": 441,
        "commissions": 441,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5566,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1447,
        "ordered_items": 97,
        "sell_earnings": 543,
        "commissions": 543,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6101,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 1785,
        "ordered_items": 177,
        "sell_earnings": 673,
        "commissions": 673,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8305,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 1841,
        "ordered_items": 153,
        "sell_earnings": 775,
        "commissions": 775,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8840,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1530,
        "ordered_items": 106,
        "sell_earnings": 447,
        "commissions": 447,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5069,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 1702,
        "ordered_items": 168,
        "sell_earnings": 769,
        "commissions": 769,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9337,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];