export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1271,
        "ordered_items": 132,
        "sell_earnings": 619,
        "commissions": 619,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6333,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1568,
        "ordered_items": 127,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5685,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1461,
        "ordered_items": 142,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5500,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 1879,
        "ordered_items": 142,
        "sell_earnings": 765,
        "commissions": 765,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9386,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 1772,
        "ordered_items": 157,
        "sell_earnings": 638,
        "commissions": 638,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 167,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9201,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 2069,
        "ordered_items": 152,
        "sell_earnings": 637,
        "commissions": 637,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8553,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1247,
        "ordered_items": 132,
        "sell_earnings": 558,
        "commissions": 558,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5862,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1405,
        "ordered_items": 121,
        "sell_earnings": 558,
        "commissions": 558,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5319,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1580,
        "ordered_items": 117,
        "sell_earnings": 594,
        "commissions": 594,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7359,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 1760,
        "ordered_items": 167,
        "sell_earnings": 662,
        "commissions": 662,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7527,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 1935,
        "ordered_items": 163,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9567,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 2093,
        "ordered_items": 152,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 165,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9024,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1267,
        "ordered_items": 101,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6101,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 2073,
        "ordered_items": 183,
        "sell_earnings": 810,
        "commissions": 810,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8785,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1301,
        "ordered_items": 109,
        "sell_earnings": 472,
        "commissions": 472,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5809,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 2039,
        "ordered_items": 175,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 165,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9077,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1324,
        "ordered_items": 124,
        "sell_earnings": 544,
        "commissions": 544,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6490,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1652,
        "ordered_items": 109,
        "sell_earnings": 466,
        "commissions": 466,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5460,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1197,
        "ordered_items": 142,
        "sell_earnings": 454,
        "commissions": 454,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7337,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1374,
        "ordered_items": 132,
        "sell_earnings": 524,
        "commissions": 524,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6806,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 1966,
        "ordered_items": 152,
        "sell_earnings": 732,
        "commissions": 732,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 168,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8080,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 2143,
        "ordered_items": 142,
        "sell_earnings": 802,
        "commissions": 802,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7549,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 1688,
        "ordered_items": 175,
        "sell_earnings": 790,
        "commissions": 790,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 166,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9426,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 2016,
        "ordered_items": 160,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8396,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1204,
        "ordered_items": 138,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5900,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1330,
        "ordered_items": 105,
        "sell_earnings": 486,
        "commissions": 486,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6818,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 2010,
        "ordered_items": 179,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8068,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 2136,
        "ordered_items": 146,
        "sell_earnings": 729,
        "commissions": 729,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8986,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1293,
        "ordered_items": 125,
        "sell_earnings": 557,
        "commissions": 557,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7258,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 2047,
        "ordered_items": 159,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 165,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7628,
        "bonus": 0
    }
];