export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1219,
        "ordered_items": 109,
        "sell_earnings": 437,
        "commissions": 437,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5557,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1247,
        "ordered_items": 133,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6050,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1262,
        "ordered_items": 110,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5632,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 1970,
        "ordered_items": 164,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8774,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1985,
        "ordered_items": 141,
        "sell_earnings": 676,
        "commissions": 676,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8356,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 2013,
        "ordered_items": 165,
        "sell_earnings": 779,
        "commissions": 779,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8849,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1588,
        "ordered_items": 110,
        "sell_earnings": 522,
        "commissions": 522,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5742,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1567,
        "ordered_items": 99,
        "sell_earnings": 431,
        "commissions": 431,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6230,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1335,
        "ordered_items": 117,
        "sell_earnings": 541,
        "commissions": 541,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5120,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1897,
        "ordered_items": 157,
        "sell_earnings": 675,
        "commissions": 675,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9286,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 1665,
        "ordered_items": 175,
        "sell_earnings": 785,
        "commissions": 785,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8176,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1644,
        "ordered_items": 164,
        "sell_earnings": 694,
        "commissions": 694,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8664,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1365,
        "ordered_items": 123,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7093,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1867,
        "ordered_items": 151,
        "sell_earnings": 752,
        "commissions": 752,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7313,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1280,
        "ordered_items": 108,
        "sell_earnings": 556,
        "commissions": 556,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6442,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1952,
        "ordered_items": 166,
        "sell_earnings": 660,
        "commissions": 660,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7964,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1276,
        "ordered_items": 128,
        "sell_earnings": 503,
        "commissions": 503,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5645,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1309,
        "ordered_items": 123,
        "sell_earnings": 539,
        "commissions": 539,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5221,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1486,
        "ordered_items": 116,
        "sell_earnings": 457,
        "commissions": 457,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5513,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1463,
        "ordered_items": 98,
        "sell_earnings": 552,
        "commissions": 552,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7133,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 1769,
        "ordered_items": 176,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7273,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1746,
        "ordered_items": 158,
        "sell_earnings": 759,
        "commissions": 759,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8893,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 1923,
        "ordered_items": 151,
        "sell_earnings": 677,
        "commissions": 677,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9185,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1956,
        "ordered_items": 146,
        "sell_earnings": 713,
        "commissions": 713,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8761,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1139,
        "ordered_items": 117,
        "sell_earnings": 558,
        "commissions": 558,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5780,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1367,
        "ordered_items": 130,
        "sell_earnings": 539,
        "commissions": 539,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5908,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1865,
        "ordered_items": 144,
        "sell_earnings": 677,
        "commissions": 677,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8498,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 2093,
        "ordered_items": 157,
        "sell_earnings": 658,
        "commissions": 658,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8626,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1151,
        "ordered_items": 108,
        "sell_earnings": 432,
        "commissions": 432,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5153,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 2081,
        "ordered_items": 166,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9253,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];