export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 1247,
        "ordered_items": 106,
        "sell_earnings": 508,
        "commissions": 508,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5938,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 1364,
        "ordered_items": 112,
        "sell_earnings": 599,
        "commissions": 599,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5864,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 1251,
        "ordered_items": 119,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6289,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 2089,
        "ordered_items": 165,
        "sell_earnings": 798,
        "commissions": 798,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8597,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 1976,
        "ordered_items": 172,
        "sell_earnings": 657,
        "commissions": 657,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9022,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 2093,
        "ordered_items": 178,
        "sell_earnings": 748,
        "commissions": 748,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8948,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 1377,
        "ordered_items": 112,
        "sell_earnings": 567,
        "commissions": 567,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6256,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 1669,
        "ordered_items": 103,
        "sell_earnings": 497,
        "commissions": 497,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6985,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 1551,
        "ordered_items": 138,
        "sell_earnings": 452,
        "commissions": 452,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6427,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 1789,
        "ordered_items": 146,
        "sell_earnings": 804,
        "commissions": 804,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8459,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 1671,
        "ordered_items": 181,
        "sell_earnings": 759,
        "commissions": 759,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 165,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7901,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 1963,
        "ordered_items": 172,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8630,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 1523,
        "ordered_items": 128,
        "sell_earnings": 543,
        "commissions": 543,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6290,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 1817,
        "ordered_items": 156,
        "sell_earnings": 713,
        "commissions": 713,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 168,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8596,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 1199,
        "ordered_items": 101,
        "sell_earnings": 600,
        "commissions": 600,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5381,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 2141,
        "ordered_items": 183,
        "sell_earnings": 656,
        "commissions": 656,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9505,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 1411,
        "ordered_items": 112,
        "sell_earnings": 472,
        "commissions": 472,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6421,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 1648,
        "ordered_items": 135,
        "sell_earnings": 563,
        "commissions": 563,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7413,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 1428,
        "ordered_items": 130,
        "sell_earnings": 628,
        "commissions": 628,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6116,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 1559,
        "ordered_items": 101,
        "sell_earnings": 451,
        "commissions": 451,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6825,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 1781,
        "ordered_items": 183,
        "sell_earnings": 805,
        "commissions": 805,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 167,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8061,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 1912,
        "ordered_items": 154,
        "sell_earnings": 628,
        "commissions": 628,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8770,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 1692,
        "ordered_items": 149,
        "sell_earnings": 693,
        "commissions": 693,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 167,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7473,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 1929,
        "ordered_items": 172,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 167,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8465,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 1459,
        "ordered_items": 101,
        "sell_earnings": 551,
        "commissions": 551,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6840,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 1445,
        "ordered_items": 136,
        "sell_earnings": 590,
        "commissions": 590,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5406,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 1895,
        "ordered_items": 148,
        "sell_earnings": 666,
        "commissions": 666,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9480,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 1881,
        "ordered_items": 183,
        "sell_earnings": 705,
        "commissions": 705,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8046,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 1654,
        "ordered_items": 117,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5536,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 1686,
        "ordered_items": 167,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9350,
        "bonus": 0
    }
];