export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1565,
        "ordered_items": 121,
        "sell_earnings": 519,
        "commissions": 519,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5256,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1258,
        "ordered_items": 118,
        "sell_earnings": 521,
        "commissions": 521,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6638,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1143,
        "ordered_items": 121,
        "sell_earnings": 454,
        "commissions": 454,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6389,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 2089,
        "ordered_items": 153,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8017,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 1974,
        "ordered_items": 156,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7768,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 1667,
        "ordered_items": 153,
        "sell_earnings": 697,
        "commissions": 697,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9150,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1461,
        "ordered_items": 114,
        "sell_earnings": 514,
        "commissions": 514,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6123,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1271,
        "ordered_items": 130,
        "sell_earnings": 485,
        "commissions": 485,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5719,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1411,
        "ordered_items": 132,
        "sell_earnings": 442,
        "commissions": 442,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5094,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 1821,
        "ordered_items": 142,
        "sell_earnings": 774,
        "commissions": 774,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9312,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1961,
        "ordered_items": 144,
        "sell_earnings": 731,
        "commissions": 731,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8687,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 1771,
        "ordered_items": 160,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8283,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1328,
        "ordered_items": 105,
        "sell_earnings": 549,
        "commissions": 549,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7115,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 1904,
        "ordered_items": 169,
        "sell_earnings": 667,
        "commissions": 667,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7291,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1168,
        "ordered_items": 112,
        "sell_earnings": 577,
        "commissions": 577,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6347,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 2064,
        "ordered_items": 162,
        "sell_earnings": 639,
        "commissions": 639,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8059,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1341,
        "ordered_items": 133,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6478,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1498,
        "ordered_items": 99,
        "sell_earnings": 530,
        "commissions": 530,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5216,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1140,
        "ordered_items": 129,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5553,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1248,
        "ordered_items": 116,
        "sell_earnings": 432,
        "commissions": 432,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6938,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 1984,
        "ordered_items": 158,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7468,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 2092,
        "ordered_items": 145,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8853,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 1734,
        "ordered_items": 175,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9190,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 1891,
        "ordered_items": 141,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7928,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1357,
        "ordered_items": 113,
        "sell_earnings": 602,
        "commissions": 602,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6820,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1292,
        "ordered_items": 101,
        "sell_earnings": 572,
        "commissions": 572,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6046,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1940,
        "ordered_items": 173,
        "sell_earnings": 644,
        "commissions": 644,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8360,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 1875,
        "ordered_items": 161,
        "sell_earnings": 614,
        "commissions": 614,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7586,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1613,
        "ordered_items": 121,
        "sell_earnings": 483,
        "commissions": 483,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5659,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 1619,
        "ordered_items": 153,
        "sell_earnings": 733,
        "commissions": 733,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8747,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];