export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1354,
        "ordered_items": 112,
        "sell_earnings": 457,
        "commissions": 457,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5113,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1250,
        "ordered_items": 108,
        "sell_earnings": 440,
        "commissions": 440,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6217,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1367,
        "ordered_items": 130,
        "sell_earnings": 439,
        "commissions": 439,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5307,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 1865,
        "ordered_items": 144,
        "sell_earnings": 777,
        "commissions": 777,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9099,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 1982,
        "ordered_items": 166,
        "sell_earnings": 776,
        "commissions": 776,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8189,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 1878,
        "ordered_items": 162,
        "sell_earnings": 759,
        "commissions": 759,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9293,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1565,
        "ordered_items": 103,
        "sell_earnings": 465,
        "commissions": 465,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5612,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1377,
        "ordered_items": 104,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5355,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1501,
        "ordered_items": 119,
        "sell_earnings": 586,
        "commissions": 586,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5866,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 1731,
        "ordered_items": 155,
        "sell_earnings": 630,
        "commissions": 630,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8540,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 1855,
        "ordered_items": 170,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9051,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 1667,
        "ordered_items": 171,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8794,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1450,
        "ordered_items": 118,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7004,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 1782,
        "ordered_items": 156,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7402,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1327,
        "ordered_items": 123,
        "sell_earnings": 483,
        "commissions": 483,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6238,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 1905,
        "ordered_items": 151,
        "sell_earnings": 733,
        "commissions": 733,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8168,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1572,
        "ordered_items": 112,
        "sell_earnings": 578,
        "commissions": 578,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5345,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1249,
        "ordered_items": 103,
        "sell_earnings": 532,
        "commissions": 532,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7200,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1393,
        "ordered_items": 110,
        "sell_earnings": 502,
        "commissions": 502,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5930,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1393,
        "ordered_items": 126,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6476,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 1839,
        "ordered_items": 148,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7930,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1839,
        "ordered_items": 164,
        "sell_earnings": 714,
        "commissions": 714,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8476,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 1983,
        "ordered_items": 171,
        "sell_earnings": 684,
        "commissions": 684,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7206,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 1660,
        "ordered_items": 162,
        "sell_earnings": 638,
        "commissions": 638,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9061,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1475,
        "ordered_items": 106,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7163,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1428,
        "ordered_items": 102,
        "sell_earnings": 522,
        "commissions": 522,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5416,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 1804,
        "ordered_items": 172,
        "sell_earnings": 694,
        "commissions": 694,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8990,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1757,
        "ordered_items": 168,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7243,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1604,
        "ordered_items": 100,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5479,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 1628,
        "ordered_items": 174,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8927,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];