export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1341,
        "ordered_items": 112,
        "sell_earnings": 577,
        "commissions": 577,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6997,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1324,
        "ordered_items": 117,
        "sell_earnings": 508,
        "commissions": 508,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6484,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1527,
        "ordered_items": 108,
        "sell_earnings": 601,
        "commissions": 601,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5469,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 1705,
        "ordered_items": 166,
        "sell_earnings": 615,
        "commissions": 615,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8937,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 1908,
        "ordered_items": 157,
        "sell_earnings": 708,
        "commissions": 708,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7922,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 1891,
        "ordered_items": 162,
        "sell_earnings": 639,
        "commissions": 639,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7409,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1606,
        "ordered_items": 110,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6814,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1170,
        "ordered_items": 116,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6648,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1157,
        "ordered_items": 103,
        "sell_earnings": 522,
        "commissions": 522,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6865,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 2075,
        "ordered_items": 171,
        "sell_earnings": 694,
        "commissions": 694,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7541,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 2062,
        "ordered_items": 158,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7758,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 1626,
        "ordered_items": 164,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7592,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1141,
        "ordered_items": 107,
        "sell_earnings": 524,
        "commissions": 524,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5593,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 2091,
        "ordered_items": 167,
        "sell_earnings": 692,
        "commissions": 692,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8813,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1430,
        "ordered_items": 104,
        "sell_earnings": 507,
        "commissions": 507,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6924,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 1802,
        "ordered_items": 170,
        "sell_earnings": 709,
        "commissions": 709,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7482,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1570,
        "ordered_items": 120,
        "sell_earnings": 486,
        "commissions": 486,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5234,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1550,
        "ordered_items": 123,
        "sell_earnings": 427,
        "commissions": 427,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6251,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1193,
        "ordered_items": 130,
        "sell_earnings": 575,
        "commissions": 575,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5638,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1429,
        "ordered_items": 135,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6797,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 1803,
        "ordered_items": 139,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7609,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 2039,
        "ordered_items": 144,
        "sell_earnings": 641,
        "commissions": 641,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8768,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 1682,
        "ordered_items": 151,
        "sell_earnings": 789,
        "commissions": 789,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8155,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 1662,
        "ordered_items": 154,
        "sell_earnings": 730,
        "commissions": 730,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9172,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1234,
        "ordered_items": 127,
        "sell_earnings": 488,
        "commissions": 488,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7034,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1582,
        "ordered_items": 107,
        "sell_earnings": 595,
        "commissions": 595,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5080,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 1650,
        "ordered_items": 167,
        "sell_earnings": 621,
        "commissions": 621,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9326,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 1998,
        "ordered_items": 147,
        "sell_earnings": 728,
        "commissions": 728,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7372,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1353,
        "ordered_items": 133,
        "sell_earnings": 437,
        "commissions": 437,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6316,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 1879,
        "ordered_items": 141,
        "sell_earnings": 779,
        "commissions": 779,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8090,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];