export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1392,
        "ordered_items": 130,
        "sell_earnings": 526,
        "commissions": 526,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6912,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1313,
        "ordered_items": 103,
        "sell_earnings": 581,
        "commissions": 581,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5459,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1439,
        "ordered_items": 135,
        "sell_earnings": 546,
        "commissions": 546,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7363,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 1901,
        "ordered_items": 149,
        "sell_earnings": 710,
        "commissions": 710,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7523,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 2027,
        "ordered_items": 181,
        "sell_earnings": 675,
        "commissions": 675,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9427,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 1948,
        "ordered_items": 154,
        "sell_earnings": 730,
        "commissions": 730,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7974,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1416,
        "ordered_items": 104,
        "sell_earnings": 573,
        "commissions": 573,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6506,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1279,
        "ordered_items": 106,
        "sell_earnings": 524,
        "commissions": 524,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7069,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1421,
        "ordered_items": 116,
        "sell_earnings": 535,
        "commissions": 535,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7388,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 1919,
        "ordered_items": 168,
        "sell_earnings": 721,
        "commissions": 721,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7498,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 2061,
        "ordered_items": 178,
        "sell_earnings": 732,
        "commissions": 732,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 166,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7817,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 1924,
        "ordered_items": 180,
        "sell_earnings": 683,
        "commissions": 683,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8380,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1219,
        "ordered_items": 137,
        "sell_earnings": 615,
        "commissions": 615,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5528,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 2121,
        "ordered_items": 147,
        "sell_earnings": 641,
        "commissions": 641,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9358,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1200,
        "ordered_items": 127,
        "sell_earnings": 529,
        "commissions": 529,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6529,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 2140,
        "ordered_items": 157,
        "sell_earnings": 727,
        "commissions": 727,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8357,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1418,
        "ordered_items": 134,
        "sell_earnings": 443,
        "commissions": 443,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6648,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1483,
        "ordered_items": 132,
        "sell_earnings": 514,
        "commissions": 514,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6578,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1278,
        "ordered_items": 120,
        "sell_earnings": 484,
        "commissions": 484,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5492,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1457,
        "ordered_items": 115,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6597,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 1883,
        "ordered_items": 169,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8289,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 2062,
        "ordered_items": 164,
        "sell_earnings": 772,
        "commissions": 772,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9394,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 1857,
        "ordered_items": 152,
        "sell_earnings": 742,
        "commissions": 742,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 166,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8308,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 1922,
        "ordered_items": 150,
        "sell_earnings": 813,
        "commissions": 813,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8238,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1548,
        "ordered_items": 113,
        "sell_earnings": 525,
        "commissions": 525,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6034,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1539,
        "ordered_items": 104,
        "sell_earnings": 552,
        "commissions": 552,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5469,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 1801,
        "ordered_items": 180,
        "sell_earnings": 704,
        "commissions": 704,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9417,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 1792,
        "ordered_items": 171,
        "sell_earnings": 731,
        "commissions": 731,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8852,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1181,
        "ordered_items": 125,
        "sell_earnings": 470,
        "commissions": 470,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6854,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 2159,
        "ordered_items": 159,
        "sell_earnings": 786,
        "commissions": 786,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8032,
        "bonus": 1
    }
];