export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1502,
        "ordered_items": 122,
        "sell_earnings": 498,
        "commissions": 498,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7072,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1278,
        "ordered_items": 123,
        "sell_earnings": 442,
        "commissions": 442,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7154,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1504,
        "ordered_items": 103,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6508,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 1728,
        "ordered_items": 171,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7898,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 1954,
        "ordered_items": 151,
        "sell_earnings": 774,
        "commissions": 774,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7252,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 1730,
        "ordered_items": 152,
        "sell_earnings": 718,
        "commissions": 718,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7334,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1405,
        "ordered_items": 124,
        "sell_earnings": 531,
        "commissions": 531,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5797,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1162,
        "ordered_items": 114,
        "sell_earnings": 460,
        "commissions": 460,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6657,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1340,
        "ordered_items": 117,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6997,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 1892,
        "ordered_items": 157,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7409,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 2070,
        "ordered_items": 160,
        "sell_earnings": 756,
        "commissions": 756,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7749,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1827,
        "ordered_items": 150,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8609,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1350,
        "ordered_items": 123,
        "sell_earnings": 490,
        "commissions": 490,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6338,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 1882,
        "ordered_items": 151,
        "sell_earnings": 726,
        "commissions": 726,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8068,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1200,
        "ordered_items": 104,
        "sell_earnings": 587,
        "commissions": 587,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6341,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 2032,
        "ordered_items": 170,
        "sell_earnings": 629,
        "commissions": 629,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8065,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1361,
        "ordered_items": 105,
        "sell_earnings": 552,
        "commissions": 552,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6239,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1164,
        "ordered_items": 108,
        "sell_earnings": 530,
        "commissions": 530,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6425,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1268,
        "ordered_items": 135,
        "sell_earnings": 532,
        "commissions": 532,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6271,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1230,
        "ordered_items": 132,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6891,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 2002,
        "ordered_items": 142,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7515,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 1964,
        "ordered_items": 139,
        "sell_earnings": 684,
        "commissions": 684,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8135,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 2068,
        "ordered_items": 166,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7981,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1871,
        "ordered_items": 169,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8167,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1492,
        "ordered_items": 112,
        "sell_earnings": 454,
        "commissions": 454,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6514,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1548,
        "ordered_items": 115,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6940,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 1684,
        "ordered_items": 159,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7466,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 1740,
        "ordered_items": 162,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7892,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1598,
        "ordered_items": 124,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7067,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 1634,
        "ordered_items": 150,
        "sell_earnings": 720,
        "commissions": 720,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7339,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];