export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1607,
        "ordered_items": 120,
        "sell_earnings": 512,
        "commissions": 512,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6148,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1499,
        "ordered_items": 115,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6023,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1345,
        "ordered_items": 121,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5252,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 1887,
        "ordered_items": 153,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9154,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1733,
        "ordered_items": 159,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8383,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 1625,
        "ordered_items": 154,
        "sell_earnings": 704,
        "commissions": 704,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8258,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1465,
        "ordered_items": 122,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5945,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1432,
        "ordered_items": 113,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6849,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1508,
        "ordered_items": 121,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6148,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1724,
        "ordered_items": 153,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8258,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 1800,
        "ordered_items": 161,
        "sell_earnings": 721,
        "commissions": 721,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7557,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1767,
        "ordered_items": 152,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8461,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1251,
        "ordered_items": 130,
        "sell_earnings": 505,
        "commissions": 505,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5307,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1981,
        "ordered_items": 144,
        "sell_earnings": 711,
        "commissions": 711,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9099,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1359,
        "ordered_items": 134,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5074,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1873,
        "ordered_items": 140,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9332,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1420,
        "ordered_items": 115,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5908,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1216,
        "ordered_items": 100,
        "sell_earnings": 435,
        "commissions": 435,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6723,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1403,
        "ordered_items": 122,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6940,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1405,
        "ordered_items": 135,
        "sell_earnings": 454,
        "commissions": 454,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6977,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 1827,
        "ordered_items": 139,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7429,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1829,
        "ordered_items": 152,
        "sell_earnings": 725,
        "commissions": 725,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7466,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 2016,
        "ordered_items": 174,
        "sell_earnings": 781,
        "commissions": 781,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7683,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1812,
        "ordered_items": 159,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8498,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1491,
        "ordered_items": 120,
        "sell_earnings": 526,
        "commissions": 526,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6360,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1234,
        "ordered_items": 113,
        "sell_earnings": 483,
        "commissions": 483,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6933,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1998,
        "ordered_items": 161,
        "sell_earnings": 733,
        "commissions": 733,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7473,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1741,
        "ordered_items": 154,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8046,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1278,
        "ordered_items": 97,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7037,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1954,
        "ordered_items": 177,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7369,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];