export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 1599,
        "ordered_items": 103,
        "sell_earnings": 490,
        "commissions": 490,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6926,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 1623,
        "ordered_items": 131,
        "sell_earnings": 597,
        "commissions": 597,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6248,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 1658,
        "ordered_items": 100,
        "sell_earnings": 483,
        "commissions": 483,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5719,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 1682,
        "ordered_items": 184,
        "sell_earnings": 773,
        "commissions": 773,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9167,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 1717,
        "ordered_items": 153,
        "sell_earnings": 659,
        "commissions": 659,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8638,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 1741,
        "ordered_items": 181,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7960,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 1188,
        "ordered_items": 103,
        "sell_earnings": 570,
        "commissions": 570,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5357,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 1461,
        "ordered_items": 142,
        "sell_earnings": 584,
        "commissions": 584,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6424,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 1277,
        "ordered_items": 109,
        "sell_earnings": 476,
        "commissions": 476,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6228,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 2063,
        "ordered_items": 175,
        "sell_earnings": 780,
        "commissions": 780,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8658,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 1879,
        "ordered_items": 142,
        "sell_earnings": 672,
        "commissions": 672,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8462,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 2152,
        "ordered_items": 181,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9529,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 1557,
        "ordered_items": 104,
        "sell_earnings": 571,
        "commissions": 571,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7107,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 1783,
        "ordered_items": 180,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7779,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 1611,
        "ordered_items": 140,
        "sell_earnings": 445,
        "commissions": 445,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6352,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 1729,
        "ordered_items": 144,
        "sell_earnings": 811,
        "commissions": 811,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8534,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 1379,
        "ordered_items": 125,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6353,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 1231,
        "ordered_items": 105,
        "sell_earnings": 554,
        "commissions": 554,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6438,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 1559,
        "ordered_items": 103,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7378,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 1427,
        "ordered_items": 117,
        "sell_earnings": 563,
        "commissions": 563,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7272,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 1913,
        "ordered_items": 167,
        "sell_earnings": 693,
        "commissions": 693,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7614,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 1781,
        "ordered_items": 181,
        "sell_earnings": 634,
        "commissions": 634,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7508,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 2109,
        "ordered_items": 179,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8448,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 1961,
        "ordered_items": 159,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8533,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 1248,
        "ordered_items": 122,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6006,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 1411,
        "ordered_items": 137,
        "sell_earnings": 621,
        "commissions": 621,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5660,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 1929,
        "ordered_items": 147,
        "sell_earnings": 635,
        "commissions": 635,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9226,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 2092,
        "ordered_items": 162,
        "sell_earnings": 658,
        "commissions": 658,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8880,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 1325,
        "ordered_items": 121,
        "sell_earnings": 597,
        "commissions": 597,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6229,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 2015,
        "ordered_items": 163,
        "sell_earnings": 659,
        "commissions": 659,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8657,
        "bonus": 0
    }
];