export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1206,
        "ordered_items": 117,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5942,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1595,
        "ordered_items": 110,
        "sell_earnings": 488,
        "commissions": 488,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5893,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1314,
        "ordered_items": 136,
        "sell_earnings": 476,
        "commissions": 476,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6129,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 1918,
        "ordered_items": 138,
        "sell_earnings": 740,
        "commissions": 740,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8277,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 1637,
        "ordered_items": 164,
        "sell_earnings": 728,
        "commissions": 728,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8513,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 2026,
        "ordered_items": 157,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8464,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1200,
        "ordered_items": 114,
        "sell_earnings": 435,
        "commissions": 435,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6642,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1389,
        "ordered_items": 120,
        "sell_earnings": 547,
        "commissions": 547,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6277,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1225,
        "ordered_items": 135,
        "sell_earnings": 498,
        "commissions": 498,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5760,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 2007,
        "ordered_items": 139,
        "sell_earnings": 718,
        "commissions": 718,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8646,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 1843,
        "ordered_items": 154,
        "sell_earnings": 669,
        "commissions": 669,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8129,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 2032,
        "ordered_items": 160,
        "sell_earnings": 781,
        "commissions": 781,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7764,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1436,
        "ordered_items": 114,
        "sell_earnings": 603,
        "commissions": 603,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5580,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 1796,
        "ordered_items": 160,
        "sell_earnings": 613,
        "commissions": 613,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8826,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1327,
        "ordered_items": 128,
        "sell_earnings": 448,
        "commissions": 448,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5213,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 1905,
        "ordered_items": 146,
        "sell_earnings": 768,
        "commissions": 768,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9193,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1441,
        "ordered_items": 120,
        "sell_earnings": 430,
        "commissions": 430,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6933,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1461,
        "ordered_items": 124,
        "sell_earnings": 471,
        "commissions": 471,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6031,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1254,
        "ordered_items": 126,
        "sell_earnings": 554,
        "commissions": 554,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7178,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1240,
        "ordered_items": 114,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6524,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 1992,
        "ordered_items": 160,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7882,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1978,
        "ordered_items": 148,
        "sell_earnings": 662,
        "commissions": 662,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7228,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 1771,
        "ordered_items": 150,
        "sell_earnings": 745,
        "commissions": 745,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8375,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 1791,
        "ordered_items": 154,
        "sell_earnings": 786,
        "commissions": 786,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7473,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1563,
        "ordered_items": 134,
        "sell_earnings": 586,
        "commissions": 586,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5207,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1469,
        "ordered_items": 99,
        "sell_earnings": 469,
        "commissions": 469,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5775,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 1763,
        "ordered_items": 175,
        "sell_earnings": 747,
        "commissions": 747,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8631,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1669,
        "ordered_items": 140,
        "sell_earnings": 630,
        "commissions": 630,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9199,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1462,
        "ordered_items": 99,
        "sell_earnings": 490,
        "commissions": 490,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6818,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 1770,
        "ordered_items": 175,
        "sell_earnings": 726,
        "commissions": 726,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7588,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];