export let mar = [
    {
        "month": "Mar",
        "day": "01",
        "clicks": 1273,
        "ordered_items": 119,
        "sell_earnings": 453,
        "commissions": 453,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5470,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "02",
        "clicks": 1466,
        "ordered_items": 112,
        "sell_earnings": 524,
        "commissions": 524,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6446,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "03",
        "clicks": 1609,
        "ordered_items": 111,
        "sell_earnings": 549,
        "commissions": 549,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5695,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "04",
        "clicks": 1623,
        "ordered_items": 163,
        "sell_earnings": 667,
        "commissions": 667,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8711,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "05",
        "clicks": 1766,
        "ordered_items": 162,
        "sell_earnings": 692,
        "commissions": 692,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7960,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "06",
        "clicks": 1959,
        "ordered_items": 155,
        "sell_earnings": 763,
        "commissions": 763,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8936,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "07",
        "clicks": 1211,
        "ordered_items": 118,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5636,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "08",
        "clicks": 1609,
        "ordered_items": 125,
        "sell_earnings": 603,
        "commissions": 603,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7091,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "09",
        "clicks": 1387,
        "ordered_items": 108,
        "sell_earnings": 511,
        "commissions": 511,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5974,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "10",
        "clicks": 1845,
        "ordered_items": 166,
        "sell_earnings": 705,
        "commissions": 705,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8432,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "11",
        "clicks": 1623,
        "ordered_items": 149,
        "sell_earnings": 613,
        "commissions": 613,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7315,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "12",
        "clicks": 2021,
        "ordered_items": 156,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8770,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "13",
        "clicks": 1271,
        "ordered_items": 127,
        "sell_earnings": 553,
        "commissions": 553,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7129,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "14",
        "clicks": 1961,
        "ordered_items": 147,
        "sell_earnings": 663,
        "commissions": 663,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7277,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "15",
        "clicks": 1265,
        "ordered_items": 102,
        "sell_earnings": 472,
        "commissions": 472,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6514,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "16",
        "clicks": 1967,
        "ordered_items": 172,
        "sell_earnings": 744,
        "commissions": 744,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7892,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "17",
        "clicks": 1264,
        "ordered_items": 111,
        "sell_earnings": 553,
        "commissions": 553,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5149,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "18",
        "clicks": 1320,
        "ordered_items": 136,
        "sell_earnings": 581,
        "commissions": 581,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6281,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "19",
        "clicks": 1212,
        "ordered_items": 118,
        "sell_earnings": 514,
        "commissions": 514,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5648,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "20",
        "clicks": 1370,
        "ordered_items": 114,
        "sell_earnings": 544,
        "commissions": 544,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6428,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "21",
        "clicks": 1862,
        "ordered_items": 160,
        "sell_earnings": 672,
        "commissions": 672,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7978,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "22",
        "clicks": 2020,
        "ordered_items": 156,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8758,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "23",
        "clicks": 1912,
        "ordered_items": 138,
        "sell_earnings": 635,
        "commissions": 635,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8125,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "24",
        "clicks": 1968,
        "ordered_items": 163,
        "sell_earnings": 663,
        "commissions": 663,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9257,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "25",
        "clicks": 1503,
        "ordered_items": 128,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6325,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "26",
        "clicks": 1429,
        "ordered_items": 132,
        "sell_earnings": 485,
        "commissions": 485,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6935,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "27",
        "clicks": 1803,
        "ordered_items": 142,
        "sell_earnings": 731,
        "commissions": 731,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7471,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "28",
        "clicks": 1729,
        "ordered_items": 146,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8081,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "29",
        "clicks": 1326,
        "ordered_items": 106,
        "sell_earnings": 525,
        "commissions": 525,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7085,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "30",
        "clicks": 1906,
        "ordered_items": 168,
        "sell_earnings": 691,
        "commissions": 691,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7321,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];