export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1436,
        "ordered_items": 105,
        "sell_earnings": 509,
        "commissions": 509,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6154,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1162,
        "ordered_items": 105,
        "sell_earnings": 455,
        "commissions": 455,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5951,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1509,
        "ordered_items": 114,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6685,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 1723,
        "ordered_items": 160,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7721,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 2070,
        "ordered_items": 169,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8455,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 1796,
        "ordered_items": 169,
        "sell_earnings": 707,
        "commissions": 707,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8252,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1524,
        "ordered_items": 103,
        "sell_earnings": 566,
        "commissions": 566,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5053,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1501,
        "ordered_items": 118,
        "sell_earnings": 442,
        "commissions": 442,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5343,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1506,
        "ordered_items": 101,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5926,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1726,
        "ordered_items": 173,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8480,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 1731,
        "ordered_items": 156,
        "sell_earnings": 774,
        "commissions": 774,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9063,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1708,
        "ordered_items": 171,
        "sell_earnings": 650,
        "commissions": 650,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9353,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1526,
        "ordered_items": 110,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6891,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1706,
        "ordered_items": 164,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7515,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1320,
        "ordered_items": 101,
        "sell_earnings": 596,
        "commissions": 596,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5400,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1912,
        "ordered_items": 173,
        "sell_earnings": 620,
        "commissions": 620,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9006,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1183,
        "ordered_items": 99,
        "sell_earnings": 461,
        "commissions": 461,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5708,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1236,
        "ordered_items": 112,
        "sell_earnings": 583,
        "commissions": 583,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6048,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1275,
        "ordered_items": 108,
        "sell_earnings": 571,
        "commissions": 571,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7197,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1469,
        "ordered_items": 102,
        "sell_earnings": 541,
        "commissions": 541,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5796,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 1763,
        "ordered_items": 172,
        "sell_earnings": 675,
        "commissions": 675,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8610,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1957,
        "ordered_items": 166,
        "sell_earnings": 645,
        "commissions": 645,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7209,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 1996,
        "ordered_items": 162,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8358,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 2049,
        "ordered_items": 175,
        "sell_earnings": 755,
        "commissions": 755,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8698,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1249,
        "ordered_items": 137,
        "sell_earnings": 542,
        "commissions": 542,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5701,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1600,
        "ordered_items": 123,
        "sell_earnings": 505,
        "commissions": 505,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5333,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1632,
        "ordered_items": 151,
        "sell_earnings": 711,
        "commissions": 711,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9073,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1983,
        "ordered_items": 137,
        "sell_earnings": 674,
        "commissions": 674,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8705,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1278,
        "ordered_items": 114,
        "sell_earnings": 436,
        "commissions": 436,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6605,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1954,
        "ordered_items": 160,
        "sell_earnings": 780,
        "commissions": 780,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7801,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];