export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 1548,
        "ordered_items": 138,
        "sell_earnings": 626,
        "commissions": 626,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5791,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 1248,
        "ordered_items": 133,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6951,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 1237,
        "ordered_items": 129,
        "sell_earnings": 601,
        "commissions": 601,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5980,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 2103,
        "ordered_items": 155,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8906,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 2092,
        "ordered_items": 151,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7935,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 1792,
        "ordered_items": 146,
        "sell_earnings": 630,
        "commissions": 630,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9095,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 1461,
        "ordered_items": 133,
        "sell_earnings": 625,
        "commissions": 625,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6103,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 1666,
        "ordered_items": 116,
        "sell_earnings": 455,
        "commissions": 455,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6244,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 1356,
        "ordered_items": 101,
        "sell_earnings": 536,
        "commissions": 536,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6244,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 1984,
        "ordered_items": 183,
        "sell_earnings": 720,
        "commissions": 720,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8642,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 1674,
        "ordered_items": 168,
        "sell_earnings": 801,
        "commissions": 801,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8642,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 1879,
        "ordered_items": 151,
        "sell_earnings": 631,
        "commissions": 631,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8783,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 1495,
        "ordered_items": 104,
        "sell_earnings": 507,
        "commissions": 507,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5374,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 1845,
        "ordered_items": 180,
        "sell_earnings": 749,
        "commissions": 749,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 166,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9512,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 1362,
        "ordered_items": 114,
        "sell_earnings": 493,
        "commissions": 493,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5413,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 1978,
        "ordered_items": 170,
        "sell_earnings": 763,
        "commissions": 763,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9473,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 1455,
        "ordered_items": 108,
        "sell_earnings": 512,
        "commissions": 512,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7415,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 1606,
        "ordered_items": 129,
        "sell_earnings": 484,
        "commissions": 484,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5646,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 1663,
        "ordered_items": 116,
        "sell_earnings": 592,
        "commissions": 592,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6260,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 1195,
        "ordered_items": 114,
        "sell_earnings": 539,
        "commissions": 539,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6642,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 2145,
        "ordered_items": 170,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8244,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 1677,
        "ordered_items": 168,
        "sell_earnings": 664,
        "commissions": 664,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8626,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 1734,
        "ordered_items": 155,
        "sell_earnings": 772,
        "commissions": 772,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9240,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 1885,
        "ordered_items": 176,
        "sell_earnings": 744,
        "commissions": 744,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 165,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7471,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 1396,
        "ordered_items": 134,
        "sell_earnings": 574,
        "commissions": 574,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6989,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 1379,
        "ordered_items": 120,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6867,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 1961,
        "ordered_items": 164,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8019,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 1944,
        "ordered_items": 150,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7897,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 1392,
        "ordered_items": 129,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7336,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 1948,
        "ordered_items": 155,
        "sell_earnings": 752,
        "commissions": 752,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7550,
        "bonus": 1
    }
];