export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1394,
        "ordered_items": 110,
        "sell_earnings": 435,
        "commissions": 435,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6320,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1371,
        "ordered_items": 137,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6872,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1269,
        "ordered_items": 124,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5053,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 1963,
        "ordered_items": 150,
        "sell_earnings": 760,
        "commissions": 760,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9353,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 1861,
        "ordered_items": 137,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7534,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 1838,
        "ordered_items": 164,
        "sell_earnings": 781,
        "commissions": 781,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8086,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1473,
        "ordered_items": 130,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6277,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1599,
        "ordered_items": 134,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5385,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1602,
        "ordered_items": 118,
        "sell_earnings": 573,
        "commissions": 573,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5821,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 1630,
        "ordered_items": 156,
        "sell_earnings": 643,
        "commissions": 643,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8585,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1633,
        "ordered_items": 140,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9021,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 1759,
        "ordered_items": 144,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8129,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1143,
        "ordered_items": 110,
        "sell_earnings": 518,
        "commissions": 518,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5483,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 2089,
        "ordered_items": 164,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8923,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1283,
        "ordered_items": 118,
        "sell_earnings": 518,
        "commissions": 518,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5570,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 1949,
        "ordered_items": 156,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8836,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1220,
        "ordered_items": 129,
        "sell_earnings": 479,
        "commissions": 479,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5946,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1379,
        "ordered_items": 132,
        "sell_earnings": 528,
        "commissions": 528,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5247,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1370,
        "ordered_items": 137,
        "sell_earnings": 564,
        "commissions": 564,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5382,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1172,
        "ordered_items": 115,
        "sell_earnings": 549,
        "commissions": 549,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6814,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 2060,
        "ordered_items": 159,
        "sell_earnings": 667,
        "commissions": 667,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7592,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 1862,
        "ordered_items": 137,
        "sell_earnings": 652,
        "commissions": 652,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9024,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 1853,
        "ordered_items": 142,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9159,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 2012,
        "ordered_items": 145,
        "sell_earnings": 737,
        "commissions": 737,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8460,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1203,
        "ordered_items": 100,
        "sell_earnings": 468,
        "commissions": 468,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7076,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1456,
        "ordered_items": 127,
        "sell_earnings": 554,
        "commissions": 554,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5665,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1776,
        "ordered_items": 147,
        "sell_earnings": 662,
        "commissions": 662,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8741,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 2029,
        "ordered_items": 174,
        "sell_earnings": 748,
        "commissions": 748,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7330,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1369,
        "ordered_items": 134,
        "sell_earnings": 479,
        "commissions": 479,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5634,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 1863,
        "ordered_items": 140,
        "sell_earnings": 737,
        "commissions": 737,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8772,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];