export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1398,
        "ordered_items": 102,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6181,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1442,
        "ordered_items": 127,
        "sell_earnings": 510,
        "commissions": 510,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6752,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1350,
        "ordered_items": 134,
        "sell_earnings": 449,
        "commissions": 449,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5046,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 1882,
        "ordered_items": 140,
        "sell_earnings": 767,
        "commissions": 767,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9360,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 1790,
        "ordered_items": 147,
        "sell_earnings": 706,
        "commissions": 706,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7654,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 1834,
        "ordered_items": 172,
        "sell_earnings": 651,
        "commissions": 651,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8225,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1232,
        "ordered_items": 102,
        "sell_earnings": 521,
        "commissions": 521,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5445,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1161,
        "ordered_items": 134,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7173,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1395,
        "ordered_items": 127,
        "sell_earnings": 447,
        "commissions": 447,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5061,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 1837,
        "ordered_items": 147,
        "sell_earnings": 769,
        "commissions": 769,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9345,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 2071,
        "ordered_items": 140,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7233,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 2000,
        "ordered_items": 172,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8961,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1173,
        "ordered_items": 97,
        "sell_earnings": 580,
        "commissions": 580,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6589,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 2059,
        "ordered_items": 177,
        "sell_earnings": 636,
        "commissions": 636,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7817,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1210,
        "ordered_items": 135,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5312,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 2022,
        "ordered_items": 139,
        "sell_earnings": 676,
        "commissions": 676,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9094,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1177,
        "ordered_items": 130,
        "sell_earnings": 570,
        "commissions": 570,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5181,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1335,
        "ordered_items": 107,
        "sell_earnings": 465,
        "commissions": 465,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6546,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1317,
        "ordered_items": 130,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6388,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1309,
        "ordered_items": 118,
        "sell_earnings": 462,
        "commissions": 462,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7123,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 1923,
        "ordered_items": 156,
        "sell_earnings": 754,
        "commissions": 754,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7283,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1915,
        "ordered_items": 144,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8018,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 1897,
        "ordered_items": 167,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7860,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 2055,
        "ordered_items": 144,
        "sell_earnings": 646,
        "commissions": 646,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9225,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1452,
        "ordered_items": 134,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7084,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1198,
        "ordered_items": 111,
        "sell_earnings": 543,
        "commissions": 543,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5420,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 2034,
        "ordered_items": 163,
        "sell_earnings": 673,
        "commissions": 673,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8986,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1780,
        "ordered_items": 140,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7322,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1404,
        "ordered_items": 131,
        "sell_earnings": 509,
        "commissions": 509,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6992,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 1828,
        "ordered_items": 143,
        "sell_earnings": 707,
        "commissions": 707,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7414,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];