export let mar = [
    {
        "month": "Mar",
        "day": "01",
        "clicks": 1388,
        "ordered_items": 99,
        "sell_earnings": 578,
        "commissions": 578,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5170,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "02",
        "clicks": 1600,
        "ordered_items": 126,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6237,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "03",
        "clicks": 1259,
        "ordered_items": 125,
        "sell_earnings": 542,
        "commissions": 542,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6352,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "04",
        "clicks": 1973,
        "ordered_items": 149,
        "sell_earnings": 674,
        "commissions": 674,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8054,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "05",
        "clicks": 1632,
        "ordered_items": 148,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8169,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "06",
        "clicks": 1844,
        "ordered_items": 175,
        "sell_earnings": 638,
        "commissions": 638,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9236,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "07",
        "clicks": 1186,
        "ordered_items": 130,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6004,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "08",
        "clicks": 1296,
        "ordered_items": 115,
        "sell_earnings": 523,
        "commissions": 523,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7197,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "09",
        "clicks": 1183,
        "ordered_items": 132,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5861,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "10",
        "clicks": 2049,
        "ordered_items": 142,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8545,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "11",
        "clicks": 1936,
        "ordered_items": 159,
        "sell_earnings": 693,
        "commissions": 693,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7209,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "12",
        "clicks": 2046,
        "ordered_items": 144,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8402,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "13",
        "clicks": 1461,
        "ordered_items": 110,
        "sell_earnings": 584,
        "commissions": 584,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6305,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "14",
        "clicks": 1771,
        "ordered_items": 164,
        "sell_earnings": 632,
        "commissions": 632,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8101,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "15",
        "clicks": 1281,
        "ordered_items": 114,
        "sell_earnings": 433,
        "commissions": 433,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5316,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "16",
        "clicks": 1951,
        "ordered_items": 160,
        "sell_earnings": 783,
        "commissions": 783,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9090,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "17",
        "clicks": 1543,
        "ordered_items": 129,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6336,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "18",
        "clicks": 1396,
        "ordered_items": 125,
        "sell_earnings": 459,
        "commissions": 459,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6836,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "19",
        "clicks": 1256,
        "ordered_items": 105,
        "sell_earnings": 563,
        "commissions": 563,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5190,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "20",
        "clicks": 1244,
        "ordered_items": 101,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5389,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "21",
        "clicks": 1988,
        "ordered_items": 173,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9017,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "22",
        "clicks": 1976,
        "ordered_items": 169,
        "sell_earnings": 653,
        "commissions": 653,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9216,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "23",
        "clicks": 1836,
        "ordered_items": 149,
        "sell_earnings": 757,
        "commissions": 757,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7570,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "24",
        "clicks": 1689,
        "ordered_items": 145,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8070,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "25",
        "clicks": 1227,
        "ordered_items": 125,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5902,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "26",
        "clicks": 1434,
        "ordered_items": 97,
        "sell_earnings": 489,
        "commissions": 489,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6326,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "27",
        "clicks": 1798,
        "ordered_items": 177,
        "sell_earnings": 727,
        "commissions": 727,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8080,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "28",
        "clicks": 2005,
        "ordered_items": 149,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8504,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "29",
        "clicks": 1615,
        "ordered_items": 127,
        "sell_earnings": 555,
        "commissions": 555,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5309,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "30",
        "clicks": 1617,
        "ordered_items": 147,
        "sell_earnings": 661,
        "commissions": 661,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9097,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];