export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1236,
        "ordered_items": 99,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6309,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1159,
        "ordered_items": 122,
        "sell_earnings": 509,
        "commissions": 509,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5393,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1580,
        "ordered_items": 128,
        "sell_earnings": 596,
        "commissions": 596,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5200,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 1652,
        "ordered_items": 146,
        "sell_earnings": 620,
        "commissions": 620,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9206,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 2073,
        "ordered_items": 152,
        "sell_earnings": 707,
        "commissions": 707,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9013,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 1996,
        "ordered_items": 175,
        "sell_earnings": 725,
        "commissions": 725,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8097,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1353,
        "ordered_items": 111,
        "sell_earnings": 508,
        "commissions": 508,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6780,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1334,
        "ordered_items": 128,
        "sell_earnings": 587,
        "commissions": 587,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5587,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1447,
        "ordered_items": 123,
        "sell_earnings": 559,
        "commissions": 559,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6133,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 1785,
        "ordered_items": 151,
        "sell_earnings": 657,
        "commissions": 657,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8273,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 1898,
        "ordered_items": 146,
        "sell_earnings": 629,
        "commissions": 629,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8819,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1879,
        "ordered_items": 163,
        "sell_earnings": 708,
        "commissions": 708,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7626,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1478,
        "ordered_items": 126,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7147,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 1754,
        "ordered_items": 148,
        "sell_earnings": 720,
        "commissions": 720,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7259,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1388,
        "ordered_items": 109,
        "sell_earnings": 449,
        "commissions": 449,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7043,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 1844,
        "ordered_items": 165,
        "sell_earnings": 767,
        "commissions": 767,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7363,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1534,
        "ordered_items": 99,
        "sell_earnings": 596,
        "commissions": 596,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6569,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1424,
        "ordered_items": 135,
        "sell_earnings": 474,
        "commissions": 474,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5628,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1320,
        "ordered_items": 99,
        "sell_earnings": 472,
        "commissions": 472,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5902,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1311,
        "ordered_items": 124,
        "sell_earnings": 442,
        "commissions": 442,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6746,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 1921,
        "ordered_items": 150,
        "sell_earnings": 774,
        "commissions": 774,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7660,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 1912,
        "ordered_items": 175,
        "sell_earnings": 744,
        "commissions": 744,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8504,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 1808,
        "ordered_items": 139,
        "sell_earnings": 742,
        "commissions": 742,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8778,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1698,
        "ordered_items": 175,
        "sell_earnings": 620,
        "commissions": 620,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7837,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1371,
        "ordered_items": 132,
        "sell_earnings": 583,
        "commissions": 583,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6716,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1504,
        "ordered_items": 105,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5970,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 1728,
        "ordered_items": 169,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8436,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 1861,
        "ordered_items": 142,
        "sell_earnings": 633,
        "commissions": 633,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7690,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1487,
        "ordered_items": 103,
        "sell_earnings": 501,
        "commissions": 501,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7042,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 1745,
        "ordered_items": 171,
        "sell_earnings": 715,
        "commissions": 715,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7364,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];