export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1478,
        "ordered_items": 138,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6508,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1392,
        "ordered_items": 133,
        "sell_earnings": 558,
        "commissions": 558,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6922,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1305,
        "ordered_items": 123,
        "sell_earnings": 627,
        "commissions": 627,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7295,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 2035,
        "ordered_items": 161,
        "sell_earnings": 629,
        "commissions": 629,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7591,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 1948,
        "ordered_items": 151,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7964,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 1862,
        "ordered_items": 146,
        "sell_earnings": 800,
        "commissions": 800,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8378,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1442,
        "ordered_items": 115,
        "sell_earnings": 509,
        "commissions": 509,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7000,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1511,
        "ordered_items": 113,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7013,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1267,
        "ordered_items": 137,
        "sell_earnings": 559,
        "commissions": 559,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5543,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 2073,
        "ordered_items": 147,
        "sell_earnings": 697,
        "commissions": 697,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 165,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9343,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 1829,
        "ordered_items": 171,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7873,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 1898,
        "ordered_items": 169,
        "sell_earnings": 747,
        "commissions": 747,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7886,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1404,
        "ordered_items": 125,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5494,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 1936,
        "ordered_items": 159,
        "sell_earnings": 798,
        "commissions": 798,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9392,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1572,
        "ordered_items": 141,
        "sell_earnings": 573,
        "commissions": 573,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5234,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 1768,
        "ordered_items": 143,
        "sell_earnings": 683,
        "commissions": 683,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9652,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1383,
        "ordered_items": 132,
        "sell_earnings": 443,
        "commissions": 443,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6856,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1267,
        "ordered_items": 115,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5547,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1209,
        "ordered_items": 104,
        "sell_earnings": 536,
        "commissions": 536,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6198,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1417,
        "ordered_items": 100,
        "sell_earnings": 502,
        "commissions": 502,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6532,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 1923,
        "ordered_items": 184,
        "sell_earnings": 754,
        "commissions": 754,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8354,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 2131,
        "ordered_items": 180,
        "sell_earnings": 720,
        "commissions": 720,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 167,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8688,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 2073,
        "ordered_items": 169,
        "sell_earnings": 757,
        "commissions": 757,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 166,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9339,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 1957,
        "ordered_items": 152,
        "sell_earnings": 813,
        "commissions": 813,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8030,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1590,
        "ordered_items": 130,
        "sell_earnings": 478,
        "commissions": 478,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5249,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1357,
        "ordered_items": 135,
        "sell_earnings": 624,
        "commissions": 624,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6096,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 1983,
        "ordered_items": 149,
        "sell_earnings": 632,
        "commissions": 632,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 167,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8790,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 1750,
        "ordered_items": 154,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9637,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1230,
        "ordered_items": 127,
        "sell_earnings": 533,
        "commissions": 533,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6241,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 2110,
        "ordered_items": 157,
        "sell_earnings": 723,
        "commissions": 723,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8645,
        "bonus": 1
    }
];