export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 1656,
        "ordered_items": 123,
        "sell_earnings": 502,
        "commissions": 502,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6903,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 1418,
        "ordered_items": 118,
        "sell_earnings": 587,
        "commissions": 587,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5405,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 1243,
        "ordered_items": 108,
        "sell_earnings": 512,
        "commissions": 512,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5282,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 2097,
        "ordered_items": 176,
        "sell_earnings": 744,
        "commissions": 744,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9604,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 1922,
        "ordered_items": 166,
        "sell_earnings": 669,
        "commissions": 669,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9481,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 1684,
        "ordered_items": 161,
        "sell_earnings": 754,
        "commissions": 754,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7983,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 1660,
        "ordered_items": 142,
        "sell_earnings": 483,
        "commissions": 483,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 128,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6658,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 1327,
        "ordered_items": 115,
        "sell_earnings": 550,
        "commissions": 550,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6439,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 1467,
        "ordered_items": 109,
        "sell_earnings": 502,
        "commissions": 502,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5577,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 1873,
        "ordered_items": 175,
        "sell_earnings": 754,
        "commissions": 754,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9309,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 2013,
        "ordered_items": 169,
        "sell_earnings": 706,
        "commissions": 706,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 168,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8447,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 1680,
        "ordered_items": 142,
        "sell_earnings": 773,
        "commissions": 773,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8228,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 1402,
        "ordered_items": 104,
        "sell_earnings": 621,
        "commissions": 621,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6610,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 1938,
        "ordered_items": 180,
        "sell_earnings": 635,
        "commissions": 635,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8276,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 1597,
        "ordered_items": 137,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6436,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 1743,
        "ordered_items": 147,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8450,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 1337,
        "ordered_items": 138,
        "sell_earnings": 574,
        "commissions": 574,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7144,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 1180,
        "ordered_items": 110,
        "sell_earnings": 506,
        "commissions": 506,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7076,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 1548,
        "ordered_items": 128,
        "sell_earnings": 508,
        "commissions": 508,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5315,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 1353,
        "ordered_items": 132,
        "sell_earnings": 459,
        "commissions": 459,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7087,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 1987,
        "ordered_items": 152,
        "sell_earnings": 797,
        "commissions": 797,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7799,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 1792,
        "ordered_items": 156,
        "sell_earnings": 748,
        "commissions": 748,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9571,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 2160,
        "ordered_items": 174,
        "sell_earnings": 750,
        "commissions": 750,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7810,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 2003,
        "ordered_items": 146,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 168,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7742,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 1330,
        "ordered_items": 133,
        "sell_earnings": 541,
        "commissions": 541,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5477,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 1189,
        "ordered_items": 119,
        "sell_earnings": 611,
        "commissions": 611,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7014,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 2151,
        "ordered_items": 165,
        "sell_earnings": 645,
        "commissions": 645,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7872,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 2010,
        "ordered_items": 151,
        "sell_earnings": 715,
        "commissions": 715,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9409,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 1297,
        "ordered_items": 106,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 113,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6866,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 2043,
        "ordered_items": 178,
        "sell_earnings": 765,
        "commissions": 765,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8020,
        "bonus": 2
    }
];