export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1359,
        "ordered_items": 103,
        "sell_earnings": 582,
        "commissions": 582,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6203,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1451,
        "ordered_items": 110,
        "sell_earnings": 603,
        "commissions": 603,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6407,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1606,
        "ordered_items": 128,
        "sell_earnings": 574,
        "commissions": 574,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6013,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 1626,
        "ordered_items": 146,
        "sell_earnings": 642,
        "commissions": 642,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8393,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 1781,
        "ordered_items": 164,
        "sell_earnings": 613,
        "commissions": 613,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7999,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 1873,
        "ordered_items": 171,
        "sell_earnings": 634,
        "commissions": 634,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8203,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1372,
        "ordered_items": 113,
        "sell_earnings": 519,
        "commissions": 519,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6083,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1314,
        "ordered_items": 113,
        "sell_earnings": 601,
        "commissions": 601,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6525,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1326,
        "ordered_items": 113,
        "sell_earnings": 475,
        "commissions": 475,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7002,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 1906,
        "ordered_items": 161,
        "sell_earnings": 741,
        "commissions": 741,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7404,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1918,
        "ordered_items": 161,
        "sell_earnings": 615,
        "commissions": 615,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7881,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 1860,
        "ordered_items": 161,
        "sell_earnings": 697,
        "commissions": 697,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8323,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1472,
        "ordered_items": 103,
        "sell_earnings": 586,
        "commissions": 586,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5623,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 1760,
        "ordered_items": 171,
        "sell_earnings": 630,
        "commissions": 630,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8783,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1145,
        "ordered_items": 134,
        "sell_earnings": 600,
        "commissions": 600,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6549,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 2087,
        "ordered_items": 140,
        "sell_earnings": 616,
        "commissions": 616,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7857,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1268,
        "ordered_items": 133,
        "sell_earnings": 549,
        "commissions": 549,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5723,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1531,
        "ordered_items": 137,
        "sell_earnings": 479,
        "commissions": 479,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5322,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1135,
        "ordered_items": 109,
        "sell_earnings": 545,
        "commissions": 545,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6861,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1458,
        "ordered_items": 102,
        "sell_earnings": 576,
        "commissions": 576,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5171,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 1774,
        "ordered_items": 172,
        "sell_earnings": 640,
        "commissions": 640,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9235,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 2097,
        "ordered_items": 165,
        "sell_earnings": 671,
        "commissions": 671,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7545,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 1701,
        "ordered_items": 137,
        "sell_earnings": 737,
        "commissions": 737,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9084,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 1964,
        "ordered_items": 141,
        "sell_earnings": 667,
        "commissions": 667,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8683,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1600,
        "ordered_items": 123,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5715,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1420,
        "ordered_items": 107,
        "sell_earnings": 471,
        "commissions": 471,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6351,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1812,
        "ordered_items": 167,
        "sell_earnings": 745,
        "commissions": 745,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8055,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 1632,
        "ordered_items": 151,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8691,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1200,
        "ordered_items": 97,
        "sell_earnings": 519,
        "commissions": 519,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5360,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 2032,
        "ordered_items": 177,
        "sell_earnings": 697,
        "commissions": 697,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9046,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];