export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 1305,
        "ordered_items": 132,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5666,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 1332,
        "ordered_items": 130,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6917,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 1556,
        "ordered_items": 97,
        "sell_earnings": 514,
        "commissions": 514,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5213,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 1676,
        "ordered_items": 177,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9193,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 1900,
        "ordered_items": 144,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7489,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 1927,
        "ordered_items": 142,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8740,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 1293,
        "ordered_items": 114,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5118,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 1409,
        "ordered_items": 109,
        "sell_earnings": 526,
        "commissions": 526,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6552,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 1484,
        "ordered_items": 129,
        "sell_earnings": 573,
        "commissions": 573,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6601,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 1748,
        "ordered_items": 145,
        "sell_earnings": 643,
        "commissions": 643,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7805,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 1823,
        "ordered_items": 165,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7854,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 1939,
        "ordered_items": 160,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9288,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 1559,
        "ordered_items": 97,
        "sell_earnings": 572,
        "commissions": 572,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5452,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 1673,
        "ordered_items": 177,
        "sell_earnings": 644,
        "commissions": 644,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8954,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 1598,
        "ordered_items": 134,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6249,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 1634,
        "ordered_items": 140,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8157,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 1590,
        "ordered_items": 112,
        "sell_earnings": 530,
        "commissions": 530,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5539,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 1517,
        "ordered_items": 123,
        "sell_earnings": 589,
        "commissions": 589,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6390,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 1555,
        "ordered_items": 104,
        "sell_earnings": 532,
        "commissions": 532,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7133,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 1283,
        "ordered_items": 119,
        "sell_earnings": 453,
        "commissions": 453,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6933,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 1949,
        "ordered_items": 155,
        "sell_earnings": 763,
        "commissions": 763,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7473,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 1677,
        "ordered_items": 170,
        "sell_earnings": 684,
        "commissions": 684,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7273,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 1715,
        "ordered_items": 151,
        "sell_earnings": 627,
        "commissions": 627,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8016,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 1642,
        "ordered_items": 162,
        "sell_earnings": 686,
        "commissions": 686,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8867,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 1227,
        "ordered_items": 101,
        "sell_earnings": 506,
        "commissions": 506,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6357,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 1422,
        "ordered_items": 108,
        "sell_earnings": 481,
        "commissions": 481,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5927,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 1810,
        "ordered_items": 166,
        "sell_earnings": 735,
        "commissions": 735,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8479,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 2005,
        "ordered_items": 173,
        "sell_earnings": 710,
        "commissions": 710,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8049,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 1315,
        "ordered_items": 99,
        "sell_earnings": 545,
        "commissions": 545,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7102,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 1917,
        "ordered_items": 175,
        "sell_earnings": 671,
        "commissions": 671,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7304,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];