export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1176,
        "ordered_items": 118,
        "sell_earnings": 588,
        "commissions": 588,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6541,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1254,
        "ordered_items": 134,
        "sell_earnings": 571,
        "commissions": 571,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7171,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1575,
        "ordered_items": 125,
        "sell_earnings": 582,
        "commissions": 582,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7013,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 1765,
        "ordered_items": 159,
        "sell_earnings": 674,
        "commissions": 674,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7873,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 2086,
        "ordered_items": 150,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 167,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7715,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 2164,
        "ordered_items": 166,
        "sell_earnings": 668,
        "commissions": 668,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8345,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1562,
        "ordered_items": 109,
        "sell_earnings": 617,
        "commissions": 617,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6321,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1185,
        "ordered_items": 122,
        "sell_earnings": 484,
        "commissions": 484,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5665,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1386,
        "ordered_items": 128,
        "sell_earnings": 498,
        "commissions": 498,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6151,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 1954,
        "ordered_items": 156,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8735,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 2155,
        "ordered_items": 162,
        "sell_earnings": 772,
        "commissions": 772,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9221,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 1778,
        "ordered_items": 175,
        "sell_earnings": 639,
        "commissions": 639,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8565,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1411,
        "ordered_items": 131,
        "sell_earnings": 512,
        "commissions": 512,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7020,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 1929,
        "ordered_items": 153,
        "sell_earnings": 744,
        "commissions": 744,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7866,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1625,
        "ordered_items": 126,
        "sell_earnings": 457,
        "commissions": 457,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6241,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 1715,
        "ordered_items": 158,
        "sell_earnings": 799,
        "commissions": 799,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8645,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1526,
        "ordered_items": 120,
        "sell_earnings": 600,
        "commissions": 600,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6284,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1423,
        "ordered_items": 122,
        "sell_earnings": 471,
        "commissions": 471,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6028,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1637,
        "ordered_items": 128,
        "sell_earnings": 576,
        "commissions": 576,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7050,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1291,
        "ordered_items": 101,
        "sell_earnings": 548,
        "commissions": 548,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7226,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 2049,
        "ordered_items": 183,
        "sell_earnings": 708,
        "commissions": 708,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7660,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 1703,
        "ordered_items": 156,
        "sell_earnings": 680,
        "commissions": 680,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 168,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7836,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 1917,
        "ordered_items": 162,
        "sell_earnings": 785,
        "commissions": 785,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8858,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 1814,
        "ordered_items": 164,
        "sell_earnings": 656,
        "commissions": 656,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8602,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1536,
        "ordered_items": 105,
        "sell_earnings": 626,
        "commissions": 626,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6487,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1412,
        "ordered_items": 118,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5733,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 1928,
        "ordered_items": 166,
        "sell_earnings": 638,
        "commissions": 638,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9153,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 1804,
        "ordered_items": 179,
        "sell_earnings": 630,
        "commissions": 630,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8399,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1307,
        "ordered_items": 109,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7439,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 2033,
        "ordered_items": 175,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7447,
        "bonus": 0
    }
];