export let mar = [
    {
        "month": "Mar",
        "day": "01",
        "clicks": 1603,
        "ordered_items": 136,
        "sell_earnings": 509,
        "commissions": 509,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5715,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "02",
        "clicks": 1275,
        "ordered_items": 125,
        "sell_earnings": 427,
        "commissions": 427,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5249,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "03",
        "clicks": 1549,
        "ordered_items": 114,
        "sell_earnings": 467,
        "commissions": 467,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6808,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "04",
        "clicks": 1683,
        "ordered_items": 160,
        "sell_earnings": 749,
        "commissions": 749,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7598,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "05",
        "clicks": 1957,
        "ordered_items": 149,
        "sell_earnings": 789,
        "commissions": 789,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9157,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "06",
        "clicks": 1629,
        "ordered_items": 138,
        "sell_earnings": 707,
        "commissions": 707,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8691,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "07",
        "clicks": 1385,
        "ordered_items": 108,
        "sell_earnings": 452,
        "commissions": 452,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5552,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "08",
        "clicks": 1486,
        "ordered_items": 114,
        "sell_earnings": 484,
        "commissions": 484,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6754,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "09",
        "clicks": 1368,
        "ordered_items": 122,
        "sell_earnings": 585,
        "commissions": 585,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5176,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "10",
        "clicks": 1864,
        "ordered_items": 152,
        "sell_earnings": 631,
        "commissions": 631,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9230,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "11",
        "clicks": 1746,
        "ordered_items": 160,
        "sell_earnings": 732,
        "commissions": 732,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7652,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "12",
        "clicks": 1847,
        "ordered_items": 166,
        "sell_earnings": 764,
        "commissions": 764,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8854,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "13",
        "clicks": 1314,
        "ordered_items": 136,
        "sell_earnings": 521,
        "commissions": 521,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6807,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "14",
        "clicks": 1918,
        "ordered_items": 138,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7599,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "15",
        "clicks": 1272,
        "ordered_items": 119,
        "sell_earnings": 544,
        "commissions": 544,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5726,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "16",
        "clicks": 1960,
        "ordered_items": 155,
        "sell_earnings": 672,
        "commissions": 672,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8680,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "17",
        "clicks": 1609,
        "ordered_items": 105,
        "sell_earnings": 470,
        "commissions": 470,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5299,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "18",
        "clicks": 1403,
        "ordered_items": 131,
        "sell_earnings": 506,
        "commissions": 506,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6980,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "19",
        "clicks": 1608,
        "ordered_items": 97,
        "sell_earnings": 436,
        "commissions": 436,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6522,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "20",
        "clicks": 1462,
        "ordered_items": 105,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6010,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "21",
        "clicks": 1770,
        "ordered_items": 169,
        "sell_earnings": 696,
        "commissions": 696,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8396,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "22",
        "clicks": 1624,
        "ordered_items": 177,
        "sell_earnings": 780,
        "commissions": 780,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7884,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "23",
        "clicks": 1829,
        "ordered_items": 143,
        "sell_earnings": 710,
        "commissions": 710,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7426,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "24",
        "clicks": 1623,
        "ordered_items": 169,
        "sell_earnings": 746,
        "commissions": 746,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9107,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "25",
        "clicks": 1416,
        "ordered_items": 109,
        "sell_earnings": 542,
        "commissions": 542,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6942,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "26",
        "clicks": 1440,
        "ordered_items": 97,
        "sell_earnings": 512,
        "commissions": 512,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7177,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "27",
        "clicks": 1792,
        "ordered_items": 177,
        "sell_earnings": 704,
        "commissions": 704,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7229,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "28",
        "clicks": 1816,
        "ordered_items": 165,
        "sell_earnings": 674,
        "commissions": 674,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7464,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "29",
        "clicks": 1227,
        "ordered_items": 105,
        "sell_earnings": 432,
        "commissions": 432,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6330,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "30",
        "clicks": 2005,
        "ordered_items": 169,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8076,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];