export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1147,
        "ordered_items": 124,
        "sell_earnings": 433,
        "commissions": 433,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6287,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1365,
        "ordered_items": 134,
        "sell_earnings": 489,
        "commissions": 489,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5066,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1291,
        "ordered_items": 135,
        "sell_earnings": 537,
        "commissions": 537,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6297,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 1941,
        "ordered_items": 139,
        "sell_earnings": 679,
        "commissions": 679,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8109,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1867,
        "ordered_items": 140,
        "sell_earnings": 727,
        "commissions": 727,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9340,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 2085,
        "ordered_items": 150,
        "sell_earnings": 783,
        "commissions": 783,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8119,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1587,
        "ordered_items": 126,
        "sell_earnings": 465,
        "commissions": 465,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6340,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1228,
        "ordered_items": 132,
        "sell_earnings": 596,
        "commissions": 596,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6661,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1487,
        "ordered_items": 135,
        "sell_earnings": 603,
        "commissions": 603,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6165,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 1745,
        "ordered_items": 139,
        "sell_earnings": 613,
        "commissions": 613,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8241,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 2004,
        "ordered_items": 142,
        "sell_earnings": 620,
        "commissions": 620,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7745,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1645,
        "ordered_items": 148,
        "sell_earnings": 751,
        "commissions": 751,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 145,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8066,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1346,
        "ordered_items": 126,
        "sell_earnings": 599,
        "commissions": 599,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5442,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1886,
        "ordered_items": 148,
        "sell_earnings": 617,
        "commissions": 617,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8964,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1555,
        "ordered_items": 104,
        "sell_earnings": 550,
        "commissions": 550,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5507,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1677,
        "ordered_items": 170,
        "sell_earnings": 666,
        "commissions": 666,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8899,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1421,
        "ordered_items": 125,
        "sell_earnings": 450,
        "commissions": 450,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6700,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1289,
        "ordered_items": 136,
        "sell_earnings": 475,
        "commissions": 475,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5291,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1185,
        "ordered_items": 106,
        "sell_earnings": 573,
        "commissions": 573,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6084,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1219,
        "ordered_items": 129,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6989,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 2013,
        "ordered_items": 145,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7417,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 2047,
        "ordered_items": 168,
        "sell_earnings": 643,
        "commissions": 643,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8322,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 1943,
        "ordered_items": 138,
        "sell_earnings": 741,
        "commissions": 741,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9115,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1811,
        "ordered_items": 149,
        "sell_earnings": 766,
        "commissions": 766,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7706,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1239,
        "ordered_items": 99,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7040,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1235,
        "ordered_items": 108,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5682,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 1997,
        "ordered_items": 166,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8724,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1993,
        "ordered_items": 175,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7366,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1339,
        "ordered_items": 118,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5104,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1893,
        "ordered_items": 156,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9302,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];