export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 1282,
        "ordered_items": 116,
        "sell_earnings": 506,
        "commissions": 506,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6457,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 1480,
        "ordered_items": 105,
        "sell_earnings": 513,
        "commissions": 513,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5510,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 1657,
        "ordered_items": 124,
        "sell_earnings": 559,
        "commissions": 559,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6904,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 1683,
        "ordered_items": 160,
        "sell_earnings": 697,
        "commissions": 697,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7982,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 1860,
        "ordered_items": 179,
        "sell_earnings": 743,
        "commissions": 743,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9376,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 2058,
        "ordered_items": 168,
        "sell_earnings": 750,
        "commissions": 750,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 169,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8429,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 1292,
        "ordered_items": 117,
        "sell_earnings": 545,
        "commissions": 545,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6748,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 1582,
        "ordered_items": 125,
        "sell_earnings": 543,
        "commissions": 543,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6530,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 1468,
        "ordered_items": 129,
        "sell_earnings": 452,
        "commissions": 452,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5253,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 1872,
        "ordered_items": 155,
        "sell_earnings": 804,
        "commissions": 804,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9633,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 1758,
        "ordered_items": 159,
        "sell_earnings": 713,
        "commissions": 713,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8356,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 2048,
        "ordered_items": 167,
        "sell_earnings": 711,
        "commissions": 711,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 166,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8138,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 1541,
        "ordered_items": 110,
        "sell_earnings": 615,
        "commissions": 615,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6828,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 1799,
        "ordered_items": 174,
        "sell_earnings": 641,
        "commissions": 641,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8058,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 1201,
        "ordered_items": 114,
        "sell_earnings": 566,
        "commissions": 566,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5547,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 2139,
        "ordered_items": 170,
        "sell_earnings": 690,
        "commissions": 690,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9339,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 1593,
        "ordered_items": 127,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6801,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 1307,
        "ordered_items": 107,
        "sell_earnings": 603,
        "commissions": 603,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6776,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 1625,
        "ordered_items": 106,
        "sell_earnings": 475,
        "commissions": 475,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6219,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 1509,
        "ordered_items": 142,
        "sell_earnings": 470,
        "commissions": 470,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6002,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 1831,
        "ordered_items": 142,
        "sell_earnings": 786,
        "commissions": 786,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8884,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 1715,
        "ordered_items": 178,
        "sell_earnings": 781,
        "commissions": 781,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8667,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 2033,
        "ordered_items": 177,
        "sell_earnings": 653,
        "commissions": 653,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8110,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 1747,
        "ordered_items": 157,
        "sell_earnings": 638,
        "commissions": 638,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8085,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 1304,
        "ordered_items": 128,
        "sell_earnings": 544,
        "commissions": 544,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6427,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 1595,
        "ordered_items": 101,
        "sell_earnings": 572,
        "commissions": 572,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7231,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 1745,
        "ordered_items": 183,
        "sell_earnings": 684,
        "commissions": 684,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 139,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7655,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 2036,
        "ordered_items": 156,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 141,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8459,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 1227,
        "ordered_items": 114,
        "sell_earnings": 474,
        "commissions": 474,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7225,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 2113,
        "ordered_items": 170,
        "sell_earnings": 782,
        "commissions": 782,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7661,
        "bonus": 0
    }
];