export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 3404,
        "ordered_items": 137,
        "sell_earnings": 459,
        "commissions": 459,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5506,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 3843,
        "ordered_items": 104,
        "sell_earnings": 586,
        "commissions": 586,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6133,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 3420,
        "ordered_items": 100,
        "sell_earnings": 537,
        "commissions": 537,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7042,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 5154,
        "ordered_items": 180,
        "sell_earnings": 771,
        "commissions": 771,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7364,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 4731,
        "ordered_items": 176,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8273,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 5170,
        "ordered_items": 143,
        "sell_earnings": 849,
        "commissions": 849,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8900,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 3565,
        "ordered_items": 136,
        "sell_earnings": 643,
        "commissions": 643,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6935,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 4045,
        "ordered_items": 126,
        "sell_earnings": 554,
        "commissions": 554,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6664,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 3041,
        "ordered_items": 105,
        "sell_earnings": 654,
        "commissions": 654,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5505,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 5533,
        "ordered_items": 175,
        "sell_earnings": 654,
        "commissions": 654,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8901,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 4529,
        "ordered_items": 154,
        "sell_earnings": 754,
        "commissions": 754,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7742,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 5009,
        "ordered_items": 144,
        "sell_earnings": 665,
        "commissions": 665,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7471,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 3727,
        "ordered_items": 132,
        "sell_earnings": 485,
        "commissions": 485,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6219,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 4847,
        "ordered_items": 148,
        "sell_earnings": 823,
        "commissions": 823,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8187,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 3267,
        "ordered_items": 138,
        "sell_earnings": 632,
        "commissions": 632,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6461,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 5307,
        "ordered_items": 142,
        "sell_earnings": 676,
        "commissions": 676,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7945,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 4047,
        "ordered_items": 115,
        "sell_earnings": 603,
        "commissions": 603,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5708,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 3039,
        "ordered_items": 110,
        "sell_earnings": 469,
        "commissions": 469,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6066,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 3782,
        "ordered_items": 132,
        "sell_earnings": 581,
        "commissions": 581,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5077,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 3875,
        "ordered_items": 127,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5297,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 4699,
        "ordered_items": 153,
        "sell_earnings": 715,
        "commissions": 715,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9109,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 4792,
        "ordered_items": 148,
        "sell_earnings": 727,
        "commissions": 727,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9329,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 5535,
        "ordered_items": 170,
        "sell_earnings": 839,
        "commissions": 839,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8340,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 4527,
        "ordered_items": 165,
        "sell_earnings": 705,
        "commissions": 705,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8698,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 3795,
        "ordered_items": 116,
        "sell_earnings": 503,
        "commissions": 503,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5817,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 4281,
        "ordered_items": 138,
        "sell_earnings": 646,
        "commissions": 646,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7050,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 4293,
        "ordered_items": 142,
        "sell_earnings": 662,
        "commissions": 662,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7356,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 4779,
        "ordered_items": 164,
        "sell_earnings": 805,
        "commissions": 805,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8589,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 3439,
        "ordered_items": 133,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7143,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 5135,
        "ordered_items": 147,
        "sell_earnings": 788,
        "commissions": 788,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7263,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 4287,
        "ordered_items": 140,
        "sell_earnings": 654,
        "commissions": 654,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];