export let jul = [
    {
        "month": "Jul",
        "day": "01",
        "clicks": 2555,
        "ordered_items": 112,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6399,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "02",
        "clicks": 2827,
        "ordered_items": 125,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6392,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "03",
        "clicks": 3017,
        "ordered_items": 120,
        "sell_earnings": 576,
        "commissions": 576,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5799,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "04",
        "clicks": 3441,
        "ordered_items": 154,
        "sell_earnings": 640,
        "commissions": 640,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8607,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "05",
        "clicks": 3631,
        "ordered_items": 149,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8014,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "06",
        "clicks": 3903,
        "ordered_items": 162,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8007,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "07",
        "clicks": 2282,
        "ordered_items": 105,
        "sell_earnings": 546,
        "commissions": 546,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6801,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "08",
        "clicks": 2923,
        "ordered_items": 131,
        "sell_earnings": 500,
        "commissions": 500,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5704,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "09",
        "clicks": 3060,
        "ordered_items": 124,
        "sell_earnings": 595,
        "commissions": 595,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5993,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "10",
        "clicks": 3398,
        "ordered_items": 150,
        "sell_earnings": 621,
        "commissions": 621,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8413,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "11",
        "clicks": 3535,
        "ordered_items": 143,
        "sell_earnings": 716,
        "commissions": 716,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8702,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "12",
        "clicks": 4176,
        "ordered_items": 169,
        "sell_earnings": 670,
        "commissions": 670,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7605,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "13",
        "clicks": 2672,
        "ordered_items": 98,
        "sell_earnings": 454,
        "commissions": 454,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5399,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "14",
        "clicks": 3786,
        "ordered_items": 176,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9007,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "15",
        "clicks": 2380,
        "ordered_items": 112,
        "sell_earnings": 527,
        "commissions": 527,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5054,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "16",
        "clicks": 4078,
        "ordered_items": 162,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9352,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "17",
        "clicks": 3125,
        "ordered_items": 106,
        "sell_earnings": 457,
        "commissions": 457,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5657,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "18",
        "clicks": 3161,
        "ordered_items": 101,
        "sell_earnings": 564,
        "commissions": 564,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5605,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "19",
        "clicks": 2874,
        "ordered_items": 115,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6769,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "20",
        "clicks": 2329,
        "ordered_items": 104,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6526,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "21",
        "clicks": 4129,
        "ordered_items": 170,
        "sell_earnings": 753,
        "commissions": 753,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7880,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "22",
        "clicks": 3584,
        "ordered_items": 159,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7637,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "23",
        "clicks": 3297,
        "ordered_items": 173,
        "sell_earnings": 652,
        "commissions": 652,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8801,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "24",
        "clicks": 3333,
        "ordered_items": 168,
        "sell_earnings": 759,
        "commissions": 759,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8749,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "25",
        "clicks": 3219,
        "ordered_items": 132,
        "sell_earnings": 442,
        "commissions": 442,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5184,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "26",
        "clicks": 3194,
        "ordered_items": 106,
        "sell_earnings": 593,
        "commissions": 593,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5168,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "27",
        "clicks": 3264,
        "ordered_items": 168,
        "sell_earnings": 623,
        "commissions": 623,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9238,
        "bonus": 0
    },
    {
        "month": "Jul",
        "day": "28",
        "clicks": 3239,
        "ordered_items": 142,
        "sell_earnings": 774,
        "commissions": 774,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9222,
        "bonus": 2
    },
    {
        "month": "Jul",
        "day": "29",
        "clicks": 2926,
        "ordered_items": 126,
        "sell_earnings": 565,
        "commissions": 565,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7062,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "30",
        "clicks": 3532,
        "ordered_items": 148,
        "sell_earnings": 651,
        "commissions": 651,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7344,
        "bonus": 1
    },
    {
        "month": "Jul",
        "day": "31",
        "clicks": 3229,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];