export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 2576,
        "ordered_items": 102,
        "sell_earnings": 391,
        "commissions": 391,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5596,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 3004,
        "ordered_items": 93,
        "sell_earnings": 385,
        "commissions": 385,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5496,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 2306,
        "ordered_items": 100,
        "sell_earnings": 353,
        "commissions": 353,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7235,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 4254,
        "ordered_items": 108,
        "sell_earnings": 431,
        "commissions": 431,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7651,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 3556,
        "ordered_items": 115,
        "sell_earnings": 399,
        "commissions": 399,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9390,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 3984,
        "ordered_items": 106,
        "sell_earnings": 393,
        "commissions": 393,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9290,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 3239,
        "ordered_items": 85,
        "sell_earnings": 338,
        "commissions": 338,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5836,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 3064,
        "ordered_items": 86,
        "sell_earnings": 288,
        "commissions": 288,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5472,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 2577,
        "ordered_items": 88,
        "sell_earnings": 357,
        "commissions": 357,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6478,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 3983,
        "ordered_items": 120,
        "sell_earnings": 427,
        "commissions": 427,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8408,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 3496,
        "ordered_items": 122,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9414,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 3321,
        "ordered_items": 123,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9050,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 3064,
        "ordered_items": 94,
        "sell_earnings": 349,
        "commissions": 349,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6423,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 3496,
        "ordered_items": 114,
        "sell_earnings": 435,
        "commissions": 435,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8463,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 3058,
        "ordered_items": 78,
        "sell_earnings": 378,
        "commissions": 378,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6479,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 3502,
        "ordered_items": 130,
        "sell_earnings": 406,
        "commissions": 406,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 156,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8407,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 3039,
        "ordered_items": 88,
        "sell_earnings": 384,
        "commissions": 384,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6523,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 2943,
        "ordered_items": 98,
        "sell_earnings": 373,
        "commissions": 373,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5900,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 2320,
        "ordered_items": 75,
        "sell_earnings": 339,
        "commissions": 339,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7038,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 2568,
        "ordered_items": 97,
        "sell_earnings": 327,
        "commissions": 327,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6702,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 3992,
        "ordered_items": 111,
        "sell_earnings": 457,
        "commissions": 457,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8184,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 4240,
        "ordered_items": 133,
        "sell_earnings": 445,
        "commissions": 445,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7848,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 3617,
        "ordered_items": 110,
        "sell_earnings": 411,
        "commissions": 411,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8986,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 3521,
        "ordered_items": 120,
        "sell_earnings": 400,
        "commissions": 400,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8363,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 3169,
        "ordered_items": 99,
        "sell_earnings": 358,
        "commissions": 358,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6688,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 2387,
        "ordered_items": 90,
        "sell_earnings": 324,
        "commissions": 324,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5786,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 4173,
        "ordered_items": 118,
        "sell_earnings": 460,
        "commissions": 460,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9100,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 3391,
        "ordered_items": 109,
        "sell_earnings": 426,
        "commissions": 426,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8198,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 2937,
        "ordered_items": 99,
        "sell_earnings": 359,
        "commissions": 359,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6699,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 3623,
        "ordered_items": 109,
        "sell_earnings": 425,
        "commissions": 425,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8187,
        "bonus": 0
    }
];