export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 2777,
        "ordered_items": 94,
        "sell_earnings": 421,
        "commissions": 421,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6723,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 2834,
        "ordered_items": 84,
        "sell_earnings": 427,
        "commissions": 427,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6851,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 2786,
        "ordered_items": 91,
        "sell_earnings": 449,
        "commissions": 449,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6613,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 3366,
        "ordered_items": 133,
        "sell_earnings": 625,
        "commissions": 625,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7793,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 3318,
        "ordered_items": 140,
        "sell_earnings": 647,
        "commissions": 647,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7555,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 3375,
        "ordered_items": 130,
        "sell_earnings": 653,
        "commissions": 653,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7683,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 2576,
        "ordered_items": 83,
        "sell_earnings": 537,
        "commissions": 537,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6158,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 2582,
        "ordered_items": 105,
        "sell_earnings": 474,
        "commissions": 474,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 115,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7038,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 2616,
        "ordered_items": 107,
        "sell_earnings": 465,
        "commissions": 465,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6741,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 3536,
        "ordered_items": 117,
        "sell_earnings": 609,
        "commissions": 609,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7665,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 3570,
        "ordered_items": 119,
        "sell_earnings": 600,
        "commissions": 600,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7368,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 3576,
        "ordered_items": 141,
        "sell_earnings": 537,
        "commissions": 537,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8248,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 2899,
        "ordered_items": 104,
        "sell_earnings": 497,
        "commissions": 497,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 115,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7189,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 3253,
        "ordered_items": 120,
        "sell_earnings": 577,
        "commissions": 577,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7217,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 2978,
        "ordered_items": 91,
        "sell_earnings": 512,
        "commissions": 512,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6429,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 3174,
        "ordered_items": 133,
        "sell_earnings": 562,
        "commissions": 562,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7977,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 2509,
        "ordered_items": 87,
        "sell_earnings": 490,
        "commissions": 490,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5131,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 2886,
        "ordered_items": 85,
        "sell_earnings": 478,
        "commissions": 478,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 101,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6957,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 2619,
        "ordered_items": 90,
        "sell_earnings": 420,
        "commissions": 420,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5541,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 2681,
        "ordered_items": 103,
        "sell_earnings": 519,
        "commissions": 519,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 123,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6747,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 3471,
        "ordered_items": 121,
        "sell_earnings": 555,
        "commissions": 555,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 129,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7659,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 3533,
        "ordered_items": 134,
        "sell_earnings": 654,
        "commissions": 654,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8865,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 3266,
        "ordered_items": 139,
        "sell_earnings": 596,
        "commissions": 596,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7449,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 3643,
        "ordered_items": 137,
        "sell_earnings": 584,
        "commissions": 584,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9275,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 2867,
        "ordered_items": 100,
        "sell_earnings": 419,
        "commissions": 419,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5175,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 2793,
        "ordered_items": 84,
        "sell_earnings": 468,
        "commissions": 468,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6570,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 3359,
        "ordered_items": 140,
        "sell_earnings": 606,
        "commissions": 606,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7836,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 3285,
        "ordered_items": 124,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9231,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 2420,
        "ordered_items": 99,
        "sell_earnings": 453,
        "commissions": 453,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6167,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 3732,
        "ordered_items": 125,
        "sell_earnings": 621,
        "commissions": 621,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8239,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 3076,
        "ordered_items": 112,
        "sell_earnings": 537,
        "commissions": 537,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];