export let sep = [
    {
        "month": "Sep",
        "day": "01",
        "clicks": 2588,
        "ordered_items": 134,
        "sell_earnings": 521,
        "commissions": 521,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6514,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "02",
        "clicks": 3288,
        "ordered_items": 111,
        "sell_earnings": 431,
        "commissions": 431,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6336,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "03",
        "clicks": 2710,
        "ordered_items": 126,
        "sell_earnings": 423,
        "commissions": 423,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7363,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "04",
        "clicks": 4110,
        "ordered_items": 142,
        "sell_earnings": 729,
        "commissions": 729,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7523,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "05",
        "clicks": 3532,
        "ordered_items": 157,
        "sell_earnings": 721,
        "commissions": 721,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8550,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "06",
        "clicks": 4232,
        "ordered_items": 134,
        "sell_earnings": 631,
        "commissions": 631,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8372,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "07",
        "clicks": 2423,
        "ordered_items": 102,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6964,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "08",
        "clicks": 2627,
        "ordered_items": 112,
        "sell_earnings": 404,
        "commissions": 404,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7307,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "09",
        "clicks": 2855,
        "ordered_items": 107,
        "sell_earnings": 465,
        "commissions": 465,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6417,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "10",
        "clicks": 3965,
        "ordered_items": 161,
        "sell_earnings": 687,
        "commissions": 687,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8469,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "11",
        "clicks": 4193,
        "ordered_items": 156,
        "sell_earnings": 748,
        "commissions": 748,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7579,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "12",
        "clicks": 4397,
        "ordered_items": 166,
        "sell_earnings": 657,
        "commissions": 657,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7922,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "13",
        "clicks": 2430,
        "ordered_items": 124,
        "sell_earnings": 553,
        "commissions": 553,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7082,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "14",
        "clicks": 4390,
        "ordered_items": 144,
        "sell_earnings": 599,
        "commissions": 599,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7804,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "15",
        "clicks": 2758,
        "ordered_items": 116,
        "sell_earnings": 406,
        "commissions": 406,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5444,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "16",
        "clicks": 4062,
        "ordered_items": 152,
        "sell_earnings": 746,
        "commissions": 746,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9442,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "17",
        "clicks": 2925,
        "ordered_items": 109,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6119,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "18",
        "clicks": 2893,
        "ordered_items": 103,
        "sell_earnings": 539,
        "commissions": 539,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5962,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "19",
        "clicks": 3216,
        "ordered_items": 106,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7439,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "20",
        "clicks": 3409,
        "ordered_items": 123,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5267,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "21",
        "clicks": 3411,
        "ordered_items": 145,
        "sell_earnings": 591,
        "commissions": 591,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9619,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "22",
        "clicks": 3604,
        "ordered_items": 162,
        "sell_earnings": 689,
        "commissions": 689,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7447,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "23",
        "clicks": 3927,
        "ordered_items": 165,
        "sell_earnings": 613,
        "commissions": 613,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8924,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "24",
        "clicks": 3895,
        "ordered_items": 159,
        "sell_earnings": 688,
        "commissions": 688,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8767,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "25",
        "clicks": 2783,
        "ordered_items": 129,
        "sell_earnings": 503,
        "commissions": 503,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5760,
        "bonus": 2
    },
    {
        "month": "Sep",
        "day": "26",
        "clicks": 2467,
        "ordered_items": 134,
        "sell_earnings": 567,
        "commissions": 567,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6958,
        "bonus": 1
    },
    {
        "month": "Sep",
        "day": "27",
        "clicks": 4353,
        "ordered_items": 134,
        "sell_earnings": 585,
        "commissions": 585,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 154,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7928,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "28",
        "clicks": 4037,
        "ordered_items": 139,
        "sell_earnings": 649,
        "commissions": 649,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9126,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "29",
        "clicks": 3151,
        "ordered_items": 115,
        "sell_earnings": 496,
        "commissions": 496,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6855,
        "bonus": 0
    },
    {
        "month": "Sep",
        "day": "30",
        "clicks": 3669,
        "ordered_items": 153,
        "sell_earnings": 656,
        "commissions": 656,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8031,
        "bonus": 0
    }
];