export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1368,
        "ordered_items": 109,
        "sell_earnings": 585,
        "commissions": 585,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 114,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6707,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1588,
        "ordered_items": 121,
        "sell_earnings": 538,
        "commissions": 538,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5637,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1192,
        "ordered_items": 105,
        "sell_earnings": 591,
        "commissions": 591,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6699,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 2040,
        "ordered_items": 169,
        "sell_earnings": 625,
        "commissions": 625,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7707,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 1644,
        "ordered_items": 153,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8769,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 1864,
        "ordered_items": 165,
        "sell_earnings": 631,
        "commissions": 631,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7699,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1569,
        "ordered_items": 117,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5630,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1401,
        "ordered_items": 137,
        "sell_earnings": 590,
        "commissions": 590,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6096,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1182,
        "ordered_items": 134,
        "sell_earnings": 600,
        "commissions": 600,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 114,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5500,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 2050,
        "ordered_items": 140,
        "sell_earnings": 616,
        "commissions": 616,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8906,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 1831,
        "ordered_items": 137,
        "sell_earnings": 626,
        "commissions": 626,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8310,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 1663,
        "ordered_items": 157,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8776,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1222,
        "ordered_items": 124,
        "sell_earnings": 468,
        "commissions": 468,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5836,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 2010,
        "ordered_items": 150,
        "sell_earnings": 748,
        "commissions": 748,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8570,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1228,
        "ordered_items": 105,
        "sell_earnings": 571,
        "commissions": 571,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6571,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 2004,
        "ordered_items": 169,
        "sell_earnings": 645,
        "commissions": 645,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7835,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1361,
        "ordered_items": 118,
        "sell_earnings": 478,
        "commissions": 478,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6045,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1487,
        "ordered_items": 131,
        "sell_earnings": 547,
        "commissions": 547,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6839,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1577,
        "ordered_items": 103,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5900,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1563,
        "ordered_items": 130,
        "sell_earnings": 464,
        "commissions": 464,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6863,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 1669,
        "ordered_items": 144,
        "sell_earnings": 752,
        "commissions": 752,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7543,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 1655,
        "ordered_items": 171,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 157,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8506,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 1745,
        "ordered_items": 143,
        "sell_earnings": 669,
        "commissions": 669,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7567,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 1871,
        "ordered_items": 156,
        "sell_earnings": 738,
        "commissions": 738,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 161,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8361,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1286,
        "ordered_items": 98,
        "sell_earnings": 476,
        "commissions": 476,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5253,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1299,
        "ordered_items": 136,
        "sell_earnings": 562,
        "commissions": 562,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5986,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1933,
        "ordered_items": 138,
        "sell_earnings": 654,
        "commissions": 654,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8420,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 1946,
        "ordered_items": 176,
        "sell_earnings": 740,
        "commissions": 740,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9153,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1438,
        "ordered_items": 103,
        "sell_earnings": 484,
        "commissions": 484,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6357,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 1794,
        "ordered_items": 171,
        "sell_earnings": 732,
        "commissions": 732,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8049,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];