export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1400,
        "ordered_items": 132,
        "sell_earnings": 447,
        "commissions": 447,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5194,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1494,
        "ordered_items": 118,
        "sell_earnings": 529,
        "commissions": 529,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6609,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1160,
        "ordered_items": 112,
        "sell_earnings": 567,
        "commissions": 567,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5824,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 2072,
        "ordered_items": 162,
        "sell_earnings": 649,
        "commissions": 649,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8582,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 1738,
        "ordered_items": 156,
        "sell_earnings": 687,
        "commissions": 687,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7797,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 1832,
        "ordered_items": 142,
        "sell_earnings": 769,
        "commissions": 769,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9212,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1513,
        "ordered_items": 101,
        "sell_earnings": 498,
        "commissions": 498,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6795,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1360,
        "ordered_items": 118,
        "sell_earnings": 475,
        "commissions": 475,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 107,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6336,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1350,
        "ordered_items": 97,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 89,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6422,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 1882,
        "ordered_items": 177,
        "sell_earnings": 725,
        "commissions": 725,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7984,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 1872,
        "ordered_items": 156,
        "sell_earnings": 741,
        "commissions": 741,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 145,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8070,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 1719,
        "ordered_items": 173,
        "sell_earnings": 718,
        "commissions": 718,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 159,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7611,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1579,
        "ordered_items": 130,
        "sell_earnings": 481,
        "commissions": 481,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6433,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 1653,
        "ordered_items": 144,
        "sell_earnings": 735,
        "commissions": 735,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7973,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1149,
        "ordered_items": 104,
        "sell_earnings": 518,
        "commissions": 518,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6185,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 2083,
        "ordered_items": 170,
        "sell_earnings": 698,
        "commissions": 698,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8221,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1596,
        "ordered_items": 133,
        "sell_earnings": 469,
        "commissions": 469,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6641,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1615,
        "ordered_items": 102,
        "sell_earnings": 602,
        "commissions": 602,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 96,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6440,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1598,
        "ordered_items": 103,
        "sell_earnings": 487,
        "commissions": 487,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6109,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1213,
        "ordered_items": 117,
        "sell_earnings": 561,
        "commissions": 561,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6789,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 2019,
        "ordered_items": 157,
        "sell_earnings": 655,
        "commissions": 655,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7617,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1634,
        "ordered_items": 171,
        "sell_earnings": 729,
        "commissions": 729,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8297,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 1617,
        "ordered_items": 172,
        "sell_earnings": 614,
        "commissions": 614,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7966,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 1636,
        "ordered_items": 141,
        "sell_earnings": 747,
        "commissions": 747,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7765,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1278,
        "ordered_items": 127,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5749,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1142,
        "ordered_items": 115,
        "sell_earnings": 558,
        "commissions": 558,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6390,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 2090,
        "ordered_items": 159,
        "sell_earnings": 658,
        "commissions": 658,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8016,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1954,
        "ordered_items": 147,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8657,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1300,
        "ordered_items": 101,
        "sell_earnings": 447,
        "commissions": 447,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5896,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 1932,
        "ordered_items": 173,
        "sell_earnings": 769,
        "commissions": 769,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 139,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8510,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];