export let mar = [
    {
        "month": "Mar",
        "day": "01",
        "clicks": 1218,
        "ordered_items": 131,
        "sell_earnings": 535,
        "commissions": 535,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6994,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "02",
        "clicks": 1223,
        "ordered_items": 113,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6312,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "03",
        "clicks": 1318,
        "ordered_items": 137,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6054,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "04",
        "clicks": 1914,
        "ordered_items": 137,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8352,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "05",
        "clicks": 2009,
        "ordered_items": 161,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8094,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "06",
        "clicks": 2014,
        "ordered_items": 143,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7412,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "07",
        "clicks": 1356,
        "ordered_items": 99,
        "sell_earnings": 569,
        "commissions": 569,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 100,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5332,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "08",
        "clicks": 1575,
        "ordered_items": 131,
        "sell_earnings": 560,
        "commissions": 560,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5188,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "09",
        "clicks": 1171,
        "ordered_items": 102,
        "sell_earnings": 490,
        "commissions": 490,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6255,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "10",
        "clicks": 2061,
        "ordered_items": 172,
        "sell_earnings": 726,
        "commissions": 726,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8151,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "11",
        "clicks": 1657,
        "ordered_items": 143,
        "sell_earnings": 656,
        "commissions": 656,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9218,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "12",
        "clicks": 1876,
        "ordered_items": 175,
        "sell_earnings": 647,
        "commissions": 647,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 152,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9074,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "13",
        "clicks": 1544,
        "ordered_items": 115,
        "sell_earnings": 568,
        "commissions": 568,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6665,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "14",
        "clicks": 1688,
        "ordered_items": 159,
        "sell_earnings": 648,
        "commissions": 648,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7741,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "15",
        "clicks": 1321,
        "ordered_items": 124,
        "sell_earnings": 437,
        "commissions": 437,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6705,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "16",
        "clicks": 1911,
        "ordered_items": 150,
        "sell_earnings": 779,
        "commissions": 779,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7701,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "17",
        "clicks": 1437,
        "ordered_items": 129,
        "sell_earnings": 484,
        "commissions": 484,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5577,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "18",
        "clicks": 1546,
        "ordered_items": 136,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7021,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "19",
        "clicks": 1182,
        "ordered_items": 101,
        "sell_earnings": 491,
        "commissions": 491,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6762,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "20",
        "clicks": 1136,
        "ordered_items": 110,
        "sell_earnings": 567,
        "commissions": 567,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5373,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "21",
        "clicks": 2096,
        "ordered_items": 164,
        "sell_earnings": 649,
        "commissions": 649,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9033,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "22",
        "clicks": 2050,
        "ordered_items": 173,
        "sell_earnings": 725,
        "commissions": 725,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7644,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "23",
        "clicks": 1686,
        "ordered_items": 138,
        "sell_earnings": 717,
        "commissions": 717,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7385,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "24",
        "clicks": 1795,
        "ordered_items": 145,
        "sell_earnings": 732,
        "commissions": 732,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8829,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "25",
        "clicks": 1137,
        "ordered_items": 100,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5705,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "26",
        "clicks": 1583,
        "ordered_items": 110,
        "sell_earnings": 458,
        "commissions": 458,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6734,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "27",
        "clicks": 1649,
        "ordered_items": 164,
        "sell_earnings": 758,
        "commissions": 758,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7672,
        "bonus": 2
    },
    {
        "month": "Mar",
        "day": "28",
        "clicks": 2095,
        "ordered_items": 174,
        "sell_earnings": 721,
        "commissions": 721,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8701,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "29",
        "clicks": 1267,
        "ordered_items": 117,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6802,
        "bonus": 0
    },
    {
        "month": "Mar",
        "day": "30",
        "clicks": 1965,
        "ordered_items": 157,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7604,
        "bonus": 1
    },
    {
        "month": "Mar",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];