export let may = [
    {
        "month": "May",
        "day": "01",
        "clicks": 1280,
        "ordered_items": 109,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6704,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "02",
        "clicks": 1225,
        "ordered_items": 99,
        "sell_earnings": 521,
        "commissions": 521,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6052,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "03",
        "clicks": 1298,
        "ordered_items": 131,
        "sell_earnings": 540,
        "commissions": 540,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7115,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "04",
        "clicks": 1934,
        "ordered_items": 143,
        "sell_earnings": 676,
        "commissions": 676,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7291,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "05",
        "clicks": 2007,
        "ordered_items": 175,
        "sell_earnings": 695,
        "commissions": 695,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8354,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "06",
        "clicks": 1952,
        "ordered_items": 165,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7702,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "07",
        "clicks": 1410,
        "ordered_items": 135,
        "sell_earnings": 579,
        "commissions": 579,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 91,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5756,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "08",
        "clicks": 1163,
        "ordered_items": 135,
        "sell_earnings": 432,
        "commissions": 432,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5061,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "09",
        "clicks": 1545,
        "ordered_items": 115,
        "sell_earnings": 564,
        "commissions": 564,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6759,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "10",
        "clicks": 1687,
        "ordered_items": 159,
        "sell_earnings": 652,
        "commissions": 652,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7647,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "11",
        "clicks": 2069,
        "ordered_items": 139,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 136,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9345,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "12",
        "clicks": 1822,
        "ordered_items": 139,
        "sell_earnings": 637,
        "commissions": 637,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 161,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8650,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "13",
        "clicks": 1338,
        "ordered_items": 118,
        "sell_earnings": 589,
        "commissions": 589,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7196,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "14",
        "clicks": 1894,
        "ordered_items": 156,
        "sell_earnings": 627,
        "commissions": 627,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 148,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7210,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "15",
        "clicks": 1496,
        "ordered_items": 136,
        "sell_earnings": 435,
        "commissions": 435,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7199,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "16",
        "clicks": 1736,
        "ordered_items": 138,
        "sell_earnings": 781,
        "commissions": 781,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7207,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "17",
        "clicks": 1465,
        "ordered_items": 115,
        "sell_earnings": 570,
        "commissions": 570,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6904,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "18",
        "clicks": 1348,
        "ordered_items": 102,
        "sell_earnings": 487,
        "commissions": 487,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6137,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "19",
        "clicks": 1368,
        "ordered_items": 111,
        "sell_earnings": 506,
        "commissions": 506,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7173,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "20",
        "clicks": 1601,
        "ordered_items": 120,
        "sell_earnings": 471,
        "commissions": 471,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5187,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "21",
        "clicks": 1631,
        "ordered_items": 154,
        "sell_earnings": 745,
        "commissions": 745,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9219,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "22",
        "clicks": 1864,
        "ordered_items": 163,
        "sell_earnings": 710,
        "commissions": 710,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7233,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "23",
        "clicks": 1884,
        "ordered_items": 172,
        "sell_earnings": 729,
        "commissions": 729,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8269,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "24",
        "clicks": 1767,
        "ordered_items": 159,
        "sell_earnings": 646,
        "commissions": 646,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7502,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "25",
        "clicks": 1237,
        "ordered_items": 134,
        "sell_earnings": 517,
        "commissions": 517,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 99,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6341,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "26",
        "clicks": 1190,
        "ordered_items": 105,
        "sell_earnings": 522,
        "commissions": 522,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 105,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5955,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "27",
        "clicks": 2042,
        "ordered_items": 169,
        "sell_earnings": 694,
        "commissions": 694,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 147,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8451,
        "bonus": 1
    },
    {
        "month": "May",
        "day": "28",
        "clicks": 1995,
        "ordered_items": 140,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8065,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "29",
        "clicks": 1250,
        "ordered_items": 112,
        "sell_earnings": 497,
        "commissions": 497,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 105,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5367,
        "bonus": 0
    },
    {
        "month": "May",
        "day": "30",
        "clicks": 1982,
        "ordered_items": 162,
        "sell_earnings": 719,
        "commissions": 719,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 147,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9039,
        "bonus": 2
    },
    {
        "month": "May",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 0
    }
];