export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1321,
        "ordered_items": 109,
        "sell_earnings": 460,
        "commissions": 460,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6740,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1351,
        "ordered_items": 110,
        "sell_earnings": 479,
        "commissions": 479,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5285,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1468,
        "ordered_items": 137,
        "sell_earnings": 443,
        "commissions": 443,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6483,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 1872,
        "ordered_items": 147,
        "sell_earnings": 813,
        "commissions": 813,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8403,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 1989,
        "ordered_items": 174,
        "sell_earnings": 777,
        "commissions": 777,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9601,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 2019,
        "ordered_items": 175,
        "sell_earnings": 796,
        "commissions": 796,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8146,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1394,
        "ordered_items": 131,
        "sell_earnings": 555,
        "commissions": 555,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6767,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1529,
        "ordered_items": 133,
        "sell_earnings": 571,
        "commissions": 571,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6084,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1482,
        "ordered_items": 106,
        "sell_earnings": 607,
        "commissions": 607,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7212,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 1858,
        "ordered_items": 178,
        "sell_earnings": 649,
        "commissions": 649,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 167,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7674,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 1811,
        "ordered_items": 151,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8802,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 1946,
        "ordered_items": 153,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 138,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8119,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1337,
        "ordered_items": 122,
        "sell_earnings": 581,
        "commissions": 581,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5389,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 2003,
        "ordered_items": 162,
        "sell_earnings": 675,
        "commissions": 675,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9497,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1472,
        "ordered_items": 134,
        "sell_earnings": 474,
        "commissions": 474,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 97,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6146,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 1868,
        "ordered_items": 150,
        "sell_earnings": 782,
        "commissions": 782,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 165,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8740,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1319,
        "ordered_items": 140,
        "sell_earnings": 530,
        "commissions": 530,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7437,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1488,
        "ordered_items": 138,
        "sell_earnings": 494,
        "commissions": 494,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6221,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1655,
        "ordered_items": 125,
        "sell_earnings": 478,
        "commissions": 478,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5675,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1629,
        "ordered_items": 112,
        "sell_earnings": 585,
        "commissions": 585,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6272,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 1711,
        "ordered_items": 172,
        "sell_earnings": 671,
        "commissions": 671,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8614,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 1685,
        "ordered_items": 159,
        "sell_earnings": 778,
        "commissions": 778,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 169,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9211,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 1852,
        "ordered_items": 146,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8665,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 2021,
        "ordered_items": 144,
        "sell_earnings": 726,
        "commissions": 726,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 138,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7449,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1557,
        "ordered_items": 129,
        "sell_earnings": 557,
        "commissions": 557,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7250,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1415,
        "ordered_items": 120,
        "sell_earnings": 456,
        "commissions": 456,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6210,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 1925,
        "ordered_items": 164,
        "sell_earnings": 800,
        "commissions": 800,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8676,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 1783,
        "ordered_items": 155,
        "sell_earnings": 699,
        "commissions": 699,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7636,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1171,
        "ordered_items": 113,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 125,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5750,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 2169,
        "ordered_items": 171,
        "sell_earnings": 776,
        "commissions": 776,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 137,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9136,
        "bonus": 2
    }
];