export let aug = [
    {
        "month": "Aug",
        "day": "01",
        "clicks": 1354,
        "ordered_items": 133,
        "sell_earnings": 586,
        "commissions": 586,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5927,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "02",
        "clicks": 1466,
        "ordered_items": 124,
        "sell_earnings": 429,
        "commissions": 429,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 125,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6554,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "03",
        "clicks": 1362,
        "ordered_items": 106,
        "sell_earnings": 501,
        "commissions": 501,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5870,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "04",
        "clicks": 1870,
        "ordered_items": 168,
        "sell_earnings": 715,
        "commissions": 715,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8536,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "05",
        "clicks": 1766,
        "ordered_items": 150,
        "sell_earnings": 787,
        "commissions": 787,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7852,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "06",
        "clicks": 1878,
        "ordered_items": 141,
        "sell_earnings": 630,
        "commissions": 630,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8479,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "07",
        "clicks": 1602,
        "ordered_items": 115,
        "sell_earnings": 432,
        "commissions": 432,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 103,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5705,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "08",
        "clicks": 1177,
        "ordered_items": 116,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 108,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5200,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "09",
        "clicks": 1259,
        "ordered_items": 115,
        "sell_earnings": 482,
        "commissions": 482,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7191,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "10",
        "clicks": 1973,
        "ordered_items": 159,
        "sell_earnings": 734,
        "commissions": 734,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7215,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "11",
        "clicks": 2055,
        "ordered_items": 158,
        "sell_earnings": 753,
        "commissions": 753,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 144,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9206,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "12",
        "clicks": 1630,
        "ordered_items": 159,
        "sell_earnings": 784,
        "commissions": 784,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 149,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8701,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "13",
        "clicks": 1246,
        "ordered_items": 130,
        "sell_earnings": 461,
        "commissions": 461,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7051,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "14",
        "clicks": 1986,
        "ordered_items": 144,
        "sell_earnings": 755,
        "commissions": 755,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7355,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "15",
        "clicks": 1297,
        "ordered_items": 123,
        "sell_earnings": 427,
        "commissions": 427,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5917,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "16",
        "clicks": 1935,
        "ordered_items": 151,
        "sell_earnings": 789,
        "commissions": 789,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8489,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "17",
        "clicks": 1400,
        "ordered_items": 114,
        "sell_earnings": 454,
        "commissions": 454,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 97,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7015,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "18",
        "clicks": 1582,
        "ordered_items": 105,
        "sell_earnings": 556,
        "commissions": 556,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5210,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "19",
        "clicks": 1425,
        "ordered_items": 135,
        "sell_earnings": 594,
        "commissions": 594,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5758,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "20",
        "clicks": 1213,
        "ordered_items": 107,
        "sell_earnings": 430,
        "commissions": 430,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5045,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "21",
        "clicks": 2019,
        "ordered_items": 167,
        "sell_earnings": 786,
        "commissions": 786,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9361,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "22",
        "clicks": 1807,
        "ordered_items": 139,
        "sell_earnings": 622,
        "commissions": 622,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8648,
        "bonus": 1
    },
    {
        "month": "Aug",
        "day": "23",
        "clicks": 1650,
        "ordered_items": 169,
        "sell_earnings": 660,
        "commissions": 660,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9196,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "24",
        "clicks": 1832,
        "ordered_items": 160,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 155,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7391,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "25",
        "clicks": 1282,
        "ordered_items": 103,
        "sell_earnings": 460,
        "commissions": 460,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5818,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "26",
        "clicks": 1332,
        "ordered_items": 128,
        "sell_earnings": 509,
        "commissions": 509,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5779,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "27",
        "clicks": 1900,
        "ordered_items": 146,
        "sell_earnings": 707,
        "commissions": 707,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 134,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8627,
        "bonus": 0
    },
    {
        "month": "Aug",
        "day": "28",
        "clicks": 1950,
        "ordered_items": 171,
        "sell_earnings": 756,
        "commissions": 756,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8588,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "29",
        "clicks": 1152,
        "ordered_items": 110,
        "sell_earnings": 504,
        "commissions": 504,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6806,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "30",
        "clicks": 2080,
        "ordered_items": 164,
        "sell_earnings": 712,
        "commissions": 712,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 133,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7600,
        "bonus": 2
    },
    {
        "month": "Aug",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 1
    }
];