export let jan = [
    {
        "month": "Jan",
        "day": "01",
        "clicks": 1572,
        "ordered_items": 118,
        "sell_earnings": 515,
        "commissions": 515,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 90,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5861,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "02",
        "clicks": 1402,
        "ordered_items": 120,
        "sell_earnings": 475,
        "commissions": 475,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5428,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "03",
        "clicks": 1223,
        "ordered_items": 113,
        "sell_earnings": 507,
        "commissions": 507,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 120,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5291,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "04",
        "clicks": 2009,
        "ordered_items": 161,
        "sell_earnings": 709,
        "commissions": 709,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9115,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "05",
        "clicks": 1830,
        "ordered_items": 154,
        "sell_earnings": 741,
        "commissions": 741,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8978,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "06",
        "clicks": 1660,
        "ordered_items": 156,
        "sell_earnings": 701,
        "commissions": 701,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 162,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8545,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "07",
        "clicks": 1447,
        "ordered_items": 109,
        "sell_earnings": 538,
        "commissions": 538,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 117,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6037,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "08",
        "clicks": 1458,
        "ordered_items": 100,
        "sell_earnings": 448,
        "commissions": 448,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6738,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "09",
        "clicks": 1552,
        "ordered_items": 108,
        "sell_earnings": 535,
        "commissions": 535,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 110,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5328,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "10",
        "clicks": 1680,
        "ordered_items": 166,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 142,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9078,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "11",
        "clicks": 1774,
        "ordered_items": 174,
        "sell_earnings": 768,
        "commissions": 768,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7668,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "12",
        "clicks": 1785,
        "ordered_items": 165,
        "sell_earnings": 678,
        "commissions": 678,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8369,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "13",
        "clicks": 1613,
        "ordered_items": 121,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7114,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "14",
        "clicks": 1619,
        "ordered_items": 153,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7292,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "15",
        "clicks": 1292,
        "ordered_items": 109,
        "sell_earnings": 605,
        "commissions": 605,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6757,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "16",
        "clicks": 1940,
        "ordered_items": 165,
        "sell_earnings": 611,
        "commissions": 611,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7649,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "17",
        "clicks": 1515,
        "ordered_items": 127,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 89,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5198,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "18",
        "clicks": 1384,
        "ordered_items": 116,
        "sell_earnings": 586,
        "commissions": 586,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 100,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5123,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "19",
        "clicks": 1418,
        "ordered_items": 115,
        "sell_earnings": 576,
        "commissions": 576,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5089,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "20",
        "clicks": 1313,
        "ordered_items": 127,
        "sell_earnings": 573,
        "commissions": 573,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 117,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5098,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "21",
        "clicks": 1919,
        "ordered_items": 147,
        "sell_earnings": 643,
        "commissions": 643,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9308,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "22",
        "clicks": 1814,
        "ordered_items": 159,
        "sell_earnings": 640,
        "commissions": 640,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9317,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "23",
        "clicks": 1848,
        "ordered_items": 158,
        "sell_earnings": 630,
        "commissions": 630,
        "bounties": 1,
        "referrals": 2,
        "referral_earnings": 1,
        "shipped": 152,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9283,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "24",
        "clicks": 1717,
        "ordered_items": 147,
        "sell_earnings": 739,
        "commissions": 739,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 163,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9208,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "25",
        "clicks": 1284,
        "ordered_items": 130,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5555,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "26",
        "clicks": 1346,
        "ordered_items": 106,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 121,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7090,
        "bonus": 0
    },
    {
        "month": "Jan",
        "day": "27",
        "clicks": 1886,
        "ordered_items": 168,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7316,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "28",
        "clicks": 1948,
        "ordered_items": 144,
        "sell_earnings": 770,
        "commissions": 770,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 158,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8851,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "29",
        "clicks": 1598,
        "ordered_items": 130,
        "sell_earnings": 531,
        "commissions": 531,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7092,
        "bonus": 1
    },
    {
        "month": "Jan",
        "day": "30",
        "clicks": 1634,
        "ordered_items": 144,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7314,
        "bonus": 2
    },
    {
        "month": "Jan",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];