export let jun = [
    {
        "month": "Jun",
        "day": "01",
        "clicks": 1370,
        "ordered_items": 118,
        "sell_earnings": 599,
        "commissions": 599,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 94,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6392,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "02",
        "clicks": 1305,
        "ordered_items": 140,
        "sell_earnings": 516,
        "commissions": 516,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 107,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6798,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "03",
        "clicks": 1384,
        "ordered_items": 126,
        "sell_earnings": 604,
        "commissions": 604,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6259,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "04",
        "clicks": 1956,
        "ordered_items": 158,
        "sell_earnings": 652,
        "commissions": 652,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8627,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "05",
        "clicks": 2035,
        "ordered_items": 144,
        "sell_earnings": 740,
        "commissions": 740,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 155,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8088,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "06",
        "clicks": 1970,
        "ordered_items": 166,
        "sell_earnings": 657,
        "commissions": 657,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 168,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8494,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "07",
        "clicks": 1613,
        "ordered_items": 122,
        "sell_earnings": 513,
        "commissions": 513,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6539,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "08",
        "clicks": 1171,
        "ordered_items": 121,
        "sell_earnings": 499,
        "commissions": 499,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 127,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6777,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "09",
        "clicks": 1224,
        "ordered_items": 102,
        "sell_earnings": 620,
        "commissions": 620,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 116,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7169,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "10",
        "clicks": 2116,
        "ordered_items": 182,
        "sell_earnings": 636,
        "commissions": 636,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 146,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7717,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "11",
        "clicks": 2169,
        "ordered_items": 163,
        "sell_earnings": 757,
        "commissions": 757,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 135,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8109,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "12",
        "clicks": 1727,
        "ordered_items": 162,
        "sell_earnings": 743,
        "commissions": 743,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 136,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8347,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "13",
        "clicks": 1286,
        "ordered_items": 121,
        "sell_earnings": 530,
        "commissions": 530,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5504,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "14",
        "clicks": 2054,
        "ordered_items": 163,
        "sell_earnings": 726,
        "commissions": 726,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9382,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "15",
        "clicks": 1194,
        "ordered_items": 124,
        "sell_earnings": 627,
        "commissions": 627,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 113,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6858,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "16",
        "clicks": 2146,
        "ordered_items": 160,
        "sell_earnings": 629,
        "commissions": 629,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 149,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8028,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "17",
        "clicks": 1220,
        "ordered_items": 110,
        "sell_earnings": 477,
        "commissions": 477,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7403,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "18",
        "clicks": 1327,
        "ordered_items": 142,
        "sell_earnings": 603,
        "commissions": 603,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7373,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "19",
        "clicks": 1196,
        "ordered_items": 102,
        "sell_earnings": 575,
        "commissions": 575,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 111,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6955,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "20",
        "clicks": 1200,
        "ordered_items": 141,
        "sell_earnings": 520,
        "commissions": 520,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 106,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6319,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "21",
        "clicks": 2140,
        "ordered_items": 143,
        "sell_earnings": 736,
        "commissions": 736,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 156,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8567,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "22",
        "clicks": 2144,
        "ordered_items": 182,
        "sell_earnings": 681,
        "commissions": 681,
        "bounties": 1,
        "referrals": 1,
        "referral_earnings": 1,
        "shipped": 151,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7931,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "23",
        "clicks": 2013,
        "ordered_items": 142,
        "sell_earnings": 653,
        "commissions": 653,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 167,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7513,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "24",
        "clicks": 2120,
        "ordered_items": 174,
        "sell_earnings": 779,
        "commissions": 779,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 158,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7483,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "25",
        "clicks": 1234,
        "ordered_items": 103,
        "sell_earnings": 493,
        "commissions": 493,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 99,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6630,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "26",
        "clicks": 1175,
        "ordered_items": 130,
        "sell_earnings": 538,
        "commissions": 538,
        "bounties": 2,
        "referrals": 2,
        "referral_earnings": 2,
        "shipped": 119,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6346,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "27",
        "clicks": 2165,
        "ordered_items": 154,
        "sell_earnings": 718,
        "commissions": 718,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 143,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8540,
        "bonus": 2
    },
    {
        "month": "Jun",
        "day": "28",
        "clicks": 2106,
        "ordered_items": 181,
        "sell_earnings": 763,
        "commissions": 763,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 163,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8256,
        "bonus": 0
    },
    {
        "month": "Jun",
        "day": "29",
        "clicks": 1587,
        "ordered_items": 114,
        "sell_earnings": 445,
        "commissions": 445,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6312,
        "bonus": 1
    },
    {
        "month": "Jun",
        "day": "30",
        "clicks": 1753,
        "ordered_items": 170,
        "sell_earnings": 811,
        "commissions": 811,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8574,
        "bonus": 0
    }
];