export let nov = [
    {
        "month": "Nov",
        "day": "01",
        "clicks": 1310,
        "ordered_items": 122,
        "sell_earnings": 612,
        "commissions": 612,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 108,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6030,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "02",
        "clicks": 1353,
        "ordered_items": 107,
        "sell_earnings": 445,
        "commissions": 445,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6909,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "03",
        "clicks": 1445,
        "ordered_items": 103,
        "sell_earnings": 571,
        "commissions": 571,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6765,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "04",
        "clicks": 1895,
        "ordered_items": 181,
        "sell_earnings": 685,
        "commissions": 685,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8121,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "05",
        "clicks": 1987,
        "ordered_items": 177,
        "sell_earnings": 811,
        "commissions": 811,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7977,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "06",
        "clicks": 2030,
        "ordered_items": 162,
        "sell_earnings": 644,
        "commissions": 644,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 154,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8856,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "07",
        "clicks": 1209,
        "ordered_items": 117,
        "sell_earnings": 616,
        "commissions": 616,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6760,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "08",
        "clicks": 1443,
        "ordered_items": 126,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6604,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "09",
        "clicks": 1455,
        "ordered_items": 139,
        "sell_earnings": 495,
        "commissions": 495,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 111,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7259,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "10",
        "clicks": 1885,
        "ordered_items": 145,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 151,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7627,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "11",
        "clicks": 1897,
        "ordered_items": 158,
        "sell_earnings": 722,
        "commissions": 722,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 131,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8282,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "12",
        "clicks": 2131,
        "ordered_items": 167,
        "sell_earnings": 640,
        "commissions": 640,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8126,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "13",
        "clicks": 1419,
        "ordered_items": 114,
        "sell_earnings": 468,
        "commissions": 468,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 121,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6652,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "14",
        "clicks": 1921,
        "ordered_items": 170,
        "sell_earnings": 788,
        "commissions": 788,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 141,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8234,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "15",
        "clicks": 1491,
        "ordered_items": 126,
        "sell_earnings": 459,
        "commissions": 459,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 96,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6562,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "16",
        "clicks": 1849,
        "ordered_items": 158,
        "sell_earnings": 797,
        "commissions": 797,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 166,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8324,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "17",
        "clicks": 1561,
        "ordered_items": 126,
        "sell_earnings": 512,
        "commissions": 512,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 98,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7045,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "18",
        "clicks": 1534,
        "ordered_items": 140,
        "sell_earnings": 507,
        "commissions": 507,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7433,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "19",
        "clicks": 1570,
        "ordered_items": 106,
        "sell_earnings": 480,
        "commissions": 480,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 109,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6162,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "20",
        "clicks": 1569,
        "ordered_items": 113,
        "sell_earnings": 625,
        "commissions": 625,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7076,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "21",
        "clicks": 1771,
        "ordered_items": 171,
        "sell_earnings": 631,
        "commissions": 631,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7810,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "22",
        "clicks": 1770,
        "ordered_items": 178,
        "sell_earnings": 776,
        "commissions": 776,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 153,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8724,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "23",
        "clicks": 1806,
        "ordered_items": 144,
        "sell_earnings": 749,
        "commissions": 749,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7453,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "24",
        "clicks": 1779,
        "ordered_items": 158,
        "sell_earnings": 744,
        "commissions": 744,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 164,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7841,
        "bonus": 2
    },
    {
        "month": "Nov",
        "day": "25",
        "clicks": 1581,
        "ordered_items": 118,
        "sell_earnings": 446,
        "commissions": 446,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 6930,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "26",
        "clicks": 1388,
        "ordered_items": 114,
        "sell_earnings": 442,
        "commissions": 442,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 7015,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "27",
        "clicks": 1952,
        "ordered_items": 170,
        "sell_earnings": 814,
        "commissions": 814,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7871,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "28",
        "clicks": 1759,
        "ordered_items": 166,
        "sell_earnings": 810,
        "commissions": 810,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 169,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 7956,
        "bonus": 0
    },
    {
        "month": "Nov",
        "day": "29",
        "clicks": 1420,
        "ordered_items": 129,
        "sell_earnings": 463,
        "commissions": 463,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6961,
        "bonus": 1
    },
    {
        "month": "Nov",
        "day": "30",
        "clicks": 1920,
        "ordered_items": 155,
        "sell_earnings": 793,
        "commissions": 793,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 167,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7925,
        "bonus": 0
    }
];