export let oct = [
    {
        "month": "Oct",
        "day": "01",
        "clicks": 1145,
        "ordered_items": 109,
        "sell_earnings": 470,
        "commissions": 470,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 92,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6868,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "02",
        "clicks": 1321,
        "ordered_items": 116,
        "sell_earnings": 428,
        "commissions": 428,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 118,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5962,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "03",
        "clicks": 1278,
        "ordered_items": 114,
        "sell_earnings": 514,
        "commissions": 514,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5515,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "04",
        "clicks": 1954,
        "ordered_items": 160,
        "sell_earnings": 702,
        "commissions": 702,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8891,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "05",
        "clicks": 1911,
        "ordered_items": 158,
        "sell_earnings": 788,
        "commissions": 788,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 134,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8444,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "06",
        "clicks": 2087,
        "ordered_items": 165,
        "sell_earnings": 746,
        "commissions": 746,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 160,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7538,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "07",
        "clicks": 1551,
        "ordered_items": 122,
        "sell_earnings": 436,
        "commissions": 436,
        "bounties": 2,
        "referrals": 1,
        "referral_earnings": 2,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6998,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "08",
        "clicks": 1227,
        "ordered_items": 124,
        "sell_earnings": 454,
        "commissions": 454,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6139,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "09",
        "clicks": 1142,
        "ordered_items": 112,
        "sell_earnings": 453,
        "commissions": 453,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 104,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6569,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "10",
        "clicks": 2090,
        "ordered_items": 162,
        "sell_earnings": 763,
        "commissions": 763,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7837,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "11",
        "clicks": 2005,
        "ordered_items": 150,
        "sell_earnings": 762,
        "commissions": 762,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8267,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "12",
        "clicks": 1681,
        "ordered_items": 152,
        "sell_earnings": 780,
        "commissions": 780,
        "bounties": 0,
        "referrals": 1,
        "referral_earnings": 0,
        "shipped": 148,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7408,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "13",
        "clicks": 1429,
        "ordered_items": 118,
        "sell_earnings": 455,
        "commissions": 455,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 120,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5258,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "14",
        "clicks": 1803,
        "ordered_items": 156,
        "sell_earnings": 761,
        "commissions": 761,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 132,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9148,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "15",
        "clicks": 1563,
        "ordered_items": 112,
        "sell_earnings": 536,
        "commissions": 536,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 102,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6019,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "16",
        "clicks": 1669,
        "ordered_items": 162,
        "sell_earnings": 680,
        "commissions": 680,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 150,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8387,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "17",
        "clicks": 1388,
        "ordered_items": 126,
        "sell_earnings": 547,
        "commissions": 547,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 6693,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "18",
        "clicks": 1597,
        "ordered_items": 109,
        "sell_earnings": 587,
        "commissions": 587,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 95,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5188,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "19",
        "clicks": 1239,
        "ordered_items": 119,
        "sell_earnings": 598,
        "commissions": 598,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 93,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5810,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "20",
        "clicks": 1596,
        "ordered_items": 137,
        "sell_earnings": 443,
        "commissions": 443,
        "bounties": 0,
        "referrals": 2,
        "referral_earnings": 0,
        "shipped": 122,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5368,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "21",
        "clicks": 1636,
        "ordered_items": 137,
        "sell_earnings": 773,
        "commissions": 773,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 130,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 9038,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "22",
        "clicks": 1993,
        "ordered_items": 155,
        "sell_earnings": 618,
        "commissions": 618,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 159,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8596,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "23",
        "clicks": 1635,
        "ordered_items": 165,
        "sell_earnings": 629,
        "commissions": 629,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 157,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9218,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "24",
        "clicks": 1844,
        "ordered_items": 148,
        "sell_earnings": 669,
        "commissions": 669,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7713,
        "bonus": 0
    },
    {
        "month": "Oct",
        "day": "25",
        "clicks": 1491,
        "ordered_items": 116,
        "sell_earnings": 600,
        "commissions": 600,
        "bounties": 2,
        "referrals": 0,
        "referral_earnings": 2,
        "shipped": 112,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5279,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "26",
        "clicks": 1224,
        "ordered_items": 117,
        "sell_earnings": 529,
        "commissions": 529,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 123,
        "returned": 5,
        "conversion": 0,
        "shippedRev": 5763,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "27",
        "clicks": 2008,
        "ordered_items": 157,
        "sell_earnings": 687,
        "commissions": 687,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 129,
        "returned": 7,
        "conversion": 0,
        "shippedRev": 8643,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "28",
        "clicks": 1741,
        "ordered_items": 158,
        "sell_earnings": 616,
        "commissions": 616,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 140,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 9127,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "29",
        "clicks": 1312,
        "ordered_items": 110,
        "sell_earnings": 534,
        "commissions": 534,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 124,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 5708,
        "bonus": 2
    },
    {
        "month": "Oct",
        "day": "30",
        "clicks": 1920,
        "ordered_items": 164,
        "sell_earnings": 682,
        "commissions": 682,
        "bounties": 0,
        "referrals": 0,
        "referral_earnings": 0,
        "shipped": 128,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 8698,
        "bonus": 1
    },
    {
        "month": "Oct",
        "day": "31",
        "clicks": 1616,
        "ordered_items": 137,
        "sell_earnings": 608,
        "commissions": 608,
        "bounties": 1,
        "referrals": 0,
        "referral_earnings": 1,
        "shipped": 126,
        "returned": 6,
        "conversion": 0,
        "shippedRev": 7203,
        "bonus": 2
    }
];